### ISSUE TITLE
neroAacEnc.exe is still in the distribution, but path not defined. Is this the desired behaviour?

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#434] opened 2021-01-10 10:23 UTC
**Describe the bug**

Apple quicktime files have been removed from releases => this is OK

FDKaac files removed from releases => this is OK

**neroAacEnc.exe** is still released in folder APPS\EAC3To  ===> **IS THAT OK ?**

**Comment by Patman86** [comment] 2021-01-10 11:16
[I think it's freeware](https://en.wikipedia.org/wiki/Nero_AAC_Codec)

**Comment by 44vince44** [comment] 2021-01-10 11:18
Well in this case it should not be excluded from the staxrip tree paths. Currently, the file is there, but the path is not correctly defined, so the app manager asks you to locate it (outside the staxrip app tree)

**Comment by Patman86** [comment] 2021-01-10 11:22
Alternatively, a link to the download could still be inserted. For example [this one](https://www.rarewares.org/rrw/neroaac.php)

**Comment by Dendraspis** [comment] 2021-01-10 12:52
> Is this the desired behaviour?

It's not a bug - it's a feature❗   😁 

> I think it's freeware

It is, it was only removed by Nero from the website and couldn't been downloaded.

We should also change the description (*Non-free AAC audio convertor console app.*).  🤔

**Comment by 44vince44** [comment] 2021-01-10 13:29
> So I think the best usecase would be removing neroAacEnc from the apps list while keeping it where it is. 🤔

Indeed maybe it's as simple as that.

**Comment by JJKylee** [comment] 2021-01-10 16:40
> > So I think the best usecase would be removing neroAacEnc from the apps list while keeping it where it is. 🤔
> 
> Indeed maybe it's as simple as that.

But in order to do so, we should also remove `eac3to` from the `AAC` encoders list.

![StaxRip_2 1 7 0_Audio-Settings_eac3to_in_AAC_20210110](https://user-images.githubusercontent.com/3157518/104128974-5203bb80-531f-11eb-8324-fc1dfead0544.jpg)

I'm pretty sure some people will be complaining about this. 😃

**Comment by JJKylee** [comment] 2021-01-10 16:44
Ditto.

**Comment by Dendraspis** [comment] 2021-01-10 16:45
> But in order to do so, we should also remove `eac3to` from the `AAC` encoders list.

Not necessary, because eac3to can encode to aac - using NeroAacEnc itself.

> I'm pretty sure some people will be complaining about this. 😃

I don't care, but I'm pretty sure @stax76 does. :grin:
Let's see what he decides.  😎

**Comment by JJKylee** [comment] 2021-01-10 16:49
@Dendraspis, I reached the same conclusion as you on second thought, and deleted the wrong statement. Geez, you're really quick at snapping my mistake. 😆

**Comment by 44vince44** [comment] 2021-01-10 18:32
I bet no one will complain. They'll have eac3to encoding aac simply, not asking any question.
People who nag about quality will anyway be using qaac.

**Comment by stax76** [comment] 2021-01-10 20:06
Nero has the license issue too, megui for instance had it never included because of that. I thought having it already removed, the removal is even written in the changelog, now it's definitely removed.

**Comment by Dendraspis** [comment] 2021-01-10 20:15
...so let's close this.  ☺️

**Closed by Dendraspis** 2021-01-10 20:15 UTC
Labels: added/fixed/done, bug, question
