### ISSUE TITLE
GUI delayed in Audio settings

### ISSUE THREAD

**Issue by Morku** [staxrip/staxrip#1175] opened 2024-01-04 12:53 UTC
**Describe the bug**
When I go into Audio Settings (in my example AAC) and select "Default", the GUI is simply slow.
The issue started to happen with 2.31.0 and with 2.30.0 I don't have that delay.

**How to reproduce the issue**

1. Select AAC
2. Click Edit
3. Now the Pop-up window is delayed for 1-3 seconds
4. You can test this by setting Hooks

StaxRip 2.31.0 with the issue:

https://github.com/staxrip/staxrip/assets/6276915/c7d453cd-4632-423e-953a-ab182f8b33eb

Notice the yellow circle which means a "click" of mine and how it takes 2-3 seconds until the Hooks are finally set.

Now 2.30.0:

https://github.com/staxrip/staxrip/assets/6276915/c5b98142-9880-446c-b6b7-970c9ad3eb1d

As soo the Edit Pop-up is open, the GUI is responsive and you can cirectly click without any delay.

**Provide information**

I have tested StaxRip 2.31.0 and 2.30.0 in a fresh, clean installation with new Setting. The issue already is without any modification.
Use Windows 11 Version 22H2 Build 22621.2861

**Comment by Dendraspis** [comment] 2024-01-04 13:42
I can definitely reproduce this issue, but not sure if and/or how I can solve it.

Due to the change of languages and codes, the language box has to be filled with almost 10x as many languages as before every time it shows up and that takes a while. 🫤

I will try to optimise it a bit, but it might take a while.

**Comment by Dendraspis** [comment] 2024-01-05 15:12
Okay, I have improved it ... somehow.  The Language is not selectable while the menu is building up, but I guess this is negotiable. 

Will be included in the next release....

**Closed by Dendraspis** 2024-01-05 15:12 UTC
Labels: bug, added/fixed/done
