### ISSUE TITLE
StaxRip freezes with ~100 frames left to encode

### ISSUE THREAD

**Issue by Vyndros** [staxrip/staxrip#771] opened 2021-08-15 09:25 UTC
I encode with x265 and AviSynth filters. At first I noticed this error in StaxRip 2.6.0 and then recently I've done clean installs (including AviSynth) of StaxRip 2.8.0 on all my machines and the error still persists.

The machine this is happening on is a brand new Asus ROG G533QR laptop with Windows 10 Home Edition pre-installed.

The standard encoding scenario is x265 using SMDegrain, LSFmod and neo_f3kdb in that order.

Case 1:
![StaxStuck](https://user-images.githubusercontent.com/88965404/129473667-cf65358b-5739-4ce1-b38e-06454922a050.png)
Encode freezes here, I've tried Suspend/Resume with no effect, the only thing left to do is ABORT.

Log BEFORE abort:
[I Know That Girl - Bailey Blue & Brittney Banxxx (Love The Situation 2011.08.24) 1080p_PREABORT.log](https://github.com/staxrip/staxrip/files/6987854/I.Know.That.Girl.-.Bailey.Blue.Brittney.Banxxx.Love.The.Situation.2011.08.24.1080p_PREABORT.log)

Log AFTER abort:
[I Know That Girl - Bailey Blue & Brittney Banxxx (Love The Situation 2011.08.24) 1080p_POSTABORT.log](https://github.com/staxrip/staxrip/files/6987855/I.Know.That.Girl.-.Bailey.Blue.Brittney.Banxxx.Love.The.Situation.2011.08.24.1080p_POSTABORT.log)

Case 2:
![StaxStuckRB](https://user-images.githubusercontent.com/88965404/129473730-96dcac4e-7340-486d-ba11-faa72fff4986.PNG)

Log BEFORE abort:
[Round And Brown - Ana Foxx & Tiffany Taylor (I Like Big Butts 2014.10.03) 1080p_PREABORT.log](https://github.com/staxrip/staxrip/files/6987856/Round.And.Brown.-.Ana.Foxx.Tiffany.Taylor.I.Like.Big.Butts.2014.10.03.1080p_PREABORT.log)

Log AFTER abort:
[Round And Brown - Ana Foxx & Tiffany Taylor (I Like Big Butts 2014.10.03) 1080p_POSTABORT.log](https://github.com/staxrip/staxrip/files/6987858/Round.And.Brown.-.Ana.Foxx.Tiffany.Taylor.I.Like.Big.Butts.2014.10.03.1080p_POSTABORT.log)

**Comment by menditsa** [comment] 2021-08-15 09:49
Error is in what you see in red.
Uncheck SSIM under x265 options, Statistic.

**Comment by Vyndros** [comment] 2021-08-15 10:25
No, that's just a warning, I've been using --ssim for years with no issue. 

--ssim doesn't do anything in encoding, it just calculates an image similarity metric between original and encoded image and reports it at the end. This is not hampered in any way if you use psy settings, except that the theoretical validity of using SSIM as an objective metric disappears when you include psychovisual optimizations.

I just use this metric loosely to highlight potential issues in the encode.

**Comment by Patman86** [comment] 2021-08-16 15:32
Did you test your coding without a filter? So it can be ruled out that it is due to x265.

**Comment by JJKylee** [comment] 2021-08-16 17:54
The logs don't show any pointers to why this kind of phenomenon arises.

You can either try encoding without filters as @Patman86 recommended, or try another source filter than `DSS2` (from [_DSS2mod_](http://avisynth.nl/index.php/DSS2mod) plugin) like `FFVideoSource` or `LWLibavVideoSource`. According to the _DSS2mod_ document, _**hanging at the end of the stream**_ seems to have happened from time to time in the past and I suspect the same issue is still existing with some input files like those in your case.

As you may know, you can change the _default_ source filter for `wmv` files in _Settings_ > _Source Filters_ > _AviSynth_ for future use.

**Comment by Vyndros** [comment] 2021-08-17 07:54
I have my Source Filter set on Automatic. In fact if you look at the 2nd log the same error happened and the source filter there was LSMASHVideoSource .

I'll switch to FFVideoSource exclusively and see if the error still happens.

The problem is this doesn't happen every time so to do what @Patman86 suggested I would have to probably do 10+ encodes per filter to be relatively sure the freeze doesn't happen on that particular filter and THAT is extremely time consuming.

I was hoping the fact that it freezes with around 100 frames left each time could carry a clue as to what is going wrong there. Are you aware of any subprocess being triggered like that in StaxRip?

**Comment by Patman86** [comment] 2021-08-17 11:32
Please update these plugins and test again

[LSFmod.zip](https://github.com/staxrip/staxrip/files/6999581/LSFmod.zip)
[SMDegrain.zip](https://github.com/staxrip/staxrip/files/6999584/SMDegrain.zip)

**Comment by Vyndros** [comment] 2021-08-17 23:45
I have an 8-bit source and convert to 10-bit. Is 10-bit even an option? I was asked for output_depth from the UI and the options it gave were 8 and 16-bit. I chose 8-bit because that matches the source and filters are applied before x265 goes to work AFAIK.

**Comment by Patman86** [comment] 2021-08-18 01:54
Your wmv-file is even 16bit, I can see right now. Your mp4 file is 8bit, that's right. Have you updated the filters and tested if it works then? The neo_f3kdb filter supports the output depth from 8bit to 16bit, according to the wiki and forum.

**Comment by Dendraspis** [comment] 2021-08-24 07:32
I also cannot reproduce it with my files. Maybe it's too specific or somethings else that interrupts.
Really hard to tell, when nobody is able to reproduce....

For the moment I'll close this one - feel free to re-open when you have new information.

Thanks to @Patman86 and @JJKylee for the help. 👍

**Closed by Dendraspis** 2021-08-24 07:32 UTC
Labels: bug, question, not reproducible

**Comment by Vyndros** [comment] 2021-08-31 17:30
So as a follow up I think the issue is fixed, I've switched all my profiles to FFVideoSource and I haven't had a freeze since. It seems some of the older Source scripts don't play nice with my laptop for some reason.
