### ISSUE TITLE
2.1.9.0 option to demux all subtitles but not include any in container? (hardcoded subs used)

### ISSUE THREAD

**Issue by wrzlpete** [staxrip/staxrip#622] opened 2021-03-23 21:36 UTC
I didn't see an option to pick a default renderer for vapour synth hardcoding subs yet, and I actually got to like the option to change the scale of the subs in my little workaround mentioned here: https://github.com/staxrip/staxrip/issues/385 
The only problem I have now is that the new version 2.1.9.0 seems to have removed the option to demux all subtitles but not include any of them in the final container / mkv. Is this simply not possible anymore or am I missing something here? 
Thanks for keeping up the good work either way! :)

**Comment by 44vince44** [comment] 2021-03-24 01:09
Hello @wrzlpete 
Indeed, with the new selector, you don't have the option to demux subtitles and NOT a add them. 
But:
1) when you set in options to hardcode subtitles, the textsub* filter will be created, and the hardcoded subtitle stream will NOT BE MUXED.

2) you may now use avisynth with 10bit sources, the filter for hardcoding in avisynth has been changed to pinterf's mod TextSub, it works well with 8, 10 bit sources.

3) There is no option for a Default subtitles Renderer selection. Currently
- Avisynth : TextSub (xy-VSFilter pfmod)
- Vapoursynth : vsm.TextSubMod (VSFilterMod)

However, as pinterf has recently resumed updating his version of filter xy-VSFilter we could ask to use it in VapourSynth as well....

**Comment by wrzlpete** [comment] 2021-03-24 14:34
Hey @44vince44,
thanks for your detailled explanation! I will definitely try out avisynth for hardcoding again, but I assume the scaling of the hardcoded subs won't be handled in any other way other than manually scripting them. The manual way is fine, it just gets a bit messy when you have  a set of differently tagged / named internal subtitle streams, because you have to manually set the correct name for the subtitle stream in advance, as there is (to my knowledge?) no script-macro-option to integrate a prefered language subtitle stream disregarding the actual file name the demuxing creates.
As for the gui option, I liked the idea of a simple "Demux all" "Include none" combination... less words for slow brained people like me to think about when setting up a template... xD
But that's not a request in itself, just my thoughts on it.
Thanks again for your time! :)

**Comment by Dendraspis** [comment] 2021-03-24 21:04
I added the option to demux preferred language subtitles without including them.

Here is the current DEV version, tested by @44vince44 and me.  Be aware that it already might break your templates, jobs and maybe settings:
[StaxRip v2.1.20.zip](https://github.com/staxrip/staxrip/files/6200384/StaxRip.v2.1.20.zip)

**Comment by 44vince44** [comment] 2021-03-24 21:12
IMPORTANT: before doing anything, go to options > Video and check that Demux Video is unchecked. If  checked, uncheck it and save your template.
Then you can use this build safely.
@wrzlpete this build will allow you demux preferred subs so you can create your custom automated hardcoded subs filters, and then discard the subs stream. As requested... Thanks @Dendraspis

**Comment by JJKylee** [comment] 2021-03-24 21:21
> I added the option to demux preferred language subtitles without including them.

👍

> Be aware that it already might break your templates, jobs and maybe settings:
> [StaxRip v2.1.20.zip](https://github.com/staxrip/staxrip/files/6200384/StaxRip.v2.1.20.zip)

Luckily, nothing unfortunate happens with this build despite your scary warning message. 😁

> IMPORTANT: before doing anything, go to options > Video and check that Demux Video is unchecked. If checked, uncheck it and save your template.

How kind of you, @44vince44! 😁
As for me, I already did with the previous DEV build.

**Comment by Dendraspis** [comment] 2021-03-24 21:26
> Luckily, nothing unfortunate happens with this build despite your scary warning message. 😁

Maybe I'm too tired, but which *scary warning message* do you mean?  🤔 

> How kind of you, @44vince44! 😁
> As for me, I already did with the previous DEV build.

Meanwhile not necessary anymore, it's disabled for those who haven't used the last DEV versions.  😁  Same when you start with clean settings.

**Comment by JJKylee** [comment] 2021-03-24 21:34
> > Luckily, nothing unfortunate happens with this build despite your scary warning message. 😁
> 
> Maybe I'm too tired, but which _scary warning message_ do you mean? 🤔

Maybe your warning was right.

My templates' `Subtitles` option is reset to `Include preferred languages directly without demuxing` regardless of its previous setting with v2.1.20.

Now I'm restoring my 20+ templates again. 😂😂😂😂😂

**Comment by Dendraspis** [comment] 2021-03-24 21:42
Seems like you should separate your production and testing lines.  😕

I'm everytime and still confused when something like that happens.  😕

**Comment by JJKylee** [comment] 2021-03-24 21:49
You're right. I better set up a separate copy for testing purposes only. 🙄
But these kind of minor issues were acceptable for use in practice so far.

That said, I'm pretty sure there will be reports about this modification of users' _old_ settings despite the warning against carrying them on.
Think of my case as a testing bed. 😅

**Comment by stax76** [comment] 2021-03-25 10:13
@Dendraspis 

I started testing all modes, the second mode 'Demux preferred languages but don't include them' does not work here, no subtitles are demuxed.

G: Matroska, 165 MiB, 22 s 146 ms, 62.4 Mb/s

V: HEVC, Main 10@L5.1@High, 3840x2160, 23.976 FPS, 57.5 Mb/s

A: English, DTS XLL X, 3 572 kb/s, 8ch, 48.0 kHz, Default
A: English, DTS, 1 509 kb/s, 6ch, 48.0 kHz
A: English, DTS, 255 kb/s, 2ch, 48.0 kHz
A: French, DTS, 768 kb/s, 6ch, 48.0 kHz
A: German, DTS, 768 kb/s, 6ch, 48.0 kHz
A: Italian, DTS, 768 kb/s, 6ch, 48.0 kHz
A: Turkish, DTS, 768 kb/s, 6ch, 48.0 kHz
A: English, AC-3, 192 kb/s, 2ch, 48.0 kHz

T: Japanese, PGS
T: English, PGS
T: French, PGS
T: German, PGS
T: Italian, PGS
T: Swedish, PGS
T: Danish, PGS
T: Finnish, PGS
T: Dutch, PGS
T: Norwegian, PGS
T: Greek, PGS
T: Turkish, PGS
T: Japanese, PGS
T: English, PGS
T: French, PGS
T: German, PGS
T: Italian, PGS
T: French, PGS
T: German, PGS
T: Italian, PGS
T: Turkish, PGS

M: Menu

**Comment by Dendraspis** [comment] 2021-03-25 10:29
What was the source? MKV?

We tested a lot and it worked for us. 🤔

**Comment by 44vince44** [comment] 2021-03-25 10:34
@Dendraspis it's confirmed, it doesn't demux when `all` is set in the preferred languages (i didn't do this test yesterday)

**Comment by 44vince44** [comment] 2021-03-25 10:36
@Dendraspis correction: it doesn't work, you seem to have skipped something when you committed...

**Comment by Dendraspis** [comment] 2021-03-25 10:38
Okay, @44vince44  confirms it doesn't work anymore.  I'll check the merges.  😬

**Comment by stax76** [comment] 2021-03-25 10:43
My preferred languages are defaults:

ger eng und

Sample:

https://www.dropbox.com/s/m1ztdbskjgrbku2/Snow%20White%20and%20the%20Huntsman.mkv?dl=0

**Comment by Dendraspis** [comment] 2021-03-25 12:05
I don't know why we got false positives yesterday, but this must work now:
[StaxRip v2.1.26.zip](https://github.com/staxrip/staxrip/files/6204486/StaxRip.v2.1.26.zip)

**Comment by stax76** [comment] 2021-03-25 12:29
Maybe you looked in the muxer dialog and saw subtitles, these were direct mkv subtitles.

**Comment by Dendraspis** [comment] 2021-03-25 13:12
But they should not appear with this setting.  🤔  
I think it could have been more obvious with your sample, with a lot of subtitles. At least it's fixed now and thankfully it was no merging issue. 🤝

**Closed by Dendraspis** 2021-03-25 13:12 UTC
Labels: added/fixed/done, feature request, priority high, question

**Comment by stax76** [comment] 2021-03-25 15:17
I'm sorry there is still a bug. 🙂

Last option 'Don't include subtitles' includes preferred subtitles directly.

**Comment by Dendraspis** [comment] 2021-03-25 16:06
I'm fix it yet ... I'm still searching the cameras.  😁 🙄 

[StaxRip v2.1.32.zip](https://github.com/staxrip/staxrip/files/6206147/StaxRip.v2.1.32.zip)

> I'm sorry there is still a bug. 🙂

And because of that you have to smile??  😜 
But thanks for the help.  😂  😜

**Comment by wrzlpete** [comment] 2021-03-26 02:20
I only tested out the 2nd option "Demux preferred languages but don't include them" and it seems to work perfectly. Amazing stuff! Thanks a lot 👯
