### ISSUE TITLE
New icon feedback

### ISSUE THREAD

**Issue by nulledone** [staxrip/staxrip#1] opened 2019-05-15 15:51 UTC
New icon looks awesome but it is plain black so it is harder to notice on dark color scheme, I suggest adding thin white strikes around the logo will make it perfect. Also I always loved the old 'RIP Tombstone' logo, is there any chance you could embed it into executable as well?

Anyway, thanks a lot for your continuous support for this awesome piece of software.

**Comment by stax76** [comment] 2019-05-16 11:25
Thanks for the feedback. I don't have the expertise to change this icon. I just picked a new one for the next built, I found it here:

https://www.flaticon.com/search/8?word=movie

This is how it looks:

![NewIcon](https://user-images.githubusercontent.com/11410540/57850394-1c22d280-77de-11e9-9a88-92c5c6e8de66.png)

**Comment by fmohican** [comment] 2019-05-16 13:36
+1 for 'RIP Tombstone'

**Comment by stax76** [comment] 2019-05-16 17:20
> Also I always loved the old 'RIP Tombstone' logo, is there any chance you could embed it into executable as well?

Maybe if it's not too hard to do, the black color of the Tombstone icon is however not dark mode compatible.

**Comment by Revan654** [comment] 2019-05-16 18:41
-10 for RIP StaxRip, Since the project is not dead.

If the UI was ever changed to WPF(Since it seems MS wants to kill off WinForms & VB). I created a very fast mock up of what can be done to modernize it. I threw this together in about 30 seconds, so there zero style to it just the basic format.

![cv0tR3S](https://user-images.githubusercontent.com/38091898/57878667-88a2cf00-77e8-11e9-8199-687c7f398a31.png)

**Comment by stax76** [comment] 2019-05-16 23:05
I'll try to include multiple icons. C# seem to have designer support for this and VB.NET don't, but I guess it's possible to edit proj file.

@Revan654 

It's not a problem to do new forms in WPF or rewrite basic forms but the codec form and particularly the main form would be extremely difficult to do in WPF.

**Comment by stax76** [comment] 2019-05-17 00:00
I've further researched adding multiple icons, it's possible but not in a clean, I do not like doing what it requires.

https://stackoverflow.com/questions/1832583/embed-multiple-icons-in-wpf-exe

https://stackoverflow.com/questions/3485103/automatically-embed-multiple-icons-in-a-net-executable

**Comment by nulledone** [comment] 2019-05-20 19:30
I tried my best to make a new icon with my requested changes. 
[NewIconStrike.zip](https://github.com/staxrip/staxrip/files/3199487/NewIconStrike.zip)

It looks like this (grey area being transparent
![new](https://user-images.githubusercontent.com/29547468/58046745-d9028f80-7b4e-11e9-8785-ca6b87d7b6f2.png)

**Comment by stax76** [comment] 2019-05-20 21:24
@nulledone 

Thanks for the work, I try to find a solution that everybody can agree with.

**Comment by ilko-k** [comment] 2019-05-28 15:24
@stax76 hey, I've basic skills in pictur eediting, may I try something for you ?

**Comment by stax76** [comment] 2019-05-28 16:50
@ilko-k That would be awesome! Gray instead of white stroke was requested in the doom9 forum but you may try whatever you like.

**Comment by ilko-k** [comment] 2019-05-28 17:05
@stax76 I have some ideas I'm already working on. Find me on discord : 
Zendama#7485

**Comment by fmohican** [comment] 2019-05-28 18:32
Stax can you made a discord server for us?

**Comment by stax76** [comment] 2019-05-28 18:43
I don't really know discord but I'll investigate it.

**Comment by ilko-k** [comment] 2019-05-28 18:58
@stax76 it's like skype, but a loooooot better. You can create/manage your own chat server with several channels. I wanted to show you my progress, I got some pretty good resulsts IMO.

**Comment by fmohican** [comment] 2019-05-28 22:16
> I don't really know discord but I'll investigate it.

Thank you for taking care of us and our opinions, and we also thank you for the wonderful staxrip which makes our ""business"" easier.
I firmly believe that Discord would ease and facilitate communication with us ""ordinary"" users.

**Comment by vanontom** [comment] 2019-05-29 06:21
Finally switched over to StaxRip 2.x, after enjoying 1.7.x for... a long time! Gonna miss the "RIP tombstone" icon. :) Frankly this grey icon made me sad, so I finally created one myself. You're all welcome to use it. Probably long overdue; StaxRip has been one of my favorite apps for years. Thanks @stax76 and all contributors! If you have any requests for changes, I can modify and share a few more versions. (Colors? Kept it grey for now. My priority was Windows 10 Dark, but should be fine on Light as well.)

![StaxRip 2020 Grey](https://user-images.githubusercontent.com/6421376/58534051-cec83d00-81af-11e9-859a-ddb8c1bcf028.png)

[StaxRip_2020_Grey_Icon_Vanontom.zip](https://github.com/staxrip/staxrip/files/3230992/StaxRip_2020_Grey_Icon_Vanontom.zip)

**Comment by ilko-k** [comment] 2019-05-29 15:04
@stax76 you decide...
![sr](https://user-images.githubusercontent.com/5411848/58568002-ba2d8880-8233-11e9-8fef-9b05effb9b04.jpg)

**Comment by stax76** [comment] 2019-05-29 19:48
@ilko-k 

Thanks for the effort, I like it. Do you have it in better quality  like PNG?

I've used this site to create icon files:

https://icoconvert.com

> Stax can you made a discord server for us?

I've created a channel/server at discord as 'stax76' just to explore it. I don't use social media usually but maybe I should start using, the web interface of discord sure looks nice, I like it. Maybe part of the problem is I don't play games, I mean I used to play games in my youth like everybody, today I listen to music and watch TV shows, nice beat here:

https://www.youtube.com/watch?v=aNsvCICmGJQ&list=PLnVfFuh_eWkHea5HbrAxu8PaL4frxuiA7&index=83&t=0s

> Thank you for taking care of us and our opinions, and we also thank you for the wonderful staxrip which makes our ""business"" easier.
> I firmly believe that Discord would ease and facilitate communication with us ""ordinary"" users.

Yes, I check it out.

> Frankly this grey icon made me sad, so I finally created one myself. You're all welcome to use it. 

I liked the simplicity of the grey one. Thanks for the effort, I like it.

**Comment by ilko-k** [comment] 2019-05-29 21:20
@stax76 I can compile an .ico file with several resolutions from16x16 to 256x256, just tell me wich one(s) you wish from the overview. Consider that the one located on top left is n°1.

Also, for us to be able to join your server, you must share the invite link. You can create permanent or temporary link, it's up to you. Just right clic on server's icon, then invite people. Expiration time is displayed at the bottom of the invite popup and you can edit it from there.

**Comment by ilko-k** [comment] 2019-05-30 15:42
![image](https://user-images.githubusercontent.com/5411848/58644732-2d053500-8302-11e9-8af1-234bcffc1a9b.png)

**Comment by stax76** [comment] 2019-05-31 05:15
@ilko-k 

I always use the default option 'ICO for Windows 7, Windows 8, Vista and XP'

discord server is called:

staxrip

permanent invite link is:

https://discord.gg/rRn7vGU

icon choice:

![icons](https://user-images.githubusercontent.com/11410540/58683044-4db9a300-8373-11e9-854f-bac2bebe8883.png)

**Comment by ilko-k** [comment] 2019-05-31 11:33
@stax76 thanks for your choices. I sent you the files via Discord.

**Comment by fmohican** [comment] 2019-06-09 09:14
> permanent invite link is:
> 
> https://discord.gg/rRn7vGU

Try to put in `readme.md`

**Comment by Revan654** [comment] 2019-06-29 20:20
Small Issue with the new Icon System. If you don't point textbox to ico file it defaults to ms icon for all the child containers /  Windows.

**Comment by stax76** [comment] 2019-06-30 19:52
@Revan654 

It should be fixed now.

**Closed** 2019-09-11 22:14 UTC
