### ISSUE TITLE
StaxRip no longer recognizes DGDecNV/DGIndexNV in version 2.1.3.0

### ISSUE THREAD

**Issue by Vrael0n** [staxrip/staxrip#274] opened 2020-07-14 19:05 UTC
Staxrip 2.0.8.0 detects DGDecNV/DGIndexNV when they are added in the Support/Plugins-Dual folders. This is no longer working in release 2.1.3.0, it is very useful for 4K media as it is much lighter on CPU when hardware decoded. Because of this I'm currently stuck on 2.0.8 and can't upgrade.

2.1.3.0
![2 1 3 0](https://user-images.githubusercontent.com/61518774/87465611-cc9a8b00-c5c9-11ea-93d8-4bcfe38b89c6.png)

2.0.8.0
![2 0 8 0](https://user-images.githubusercontent.com/61518774/87465637-d91ee380-c5c9-11ea-844c-9775c02ec508.png)

Folder structure (DGIndexNV added but not recognized in StaxRip)
![DGNV](https://user-images.githubusercontent.com/61518774/87465828-2438f680-c5ca-11ea-8556-65f4aea86806.png)

**Comment by stax76** [comment] 2020-07-14 19:16
Please note the L-Smash-Works fully supports hardware decoding and staxrip even has GUI support for it in the source filter context menu of the code editor.

Duplicate of #201

**Closed by stax76** 2020-07-14 19:16 UTC
