### ISSUE TITLE
Staxrip stops responding if jobs window is open when it tries to go to next job

### ISSUE THREAD

**Issue by alastair-swan** [staxrip/staxrip#482] opened 2021-01-27 05:19 UTC
Bug: Jobs window and it's source processing window will stop responding in some circumstances.

Steps to replicate:
- have a long queue of jobs
- Run 2 or more parallel processing instances
- Open jobs window from one of the two processing instances
- wait for a different instance to complete it's current job and start a new job
- try and interact with open jobs window.

Specifics:
- queue length was >2000.
- all jobs were nvenc hevc video and mp3 audio contained in mp4.
- source files were on a network drive
- temp files were on a local drive
- the frozen processing window would finish it's current processing step and then go blank, it would continue once it started responding again.
- version 2.1.7.0

**Comment by 44vince44** [comment] 2021-01-27 09:13
Try beta 2.1.7.6

**Comment by Dendraspis** [comment] 2021-01-27 10:56
> queue length was >2000.

I'm curious if anybody would try to reproduce that.  🤣 
I would never think of queuing so many jobs!  😲   But it works for ~200 jobs?

**Comment by JJKylee** [comment] 2021-01-27 13:09
I dare not, either. I'm outta here. 😝

**Comment by 44vince44** [comment] 2021-01-27 13:42
I once did that for a user, and couldn't reproduce his problem (with more than 1000 jobs) I'm not doing it again....

HOWEVER I noticed something in recent pre-betas or maybe betas (I'm not sure when it began): sometimes after a batch is finished, the icon of staxrip in the taskbar disappears and is not restored:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/105999226-1bb39380-60b6-11eb-9abb-00c940b3eba2.jpg)

So, the following happens sometimes:

![SNAG-0000 - Copy](https://user-images.githubusercontent.com/17828567/105999239-1fdfb100-60b6-11eb-9316-f864673b7d32.jpg)

**Comment by 44vince44** [comment] 2021-01-27 15:41
@Dendraspis I'm not being able to reproduce that... Maybe has been fixed (hopefully) !!

**Comment by stax76** [comment] 2021-01-31 12:19
> sometimes after a batch is finished, the icon of staxrip in the taskbar disappears and is not restored

If it's caused by a staxrip change then maybe this:

- Optional customized/shorter progress text while encoding for x264/x265 (Dendraspis)

This area is performance and stability critical, complex and uses asynchronous processing which is by nature complex, so it has to be reviewed and tested as good as possible.

But there isn't any taskbar icon code in staxrip, that are windows internals.

**Comment by stax76** [comment] 2021-01-31 12:30
I've reviewed it now, it should not cause any kind of problem.

**Comment by Dendraspis** [comment] 2021-01-31 14:43
> I've reviewed it now, it should not cause any kind of problem.

Especially because it was 2 weeks later implemented and even not officially published yet.  😁  The used version was v2.1.7.0.  😉 

I'm guessing a busy network (share).  🤔

**Comment by stax76** [comment] 2021-01-31 17:36
🙂

I should use the code editor more often instead of WhatsApp, complicated affair.

**Comment by Dendraspis** [comment] 2021-02-04 13:48
@alastair-swan 
Could you show us the content of Code Editor or Code Preview? Do you use lots of scripts?

**Comment by alastair-swan** [comment] 2021-02-05 07:08
@Dendraspis 
no scripts at all, was actually a fresh install because I just reset this computer. 
The problem seems to be related to how staxrip updates the jobs window. the problem got better as the queue size decreased and worse when the individual jobs were very short.
Basically, when the queue length was very long, it would take about a minute to update the jobs list if it was open. If another job finished within that minute the minute would be extended by another minute. this would continue until no jobs were completed for a sufficiently long period of time.

**Comment by Dendraspis** [comment] 2021-02-05 07:14
> The problem seems to be related to how staxrip updates the jobs window

Yeah, it is indeed not meant to hold that many entries.
Sadly taking care of it would need an overhaul of a lot of code.  Try to keep the queue short, for example by using multiple instances with their own settings/queue.

**Comment by alastair-swan** [comment] 2021-02-05 07:29
I've downloaded the code, I'm going to take a crack at it because I can't think of a reason that it should matter what the queue length is.

> Try to keep the queue short, for example by using multiple instances with their own settings/queue.

I would love to know how to have multiple queues because it would be nice to have separate queues for cpu vs gpu encodes. Is it as simple as just multiple install directories?

**Comment by Dendraspis** [comment] 2021-02-05 09:17
You need to extract the 7z file into different folders, so you end up with something like:
`D:\StaxRip-1\StaxRip.exe`
`D:\StaxRip-2\StaxRip.exe`

When you start StaxRip it asks you for a settings folder, where you can decide to use sub-folder, meaning:
`D:\StaxRip-1\Settings\`
`D:\StaxRip-2\Settings\`

You can set-up `StaxRip-1`, close it and copy its settings to `D:\StaxRip-2\Settings\`, so you get 2 identical instances with their own queues.

Not perfect, but it has its own advantages.

**Closed** 2021-02-11 14:54 UTC
Labels: not reproducible, priority low
