### ISSUE TITLE
Staxrip 2.1.4.8 and x265 multipass options not correctly applied

### ISSUE THREAD

**Issue by sibylantonioforanna** [staxrip/staxrip#389] opened 2020-12-08 10:51 UTC
**Describe the bug**

Using x265 as encoder:
1) option "--pass2" is applied at pass 3 and "--pass3" is applied at pass2
2) option "--analysis-save <filename>", --analysis-save-reuse-level, "--analysis-load <filename>" and --analysis-load-reuse-level are all applied at first pass
3) "Custom Third Pass" text edit box is missing (this might be seen as a feature missing or a bug in the flow)

**Expected behavior**

1) option "--pass2" has to be applied at pass 2 and "--pass3" has to be applied at pass3
2) option "--analysis-save <filename>" and --analysis-save-reuse-level must be applied at pass 1 (or optionally at pass 2 if 3 passes are chosen), instead "--analysis-load <filename>" and --analysis-load-reuse-level must be applied at pass 2 (and/or optionally at pass 3 if 3 passes are chosen)
3) Show a "Custom Third Pass" text edit box either always or when choosing 3 passes

**Provide information**

log bug 2) Video encoding returned error exit code: -1073741819 (0xC0000005)

**Comment by Dendraspis** [comment] 2020-12-10 10:55
Current state:

1. Fixed
2. *Not yet*
3. Fixed

**Comment by Patman86** [comment] 2020-12-10 14:07
Your changes are not correct, see [here](https://github.com/staxrip/staxrip/pull/315)

**Comment by Dendraspis** [comment] 2020-12-10 14:11
@Patman86 
Thanks, I'll have a look ... but I'm a little bit confused.  😁

**Comment by sibylantonioforanna** [comment] 2020-12-10 14:17
If you need clarifications just ask.
I'll reply as soon as I can.

**Comment by Dendraspis** [comment] 2020-12-10 14:28
Okay, as far as I read and understand the docs, the current order (before your fix and after mine) is right:
**Pass 1 » Pass 2 » Pass 3**

From the docs:
1. First pass, creates stats file **[» Pass 1]**
2. Last pass, does not overwrite stats file **[» Pass 3]**
3. Nth pass, overwrites stats file **[» Pass 2]**

This is written in such way because it's possible they would add a fourth and fifth pass. So the first and last passes are specific and every other (Nth) pass does the same.

**Comment by sibylantonioforanna** [comment] 2020-12-10 14:40
I don't fully understand your question, but I'll try to clarify what I meant.
If you run an encode on a short video for test you'll se printed on the window in order
--pass1, then --pass 3, then ---pass 2
For what I understand the pass number should instead be increasing by 1 at every step.

If you're talking about reuse-level, those stats are decoupled by regular stat files and the load command can't be used before or with the save command but only afterwards.

**Comment by Dendraspis** [comment] 2020-12-10 14:44
@sibylantonioforanna 
No need to explain. Your request is clear. The problem is a different understanding/interpretation of the x265 docs.
For @Patman86 the order **1 » 3 » 2** was right and implemented on purpose.

**Comment by sibylantonioforanna** [comment] 2020-12-10 15:10
Ah, ok, so the number doesn't indicate the pass number but the type of pass.
I don't actually use three passes, I was just curious to see if the quality increases by applying some further refinement. 
Btw I usually use quality mode and I use 2 passes if the size of the video doesn't go down enough in terms of size.

**Comment by Dendraspis** [comment] 2020-12-10 15:16
> Ah, ok, so the number doesn't indicate the pass number but the type of pass.

That's the point. As far as I understand the docs they say, that **1 » 2 » 3** is right.  😄 

> I don't actually use three passes, I was just curious to see if the quality increases by applying some further refinement.

AAhh, I see.  😄 

> Btw I usually use quality mode and I use 2 passes if the size of the video doesn't go down enough in terms of size.

I such cases I increment the CRF value - works great.  😁

**Comment by sibylantonioforanna** [comment] 2020-12-10 15:33
> I such cases I increment the CRF value - works great

I find that 26 is the max value I can set the quality, increasing it's value further I find that the video quality degrades too mutch uniformly, using 2 passes instead I personally find that the programs distributes better the quality degradation where it is less noticeable.

**Comment by Dendraspis** [comment] 2020-12-10 15:57
Interesting. 😊  I only use CRF in order to get almost-original picture quality.

But point 2 will take a while.... be patient.

**Comment by sibylantonioforanna** [comment] 2020-12-10 16:07
No problem, I solved it temporarily by using
Custom First Pass="--analysis-save "%temp_dir%reuse_level.stats" --analysis-save-reuse-level 10"
and Custom Second Pass="--analysis-load "%temp_dir%reuse_level.stats" --analysis-load-reuse-level 10 --scenecut-aware-qp"

**Comment by 44vince44** [comment] 2020-12-13 04:11
@Dendraspis :   

@Patman86 is right, the correct option for multipass is

pass1
pass3
pass4
....
pass n
pass2

this is important for x264 and x265 :
**pass 2 is always  LAST PASS**

**Comment by 44vince44** [comment] 2020-12-13 05:10
@Dendraspis please can you be so kind as to put a comment **INSIDE the code** about order "pass 1 >  pass 3 > pass 2 is the correct order - see docs" so no one working on the code is tempted in future to change that (anyone who doesn't use multipass can be tricked and think it's an error).   
This order is for x264 and x265.

**Comment by Dendraspis** [comment] 2020-12-13 08:23
@44vince44 
Thanks for providing the current state of the docs as screenshot, that prove I'm right. 😋
Your explaination is correct, except that you mix up the numbers. 
I really would like to know why you guys think 'last' is the second pass - just because it's listed on second position?

**Comment by Patman86** [comment] 2020-12-13 08:33
> @44vince44 
> Thanks for providing the current state of the docs as screenshot, that prove I'm right. 😋
> Your explaination is correct, except that you mix up the numbers. 
> I really would like to know why you guys think 'last' is the second pass - just because it's listed on second position?

Not the second pass, the option --pass 2 is always the last pass 😜 to clarify that, I'll ask in the doom9 forum 😝

**Comment by 44vince44** [comment] 2020-12-13 08:34
@Dendraspis
Last is a --pass 2 command. I Never said it's "second"

**Comment by Dendraspis** [comment] 2020-12-13 08:43
Yes, I meant the right thing but seems I messed up describing it right for you. "Second pass" should mean "Pass 2".

**Comment by 44vince44** [comment] 2020-12-13 08:45
@Dendraspis I think it's easy to mess up... it's better to show in a scheme like you did:

--pass 1 > --pass 3 > --pass3 > --pass 3 > -- pass 2

**Comment by Dendraspis** [comment] 2020-12-13 08:56
@44vince44 
And that order is wrong in my opinion. A 6-pass would look like
**1 » 2 » 3 » 4 » 5 » 6**
where
1 is first,
6 is last and
2, 3, 4, 5 are Nth

Your last screenshot shows the problem. You guys think the numbers have to do something with the order. I think it's just a numbered list.

**Comment by 44vince44** [comment] 2020-12-13 09:08
@Dendraspis
No, because pass 2 command doesn't change the data in stats file. You need to change the stats files when you expect that there will be another pass later.
This is why pass 2 command is at the end because it doesn't change the stats file, because it's final.

The principle of multipass is to make the stats better at every pass.
-- Pass 1 : creates and writes stats
-- Pass 3, 4, 5, 6 : uses existing stats and re-writes them better
-- Pass 2 : uses existing stats, does NOT re-write them, because pass 2 is final, no more passes after

**Comment by 44vince44** [comment] 2020-12-13 09:30
Look here is how the documentation works:

![SNAG-0001](https://user-images.githubusercontent.com/17828567/102008050-68295680-3d36-11eb-96a2-87b2401aa46e.jpg)

So this should clearly remove any doubts:

![snagg](https://user-images.githubusercontent.com/17828567/102008080-93ac4100-3d36-11eb-9624-6ba1f2b48edf.jpg)

**Comment by Dendraspis** [comment] 2020-12-13 09:32
> No, because pass 2 command doesn't change the data in stats file. You need to change the stats files when you expect that there will be another pass later.

That's the point: there is nowhere written that pass 2 is the one that doesn't change the stats file. There is only written, that **the last pass does not overwrite the stats file**. The number before ***"Last pass"*** is just a numeration. You should try to try it this way:
- First pass, creates stats file
- Last pass, does not overwrite stats file
- Nth pass, overwrites stats file

So from my point of view this should be your example:
-- Pass 1 : creates and writes stats for the first
-- Pass 2, 3, 4, 5 : uses existing stats and re-writes them better
-- Pass 6 : uses existing stats, does NOT re-write them, because pass 6 is final, no more passes after

Sorry, I don't know how to better explain the issue and why my sight should be the right one. This becomes more and more a dog biting his own tail.

**Comment by 44vince44** [comment] 2020-12-13 09:35
@Dendraspis just do a test.
Create a 3 pass encoding and you'll see if command --pass 2 changes anything. And then you'll be sure.
I'm sorry to see that you are ignoring my efforts to show you that the documentation says Integer, then lists 1.2.3, it means Integer = 1 or 2 or 3. This is how docs work.

**Comment by sibylantonioforanna** [comment] 2020-12-13 09:35
Sorry guys for having started all this.
Not having ever used 3 passes before I messed up understanding the docs.
Of course you can't change the command line arguments, but, if you want, you can label the commands in the gui to make things more clear, like...  "Pass 2 (last)" and "Pass 3 (in between passes), or you can write it down into staxrip documentation, since that of x265 isn't really clear and you have to read it very carefully.
Just a quick question guys, i know, i must be blind, but how do I specify the number of passes when I choose to use the option "3 passes"?

**Comment by 44vince44** [comment] 2020-12-13 09:38
@sibylantonioforanna there is no setting to do more than 3 passes, I think, Besides there are discussions on forums that shows that there is no real need for that. Multipass is not a new concept. There are old threads where the coders of x264 comment that multipass with more than two pass is not really useful.... So it's up to the coders to see if they implement that.

**Comment by Dendraspis** [comment] 2020-12-13 09:44
@44vince44 
> [..] that the documentation says Integer, then lists 1.2.3, it means Integer = 1 or 2 or 3.

**--pass < integer >**
*< integer >* refers to ***Range  of values: 1 to 3***, not the numbered list. 

I loose all my common sense and my coding ability if ***1 » 3 » 2*** is right.  😞

**Comment by sibylantonioforanna** [comment] 2020-12-13 09:52
Well, in fact using 3 passes I didn't gain anything, but I didn't try using the options to refine intra, inter and mv.
Btw at the address you pointed me to someone has written how to use the --pass command.

**Comment by 44vince44** [comment] 2020-12-13 09:54
@Dendraspis just do the test. If unsure, refer to serious forums.
I just did a test with 2.1.4.8 that follows the order --pass 1 > -- pass 3 > -- pass 2 
- pass 1 done, the stats file is created, CRC 7b989d71
- pass 3 done, the stats file is indeed modded because the CRC is now 2c581d48 
- pass 2 done, the stats file has not be modded, it CRC is still 2c581d48

**Comment by 44vince44** [comment] 2020-12-13 09:58
@sibylantonioforanna Look at the link I provided you, you'll learn interesting things from the coders of x264 (x265 can be considered similar, in those kinds of principles). To the question "What do you think about using more than two passes?", the coder answers:

> Useless waste of time. 99% of any benefit you'll get from it can be gotten by running the first pass with --slow-firstpass instead running a third pass, and even that benefit is tiny.

**Comment by 44vince44** [comment] 2020-12-13 10:01
> 
> 
> Well, in fact using 3 passes I didn't gain anything, but I didn't try using the options to refine intra, inter and mv.
> Btw at the address you pointed me to someone has written how to use the --pass command.

I know, it's everywhere, I'm surprised we're actually having this conversation about the order ... But I prefer to convince @Dendraspis rather than leave a regression...

**Comment by 44vince44** [comment] 2020-12-13 10:08
> 
> 
> I loose all my common sense and my coding ability if _**1 » 3 » 2**_ is right. 😞

@Dendraspis don't worry my friend, you'll get over it ;-)

**Comment by Dendraspis** [comment] 2020-12-13 11:25
Okay, I got it. One more time the docs tell #*!%$+, at least not the whole truth.

- Pass 0 is theoretically supported.
- Pass 1 can only write the stats file.
- Pass 2 can only read the stats file.
- Pass 3 can read and (re-)write the stats file.

So a multi-pass can be realized doing multiple executions of pass 3 like ***1 » 3 » 3 » 3 » 3 » 3 » 2*** - therefore pass 3 is called the ***Nth pass***.

🎉  Finally the wrong order seems to be the right one.  😡 💢 😡 
Sorry for confusion and mess and the waste of time!  😞 
I already reverted my changes, so @Patman86 's fix is the current state again.

So I lost my common sense and my coding ability .... great. I'm out.

**Comment by 44vince44** [comment] 2020-12-13 11:50
@Dendraspis thanks my friend ! those things happen ;-)
Can you please put a comment next to the code so no one will be tempted to change that in the future ?

**Comment by 44vince44** [comment] 2020-12-13 11:58
@Dendraspis @Patman86 

Can i please suggest the following, only for THREE pass mode :
When logging, instead of saying:
First pass (--pass 1)
Second pass (-- pass 3)
Third pass (--pass 2),

Can't the text be:
First pass (--pass 1)
Intermediate N pass (--pass 3)
Last pass (--pass 2)

**Comment by Dendraspis** [comment] 2020-12-13 12:04
> Can you please put a comment next to the code so no one will be tempted to change that in the future ?

You mean there are more idiots out there?? 😱😨😲

**Comment by Patman86** [comment] 2020-12-13 12:08
In the selection, I would only mention the 2-pass encode and then the n-pass encode.  When selecting the n-pass encode, a separate field is shown in which you can select the number.  The naming would generally be displayed as n-pass encode.  So my suggestion

**Comment by Dendraspis** [comment] 2020-12-13 13:06
I renamed them to:

- Video encoding first pass
- Video encoding Nth pass
- Video encoding last pass

...to not expand the strings too much. Hope this is okay for you.
Regarding the utterly uselessness I would not even thinking about creating the ability to recall pass 3 more often.  🤔 

I also added a short comment, that order 1 » 3 » 2 is correct.  🙄

**Comment by 44vince44** [comment] 2020-12-13 13:26
Wow that's great!!! thanks !!

**Comment by 44vince44** [comment] 2020-12-13 13:29
> 
> 
> > Can you please put a comment next to the code so no one will be tempted to change that in the future ?
> 
> You mean there are more idiots out there?? 😱😨😲

Oh come on @Dendraspis! no one said that ;-)))) it was really tricky and the docs are ambiguous. They could be interpreted as you did. For something that defies common sense, they should have illustrated the docs with an example.

**Comment by 44vince44** [comment] 2020-12-13 13:55
@sibylantonioforanna about the missimg "custom 3rd pass", currently here are the options:
- Custom: items here apply to all encoder commands issues (including single pass, 2 pass and 3 pass, all passes are affected)
- Custom first pass: applies ONLY to the first pass, in 2 pass and 3 pass modes
- Custom Second pass: applies ONLY to the 2nd pass in two pass mode, and to the Nth pass AND Last pass in three pass mode. (It should be called Second, Nth and Last pass options)

Isn't that enough ? Do we really need a separate custom field for the pass 2 and pass 3 commands ?

**Comment by 44vince44** [comment] 2020-12-13 14:12
@sibylantonioforanna 

> option "--analysis-save " and --analysis-save-reuse-level must be applied at pass 1 (or optionally at pass 2 if 3 passes are chosen), instead "--analysis-load " and --analysis-load-reuse-level must be applied at pass 2 (and/or optionally at pass 3 if 3 passes are chosen)

Are you sure ? do you really know why ? these can be used in single pass encoding as well as multipass.
In multipass encoding, some of them can be used at any pass. If you really want to control what happens at what pass, you need to use the custom fields.

**Comment by Dendraspis** [comment] 2020-12-13 15:19
@44vince44 

> Oh come on @Dendraspis! no one said that ;-)))) 

Therefore I said it - this is called self-fooling. 😄 

> [..] they should have illustrated the docs with an example.

Or just clarify, that pass 3 can be executed multiple times. 
But hey, you guys were right and I'm wrong. Thanks for holding my hand.  😉 

> Isn't that enough ? Do we really need a separate custom field for the pass 2 and pass 3 commands ?

This was already fixed/added by me - was just a quick job and there was enough space for another textfield:
![SR](https://user-images.githubusercontent.com/50659978/102015923-9458cd80-3d5e-11eb-9430-72980b890000.JPG)

**Comment by 44vince44** [comment] 2020-12-13 15:43
OK thanks ;-) so now this whole thread is solved, including the "--analysis-save --analysis-save-reuse-level etc..."  stuff, since user can control everything at every step.
 I'll test that when the beta's out....

**Comment by sibylantonioforanna** [comment] 2020-12-13 16:02
@44vince44 
if you tell x265 to load and save at the same time the encoding ends immediately

**Comment by 44vince44** [comment] 2020-12-13 20:31
I see. well you can handle it with the custom fields now, right ?

**Comment by sibylantonioforanna** [comment] 2020-12-13 20:50
Well, yes, but that's not the point.
If the option is present in the gui and it isn't working I think the developers are interested in knowing it.

**Comment by 44vince44** [comment] 2020-12-14 05:32
The option was set there with single pass in mind, like most (if not all) switches. Do you have a link to an accurate documentation of those options and how to use them in multi pass?

Are you sure that you are not confusing the **analyze** file with the **stats** file ?

**Comment by sibylantonioforanna** [comment] 2020-12-14 07:20
I just read the docs and used the commands in my previous comment https://github.com/staxrip/staxrip/issues/389#issuecomment-742617174
I could use those commands both for 2 and 3 passes encodings.
I'm sorry I can't supply you more info.

Documentation with links:
`
<dl class="option">
<dt id="cmdoption-analysis-load">
<a class="headerlink" href="https://x265.readthedocs.io/en/master/cli.html#cmdoption-analysis-load" title="Permalink to this definition"><code class="descname">--analysis-load</code><code class="descclassname"> &lt;filename&gt;</code></a></dt>
<dd><p>Encoder reuses analysis information from the file specified. By reading the analysis data written by
an <b>earlier encode</b> of the same sequence, substantial redundant work may be avoided. Requires cutree, pmode
to be off. Default disabled.</p>
<p>The amount of analysis data reused is determined by <a class="reference internal" href="https://x265.readthedocs.io/en/master/cli.html#cmdoption-analysis-save-reuse-level"><code class="xref std std-option docutils literal notranslate"><span class="pre">--analysis-load-reuse-level</span></code></a>.</p>
</dd></dl>
`

**Comment by 44vince44** [comment] 2020-12-14 09:01
@sibylantonioforanna. I REALLY think you are confusing two different things.

**A) Analysis data saving and loading and using**
Analysis-load is useful when you are FULLY ENCODING (not only one pass, full complete encode) and you want to save the data to keep it, because maybe you'll want to use it if you decide later to fully encode the same file with different parameters.
You are confusing this with the STATS that are written are read within the multipass procedure.

1) Here is how to use analysis read write in CRF or any single pass mode

1. - Encode with analyse-save. when encode is finished when you watch video, maybe you decide to tweak, so
2. - Encode again with analysis-load and reuse level, and new parameters. This encode will go faster because it uses previous analysis

Let's say you encode a video in CRF mode. Then you decide to encode it again, but with different parameters. In this 
  
**B) Encoding multipass, and maybe use analysis saving**
Analysis saving IS NOT intended to be used from a pass to another pass.
The data that is required to be passed along between passes is AUTOMATICALLY stored in a stats file (NOT analysis file).
If you use analysis-load in a pass, then THIS PASS WILL NOT BE EFFICIENT, because every pass is supposed to do its OWN analysis, and inprove the STATS file. So you're ruining the quality!

So you shouldn't use analysis files with multipass, except in the following case:
- do pass 1, there is NO MEANING in using analysis files here
- do pass N, there is still NO MEANING in using analysis files here
- do pass LAST, here you can use analysis-save. ONLY HERE

If you watch the final output and decide that you need to re-encode with different encoding parameters, then you can use the analysis files.

- do pass 1, use analysis-load and load-reuse-level.
- do pass N, there is NO MEANING in using analysis files here (or you'll degrade the quality)
- do pass LAST, here you can use analysis-save, but not necessarily because you already have the analysis file.

You must understand that when you do pass 1 with analysis load, the data in the analysis file will be stored in the STATS file and handed to pass N and pass LAST.

This is how it is intended to be used, and if you want to use it at every pass, then it means you are cinfused with the STATS file, which is handled autommatically with no need to select any options or switches.

**Comment by sibylantonioforanna** [comment] 2020-12-14 09:26
Ok,
let's take a step back.
I admit I don't know how to correctly use analysis-save and analysis-load for three passes, but anyways it has been told me previously that 3 passes are useless implying that I shouldn't care about it.
As for two passes I could use those options and I'm already happy with the results I obtained, because while the first pass is a bit slower after disabling pmode option, the second pass is very really fast, so even if this option isn't fixed in the GUI I'm ok with it.
What i'm trying to say here though is that if you enable those options using the controls in the gui the encoding ends immediately/prematurely, that is it doesn't work.
Forget everything else I said because probably it's misleading.

**Comment by 44vince44** [comment] 2020-12-14 12:41
@sibylantonioforanna what i'm trying to explain, to summarize, is that using the analysis-save and analysis-load are very unusual. They are very advanced tasks that allow you to reduce calculation time in special circumstances.
And to use them along with a multipass operation is even more unusual and special.
Advanced users must be aware of that, and ready to use custom switches. We can't expect staxrip to handle all specificities of combinations of advanced switches.
The other thing that I wanted to clarify, is to avoid confusion between stats of multipass operations with analysis files.

**Comment by sibylantonioforanna** [comment] 2020-12-14 13:52
@44vince44 
I don't see it as something unusual, but as a feature long overdue.
By using this feature the first pass slows down because one can't use pmode option, on the other hand the encoding on the second pass is 3 or 4 times faster on my PC because, for what I understand, this option lets you store data that would otherwise be computed again.
Anyway, even if it's an advanced feature, a GUI is there to help the user to use advanced features as easily as possible, if possible it should even let him use them without knowing it.

BTW (at this point I don't know to whom I've to talk to) I've downloaded the new beta of staxrip and under the "Analysis" pane there's a new option not mentioned in the docs of x265: **--analysis-reuse-level**

As soon as I can I'll try to encode a video to verify the other changes.

**Comment by stax76** [comment] 2020-12-14 14:10
> BTW (at this point I don't know to whom I've to talk to) I've downloaded the new beta of staxrip and under the "Analysis" pane there's a new option not mentioned in the docs of x265: --analysis-reuse-level

After a tool gets updated on a developer machine staxrip does automatically search for problems, this includes executing x265 --fullhelp and staxrip then compares the result with the staxrip source code to find discrepancies, it does find both new and remove options so it's quite clever. Have a look in the x265 --fullhelp output.

**Comment by Dendraspis** [comment] 2020-12-14 14:13
> By using this feature the first pass slows down because one can't use pmode option, on the other hand the encoding on the second pass is 3 or 4 times faster on my PC because, for what I understand, this option lets you store data that would otherwise be computed again.

As far as I understand, these feature has nothing to do with passes, only encodes which is confirmed by the docs:
***"By reading the analysis data written by an earlier encode of the same sequence, [..]"***

It looks like this is also the reason why x265 doesn't accept both parameters at the same time, because the *save* file would be a copy of the *load* file.

Is it possible you confused this feature with the stats file like @44vince44 already mentioned? What you seem to look for is a way to store and reuse the stats file after each pass for the next encode to speed up each pass?!


> BTW (at this point I don't know to whom I've to talk to) I've downloaded the new beta of staxrip and under the "Analysis" pane there's a new option not mentioned in the docs of x265: --analysis-reuse-level

Fixed.  😄   Was under ***Analysis 2*** in earlier versions. I've removed it now - seemed to be an (very) old and deprecated parameter. Thanks for that.

**Comment by 44vince44** [comment] 2020-12-14 14:23
Yes, this is a quote from x265_project user on doom9 (it's not just anyone;)))

> Analysis reuse provides the basic framework for more advanced solutions that we are building on top of / around x265 (in UHDkit). I don't want to go into more detail about all of the use-cases, as we've seen our competition already attempting to our methods. The basic idea is to produce solutions that run faster (for live encoding scenarios) and more computationally efficient (for offline encoding scenarios). These modes are not going to provide any benefit to anyone today who is just using x265 alone. They won't produce higher quality. 

from https://forum.doom9.org/showthread.php?t=168814&page=272

Definitely they are not designed to be used with multipass.

Anyway, now with the three custom field, anyone can put any custom switches and do whatever they want.

**Comment by sibylantonioforanna** [comment] 2020-12-14 14:51
I'm puzzled.
You can't use save and load at the same time, but to use load you must have a saved file, what does that brings us to?
By "reading the analysis data written by an earlier encode of the same sequence" I think it means that the video sequence must be the same when you save and load the stat file, that is you can't load a file saved for a video for using it with a different video.
Ok, that user says that the new prcedure won't produce higher quality, but that isn't my goal, it's to speedup a 2 passes computation without loosing much quality, and I was able to do just that: the target size is achieved and the second pass is very much faster than the first one. I also compared the video produced using staxrip and using FFMetrics to have both a subjective and a numeric comparative result.
But, hey, maybe it's just me misusing a tool intended for a different task, but since it works for me...

@Dendraspis and @stax76:  stax76  you're right, the option not in the docs actually appears in x265 --fullhelp of x265 shipped with staxrip...that is surely why it was still present in the gui

**Comment by 44vince44** [comment] 2020-12-14 15:12
@sibylantonioforanna it is NOT supposed to be used inside the multi pass process, I am trying to explain that to you.

1) the "user" x265_project is the CODERS TEAM of x265 
2) I have tried ALL COMMUNICATION MEANS to explain to you that analysis-xxx is NOT FOR using INSIDE the multipass. Multipass is a well defined procedure that uses "stats" and it is handled automatically.
3) you can't use analysis LOAD and SAVE at the same time because analysis files are not "stats" files. Analysis files are currently to save the frames analysis and use this analysis later when you encode the file again with different parameters. Encode again does not mean another pass, It means FULL ENCODE. if your full encode is single pass then use analysis-save, keep it, then use analysis-load when two months laters, you watch the video and you consider that you should use crf 22 instead of crf 24. If your full encode is 3-pass, then use analysis-save on the LAST pass ONLY. Then 2 years later when you watch the video and you say "OH I should have encoded at 2000kbps instead of 1700kbps. So, 2 years later, you create a new job, 3-pass, and you use --analysis-load on first pass ONLY and NOTHING on next passes.

**Comment by Dendraspis** [comment] 2020-12-14 15:17
@sibylantonioforanna 
I think it is meant for re-encodes with same and maybe also different settings. For example if you wanna encode one movie multiple times (with different settings). So the source don't have to be analyzed every time and you only need to spend time on encoding itself. Please read my earlier comment one more time.

@44vince44 
This time I'm absolutely with you.  😄

**Comment by 44vince44** [comment] 2020-12-14 15:20
>
> @44vince44
> This time I'm absolutely with you. 😄

I think between you and I, we have written more than enough documentation on something we never use, because we both use crf 😄😄😄😄😄😄😄

**Comment by Dendraspis** [comment] 2020-12-14 15:29
@44vince44 
Indeed! Thanks for that nice fact - had a big smile on my face while reading. 😄  But it's interesting that others seem to acomplish their goals better with 2-pass.  🤔 

@sibylantonioforanna 
Hope it's clear now?  🤔

**Comment by sibylantonioforanna** [comment] 2020-12-14 15:30
Ok, I definitely got what you mean, it makes sense and it also explains why you think there's no problem in the GUI.
Let's end it here.

**Comment by Dendraspis** [comment] 2020-12-14 15:45
@sibylantonioforanna 
That's great!   👍 
So I close this issue now, because everything is solved and fixed.   ☺️ 

@44vince44 
You deserve it - one more time:   🍺  🍺  🍺  🍺  🍺

**Closed by Dendraspis** 2020-12-14 15:45 UTC
Labels: bug, fixed, priority medium

**Comment by 44vince44** [comment] 2020-12-14 16:01
@sibylantonioforanna anytime !! was a pleasure ! and we all learned something here!
@Dendraspis thanks !!
