### ISSUE TITLE
Target file has 5498 frames, but should have 2749 frames! - Problem with interlaced content. 

### ISSUE THREAD

**Issue by bobdig** [staxrip/staxrip#1322] opened 2024-04-23 11:19 UTC
**Describe the bug**
The QTGMC-Deinterlacer (slower) is producing a wrong and choppy file. I first run StaxRip in Avisynth-Mode, because I forgot that I had deleted all previous settings. 
After I noticed the problem I tried it again, this time I switched to VapourSynth and payed closer attention. I now noticed that although I had enabled QTGMC-Deinterlacer (slower) for interlaced content again, that the target FPS still was reported as 25 where it should be 50.

Then I activated a noise-filter and the target FPS was corrected. I disabled that noise-filter and FPS where still correct. Then I started the encoding and the endfile was also correct, everything worked.

So my guess is there is problem with interlaced content. 

**Expected behavior**

**How to reproduce the issue**

**Provide information**

Frame Mismatch (v2.38.0)

Target file has 5498 frames, but should have 2749 frames!

StaxRip.ErrorAbortException: Target file has 5498 frames, but should have 2749 frames!
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 464

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version v2.38

![Screenshot 2024-04-23 131908](https://github.com/staxrip/staxrip/assets/46788742/d1ca2bca-0f2d-412e-82d5-7e929fde3e47)

**Comment by Dendraspis** [comment] 2024-04-23 20:48
Thanks for the detailed report, I was able to reproduce it.  Seems one of the performance updates has its issues, so I will revert it.

> So my guess is there is problem with interlaced content.

That's right, it's only the information about the target that are broken, the **encode itself is *not* affected**.

A fix is coming soon...

**Comment by IevgenSobko** [comment] 2024-04-24 00:07
I've hit the same issue 2 times already since upgrade to 2.38.
I don't use interlaced video, so it is not related to it.
Instead I have custom filter that selects preconfigured number of frames to do compressibility check. I always disable it for final encode but seems sometime it is ignored when this mismatch warning appears. The final encode is OK.
```
--------------------------- Frame Mismatch ---------------------------

WARNING: Target file has 128978 frames, but should have 2528 frames!
Encoding was probably terminated at 5102.0% with a mismatch of -126450 frames!

--------------------------- Frame Mismatch ---------------------------

Target file has 128978 frames, but should have 2528 frames!
```

**Comment by Dendraspis** [comment] 2024-04-24 04:51
Thanks for the information.
The fix will be released soon, probably tomorrow. In the meantime you can disable `Frame Mismatch` in the project options to not get annoyed after each encode. 😕

**Comment by Dendraspis** [comment] 2024-04-24 09:12
🤔 Basically that should have nothing to do with this issue. But we will see how it looks like after the next fix, maybe there is something that interferes.

**Comment by Dendraspis** [comment] 2024-04-24 12:56
Very interesting...

The next version including the fix will be released soon, so I close this now. Feel free to reopen it when the issue eith the information persist or open a new one in case there are other problems.

**Closed** 2024-04-24 12:56 UTC
Labels: bug  :bug:, added/fixed/done
