### ISSUE TITLE
PCM audio stream with 4 channels (miniDV) Demux audio error

### ISSUE THREAD

**Issue by Kickbub** [staxrip/staxrip#621] opened 2021-03-23 16:11 UTC
[Clip 17_staxrip.log](https://github.com/staxrip/staxrip/files/6191127/Clip.17_staxrip.log)

**Comment by JJKylee** [comment] 2021-03-23 17:19
What an extremely terse report. 😑

Anyway, the cause of the error is that the employed _FFmpeg_ command line fails to get the 2 `DV muxing mode` audio tracks (second and third audio tracks) out of all 3 audio tracks.

FFmpeg error log:

```
Stream map '0:a:1' matches no streams.
```

By contrast, mediainfo fetches the audio streams info correctly. But looking at the audio metadata, you'll see the second and third audio tracks have a different muxing mode (and format settings) compared to the first one.

```
Muxing mode                         : DV
Muxing mode, more info              : Muxed in Video #1
```

Use `MP4Box` preprocessor to demux audio tracks in the `mov` file first, and then encode the demuxed audio files instead.

**Comment by 44vince44** [comment] 2021-03-23 17:48
> What an extremely terse report. 😑

Completely agree, and regret to see people contacting us in such a way.

@JJKylee the problem is that MP4Box is **already** set as preprocessor... I'm happy you took a look at that because I wanted to ask you this:
By default, MP4Box is set as preprocessor for mp4, m4v and mov.

![SNAG-0006](https://user-images.githubusercontent.com/17828567/112193306-71b53b00-8c10-11eb-909a-ced774f47f3b.jpg)

But ffmpeg is doing the extraction... why ?

**Comment by Dendraspis** [comment] 2021-03-23 18:09
This seems to be an intended behavior:
In case the audio stream format is `PCM`, ffmpeg is used to demux it.

Maybe there was a time where MP4Box was not able to do it?  🤔   Is MP4Box now able to do that?

**Comment by Kickbub** [comment] 2021-03-23 18:13
Apologies for the "terse" report.

I'm not sure if I am doing this properly, but when I click the "Tools" tab and select "Demux...", I am left with these two options.

![Stax](https://user-images.githubusercontent.com/17808984/112196567-2158d000-8c46-11eb-8818-fac453820431.png)

Is this the correct way to demux? Or is there another way?

**Comment by 44vince44** [comment] 2021-03-23 18:36
we're looking into it, we think mp4box should be used, and @Dendraspis is investigating the code...

**Comment by JJKylee** [comment] 2021-03-23 18:58
> Is MP4Box now able to do that?

I'm also curious.

It doesn't seem like @Kickbub _intentionally_ disabled the `MP4Box` demuxer as a preprocessor for `mov` files. Then it means `MP4Box` failed to demux audio tracks to separate files for encoding.

@Kickbub, can you check if separate audio files are generated after the source is loaded?

If he didn't choose the audio _tracks_ in the source file intentionally, then it means `MP4Box` definitely failed to generate separate audio files.

**Comment by Kickbub** [comment] 2021-03-23 19:14
There is only one ".wav" file in a temp folder. 

One of the two other tracks in the video is the timecode and I don't know what the last one is.

**Comment by JJKylee** [comment] 2021-03-23 19:26
Then `MP4Box` definitely fails in demuxing the said audio tracks. (Muxing mode DV, muxed in the video stream, big / signed format.)

I'm wondering if there's any way to force `MP4Box` to recognize those audio tracks. Maybe we're missing some parameter settings for those kind of audios. We need to study more.

The same applies for `ffmpeg`.

And if there are not such methods, then it's tool issues. We need to dig further to see if whether it's really tool issues or simply a wrong parameter setting.

Meanwhile, you can try other tools specialized in miniDV format videos, @Kickbub. But I cannot think of any as for me. 😅

**Comment by JJKylee** [comment] 2021-03-23 19:44
Another possibility is that the _[DVCPRO](https://www.mediacollege.com/video/format/dv/dvcpro.html)_ video format (where the problematic audio tracks are embedded) is a commercial format that it doesn't allow open source tools like `MP4Box` and `ffmpeg` to demux.

If this is the case, you should use special software for your work. See if it is true by referring to your miniDV manual, @Kickbub.

**Comment by 44vince44** [comment] 2021-03-23 19:50
@JJKylee @Kickbub 

According to @Dendraspis : mp4box will demux mp4/mov sources only if audio is NOT PCM

Why? because Mp4Box fails in extracting ANY PCM stream, I've confirmed it with a test.

So we can't use Mp4box here because it's a PCM, we can only use ffmpeg, and in this specific case ffmpeg fails. It may be possible we have no solution for this kind of files...

@Kickbub 
Please consider doing the following test, it will help us determine if there is a problem with the syntax:

1. open staxrip, go to Tools > Settings
2. In the tab Pre-processing, locate the line Mp4Box and **remove** the tick
3. Press OK to close those setting windows
4. drop the same source file in staxrip, at this stage, no demux will be done, so won't fail
5. set your encoding settings for audio and video, and begin encode
6. whether it succeeds or fails, we need the log file please.

Thank you !

**Comment by JJKylee** [comment] 2021-03-23 22:45
But isn't `ffmpeg` required in audio encoding for either transcoding to `flac`/`wav` or piping to the audio encoder except for `eac3to`? And isn't `eac3to` bad at `mov`?

I guess @Kickbub will have no luck even in the new setting. 😔

**Comment by 44vince44** [comment] 2021-03-24 00:30
oh that's the point of the test, the syntax of ffmpeg when used at that stage, is different (it has not been modded recently)

**Comment by Kickbub** [comment] 2021-03-24 08:10
Here is the log file.
[2021-03-24 - 16.04.01 - Clip 17_staxrip.log](https://github.com/staxrip/staxrip/files/6195327/2021-03-24.-.16.04.01.-.Clip.17_staxrip.log)

There weren't any errors along the encoding process, but the video ended up being 8 hours long according to VLC, and there was no audio.

**Comment by 44vince44** [comment] 2021-03-24 08:36
@Kickbub thanks for doing the test... It appears that although no error was generated, the audio was not extracted correctly.

So this is an issue with ffmpeg, that doesn't seem to work correctly on this type of file, I suggest you do as @JJKylee suggested to you. You can also check on ffmpeg or DVCPRO forums and ask if there is a way out of it. If there is a special combination of parameters we would like to hear about it, maybe we can implement it (we searched and found nothing...)


@Dendraspis  please mark this as a tool issue.

For reference, it appears we can't do much about this special multichannel format in DVCPRO with ffmpeg (which is defined as exceptional demuxer for PCM/WAV streams in mp4/m4v/mov), and even less with MP4Box (which is unable to extract correctly ANY PCM/WAV)

**Comment by Kickbub** [comment] 2021-03-24 09:38
I'm taking a look at the log file and it seems to me that the audio stream 0:2 is the one that is 8 hours long, and stream 0:1 has the correct length (1m33s).

**Comment by Dendraspis** [comment] 2021-03-24 09:42
@Kickbub 
Can you share a short sample around 15-30s with us?

**Comment by Kickbub** [comment] 2021-03-24 09:45
> @Kickbub
> Can you share a short sample around 15-30s with us?

Of the original file?

**Comment by Dendraspis** [comment] 2021-03-24 10:05
Ok, I can see what the problem is. Let's see if we can fix it....

**Comment by 44vince44** [comment] 2021-03-24 10:33
@Kickbub thanks for the file. @Dendraspis tests and mine show that the file IS EXTRACTED indeed, and is present in your temp folder, and the error happens later, when data is handed to the other stages of processing. So the ffmpeg extraction worked fine.
Investigating...

**Comment by 44vince44** [comment] 2021-03-24 10:41
This is some ugly format, no wonder Staxrip fails: here is an excerpt of the original mediainfo

```
ID : | 1
-- | --
Format : | PCM
Format settings : | Little / Signed
Codec ID : | lpcm
Duration : | 7 s 40 ms
Source duration : | 7 s 141 ms
Bit rate mode : | Constant
Bit rate : | 2 048 kb/s
Channel(s) : | 4 channels
Channel layout : | L R
Sampling rate : | 32.0 kHz
Bit depth : | 16 bits

```

Note how Channels = 4 channels and Layout = L,R
so there are two unlabelled channels...

**Comment by JJKylee** [comment] 2021-03-24 11:07
> Here is a link to a different video but from the same camera: https://drive.google.com/file/d/1kcdMMVgmRGgBrrYo6saSsWPoki_8cH-a/view?usp=sharing

The stream layout figured out by Mediainfo:

> 0: Audio 1 (a:0)
> 1: Video 1 (v:0)
> ↖ Audio 2 (a:1) (muxed in the video stream) ⇨ `ffmpeg` fails to recognize this
> ↖ Audio 3 (a:2) (muxed in the video stream) ⇨ `ffmpeg` fails to recognize this
> 2: Timecode data

But `ffmpeg` fails in demuxing since it tries to demux `Audio 2` (which is _not_ recognized by itself) _based on the stream info passed by mediainfo_.

**Comment by Kickbub** [comment] 2021-03-24 11:09
> This is some ugly format, no wonder Staxrip fails: here is an excerpt of the original mediainfo
> 
> ```
> ID : | 1
> -- | --
> Format : | PCM
> Format settings : | Little / Signed
> Codec ID : | lpcm
> Duration : | 7 s 40 ms
> Source duration : | 7 s 141 ms
> Bit rate mode : | Constant
> Bit rate : | 2 048 kb/s
> Channel(s) : | 4 channels
> Channel layout : | L R
> Sampling rate : | 32.0 kHz
> Bit depth : | 16 bits
> ```
> 
> Note how Channels = 4 channels and Layout = L,R
> so there are two unlabelled channels...

For some reason this is the default setup for my DV camera. The other option is to have 2 channel 16-bit audio at 48khz. No idea why this is the case.

**Comment by 44vince44** [comment] 2021-03-24 11:10
For this kind of recording, it is more usual to use 2channel 16-bit audio 48khz...

**Comment by Dendraspis** [comment] 2021-03-24 11:13
Indeed, and it should be preferred, especially you don't have surround mics on your camera (I guess) and the sampling rate is 48kHz instead of 32kHz.

**Comment by JJKylee** [comment] 2021-03-24 11:16
My suggested solution:

Make `ffmpeg` _not decode_ audio streams that it cannot figure out.

I guess we need to fix the `ffmpeg` command line for demux based on this peculiar audio stream type:

```
Muxing mode, more info: Muxed in Video
```

**Comment by Dendraspis** [comment] 2021-03-24 11:33
@Kickbub 
Do you have a sample file with real stereo instead of this strange one ?

**Comment by Kickbub** [comment] 2021-03-24 11:39
I don't because these videos are 20 years old.

**Comment by JJKylee** [comment] 2021-03-24 12:05
Even if we succeed in skipping ffmpeg _demux_ of the problematic audio tracks, there's still another issue: users should not choose those problematic audio tracks in the source file for encoding because it will surely fail in the course of ffmpeg transcoding or piping since _ffmpeg cannot recognize them_.

See this:

![StaxRip_2 1 9 0_DVCPRO_no-demux_issues_20210324](https://user-images.githubusercontent.com/3157518/112305897-71429180-8c5c-11eb-8034-0fa758d24670.jpg)

I skipped the demux process by disabling `MP4Box preprocessor` for `mov` files, but I still have two issues although I was able to bypass the critical error that force-closed StaxRip.

1. Audio delay time is not correct. ⇨ This can be avoided if we make ffmpeg demux only what it can recognize.

2. StaxRip fetches the stream info from Mediainfo.NET which is again based on Mediainfo, so it shows those two problematic audio tracks as if they were available for encoding. This would raise an issue if the user chooses one of those two tracks for encoding since `ffmpeg` will surely fail.

All in all, it seems that the 'mismatch of stream layout info b/w Mediainfo and ffmpeg' seems to be the real culprit for this whole series of issues. We need to report this tool issue to either FFmpeg or Mediainfo... but can we? 🤨😅

**Comment by JJKylee** [comment] 2021-03-24 12:28
But there's a practical solution to this issue that @Kickbub can do on the user's side:

**Remux the `mov` file to an `mkv` file using `ffmpeg`**.

Run this command line in CMD:

```
PATH-TO-STAXRIP\Apps\FrameServer\AviSynth\ffmpeg.exe -hide_banner -i "PATH-NAME-OF-MOV.mov" -c copy "NEW-NAME-FOR-MKV.mkv"
```
(Capital lettered part should be replaced properly.)

You'll get a remuxed `mkv` file (with original codecs/quality preserved) that works nicely in StaxRip.

**Comment by 44vince44** [comment] 2021-03-24 12:28
@JJKylee thanks for your inverstigation, meanwhile you were investigating the issue has been fixed by @Dendraspis . He spotted the problem this morning, fixed it, and he's gonna send a hotfix in a few seconds.

However it remains that the camera is generating very bad files. So here is for you @Kickbub how to do it.

1) get the latest hotfix (@Dendraspis will probably drop it here soon) it's a staxrip.exe file, you'll need to replace the one of your v2.1.9.0 folder

2) in your OPTIONS, ask to be given the choice of the streams you want to demux:
Before loading any file, open the options and set this:

![SNAG-0002](https://user-images.githubusercontent.com/17828567/112309848-8a732e80-8cac-11eb-9b2a-6a55ecb3e6b9.jpg)

At this stage you can save the template so it loads with this option always on

3) load the file, you;ll be requested to select the streams, please remove the tick from the audio tracks 2 and 3 that are fake tracks.
![SNAG-0004](https://user-images.githubusercontent.com/17828567/112310146-e63db780-8cac-11eb-893f-fd10e072b8d7.jpg)

4) carry on with your processing.

If you want to **batch process** the files, then this method will not work, you'll need to remove the tick from Settings > Preprocessing > Mp4Box, and set second track audio as "No Audio" in the main window.

**Comment by JJKylee** [comment] 2021-03-24 12:36
> ![SNAG-0002](https://user-images.githubusercontent.com/17828567/112309848-8a732e80-8cac-11eb-9b2a-6a55ecb3e6b9.jpg)

👍
 
> If you want to **batch process** the files, then this method will not work, you'll need to remove the tick from Settings > Preprocessing > Mp4Box, and set second track audio as "No Audio" in the main window.

In this case, remuxing all to `mkv` files may help.
Choosing `Demux Audio` to `None` and `Copy/Mux` for both video and audio (and second track audio as `No Audio`) produces a nice working `mkv` file.

**Comment by Dendraspis** [comment] 2021-03-24 12:45
@JJKylee 
I love your illustrations.  😁 

> Audio delay time is not correct. ⇨ This can be avoided if we make ffmpeg demux only what it can recognize.

The Audio delay is wrong, but this is what MediaInfo tells us. It seems the container file are wrongly written or something like that. If you test the short Sample `Clip 20.mkv` the first audio gives you:
```
Audio #1
Duration        : 7 s 40 ms
Delay           : 2 min 57 s 978 ms
```

I fixed the audio delay issue now, but there is no clean way to remove wrong or corrupted audio streams. So we keep them, especially under this conditions of 20 years old files.

The solution how to deal with those sources was explained by @44vince44  and @JJKylee , and with this build you also have no delay issues - hopefully.

[StaxRip v2.1.16.zip](https://github.com/staxrip/staxrip/files/6197244/StaxRip.v2.1.16.zip)

@44vince44 
I love your illustrations, too.  😁  😁

**Comment by JJKylee** [comment] 2021-03-24 12:50
Off topic:

![StaxRip_2 1 9 0_Demux-Window_old_checkbox_20210324](https://user-images.githubusercontent.com/3157518/112313198-d4382680-8c64-11eb-9adf-b3efa0dd6b73.jpg)

Sorry, @Dendraspis, but I guess you need to build another hotfix. 😝

**Comment by Dendraspis** [comment] 2021-03-24 12:59
@JJKylee 
No, this is something that we have to accept. I think we talked about it when you were ill and took a break.  🤔 
The audio list could be updated quickly, but subtitles and attachments would require a complete redrawing and re-calculation, so we ended up using the system checkbox everywhere on this window.

Btw:  I made some changes to the Options dialog.  😉

**Comment by JJKylee** [comment] 2021-03-24 13:17
> @JJKylee
> No, this is something that we have to accept. I think we talked about it when you were ill and took a break. 🤔
> The audio list could be updated quickly, but subtitles and attachments would require a complete redrawing and re-calculation, so we ended up using the system checkbox everywhere on this window.

Got it.

> Btw: I made some changes to the Options dialog. 😉

Added `Demux Video`, `Demux Chapters`?

**Comment by Dendraspis** [comment] 2021-03-24 13:26
...let's say  ***moved from preprocessing***, so that all stream types are together.  And I re-ordered the Options list on the left a bit.


I think we can close this one now ...

**Comment by JJKylee** [comment] 2021-03-24 13:26
I've found that all my templates now have `Copy/Mux` in audio encoder settings.
Fortunately, I can modify them and save the template without any reversion (back to `Copy/Mux`) issues.
Lucky that they were audio settings, not video encoder settings. 😅

**Closed by Dendraspis** 2021-03-24 13:26 UTC
Labels: added/fixed/done, bug, tool issue

**Comment by Dendraspis** [comment] 2021-03-24 13:37
@JJKylee 
That was not intended, sorry.  🥴 
I changed the default ***Opus ~250kbps*** audio profile to ***Copy/Mux***, because almost nobody is going to use Opus, especially because it doesn't work properly with mkv.

**Comment by JJKylee** [comment] 2021-03-24 13:42
> ...let's say _**moved from preprocessing**_, so that all stream types are together.

![StaxRip_2 1 16_MP4Box-preprocessor_options_20210324](https://user-images.githubusercontent.com/3157518/112319796-a4d8e800-8c6b-11eb-9298-246424c408b1.jpg)

Yeah, I can confirm it.

> I changed the default _**Opus ~250kbps**_ audio profile to _**Copy/Mux**_, because almost nobody is going to use Opus, especially because it doesn't work properly with mkv.

Isn't it `flac` not `opus` that doesn't work well with `mkv`? 🙄❓

Anyway, it doesn't matter.
The only thing I'm afraid people will complain about is that their template audio settings are _force-set_ to `Copy/Mux` after the fix. 😥

**Comment by Dendraspis** [comment] 2021-03-24 14:12
> Isn't it `flac` not `opus` that doesn't work well with `mkv`? 🙄❓

Nope, Opus has also issues. You can mux them, but they break.

> Anyway, it doesn't matter.
> The only thing I'm afraid people will complain about is that their template audio settings are _force-set_ to `Copy/Mux` after the fix. 😥

Therefore the new Changelog entries have those little sweet checkboxes that indicate such issues.  😬 
But of course I forgot (and probably will forget) to tell, that it might happen this time.

> This reminds me of the _unintended_ video encoder parameter value change every time the default value was reset.
> Do they share the same logic at the code level, by any chance? 🤔

Probably, but this was an one-time issue. Every project was initialized with Opus audio profiles, now with *Copy/Mux*. There is no need for more changes.

**Comment by JJKylee** [comment] 2021-03-24 14:19
> Therefore the new Changelog entries have those little sweet checkboxes that indicate such issues. 😬
> But of course I forgot (and probably will forget) to tell, that it might happen this time.

I bet there will be complaint regardless. 😂

**Comment by JJKylee** [comment] 2021-03-24 14:30
Back to the original issues:

[v2.1.16](https://github.com/staxrip/staxrip/files/6197244/StaxRip.v2.1.16.zip) surely fixes the _audio delay issue_ with manual audio demux selection.

![StaxRip_2 1 16_manual_audio_demux_with_no_delay_issue_20210324](https://user-images.githubusercontent.com/3157518/112327474-b2de3700-8c72-11eb-8dbf-bc9099be70b3.jpg)

👍👍👍

**Comment by kchiem** [comment] 2021-04-10 14:41
When I demux mkv's, normally mkvextract is used.  I have noticed that when one of the audio tracks is PCM, ffmpeg is used instead.  However, this results in a few problems:

1. subtitles are skipped in the demux
2. other audio tracks result in 0 byte files (at least for AC3)
3. not limited to ffmpeg, but PCM and AC3 formats can have gaps, which either needs to be handled with timecodes or have silence inserted in the demuxed track.  The only demuxer that inserts silence for gaps is eac3to, as far as I know.

Thus, can the ffmpeg override be removed and eac3to be used on PCM and AC3 tracks?  I think eac3to can be used for the other tracks as well, to demux all the tracks in a single pass.  Otherwise, a second pass to demux the other tracks should be done with mkvextract.

**Comment by 44vince44** [comment] 2021-04-10 14:59
@kchiem what version of staxrip are you using ??

**Comment by kchiem** [comment] 2021-04-10 15:57
> @kchiem what version of staxrip are you using ??
> 
> If you have updated recently, did you make sure that you started from fresh settings?

@44vince44 old actually, 1.7.0.6.  Was this behavior changed in a more recent release?

**Comment by 44vince44** [comment] 2021-04-10 16:13
Yes absolutely, it has been changed several times. And it has been recently reworked.
So I suggest you try v2.4.0 and please, do not use old settings, that would create major malfunctions.

**Comment by kchiem** [comment] 2021-04-10 19:25
Can you point to a release or releases that incorporated that ffmpeg to eac3to change?

**Comment by JJKylee** [comment] 2021-04-10 19:50
1. Go to [Changelog](https://github.com/staxrip/staxrip/blob/master/Changelog.md).
2. Press `Ctrl+F`.
3. Type in `eac3to` and Enter.

**Comment by kchiem** [comment] 2021-04-10 20:36
> 1. Go to [Changelog](https://github.com/staxrip/staxrip/blob/master/Changelog.md).
> 2. Press `Ctrl+F`.
> 3. Type in `eac3to` and Enter.

I read through the release notes prior to my previous comment and didn't see one that implied ffmpeg demuxing was switched to eac3to.  Maybe you can point it out for me?  Here's everything that matched eac3to:

- Disable *eac3to* preprocessing by default and extend re-muxing with *ffmpeg* to m2ts files (Dendraspis, stax76, JKyle, 44vince44, [#632](/../../issues/632))
- Fix eac3to demuxed tracks not named starting at ID 1. (stax76)
- Fix eac3to AAC quality mode incorrect bitrate estimation (stax76)
- eac3to AAC encoding gets correct default quality value and limits (Dendraspis, #328)
- eac3to demux dialog showed incorrect language default selection (stax76, #318)- Default AAC encoder changed from eac3to to qaac.
- update: eac3to libraries libdcadec and libFLAC
- Updated eac3to, fdkaac & qaac.
- eac3to has been Updated to 3.34

**Comment by 44vince44** [comment] 2021-04-10 20:50
@kchiem the whole demuxing has been rewritten because we had the same problem you described with mp4s.
Chances are it has been fixed, NOT using eac3to, but correcting the way ffmpeg handles it (among other changes).

I suggest you download Staxrip v2.4.0, deflate it in another location than you v1.7.0.6.
Then start it from that other location. This allows you to keep v1.7.0.6.

You can have two or more versions of staxrip on your computer (as long as each one has its OWN SETTINGS folder).

**Comment by JJKylee** [comment] 2021-04-10 20:52
> I read through the release notes prior to my previous comment and didn't see one that implied ffmpeg demuxing was switched to eac3to. Maybe you can point it out for me?

I don't understand. Why do you insist on _pinpointing_ the changes?

There have been so many changes regarding demuxing/remuxing in between releases, so it's pretty meaningless and time-consuming.

Like @44vince44 suggested, use the most recent release version, and come up with an issue thread if you still find an issue.

If you're reluctant because you want to keep old settings, make a separate copy, modify the settings based on your old version, and make a transition afterwards.

**Comment by kchiem** [comment] 2021-04-10 21:54
> @kchiem the whole demuxing of audio,for some cases, has been rewritten because we had the same problem you described with mp4s.
> Chances are it has been fixed, NOT using eac3to, but correcting the way ffmpeg handles it (among other changes).

The problem I described was with mkvs though, not mp4s.  And even if you corrected the problem with ffmpeg ignoring subtitles, that doesn't address the gap issue I mentioned--or is there a flag to ffmpeg that handles it, which I'm not aware of?

> I suggest you download Staxrip v2.4.0, deflate it in another location than you v1.7.0.6.
> Then start it from that other location. This allows you to keep v1.7.0.6.
> 
> You can have two or more versions of staxrip on your computer (as long as each one has its OWN SETTINGS folder).

I'm reluctant to upgrade, because with nearly every release, I've had to re-configure my settings, and rebuild all my templates.  And there have been 4 releases in just the past 20 days.  I'm glad to see that development has become more active, but I don't want to have to spend the effort upgrading, then find that the bug I mentioned is still there, report it again, have it fixed in yet a later version, and then have to spend more effort upgrading to that.

**Comment by JJKylee** [comment] 2021-04-10 22:31
> The problem I described was with mkvs though, not mp4s. And even if you corrected the problem with ffmpeg ignoring subtitles, that doesn't address the gap issue I mentioned--or is there a flag to ffmpeg that handles it, which I'm not aware of?

ffmpeg replaced MP4Box in demuxing PCM audio streams because MP4Box cannot handle PCM streams properly.
IMO, the reason ffmpeg replaced mkvextract is the same.

Maybe you can get around the gap issue by not demuxing the audio, but re-encoding the audio _tracks_ in the source mkv file (= piping or stream mapping via ffmpeg).

IIRC, subtitle bypassing by ffmpeg issue was fixed sometime in the past, but I cannot remember when.

BTW, if you're so wishing to use `eac3to` for demuxing an `mkv` file, why don't you try `Tools` > `Advanced` > `Demux` and launch `eac3to` for the particular mkv file? Enabling `eac3to` for a particular stream type in mkv doesn't look like a good idea because `eac3to` has so many issues and is no longer maintained.

> I'm reluctant to upgrade, because with nearly every release, I've had to re-configure my settings, and rebuild all my templates. And there have been 4 releases in just the past 20 days. I'm glad to see that development has become more active, but I don't want to have to spend the effort upgrading, then find that the bug I mentioned is still there, report it again, have it fixed in yet a later version, and then have to spend more effort upgrading to that.

Understood. But in the same vein, please understand that _we don't work on the past_. If you chose to stick to an old version, then you should understand that there's nothing we can do on our side.

**Comment by 44vince44** [comment] 2021-04-11 13:10
> I'm reluctant to upgrade, because with nearly every release, I've had to re-configure my settings, and rebuild all my templates. And there have been 4 releases in just the past 20 days. I'm glad to see that development has become more active, but I don't want to have to spend the effort upgrading, then find that the bug I mentioned is still there, report it again, have it fixed in yet a later version, and then have to spend more effort upgrading to that.

@kchiem 

We're not asking you to upgrade. Just download the newest version, deflate it anywhere on you hard disk (in a Read-Write location), in a folder called StaxRip2.4.0, far away from your 1.7.0.6 folder, and on first launch, when asked where you want to put the settings, select the first choice, which will create a settings folder inside the Staxrip2.4.0 folder. This way, the new settings will NOT interfere with the old settings.
Then you'll be able to check if your file still has demuxing issues, which is the expected information we're waiting for.
This and the mediainfo of the source file...

As @JJKylee said, we don't work in the past, because we CAN'T work in the past. Seriously, you are expecting us to debug a version that is 3 and a half years old ?

**Comment by Dendraspis** [comment] 2021-04-11 13:22
@kchiem 
Just in order to be able to tell the story with all facts:
So you still use StaxRip v1.7.0.6. And do you still use the same encoder versions that were shipped with this StaxRip version?

**Comment by kchiem** [comment] 2021-04-11 16:34
> We're not asking you to upgrade. Just download the newest version, deflate it anywhere on you hard disk (in a Read-Write location), in a folder called StaxRip2.4.0, far away from your 1.7.0.6 folder, and on first launch, when asked where you want to put the settings, select the first choice, which will create a settings folder inside the Staxrip2.4.0 folder. This way, the new settings will NOT interfere with the old settings.
> Then you'll be able to check if your file still has demuxing issues, which is the expected information we're waiting for.
> This and the mediainfo of the source file...
> 
> As @JJKylee said, we don't work in the past, because we CAN'T work in the past. Seriously, you are expecting us to debug or comment a version that is 3 and a half years old ?

I don't need you guys to work in the past, but it's pretty logical that given:

an older version of the software + a bunch of revisions with no listed changes to the desired behavior == the desired behavior won't be in the latest version

But I suppose I'll have to jump through that hoop to make you guys happy.

> @kchiem
> Just in order to be able to tell the story with all facts:
> So you still use StaxRip v1.7.0.6. And do you still use the same encoder versions that were shipped with this StaxRip version?

No, I update the components I use.
