### ISSUE TITLE
Video length shorter after encode causing audio desync

### ISSUE THREAD

**Issue by Vrael0n** [staxrip/staxrip#730] opened 2021-06-12 19:17 UTC
When transcoding an OBS recoding with dropped frames the video length shortens causing audio to desync over time.

Info:

Staxrip: 2.6.0
Frameserver: Vapoursynth
Source Filter: ffms2 and DGSource (DGDecNV) tested
Video Encoder: x265 and NVENC tested
Audio Encoder: Opus
Container (Source): MKV
Container (Encode): MKV

Log: 
[Test file 5h.13m.4s_new_staxrip.log](https://github.com/staxrip/staxrip/files/6642777/Test.file.5h.13m.4s_new_staxrip.log)

Below are the results of an FFprobe on the source and encode:

 **Source:**
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-04-27T00:24:55.000000Z
  Duration: 05:13:04.94, start: 0.000000, bitrate: 104729 kb/s
  Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709/bt709/iec61966-2-1), 3840x2160 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      BPS             : 104402072
      DURATION        : 05:13:04.945000000
      NUMBER_OF_FRAMES: 1126564
      NUMBER_OF_BYTES : 245148398709
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-04-27 00:24:55
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1: Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      BPS             : 321015
      DURATION        : 05:13:04.768000000
      NUMBER_OF_FRAMES: 220135
      NUMBER_OF_BYTES : 753775923
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-04-27 00:24:55
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

 **Encode:**
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-06-11T03:12:29.000000Z
  Duration: 05:13:04.78, start: -0.007000, bitrate: 33428 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(pc, bt709/bt709/iec61966-2-1), 3840x2160 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      BPS             : 33225649
      DURATION        : 05:12:56.066000000
      NUMBER_OF_FRAMES: 1126564
      NUMBER_OF_BYTES : 77980872570
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-06-11 03:12:29
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      ENCODER         : Lavc59.1.100 libopus
      BPS             : 212818
      DURATION        : 05:13:04.776000000
      NUMBER_OF_FRAMES: 939239
      NUMBER_OF_BYTES : 499718758
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-06-11 03:12:29
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

**Comment by JJKylee** [comment] 2021-06-12 19:46
I suspect `mkvmerge 56.1` is not setting the correct duration of the video stream.

Same number of frames before and after video encoding, but the _duration_ becomes different even if the frame rate remains the same, `60 fps`.

**[Source]**

> DURATION : 05:13:04.945000000
> NUMBER_OF_FRAMES: 1126564

**[Output]**

> DURATION : 05:**_12:56.066000000_**
> NUMBER_OF_FRAMES: 1126564

This is absurd. But it means all the processes up to muxing were done correctly, and the issue occurred when the video stream and audio stream were muxed to `mkv` by `mkvmerge`.

I believe this is somehow related to the following bug fix in _MKVToolNix_ 57.0.0.

```
## Bug fixes

* mkvmerge: HEVC/H.265 packetizer: fixed setting the track's default duration when reading HEVC/H.265 from Matroska files that don't have a default duration set.
```

Try updating _MKVToolNix_ executables to 57.0.0 and see if the issue is gone. If the issue persists, this is something to report to Moritz.
[https://gitlab.com/mbunkus/mkvtoolnix/-/issues](https://gitlab.com/mbunkus/mkvtoolnix/-/issues)

**Comment by Vrael0n** [comment] 2021-06-14 00:32
Replacing the binaries does not resolve the issue, neither does changing the encode container to MP4.

**Comment by JJKylee** [comment] 2021-06-14 00:54
Then try the `mkvmerge.exe` that worked OK in the past in muxing the existing `h265` video stream and the audio stream in the `temp` folder.

If the problem still exists, then it should be the video encoder, `NVEnc 5.32` that is shipped with StaxRip v2.6.0.

BTW, _MKVToolNix_ is updated to 58.0.0 today. Try this one as well.

No matter what, you need to understand that this issue does not come from StaxRip itself, but from one of the tools. There's nothing we can do but report a bug to the respective author(s) if this kind of issue arises.

**Comment by Vrael0n** [comment] 2021-06-14 13:45
Updated to v58, still not working. I've also tested x265 and NVENC, same issue.

**Comment by JJKylee** [comment] 2021-06-14 14:29
What you're reporting is very peculiar. I've never seen this kind of 'phenomenon', and similar reports in the past.
There's nothing more I can tell without the sample. And as you know, there's nothing we can do unless we can identify the cause. 🤔

**Comment by Vrael0n** [comment] 2021-06-14 15:55
Unfortunately the file is over 200GB. I also tested 2.1.8 (which I don't recall having problems with OBS recordings) and it has the same issue. Perhaps OBS (or StreamFX) changed something related to recording? I can use standalone FFmpeg as it does not have this issue.

**Comment by JJKylee** [comment] 2021-06-14 16:37
I think I figured out why. It's because of the **_dropped frames_** (and thus _VFR_ in `mkv`). And also because you didn't extract and apply the timestamps of the source file.

`mkvmerge` and `MP4Box` calculated the duration based on the total _number of encoded_ frames(`1126564`) and the frame rate(`60`). So the video duration in this case becomes `5:12:56.066` which is different than the source file, and the resulting output has CFR.

By contrast, `ffmpeg` uses the _original timestamps_ of the source file, and thus outputs the same VFR mkv file. So it comes out with the correct duration, `5:13:04.945`. But when a framerate value is given explicitly in the form of `-r 60`, `ffmpeg` duplicates/drops frames in order to meet the given frame rate.

Turn on `Options` > `Misc` > `Extract timestamps from VFR MKV files` and include the extracted timestamps file in `MKV Container Options` > `Options` > `Timestamps`. (It will be automatically included in v2.6.0 if auto-extraction is activated.)

BTW, the above mentioned 'naive' behavior of frameservers (AviSynth and VapourSynth) is natural considering what frameservers do.

There are filters that supplement this behavior: `TimecodeFPS`, `VfrToCfr` in AviSynth, and `VFRToCFR` in VapourSynth. They fill in the gap by trying to convert VFR to CFR. But of course their effectiveness may vary case by case.

They are included in [my current pull request](https://github.com/staxrip/staxrip/pull/725) and will be in the next release.

**Comment by Vrael0n** [comment] 2021-06-15 02:21
Success! Importing the timestamps extracted by gMKVExtractGUI solves the issue. However I already had "Extract timestamps from VFR MKV files" enabled in Staxrip 2.6.0 but it does not extract them, I think it is because OBS fails to report video as VFR.
![image](https://user-images.githubusercontent.com/61518774/121983026-7be56200-cd45-11eb-9f70-73c672355256.png)
Could StaxRip implement a sanity check that the frames and framerate match the length?

**Comment by JJKylee** [comment] 2021-06-15 02:58
> Could StaxRip implement a sanity check that the frames and framerate match the length?

AFAIK, there's no fail-safe method if OBS puts wrong metadata in the video.

But it is suggested that starting with the next release, StaxRip should automatically extract timestamps of the source `mkv` file regardless of whether it's VFR or CFR, along with an option whether to include the extracted timestamps in the output. (#729) If this request is accepted and implemented by @Dendraspis, you'll be given a wider opportunity than before.

**Comment by JJKylee** [comment] 2021-06-29 02:00
I think we can close this thread.

**Closed** 2021-06-29 02:04 UTC
