### ISSUE TITLE
Resizable x264/x265 option windows

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#481] opened 2021-01-25 20:31 UTC
I'd like the x264/x265/etc... sub windows to be resizable. When I increase the programs scale factor, I am not able to hit OK after choosing my settings

![image](https://user-images.githubusercontent.com/48299282/105762409-58e71c80-5f22-11eb-9563-f5604c925380.png)

This has been bugged like this for quite some time

**Comment by jlw4049** [comment] 2021-01-25 20:32
Seems to happen with anything over UI factor of about 1.20

**Comment by Dendraspis** [comment] 2021-01-25 20:48
Why don't you just set it below 1.20?  :thinking:

**Comment by jlw4049** [comment] 2021-01-25 21:33
> Why don't you just set it below 1.20?  :thinking:

I do and it works fine that way, but what if users like to use it larger?

**Comment by JJKylee** [comment] 2021-01-25 21:51
My scaling factor is 1.3 and I have similar problems. See [this](https://github.com/staxrip/staxrip/issues/461#issuecomment-763395673).
But (according to @Dendraspis) since this issue is related to the UI framework StaxRip is based on, there's nothing we can do unless the program code is overhauled. 😭

**Comment by jlw4049** [comment] 2021-01-25 22:00
I can deal with it at smaller ui sizes easy enough. If the work around isn't easy I wouldn't worry about it so much I guess.

**Comment by Dendraspis** [comment] 2021-01-25 22:09
@JJKylee 
Even at 1.25 I can't reproduce it - every parameter is positioned at the bottom:

![SRoptions](https://user-images.githubusercontent.com/50659978/105772202-1ba27f00-5f62-11eb-86ef-f1747ee9132e.JPG)

@jlw4049 
I'm pretty sure it would be a ton of work.

**Comment by jlw4049** [comment] 2021-01-25 22:14
It's 1920x1080 however windows is set to a larger scale. I'll check but 90% sure it's 125%.

**Comment by JJKylee** [comment] 2021-01-25 22:24
My Windows display scaling factor is 125% too. Can it be the cause? 🤔

**Comment by Dendraspis** [comment] 2021-01-25 22:32
My scale is at 150%, StaxRip UI Scale at 1.00 and at 1.25 - no issues.
Have tested on another PC with 1080p, 100% scale and StaxRip UI Scale at 1.00 - no issues.

Does this also happen to you when you use 100% Windows scale ?  🤔

**Comment by jlw4049** [comment] 2021-01-25 22:49
Let me test this now

**Comment by JJKylee** [comment] 2021-01-25 22:50
> Does this also happen to you when you use 100% Windows scale ? 🤔

Haven't tested it yet. But, well, changing Windows scale is kind'a cumbersome to me considering other programs are also related. Never mind. I'm just gonna live with it. 😓

How about you, @jlw4049?

**Comment by jlw4049** [comment] 2021-01-25 22:51
The main problem is, is the display window on the bottom with all of the text gets larger with more text. If this window could just stay a fixed size with maybe a scroll bar inside of it, the issue would be non existent.

**Comment by jlw4049** [comment] 2021-01-25 22:55
If this box here, just stayed a smaller/default size

![image](https://user-images.githubusercontent.com/48299282/105776354-70c89b80-5f36-11eb-9949-8f39d626418f.png)

Then the issue wouldn't exist at any scaling what so ever

**Comment by Dendraspis** [comment] 2021-01-25 23:02
Sadly I can't reproduce it.

> Then the issue wouldn't exist at any scaling what so ever

But it would create other problems. 🤓

**Comment by jlw4049** [comment] 2021-01-25 23:04
Try to set a custom scale on your windows machine of 125%, then set StaxRip to 1.30 and tell me if you have the issue. Make sure to use plenty of commands in x265, it should happen then.

**Comment by jlw4049** [comment] 2021-01-25 23:13
Also, maybe a work around, set a hotkey for OK and Cancel, like ALT+O and ALT+C, that way even if we can't see it, we can still apply the settings.

**Comment by 44vince44** [comment] 2021-01-26 07:07
Cancel would be simply ESC ... ?

**Comment by JJKylee** [comment] 2021-01-26 15:45
> If this box here, just stayed a smaller/default size
> 
> ![image](https://user-images.githubusercontent.com/48299282/105776354-70c89b80-5f36-11eb-9949-8f39d626418f.png)
> 
> Then the issue wouldn't exist at any scaling what so ever

Off topic, but, well, to be frank, I've never seen _this many_ option choices before. 😝
But don't get me wrong. I don't mean any offense. 😉

**Comment by jlw4049** [comment] 2021-01-26 15:46
> > If this box here, just stayed a smaller/default size
> > 
> > ![image](https://user-images.githubusercontent.com/48299282/105776354-70c89b80-5f36-11eb-9949-8f39d626418f.png)
> > 
> > Then the issue wouldn't exist at any scaling what so ever
> 
> Off topic, but, well, to be frank, I've never seen _this many_ option choices before. 😝
> But don't get me wrong. I don't mean any offense. 😉

I agree that is a lot of options. However, when encoding 4k content + hdr :P

**Comment by stax76** [comment] 2021-02-03 14:53
I've changed it to allow max 9 lines, show vertical scrollbar in that case.

Allowing manual window would be too much work. (FormBorderStyle.Sizable does not work with Form.AutoSize)

**Comment by 44vince44** [comment] 2021-02-21 07:22
That's fixed, right ? can we close it ?

**Comment by stax76** [comment] 2021-02-21 07:35
Yes, it should be fixed.

**Closed by stax76** 2021-02-21 07:35 UTC
Labels: feature request, priority low
