### ISSUE TITLE
2.1.4.8 interrupting queue processing to prompt updating 7zip 

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#381] opened 2020-10-29 14:55 UTC
**Describe the bug**
I will leave Staxrip processing a queue of 100+ batch jobs. It will process jobs as normal, I'll leave it processing and come back an hour or so later to check on its progress. It should still be processing jobs, instead the queue is interrupted and the apps manager window is open, prompting me to update 7zip. It shouldn't be needing to use 7zip, and it's got v9.2 there anyway, and all the jobs are the same settings same source and target codecs etc so if it did need to use 7zip it would need it from the outset, not after running 50 jobs. 

I can close the update window and usually I can then resume the jobs queue, and it carries on quite happily without problems and without asking me to update 7zip, then an hour or so later it will do it again. One time when I closed this window, it immediately popped back up telling me to update AutoCrop, then I closed that and it told me to update AviSynth, I closed that and it told me to update avs2pipemod...I had to go to task manager and end task staxrip to get out of this. It's only done this one time though, normally I can close the windows after the 7zip prompt and resume the queue. This has happened 5-6 times now.

I have noticed when this happens, Staxrip also outputs a log file corresponding to the last job it tried to process (i.e the job that's at the top of the queue when I go to resume it, which will be unchecked), but the log file is empty. When I resume the queue, whichever job was at the top of the queue will process as normal, so there's nothing wrong with the files or the job in question. 

**Expected behavior**
I expect the queue to run without interruptions, and without prompts to update components that are already present and updated. I have only seen this behaviour in 2.1.4.8

**How to reproduce the issue**
I cannot reliably reproduce the issue as it happens randomly during processing long batch queues when unattended

**Comment by Statick** [comment] 2020-10-29 16:42
it just did it again, this popped up
![2020-10-29_163832](https://user-images.githubusercontent.com/3793002/97604594-9280b800-1a05-11eb-959b-760d3ea8fba0.png)

out of curiosity, I clicked "check status" and this popped up
![2020-10-29_163909](https://user-images.githubusercontent.com/3793002/97604663-a6c4b500-1a05-11eb-9acc-ae09cb81e12f.png)

after closing the window, I can go back to "apps > manage" and everything looks normal, and if I click "check status" again it says "all tools have OK status"

**Comment by Statick** [comment] 2020-10-30 12:37
just watched this happen in front of me for the first time
before the updater pops up, there's an error pop-up which says something like "unable to open settings.dat - file is in use by another process" (I don't recall the exact wording). I clicked OK and the updater popped up prompting to update 7zip

maybe this will help track down the cause of the problem

**Comment by 44vince44** [comment] 2020-10-31 15:46
Well that's weird. Just press F12 in the 7z window (inside app manager) and type in 9.2 and validate.

Does it remain OK?

**Comment by Statick** [comment] 2020-10-31 16:41
Doing that makes no difference, I mean I can close the window without doing that and immediately reopen it and it shows 9.2 correctly. But I have also entered this info several times and it still comes back an hour or so later

I added more info in my last comment, it appears to be momentarily unable to open the settings file saying that there's a lock on the file, which makes it think that all modules need updating. Closing and reopening the window, or simply closing it and resuming the job queue, always works, so it doesn't seem to be a permanent problem, it's just a problem in that instant, I'm guessing it opens this file for every job in the queue and occasionally it's unable to do so, and the result is this error. I think adding some code to retry opening the settings file if it fails to open would solve this, as it does seem to only be a problem momentarily - just a problem that stops the queue from processing!

The files I'm transcoding are running very quickly, they're already quite small files and I'm compressing them to hevc with nvenc on a reasonably decent card, so I'm getting up to 1000fps. Some of them are finished extremely quickly, that you barely see the process running in the output window. I'm wondering if it's moving so quickly that an earlier process which still has a lock on this file, hasn't had time to exit yet. I've not had this problem with my regular encodes which normally take a lot longer to complete. In any case I think attempting to retry opening the settings file (perhaps after a 1 second delay or something) would sort it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 44vince44** [comment] 2020-11-01 07:08
The lock on the settings files is already addressed. It happens when you open two staxrip instances exactly as the same time.
Now. in order to validate the version of 7zip properly:
- restart your computer
- make sure that in task manager of windows, processes tab ("details"), you have no process called Staxrip (sort them by name).
  if there is, kill the process.
- now start staxrip. check in the task manager ("details" tab) that there only ONE staxrip.exe process running 
- now you can check and validate the 7zip version, then QUIT staxrip, and check that there is no more staxrip.exe in the task manager.

One question: when updating to version 2.1.4.8, did you extract the archive to a new folder, or extract it to a folder where there was an older staxrip ? This is important because previous versions of staxrip used a different method to save the data of the app manager.

**Comment by Statick** [comment] 2020-11-01 11:40
I did extract over an older the latest stable release - should I extract to a new folder then? what's the best way of migrating my settings etc to the new folder? this seems plausible as I've been processing long batch queues like this for a long time, and it had never been a problem until I upgraded to the beta version

also assuming this is the cause of the problem, does it still make sense as a possible cause when considering the problem is intermittent? the app manager shows apps correctly, and the jobs queue will process 150+ jobs as normal, before interrupting with this error, and then after closing the error everything is fine again (apps shown correctly, jobs queue will resume and will process another 150+ jobs before being interrupted again)

I will add the folder to my AV whitelist now as that definitely seems plausible

**Comment by 44vince44** [comment] 2020-11-01 14:09
@Statick, extracting to a folder with files from an older version in it leads to many malfunctions, especially this time where many things have been re-written in the code (major changes, not only bug fixes). However, there's no way I can be sure that it's what explains the problem you're facing.
Updating Staxrip should be done this way:
- if your settings folder is in Staxrip program folder, then you must clear everything in Staxrip program folder EXCEPT the settings folder, then copy the new files from the archive
- if your settings folder is not in Staxrip program folder, then clear everything inside Staxrip program folder, and then copy new files.

Now I prefer also to delete the settings and create them from scratch with the new version. But that's a personal choice.

However, this amount of 150 jobs raises some questions. Never had a job list with such a huge amount...

**Comment by Statick** [comment] 2020-11-01 14:12
I regularly have job lists running into thousands! Staxrip handles batch processing far better than any other software, this is the main reason I use it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 44vince44** [comment] 2020-11-01 14:56
I'll try to reproduce this later, maybe tomorrow. I will create a very small video, will duplicate it 200 times and do some basic and fast processing. I'll get back to you then !

**Comment by Statick** [comment] 2020-11-01 15:06
Yeah the queue I'm doing at the moment is unusually small files, as I'm going back into some older folders of videos from a few years ago. These are all mobile videos around 480x360 and of varying lengths, some are only a few minutes long so they're very small files. I've got terabytes of this stuff so I'm archiving to hevc (I'm getting good enough results with around 50% file size reduction) so my backups are smaller. There's no avisynth processing happening it's literally just a very fast transcode to improve file sizes

It's possible that this problem only started when I started processing really small files, as I started this particular hard drive around the same time I installed beta version, so I'm wondering if what's happening is the previous job process is keeping a lock on the settings file for a few seconds, which normally wouldn't be a problem if each job takes several hours, but which is messing things up here as the job completes before the lock is released, and the next job begins with the lock still active. I am of course completely speculating here

Since adding the folder to my av whitelist the problem has happened again, so it's not that. I'll reinstall to a clean folder next

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 44vince44** [comment] 2020-11-02 12:26
Performed this test:
1 small trailer, copied 204 times, resulting in 205 files (x265, aac in mkv).
Process : video very fast x265, no filters, audio copy/mux. Container mkv.

Resullt: **processing of 205 jobs completed with no problem**.
So I could not reproduce your problem.

You should definitely copy Staxrip files to a clean location (no older files there, except optionally settings folder) !

**Comment by Statick** [comment] 2020-11-04 02:19
I have downloaded 2.1.4.8 and extracted to a new folder
I created new settings from scratch (using the /settings folder in the program folder)
I have created a new jobs queue by dragging videos to the batch window

the queue processed 428 videos before stopping with a prompt to update 7zip

**Comment by 44vince44** [comment] 2020-11-04 11:05
@Statick I cannot replicate the exact settings mentioned in your post, since my hardware isn't capable of running NVEnc h265.
Now, the test I made involved 205 jobs, I don't think there is a point for me doing with more than that, provided that your previous posts stated 150 jobs.

The only things I can think about are:
- files locked by a system process
- hard drive C entering some kind of sleep mode, and timeout very short. (I guess not, however)

**Comment by Statick** [comment] 2020-11-04 14:31
well, my last attempt ran over 400 videos before stopping, so it shows the problem doesn't happen with exact regularity, but it doesn't mean the problem isn't there or is unique to my system. I don't know exactly how many videos you would definitely need to run to definitely see the problem, but obviously 205 is not enough if I can successfully get to 428 and then it still fails. I suggested 1000 as it seems much higher than any of these numbers.

I'm running procmon on this system now to try and find out what's going on, there's a lot of data appearing but hopefully it will reveal something. I'm guessing that if Staxrip gets interrupted then new procmon events for Staxrip will stop appearing, so it should be easy to check the most recent entries.

is there any other way I can trace this further myself? I can code C# a bit, is it worth me trying to build Staxrip myself and running it with a debugger? VB isn't a million miles away from C#. it looks like a *lot* of files in github, I'm not really sure how to start trying to build this

**Comment by 44vince44** [comment] 2020-11-05 05:41
OK I'll do later a check with 1000 videos, but I want to check this with you first:
- the harddrive where C: is what is is? SSD or HDD. If HDD what model (indo shown in device manager). I need to know that so I discard the sleep/timeout hypothesis.
- the temp folder of staxrip is on what drive? same C ?

**Comment by Statick** [comment] 2020-11-05 13:03
C: drive is an SSD, SanDisk SDSSDX120GG25
The temp folder for each job goes in the same folder as the job itself (which is not on C drive) and is deleted when the job is finished, I'm assuming this is the temp folder you mean?

Before you go processing 1000 jobs, let me see what procmon comes up with first, as I think that will be useful

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Statick** [comment] 2020-11-06 23:35
okay so procmon hasn't revealed anything particularly useful. there's no file locks or file access problems or anything like that. it doesn't even show an attempt to open the settings file, when the queue interrupts. it did reveal that Windows Defender was getting involved fairly continually so I have whitelisted the Staxrip folder there as well, but since doing that it hasn't changed anything

here's what I have figured out though - the likelihood of this problem happening does definitely depend on the size of the video, I don't know if this is down to a speed thing or something else, but I managed to run a queue of 800 videos 1280x720 resolution, mostly 20-30 minutes long, with no problems at all. the other queue I mentioned before, the one that failed after about 400 videos, was also videos at 1280x720, but mostly shorter videos.

then just now I set up a different queue of very small videos, 320x200 resolution, mostly 20-40 seconds long each, and it failed after less than 100 videos. the first queue I mentioned, which failed after 150 videos, was also small videos (I think these ones were 640x480). all the problems I had before I first posted this thread, which was a number of failures before I started making notes and counting how many videos would process, these were all very small videos as well. so it does look like smaller videos increases the chance of it failing. 

so to try and replicate this I think it makes sense to try with a queue of very very small videos. maybe take your trailer, cut it down to 10 seconds long, and resize it to 240 x 180 resolution, render that and then duplicate it say 200 times. I think with a video this small it should reveal the problem in less than 100 jobs, and if not then I guess it's something weird on my system which I will just have to live with

**Comment by Statick** [comment] 2020-11-07 01:38
just failed again, and again procmon shows the same "-startjobs" entry at the exact time the queue stopped, and it doesn't appear anywhere else. I hope this means something to you as it seems to be connected!

**Comment by 44vince44** [comment] 2020-11-07 03:14
Finding the -startjobs reveals indeed what is happening. Here is how to reproduce the error:

1. close all programs. Open only 1 staxrip window
2. create a batch with a few jobs, only 3 are enough, not very short so you can see what's happening
3. click on START to start the batch. the Jobs window will close automatically and first job will run
4. click on jobs (F6) to reopen the Jobs window, from the same unique staxrip running (and processing currently)
5. click on START of the jobs window, wait a few seconds, here you have the error.

So are you clicking on START again, accidentally ?
Or is there a script or something issuing the -startjobs command from the same staxtip windows that is already processing ?

Now this points out that the Job window already running the job list should not allow pressing the START button again.

**Comment by Statick** [comment] 2020-11-07 11:58
no I'm definitely not doing that! almost always when this happens, I have left Staxrip unattended (usually overnight) so I'm definitely not clicking on it. I have no scripts running (I don't know how to do scripts in Staxrip). also, Staxrip steals focus every time it processes a job (actually for each step of each job - mkvextract, autocrop, encode, mkvmerge, etc, all steal focus), which gets annoying if the jobs are running quickly and you're also using the computer, so actually I always minimise the window once processing has started to stop that happening

also, Staxrip gets really unstable if you have 1000s of jobs in the queue, and you open the jobs window while it's running. like, spinning "waiting" mouse pointer, window fades to white, windows pops up "staxrip is not responding" etc. sometimes it recovers if you keep waiting, but usually I end up having to go to task manager to end staxrip. for this reason, I never *ever* open the jobs window while it's processing, and if I need to remove or reorder anything from the queue then I stop the processing first, make the changes, then restart it. it only does this with very large queues so I've just come to accept that I'm asking too much to make changes to such large queues while also processing them :) 

in any case, I'm always careful never to open the jobs window when it's processing, and normally staxrip is minimised anyway

**Comment by Statick** [comment] 2020-11-07 12:06
to further explain the issue with instability when the jobs window is open, I find that if I have a queue of 1000s of jobs and I add or remove jobs from the queue, this usually causes it to hang for 30 seconds or so before the change appears, so I think what is happening if I open the jobs window while it's processing, is this is happening every time a job is completed and it is removed from the queue... so I have am just used to not opening the jobs queue while it is processing, and to be patient when making changes to very large queues

**Comment by 44vince44** [comment] 2020-11-07 16:54
I see. So can you please check that the folder Settings\Scripts has the following items only:
-Subfolder => EMPTY
-Hello World.ps1 => file

**Comment by Statick** [comment] 2020-11-07 17:08
yeah I only have one settings folder at c:\portable\staxrip 2.1.4.8\settings (renamed since I installed to a clean folder)
the scripts folder is as you describe, autoload is empty and there is one helloworld.ps1 file

**Comment by 44vince44** [comment] 2020-11-07 17:15
So I guess for some mysterious reason Staxrip issues a -startjob command when overwhelmed by huge job lists.
A first step to fix that problem would be disabling any -startjob command from a Staxrip window when it is already executing a job list.

We have to wait that the coders get back from their break!

**Comment by Statick** [comment] 2020-11-07 17:17
yep all good! 
CPU is Intel i5 7500
16gb RAM

**Comment by 44vince44** [comment] 2020-11-07 17:20
That should handle the load all right!
I'll do a clear summary below, for the coders...

**Comment by 44vince44** [comment] 2020-11-07 17:46
@stax76 @Dendraspis Hi there, I hope you're OK and you'll be back here soon!
**Here is a summary of the whole thread:**

User @Statick uses job lists with HUGE amount of small jobs. He got some strange behavior, he traced it with Procmon, and it showed that at one point, the Staxrip process that is working on the job list has issued a -startjobs command, in the middle of the execution of the job list, and without any human intervention.

I could not reproduce that by using a huge joblist, but I found a way to reproduce manually the same strange behavior: 
1. create a job list with a few jobs
2. press START, the job list execution begins and the Jobs window closes automatically
3. reopen the Jobs window from the same staxrip window that is processing the jobs
4. press START, wait a few seconds and see what happens (command -startjobs is issued and leads to an error)

=> conclusion : pressing START from a Jobs window that is already executing the job list leads to an error.
So either fix, or do not allow issuing -startjobs from a window that is already executing the Job list.

**Comment by Dendraspis** [comment] 2020-12-10 01:38
@44vince44 
Thanks a lot for your summary! I'll try to have a look on it in the next days/weeks.

**Comment by stax76** [comment] 2020-12-14 12:34
Good work as usual @44vince44.

> the Staxrip process that is already working on the job list has issued a -startjobs command

So I searched for -startjobs in the code and found something that is likely responsible for the problem, the job processing is implemented as a recursive function, normally when a job is finished, the function calls itself in order to process the next job, and now it comes, it not just moves on to the next job but does check the memory consumption of the staxrip process, if it's too high (> 1500 MB) then the current instance shuts down and a new instance is started.

So we probably have a memory leak somewhere and because of that we are using the emergency plan but it's also failing... 😒

https://github.com/staxrip/staxrip/blob/master/General/GlobalClass.vb#L206

**Comment by Statick** [comment] 2020-12-14 13:06
that makes sense, it does look like memory usage is pretty high before it fails

if the function is recursive then that's the problem - each function call will be holding its RAM allocation until the function returns, which it can't do until the next function call has returned, which can't finish until the call after that has returned, etc etc, which means the entire queue will be building up RAM usage with each job, until finally the queue is completed and all those functions return all at once and all the RAM releases at once. this design is guaranteed to run out of RAM at some point with long enough queues

I think it would probably be better to write a separate queue processing function, to loop while there's jobs on the queue and call the job function once per job and let the function complete and return each time, so it would release its RAM every time, instead of having the function call itself and having all the RAM usage building up until the queue is finished

separately to this, there's another issue I've noticed which I was going to report, and I think it's connected. when staxrip completes a long queue, it hangs for a long time (longer queue = longer hang). sometimes this can be 10 minutes or more, it always wakes up eventually though. at some point I watched procmon while it was doing this, and saw it was very busy doing some sort of tidying up of job files, I can't remember exactly what I saw but lots of filenames with names familiar from the job queue were in there, and it was very busy the entire time it appeared frozen

it appears that with this recursive function, this cleanup happens after the call to the next job, so like the problem with RAM not being released until the end, each job only gets cleaned up after the next job has finished, which only gets cleaned up after the job after that has finished, etc, so all of this work gets left until the entire queue is complete - and if it's a long queue then that means a lot of work, resulting in a flurry of disk activity with an unresponsive GUI while it sorts it all out

so I think with a small change to how the queue processing works, making it run in a loop instead of recursion, both of these issues would be fixed :)

**Comment by stax76** [comment] 2020-12-14 13:43
It could be but I don't believe it, the recursive function probably does not do much memory allocation, and the .NET code in general does not use much memory. In the past all memory leaks were caused by the frame servers.

It has to be recursive because the job is can be shared by many instances.

How many jobs are we taking? Maybe I can reproduce it with a small files.

**Comment by 44vince44** [comment] 2020-12-14 14:37
First time Statik had the "crash" at job number 153. Then I did the test with 200+ jobs and could **not** reproduce it.
But I could reproduce it by pressing on START in the job window that is already running jobs !
Maybe something we can do here already=> disable START button when jobs are already running in this instance.

**Comment by stax76** [comment] 2020-12-14 14:54
@44vince44 All it does is starting a new instance of staxrip by running this command line:

StaxRip.exe -StartJobs

The problem might happen randomly without a clean way to reproduce, I had tested it and it worked.

**Comment by 44vince44** [comment] 2020-12-14 15:25
@stax76 and I couldn't reproduce it !!

But can we still fix the START jobs button so it is disabled when jobs already running in this instance ?

**Comment by Statick** [comment] 2020-12-14 15:56
the number of jobs it would fail after was always really random, sometimes after just a couple of hundred, sometimes it could be many hundreds. all of these jobs are mobile phone videos of varying lengths and resolutions (some from older phones in resolutions like 640x480 and some from newer phones in 1080p), and they're being transcoded using NVEnc to hevc for archival purposes (we're saving a LOT of disk/cloud space this way, and NVEnc with everything dialed up as good as it can get is still very very fast, with a good enough image quality for our purposes). it's possible the problem is connected with NVEnc as, as mentioned above, attempts to reproduce it using x264 did not work, although it could also just be that those attempts didn't have long enough queues. 

I'd say to try and replicate it with some certainty of success, you'd want to batch process 1000 videos with NVEnc as I don't think I've ever got it past about 600-700 before failing

**Comment by stax76** [comment] 2020-12-14 17:30
Sorry I missed this:

> just watched this happen in front of me for the first time
> before the updater pops up, there's an error pop-up which says something like "unable to open settings.dat - file is in use by another process" (I don't recall the exact wording).

That's something I can work with. 🙂

**Comment by Statick** [comment] 2020-12-14 17:31
Yep - the one time I caught it happening in front of me it popped that up as well

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stax76** [comment] 2020-12-15 09:45
It's probably fixed in the new Beta, I think the problem was two instances using the settings.dat file at the same. Fixed by using a mutex.

**Closed** 2020-12-15 23:57 UTC
Labels: bug, fixed, priority medium
