### ISSUE TITLE
Encoding from ProRes has green garbage at the bottom of output, but it isn't in the preview?

### ISSUE THREAD

**Issue by JonathonSunshine** [staxrip/staxrip#692] opened 2021-05-06 08:11 UTC
**Describe the bug**
Green garbage is appearing at the bottom of videos encoded from prores format videos. The green garbage does not appear in the preview.

Googling told me that this was happening because I was encoding from a "non standard" video resolution (1440x1080).

When I encoded prores to 16:9, ie 1920x1080 with black pillarboxing, the video encoded fine, no garbage at the botton.

BUT ... once I applied cropping to the prores video, to make it 1440x1080 and encoded that, the green garbage appears again.

So, I really don't know what to think...

the archive below is the two input videos I used, (cropped and not cropped, as well as the logs and the output videos with green garbage (except the 1920x1080 output, the only one that came out ok). (smallest I could make them, the whole archive is 30MB)

I did all this with StaxRip 2.3.0 but it happens with 2.5.0, confirmed this just now before hitting submit.

https://files.catbox.moe/l9cr0f.zip

**Comment by 44vince44** [comment] 2021-05-06 11:22
This is a **tool issue** with x264 encoder. We spotted this issue on 10+ bit sources with some resolutions, but now you gave us an example that the problem appears also with 8 bit videos, for some resolutions.

You can follow the issue here:
https://github.com/Patman86/x264-Mod-by-Patman/issues/1

If you encode the same project with x265, you'll have no problem. You can also use the h264 codec of one of the hardware encoders, or also ffmpeg>x264.

And let's put some pressure on the coders @Patman86 and @DJATOM to fix this issue once and for all !!!, Please guys ;-) It's been almost 2 months !! The post above proves that this issue also happened with a 8 bit 1440x1080 video, so it is not only bit depth related...

**Comment by DJATOM** [comment] 2021-05-06 12:02
Mkay, I'll try explicit data copy which most likely fix that.

**Comment by Patman86** [comment] 2021-05-06 12:43
I've also found in my tests that the resolution is the cause and not actually the bit depth. Other tools take screen resolution into account.

**Comment by JonathonSunshine** [comment] 2021-05-06 13:04
Did this _used_ to work? Pretty sure I've encoded at this resolution before but I do tend to use HEVC instead... 

I assumed it was something to do with ProRes, I remember one time I couldn't get StaxRip to open a ProRes file at all once though that was likely a codec issue... Oh well, I wait and see. Keep up the good work guys and girls!

**Comment by DJATOM** [comment] 2021-05-06 15:31
Well, i think I managed to fix it entirely. Will make new commits into my repo soon.
Long story short: when shifting 10 bit pixels to 16 bit format, we should rely on `stride / bytes_per_sample * height` and not on `width * height`. In case of non-mod16 resolution (854x480, in my tests, stride is 1728; `width * height` = 410880, `stride/bps*height` = 414720) not all pixels actually shifted to bit bit values. 
Also it's a good practice to copy planes explicitly. That avoids various random glitches (or I didn't managed to reproduce them in few encodes).

**Comment by DJATOM** [comment] 2021-05-06 16:48
Fixes landed. Now I'd like to know if [x264.zip](https://github.com/staxrip/staxrip/files/6436298/x264.zip) works for you? If no more glitches happens, ping me and I'll make new release.

**Comment by 44vince44** [comment] 2021-05-06 17:12
I'll do some tests right now @DJATOM and thanks for the fix. Get back to you hopefully a bit later.
@JonathonSunshine can you please also test the zipped x264 provided by DJATOM above ?

**Comment by 44vince44** [comment] 2021-05-06 19:18
@DJATOM this is fixed, as per my tests, everything worked successfully !!
Thank you very much!

And I hope @Patman86 you'll sync the fixes also ?

**Comment by JonathonSunshine** [comment] 2021-05-06 22:27
> I'll do some tests right now @DJATOM and thanks for the fix. I'll get back to you hopefully a bit later.
> @JonathonSunshine can you please also test the zipped x264 provided by DJATOM above ?

yeah, it worked, sorry I went to bed : )

**Comment by 44vince44** [comment] 2021-05-08 11:59
I think we can close this .... right ?

**Comment by JonathonSunshine** [comment] 2021-05-10 01:32
actually, I probs didn't notice because the clip i tested with was only 2 seconds long but while it seems to encode ok, when i encode longer videos it actually makes the whole staxrip ui unusable. some videos it updates the onscreen gui info every 5 seconds or so and sometimes just freezes up in the completely. Video still seems to be encoding though


[Last.Week.Tonight.with.John.Oliver.S08E10.1080p.HEVC.x265-MeGusta[eztv.re]_new_staxrip.log](https://github.com/staxrip/staxrip/files/6448869/Last.Week.Tonight.with.John.Oliver.S08E10.1080p.HEVC.x265-MeGusta.eztv.re._new_staxrip.log)

**Comment by JJKylee** [comment] 2021-05-10 03:08
Your x264 is an old one:

```
x264 [info]: core:161 r3039+17 c76b8b8 (DJATOM's mod)
```

Try the most recent one by @DJATOM, `163-r3059+17-aMod` from [here](https://github.com/DJATOM/x264-aMod/releases).

**Comment by JonathonSunshine** [comment] 2021-05-10 04:09
> 
> 
> Your x264 is an old one:
> 
> ```
> x264 [info]: core:161 r3039+17 c76b8b8 (DJATOM's mod)
> ```
> 
> Try the most recent one by @DJATOM, `163-r3059+17-aMod` from [here](https://github.com/DJATOM/x264-aMod/releases).
> 
> Since your CPU (Ryzen 9 5900X) architecture is _Zen 3_, maybe you can use the optimized version, `x264-aMod-x64-core163-r3059+17-opt-znver3.exe` to improve its performance. Rename it to `x264` and put it in place of the old one.

Yup, that ones working. I'm using the ZEN3 version, doesn't seem any faster but I haven't run any proper head to head tests.

**Comment by JJKylee** [comment] 2021-05-18 02:55
@Patman86 released his mod `x264-0.163.3059+11-1aa8b82-[Mod-by-Patman]` [here](https://github.com/Patman86/x264-Mod-by-Patman/releases/tag/0.163.3059%2B11) today.

A test would be desired, @JonathonSunshine. 😉

**Comment by JJKylee** [comment] 2021-05-18 13:29
So, I tested @Patman86's new x264 build with @JonathonSunshine's `test.video (1440x1080) Input.mov`, and had **_no_** issues like green garbage (loss of chroma info) at the bottom. Both for 4:2:2 and 4:2:0 in 10 bits and 8 bits.

[4:2:2 10 bits]

Log:
[test.video (1440x1080) Input_staxrip.log](https://github.com/staxrip/staxrip/files/6501638/test.video.1440x1080.Input_staxrip.log)

Output:
[test.video (1440x1080) Input.zip](https://github.com/staxrip/staxrip/files/6501642/test.video.1440x1080.Input.zip)

IMO, at least this issue is resolved with the new build. 😃

**Closed** 2021-05-18 22:38 UTC
Labels: added/fixed/done, bug, tool issue

**Comment by 44vince44** [comment] 2021-05-18 22:56
I tested on a **47 minute video**, it went all ok, with the AVS reader and the VPY reader with @Patman86 's latest build:

x264 x264-0.163.3059+11-1aa8b82-.Mod-by-Patman.-x64-gcc10.3.0


Al seems fixed ! Congrats and thanks !!
