### ISSUE TITLE
System.ArgumentOutOfRangeException: Value to add was out of range.

### ISSUE THREAD

**Issue by stickz** [staxrip/staxrip#183] opened 2020-05-03 12:51 UTC
------------------------------ Exception ------------------------------
System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 68
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 87
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 38

**Comment by stax76** [comment] 2020-05-04 15:12
It's not clear why it could crash, is there a full log file?

**Comment by Dendraspis** [comment] 2020-05-04 15:23
It happened to me, too, when I added a job to the queue with v2.1.0.9 beta, that should be processed by a v2.0.8.0 stable instance.

Sadly there was no more information given, the log was okay. But it would be good to know if @stickz  also ran different versions of StaxRip.  🤔

**Comment by PBo34** [comment] 2020-05-22 16:42
ArgumentOutOfRangeException (2.0.8.0)

La valeur à ajouter était hors limites.
Nom du paramètre : value

System.ArgumentOutOfRangeException: La valeur à ajouter était hors limites.
Nom du paramètre : value
   à System.DateTime.Add(Double value, Int32 scale)
   à StaxRip.ServerInfo.GetInfoText(Int32 position) dans D:\Projekte\VB\staxrip\General\FrameServer.vb:ligne 68
   à StaxRip.GlobalClass.ProcessJob(String jobPath) dans D:\Projekte\VB\staxrip\General\GlobalClass.vb:ligne 87
   à StaxRip.GlobalClass.ProcessJobs() dans D:\Projekte\VB\staxrip\General\GlobalClass.vb:ligne 38

Happened when I started the jobs queue.
I tried twice.
No log no temporary folder.

**Comment by stax76** [comment] 2020-05-22 22:27
Next build has a change regarding it, only a guess as it's not enough info to make sense out of it.

**Comment by PBo34** [comment] 2020-05-23 17:33
I've tried to narrow down the problem.
1 : there was a crash trying to feed RGBA into LSFmod (I use v2.186). Converting to YV16 fixed it.
2 : too long filenames / paths crash 2.0.8.0 . I switched to 2.1.1.4 (sorry I cannot compile the latest github version), now there is a warning -> problem solved.
Thanks a lot for this quick answer and for the good work!

**Comment by stax76** [comment] 2020-05-23 19:24
Thanks for the details, the build is online:

https://staxrip.readthedocs.io/introduction.html#beta

**Comment by PBo34** [comment] 2020-05-28 23:22
The crash occurred again.
I corrected the last line of SMDegrain script like this:
    IsAvsNeo ? eval(MidStr(VersionString(),20,4)) : IsAvsPlus ? eval(MidStr(VersionString(),19,4)) : 0
Replaced the 17 by 19 because the version string of avisynth is longer.
Now it's running.
I'll try to see where I can have this corrected in SMDegrain.

**Comment by stax76** [comment] 2020-05-30 00:05
I have no problems here with SMDegrain.

**Comment by PBo34** [comment] 2020-06-01 15:29
Sorry I should have mentioned I use v3.1.2.104s instead of the 100s provided.

**Comment by PBo34** [comment] 2020-06-01 15:36
This happened at the moment I pressed space to switch file in the video comparison utility :
<<
ArgumentOutOfRangeException (2.1.1.5)

La valeur à ajouter était hors limites.
Nom du paramètre : value

System.ArgumentOutOfRangeException: La valeur à ajouter était hors limites.
Nom du paramètre : value
   à System.DateTime.Add(Double value, Int32 scale)
   à StaxRip.VideoComparisonForm.VideoTab.TrackBarValueChanged() dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 349
   à StaxRip.VideoComparisonForm.TabControl_Selected(Object sender, TabControlEventArgs e) dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 155
   à System.Windows.Forms.TabControl.OnSelected(TabControlEventArgs e)
   à System.Windows.Forms.TabControl.WmSelChange()
   à System.Windows.Forms.TabControl.set_SelectedIndex(Int32 value)
   à StaxRip.VideoComparisonForm.NextTab() dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 141
   à StaxRip.UI.ActionMenuItem.OnClick(EventArgs e) dans D:\Projekte\VB\staxrip\UI\Menu Types.vb:ligne 518
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.PerformClick()
   à StaxRip.UI.ActionMenuItem.KeyDown(Object sender, KeyEventArgs e) dans D:\Projekte\VB\staxrip\UI\Menu Types.vb:ligne 506
   à System.Windows.Forms.KeyEventHandler.Invoke(Object sender, KeyEventArgs e)
   à System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   à System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   à System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   à System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   à System.Windows.Forms.Control.WmKeyChar(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.TabControl.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>>

**Comment by vonH** [comment] 2020-06-05 07:38
I've seen the same error message appear for different causes (always mentioning the D:\ path (which I don't use). And then no error log is generated so I just move on. For me, it's usually related to path length or an incorrect avs script where I've made a small error.

**Comment by stax76** [comment] 2020-06-06 18:08
If the script has an error then there should be an error message and it should not be possible to create a job.

In the beta from today there was work on long paths, meaning long paths are blocked with an error message:

> In theory Windows supports paths that are longer than 260 characters, in reality neither Windows, nor the .NET Framework or the used tools have full long path support.

**Comment by stax76** [comment] 2020-06-06 18:30
Next build has a change regarding the video comparing crash but again only a guess since I cannot reproduce it.

**Comment by PBo34** [comment] 2020-06-07 20:20
Opening a video for compare : "conflict with outdated plugin"
... mvtools2
I click OK then : 
ArgumentOutOfRangeException (2.1.1.9)

La valeur à ajouter était hors limites.
Nom du paramètre : value

System.ArgumentOutOfRangeException: La valeur à ajouter était hors limites.
Nom du paramètre : value
   à System.DateTime.Add(Double value, Int32 scale)
   à StaxRip.VideoComparisonForm.VideoTab.TrackBarValueChanged() dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 348
   à StaxRip.VideoComparisonForm.Add(String sourePath) dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 95
   à StaxRip.VideoComparisonForm.Add() dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 59
   à StaxRip.UI.ActionMenuItem.OnClick(EventArgs e) dans D:\Projekte\VB\staxrip\UI\Menu Types.vb:ligne 542
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.PerformClick()
   à StaxRip.UI.ActionMenuItem.KeyDown(Object sender, KeyEventArgs e) dans D:\Projekte\VB\staxrip\UI\Menu Types.vb:ligne 523
   à System.Windows.Forms.KeyEventHandler.Invoke(Object sender, KeyEventArgs e)
   à System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   à System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   à System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   à System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   à System.Windows.Forms.Control.WmKeyChar(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.TabControl.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

When I go to Apps manage, mvtools2 shows v2.7.43 (02/06/20),
status OK.
If you want to write some trace to a debug file, tell me how I can help.

**Comment by stax76** [comment] 2020-06-07 20:40
Is avisynth installed, which version, which plugins are in the auto load folder, source file media info.

staxrip just creates some simple script with ffms2 in the sys temp dir I think.

**Comment by PBo34** [comment] 2020-06-08 17:59
I don't remember with which file it happened. I'll write it next time.

![avsinfo](https://user-images.githubusercontent.com/6825229/84063988-34a1f400-a9c2-11ea-8ca1-9e3495dda170.JPG)

**Comment by PBo34** [comment] 2020-06-09 18:37
I've upgraded mvtools2.
Video's info :
[mediainfo.txt](https://github.com/staxrip/staxrip/files/4754138/mediainfo.txt)

**Comment by PBo34** [comment] 2020-06-09 19:12
In case it is of interest, opening the same video with 2.0.8.0, I get this message :
OverflowException (2.0.8.0)

L'opération arithmétique a provoqué un dépassement de capacité.

System.OverflowException: L'opération arithmétique a provoqué un dépassement de capacité.
   à StaxRip.VideoComparisonForm.VideoTab.Draw() dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 342
   à StaxRip.VideoComparisonForm.VideoTab.OnPaint(PaintEventArgs e) dans D:\Projekte\VB\staxrip\Forms\VideoComparisonForm.vb:ligne 409
   à System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   à System.Windows.Forms.Control.WmPaint(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PBo34** [comment] 2020-06-17 13:07
Yesterday, I ran LSFmod in a batch. It crashed on a video with "argument out of range" error.

I reloaded the template and opened the file directly. The error (LSFmod only accepts YUV) was then displayed (in blue). The video was in RGBA.

Some errors are only discovered during execution. 
I think, in a batch, this "argument out of range" error is reported instead of the real error.

**Comment by stax76** [comment] 2020-06-18 00:24
Ok, next build has proper error handling for this situation.

**Comment by stax76** [comment] 2020-06-23 08:20
Fixed in last beta.

**Closed by stax76** 2020-06-23 08:20 UTC
Labels: bug, fixed
