### ISSUE TITLE
The last "Create job for each selection" trim outputs all splits together

### ISSUE THREAD

**Issue by HASJ** [staxrip/staxrip#676] opened 2021-04-23 01:06 UTC
**Describe the bug**
When in the Preview window and using the option to `Cut > Create job for each selection`, the last job of the file uses all splits together, this was supposed to be video_6:

`C:\Users\_\StaxRip\Apps\Support\MKVToolNix\mkvmerge.exe -o "D:\Videos\Captures\video.mkv" --no-audio --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags "D:\Videos\Captures\video.mp4" --no-chapters --audio-tracks 0 --language 0:por --default-track 0:0 --forced-track 0:0 "D:\Videos\Captures\video_temp\ID1.m4a" --title "video" --split parts-frames:0-24434,+25414-54855,+55908-83971,+85191-110131,+111190-135391,+136408-154059 --ui-language en`

but the previous job:
`C:\Users\Dudu\StaxRip\Apps\Support\MKVToolNix\mkvmerge.exe -o "D:\Videos\Captures\video_5.mkv" --no-audio --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags "D:\Videos\Captures\video.mp4" --no-chapters --audio-tracks 0 --language 0:por --default-track 0:0 --forced-track 0:0 "D:\Videos\Captures\video_temp\ID1.m4a" --title "video" --split parts-frames:111190-135391 --ui-language en`

**Expected behavior**
For the last part to have the correct split timing and duration

**How to reproduce the issue**
Use the `Create a job for each selection`

**Provide information**
No error, StaxRip v2.4.0

**Comment by 44vince44** [comment] 2021-04-23 06:50
I'll check this later and confirm. this feature is not much used.

**Comment by 44vince44** [comment] 2021-04-23 08:52
OK this is NOT CONFIRMED.

**Could not reproduce it. Works perfectly**

@HASJ Probably, when you were asked to save the project, you said YES, which created this job with all the trims merged.
Notice that your job that made all the trims together generates a video called video.mp4 and NOT video6.mp4

**Comment by Dendraspis** [comment] 2021-04-23 23:45
Took a while to understand what the problem was, but it will be fixed in the next release.  🤓

**Closed by Dendraspis** 2021-04-23 23:45 UTC
Labels: added/fixed/done, bug

**Comment by HASJ** [comment] 2021-04-26 00:31
Thanks for the quick patch
