### ISSUE TITLE
Being able to set detect volume in general options

### ISSUE THREAD

**Issue by Bandid0** [staxrip/staxrip#1484] opened 2024-09-13 09:05 UTC
Staxrip includes 3 types of normalizations volumedetect dynaudnorm loudnorm 
and you can choose one of them.
But in my view volumedetct is complementary to the other two since it is the one that analyzes the volume level in order to set it at a correct level.
I use the other two to normalize the dialogues of the surround formats.
What I think would be best is to first analyze the audio with volumedetect and establish the db that the user considers correct. 
Then if you want to apply one of the other normalizations.
In fact, I would put volumedetect in general options since I don't know who might be interested in having a video with audio with less than -13 db, for example.
As has already been mentioned here on some occasions, I do not know if the way in which this application was first programmed allows this type of modifications to be possible, and if they are, they carry a significant workload.
I leave a link where this matter is more or less explained.
https://trac.ffmpeg.org/wiki/AudioVolume

**Comment by Dendraspis** [comment] 2024-09-13 09:41
I don't think that I understand your message.  😕 

You can select the normalization method used with `ffmpeg`, which then will be used to do the normalization in case you enable this option.

> In fact, I would put volumedetect in general options since I don't know who might be interested in having a video with audio with less than -13 db, for example.

Therefore you use normalization to raise the volume to 0dB.  🤔

**Comment by Bandid0** [comment] 2024-09-13 11:00
Basically what I'm explaining is the possibility of being able to use two normalizers.
Let's imagine an audio with -15db
If I apply only dynaudnorm it balances the dialogues but the general volume level will still be low
If I only apply volume, detect the level if I left it at the correct level, but it is a linear increase in volume, the effect of the 5.1 type audios will remain the same, very low voices and very loud music.
The correct thing is to apply volumedetect to set audio to 0db for example and then apply dynaudnorm to level the voices and other effects.

**Comment by Dendraspis** [comment] 2024-09-16 07:57
It seems one of us has an understanding problem.  🤔 

Normalization by definition means, that you make the track *as loud as possible without clipping*, meaning bringing the peak volume to `0dB`. There are certain ways to do that, but none would make some channels louder while keeping the overall peak volume at `-15dB`. Whatever the effect is, it is not *Normalization* anymore.

And from what I see and know is, that each of those methods brings the result to `0dB`.  🤔

**Comment by Bandid0** [comment] 2024-09-16 09:43
When audio normalization is applied in Staxrip with the volumedetect option, an analysis of the audio is first performed to check where the maximum dB peaks are, and then the dB reduction or increase is applied based on what has been specified in the parameters panel, which by default is set to 0dB.

However, if the dynaudnorm option is chosen, this preliminary analysis is not done, so it is not known whether I need to increase or decrease the dB in the options panel. If an audio is at -15dB, even though this normalization is configured to set the audio to 0dB, it does not do so and remains at -15dB. The same happens with loudnorm.

Therefore, after applying either of these two options to the resulting audio, I have to apply the volumedetect option to find out the dB level of the audio and adjust it up or down to obtain, in my case, 0dB.

And excuse me if I am not making myself clear or if I am completely wrong.

**Comment by Dendraspis** [comment] 2024-09-16 14:50
Ok, I got you.

The problem is not, that a second run is needed - when using `dynaudnorm` or `loudnorm` the workflow is broken, means that they are not applied correctly. So we have a bug here.

**Comment by eremichyura** [comment] 2024-10-16 00:15
> Basically what I'm explaining is the possibility of being able to use two normalizers. Let's imagine an audio with -15db If I apply only dynaudnorm it balances the dialogues but the general volume level will still be low If I only apply volume, detect the level if I left it at the correct level, but it is a linear increase in volume, the effect of the 5.1 type audios will remain the same, very low voices and very loud music. The correct thing is to apply volumedetect to set audio to 0db for example and then apply dynaudnorm to level the voices and other effects.

**Bandid0**, You are compleatly wrong about how dynaudnorm working. You don't need to apply nothing before or after this type of normalization in any case. It's working in dynamic way. And it powerfull and complex. But such params like Target RMS and Target Peak are very important. You can't just make -15 dB audio louder (like to 0 dB). It's very risky to get distortions and overcliping in some parts of file. It's becouse aoudi file it's not constant - 15 dB. 
I think you should read about this in ffmpeg docs here https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm and dive deeper in that topic :)
Also, I just described case when doble normalization is applying, witch make results unpredictable and in bad quality.
see here: https://github.com/staxrip/staxrip/issues/1510.

As recap - if you use dynaudnorm you definitly doen't need any other normalizations. Play with it's params.

**Comment by eremichyura** [comment] 2024-10-16 18:04
thinking...
if you original audio is so pure, than It's maybe not good cacndidate to normalize it at  all...As I remember simple normalize like volume=x after voulemdetect is simply cut or add volumes...not processing it in some spceific way. So, for example if you have a file wtih +10 dB it's a big chance that volume=-10 dB doesn't remove existing clips, distortions in it. it's just make theme more quet.

Maybe when applying first dynanorm and then volumedect it's more chances to get better sound, but in my tests with qaac encoder wher exist --normolize param that works just like volumedetect and volume=x a got unpredictable results on good orginal audio files. sometimes clips, sometime distrions, some time both.

look like best solutiuons it to try and to check. (or change source audio:)

**Comment by Dendraspis** [comment] 2024-12-16 11:18
Should be fixed with some other issues in `v2.44.0`...

**Closed by Dendraspis** 2024-12-16 11:18 UTC
Labels: bug  :bug:, added/fixed/done, implemented for supporter releases
