### ISSUE TITLE
%source_temp_files% returns incorrect value

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#803] opened 2021-11-02 22:33 UTC
Hi,

**Describe the bug**
As mentioned above in the title, %source_temp_file% returns incorrect value. I can bore you with details but I just cut to the chase.

**Expected behavior**

**How to reproduce the issue**

The easiest and fastest way is to go to the path settings in the options, under "temp files folder" select source file directory but remove the "%source_name% so it should be something like:
"%source_dir%_temp"

Now if you load any media into Staxrip and check the macros, the %source_temp_file% is incorrect. It's just "temp" 

It should return the name of the source file. not just a "temp" 
Everything the same, %target_temp_file% is working correctly.

**Comment by Patman86** [comment] 2021-11-03 06:27
Hi LazyNCoder,

You have to replace %source_temp_file% with %source_name% in the macros.

`clip = core.lsmas.LWLibavSource(r"%source_file%", cachefile=r"%source_temp_file%.lwi")`
`clip = core.lsmas.LWLibavSource(r"%source_file%", cachefile=r"%source_name%.lwi")`

**Comment by LazyNCoder** [comment] 2021-11-03 16:51
Hi Patman86

Thank you very much. The thing is, I tried so many things, including the one you mentioned, but as I stated on Doom9, it would make Stax do weird things.
It tries to index the source multiple times and this is my log file:
```
---------------------------- Index LWLibav ----------------------------

C:\Users\Administrator\Desktop\StaxRip-v2.10.0-x64\Apps\FrameServer\VapourSynth\vspipe.exe E:\Short\_temp\Short.vpy NUL -i

Start:    8:12:40 PM
End:      8:12:41 PM
Duration: 00:00:00

---------------------------- Index LWLibav ----------------------------

C:\Users\Administrator\Desktop\StaxRip-v2.10.0-x64\Apps\FrameServer\VapourSynth\vspipe.exe E:\Short\_temp\Short.vpy NUL -i

Start:    8:13:28 PM
End:      8:13:28 PM
Duration: 00:00:00

---------------------------- Index LWLibav ----------------------------

C:\Users\Administrator\Desktop\StaxRip-v2.10.0-x64\Apps\FrameServer\VapourSynth\vspipe.exe E:\Short\_temp\Short.vpy NUL -i

Start:    8:13:29 PM
End:      8:13:29 PM
Duration: 00:00:00
```

That's all. no encoder logs or anything. Could you please check for yourself?
I can't describe this better. 

I switched from FFMS to LWLibavSource because of a bug that would make glitches which I asked about here:
https://github.com/staxrip/staxrip/discussions/794

**Comment by Patman86** [comment] 2021-11-04 20:10
I cannot reproduce it exactly. Something like that, but it works...

[with ffms](https://a.tmp.ninja/bbToZZqz.mp4)

[with libav](https://a.tmp.ninja/xaAFyvuP.mp4)

**Comment by LazyNCoder** [comment] 2021-11-05 23:16
Well, It's still a bug and should be fixed IMO.

If you use Vapoursynth+ffms, set the temp path to "%source_dir%_temp\"(or any other static name) and try to do a file batch with 2 or more files, it will definitely throws a fatal error:
Script Error
Python exception: Source: The index does not match the source file

It should be two different files on the same folder. When you start the second encode, you get the error. I can post a clip if any one needs it.

**Comment by Dendraspis** [comment] 2022-03-21 23:03
First, using `%source_name%` instead of `%source_temp_file` is the right way, like @Patman86 already mentioned.

I can imagine, that it could lead to issues, depending the used source and settings. 
A possible solution could look like:  `%temp_dir%%source_name%.lwi` , at least as long there are no projects using different cuts or similar.
With the next release it is also possible to use something like `%temp_dir%%source_name%--%random:5%.lwi` which should handle all those issues.

I'll close it for now, feel free to re-open it when the issue still occurs with the next release.

**Closed by Dendraspis** 2022-03-21 23:03 UTC
