### ISSUE TITLE
NVEncC encodes slowly grab all available RAM causing failure

### ISSUE THREAD

**Issue by ChocOranger** [staxrip/staxrip#1503] opened 2024-10-09 16:17 UTC
**Describe the bug**
StaxRip v2.42.1 (with v2.42.0)
When encoding using NVEccC, RAM is slowing consumed until it reaches the maximum available (32GB in my case, less a few other programs running). Other programs will fail and whilst the encode continues the media will be corrupt at the end.
The higher the bitrate and movie length the more likelihood of failure. 

**Expected behavior**
RAM usage should be like older versions ie just over 1.5GB or a reasonable limit

**How to reproduce the issue**

Load a movie. Choose any Nvidia encoder. Set the variable bit rate fairly high eg 25000.
Start encoding.
RAM usage will steadily increase throughout the encode.

StaxRip    : v2.42.1
Settings   : v2.42.1
Windows    : Windows 10 Home 22H2 2009 (19041.1.amd64fre.vb_release.191206-1406)
CPU        : AMD Ryzen 7 7700X 8-Core Processor
RAM        : 32GB
GPU        : NVIDIA GeForce RTX 3080

**Additional context**
Copying the Encoders/NVEncC files from the previous release (v2.41.7) into v2.42.1 makes StaxRip work as expected ie RAM usage doesn't continually grow.

**Comment by Dendraspis** [comment] 2024-10-09 22:18
> Copying the Encoders/NVEncC files from the previous release (v2.41.7) into v2.42.1 makes StaxRip work as expected ie RAM usage doesn't continually grow.

`v2.42.0` comes with `NVEncC v7.66`, so it looks like you have downgraded to `NVEncC v7.57` to get it work again. Did you try the latest version `NVEncC v7.69` as well?

**Comment by ChocOranger** [comment] 2024-10-10 15:34
> `v2.42.0` comes with `NVEncC v7.66`, so it looks like you have downgraded to `NVEncC v7.57` to get it work again. Did you try the latest version `NVEncC v7.69` as well?

NVEncC v7.69 Same issue with RAM (also tried v7.64 & 7.60 to find when issue started - these also have the issue)
NVEncC v7.58  introduced the rising RAM issue.

NVEncC v7.57 is the last good version
I also tested NVEncC v7.56 to make sure I wasn't doing something silly. That works as expected.

**Comment by Dendraspis** [comment] 2024-10-11 00:07
It looks like this is not an issue with StaxRip but NVEncC, especially because using the latest StaxRip version with an older version of NVEncC seems to work fine according to your experiences.

So it seems to be a good idea to head over to https://github.com/rigaya/NVEnc and open an issue there.
I recommend adding the complete command line and maybe the script, in case no hardware decoder was used, so rigaya can try to reproduce the issue.

**Comment by Dendraspis** [comment] 2024-10-12 12:50
It was already reported and fixed by rigaya here:
https://github.com/rigaya/NVEnc/issues/625

So I close this one...

**Closed** 2024-10-12 12:50 UTC
Labels: tool issue, added/fixed/done

**Comment by ChocOranger** [comment] 2024-11-06 16:15
The proper memory leak fix is in https://github.com/rigaya/NVEnc/releases/tag/7.73
