### ISSUE TITLE
Long File Names  and special characters

### ISSUE THREAD

**Issue by IAmMisterX** [staxrip/staxrip#209] opened 2020-05-27 15:33 UTC
StaxRip is not working with filenames greater than ca. 100 characters, or with special characters (e.g. "#") in it.
Sometimes this causes Staxrip to Abort the batchjob, sometimes it causes Staxrip to  "hang"
I understand  that some tools Staxrip uses does have those limitations.
However this may be be fixed by Staxrip using temporary working names

**Comment by stax76** [comment] 2020-05-30 12:39
Next build supports # because it was fixed in MP4Box 0.9.0, thanks!

Regarding long path issues, please provide a log file.

**Comment by IAmMisterX** [comment] 2020-06-04 09:22
Hi,

unfortunately a log file is not created at all.
Three windows do pop up very quickly after I start the job
I attached 2 of them and added the full content of one (by clicking on "Copy Message" on the window)
I hope this helps - in any case: Thanks you for your help

P.S: except the "#" also the "%" character in a file name causes StaxRip to abort (but this is less critical at least for me)

Peter

DirectoryNotFoundException (2.0.8.0)

Ein Teil des Pfades "R:\work_temp\Aktuelles und Gesellschaft - Reportagen und Recherchen-Re_ Alleingang am Mont Blanc - Grenzerfahrungen eines Solo-Bergsteigers-140968522_temp\Aktuelles und Gesellschaft - Reportagen und Recherchen-Re_ Alleingang am Mont Blanc - Grenzerfahrungen eines Solo-Bergsteigers-140968522_source.avs" konnte nicht gefunden werden.

System.IO.DirectoryNotFoundException: Ein Teil des Pfades "R:\work_temp\Aktuelles und Gesellschaft - Reportagen und Recherchen-Re_ Alleingang am Mont Blanc - Grenzerfahrungen eines Solo-Bergsteigers-140968522_temp\Aktuelles und Gesellschaft - Reportagen und Recherchen-Re_ Alleingang am Mont Blanc - Grenzerfahrungen eines Solo-Bergsteigers-140968522_source.avs" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bei StaxRip.StringExtensions.WriteFile(String value, String path, Encoding encoding) in D:\Projekte\VB\staxrip\General\Extensions.vb:Zeile 340.
   bei StaxRip.StringExtensions.WriteFile(String value, String path, Encoding encoding) in D:\Projekte\VB\staxrip\General\Extensions.vb:Zeile 340.
![StaxRip Error 1 - Long Pathname](https://user-images.githubusercontent.com/66024097/83739037-5b27fe00-a655-11ea-935f-499531320b41.jpg)
![StaxRip Error 2 - Long Pathname](https://user-images.githubusercontent.com/66024097/83739041-5bc09480-a655-11ea-9524-c1139daa0220.jpg)

**Comment by IAmMisterX** [comment] 2020-06-04 09:24
Sorry, closed by mistake :-(

**Comment by stax76** [comment] 2020-06-06 17:50
The issue is addressed in the beta from today, see danger zone in the settings dialog, if a user opens too long files, they are blocked with an error message:

> Character limit of source file paths and half of it as filename limit. In theory Windows supports paths that are longer than 260 characters, in reality neither Windows, nor the .NET Framework or the used tools have full long path support.

**Comment by stax76** [comment] 2020-06-23 06:41
[duplicate](https://github.com/staxrip/staxrip/issues/226)

**Closed by stax76** 2020-06-23 06:41 UTC
Labels: duplicate
