### ISSUE TITLE
Audio is not properly cut when the frame rate is altered in the script

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#710] opened 2021-05-18 15:18 UTC
- StaxRip version: 2.5.9

**Describe the bug**

When the _frame rate_ is altered by the script, _audio cutting_ is not properly done because the (bogus) video stream of the avi file for audio cutting is generated with the _altered_ frame rate, **_not the original source frame rate_**, while audio is cut based on the original frame rate. This esp. raises a problem when the video is bobbed (=frame rate is doubled) by QTGMC, which is the default with QTGMC. In this case, the audio duration becomes just half of the output video playback time, and audio playback becomes out of sync.

**Expected behavior**

The video stream of the avi file for audio cutting should be generated with the _original_ source frame rate.

**How to reproduce the issue**

The source file is [here](https://drive.google.com/file/d/1932O54x9mWtqhQMo0FypcCqWGltX7uKH/view?usp=sharing)(113 MiB, MBAFF interlaced 422 10bit VFR).

Encode the source file with settings as follows:

![StaxRip_2 5 9_QTGMC_cutting_sample_settings_20210518](https://user-images.githubusercontent.com/3157518/118673158-a2979380-b7ad-11eb-8060-98bc45e255bd.png)

![StaxRip_2 5 9_QTGMC_cutting_sample_settings_code-editor_20210518](https://user-images.githubusercontent.com/3157518/118673103-98759500-b7ad-11eb-81ce-7d3b8e2d44a7.png)

Since the fields are bobbed, the output frame rate is doubled.

Here's the output file: [here](https://drive.google.com/file/d/1yIsILj_v8Myd_Vk62kUTcGDjLTThLWhc/view?usp=sharing)(9 MiB).

As you can see, _the audio stops at half and does not match the video_.

**The cause**

We can see why this happens if we look into the log.

Here's the log file: 
[MBAFF interlaced 422 10bit VFR sample_new_staxrip.log](https://github.com/staxrip/staxrip/files/6502215/MBAFF.interlaced.422.10bit.VFR.sample_new_staxrip.log)

The avi file generated for audio cutting has a frame rate of 50 fps (line 339) because the video stream was generated with this option in the filter: `r=50.000000000` (line 300). I.e., its frame rate is based on the one _altered by the script_.

But the audio stream is cut based on the _original_ frame rate (25 fps): `--split parts-frames:58-430` (line 349).

Therefore, only half of the required amount is cut as a result. Furthermore, the starting time of audio becomes different than that of the video stream, and thus audio gets out of sync.

**Comment by 44vince44** [comment] 2021-05-18 20:19
@JJKylee You actually found another bug then the one you describe 🤣 

BY DESIGN: Staxrip sets and uses TRIM only at the end of the script.

The fact that you have Trim() NOT at the end means that:
- either you typed it, in that case EVERYTHING relating to audio and subs cutting will be incorrect, 
- or you created it with the preview window, then you moved it in the main window's filter section, **which should not be allowed!!!! and that's the bug you have found**.

**Comment by JJKylee** [comment] 2021-05-18 20:47
@44vince44,

Thanks for letting me know. You're right. I force put `cutting` right after the source filter _thinking it's more natural_. 😝

> BY DESIGN: Staxrip sets and uses TRIM only at the end of the script.
> This is how you are supposed to use range cutting!

Now I can figure out. That's why `cutting` was _persistently_ put back at the END of the script. Geez... 😓

Like you said, audio cutting is done right if I put `cutting` at the end of the script.

But is it OK to put it even after `Prefetch`? 🤔 Well, I guess there's no problem since there was no problem with it. 😁

**Comment by 44vince44** [comment] 2021-05-18 20:50
Yes, it can be set after Prefetch (Trim does not involve processing and multithreding, it acts as a definition)

**Comment by 44vince44** [comment] 2021-05-18 21:01
@Dendraspis This is no bug, this is a matter of being careful.

The only bug is : when Trim filter is moved in the main widow, unless you do something that resyncs the script, it will not be moved again to the bottom (which is the CORRECT PLACE).

**Comment by JJKylee** [comment] 2021-05-18 21:02
> I'm afraid it wouldn't be easy at all to allow Trim anywhere else, because it would mean changing many things in Staxrip's code...

There must be ppl who force put `cutting` somewhere else like me. 😅 
Why don't we put a stronger _red_ warning message when the user tries to move `cutting`? 😁 Would that be difficult?
Or... maybe there's a better solution. Hmm... 🤔

**Comment by 44vince44** [comment] 2021-05-18 21:30
The watchdog is already there, and it moves the filter to the bottom everytime there is a script sync.

The only problem is that if you move a filter in the main window, there should be a script sync when you release the mouse click after moving the filter, and that doesn't seem to work!

**Comment by JJKylee** [comment] 2021-05-18 22:50
> The only problem is that if you move a filter in the main window, there should be a script sync when you release the mouse click after moving the filter, and that doesn't seem to work!

You're right. Users can always move the `cutting(trim)` filter ignoring the warning message in the _Assistant_, and once it is moved, the warning message is not there anymore (as you can see in my screenshot). This seems to be the real bug, and it needs to be fixed. 🤔

**Comment by Dendraspis** [comment] 2021-05-19 07:45
I don't think we will do something on this issue, because it seems to be no real issue - as you already mentioned meanwhile, partially.

Cutting is applied at a specific definition. When you open the Preview window to start cutting, all settings are considered at that time, including the frame rate. Of course it is possible to set the frame rate to 25fps, then do the cutting and afterwards set the frame rate to 60fps. But when you start changing the order, bad things may happen, for example because of interpolated frames.

Side note:
The `Cutting` filter is not forced to be always at the bottom - it is just deleted and re-added every time you open and close the Preview.

**Comment by 44vince44** [comment] 2021-05-19 08:32
> The Cutting filter is not forced to be always at the bottom - it is just deleted and re-added every time you open and close the Preview.

....or the code editor.

**Comment by Dendraspis** [comment] 2021-05-19 08:57
> ....or the code editor.

I forgot the "for example".  😁  Bis yes, Trimming is called after closing the Code Editor.
But speaking of this, this behavior should stop.  🤔   When you have trimmed the video and then you call a function that interpolates frames or even delete them, the trimming will produce wrong results, when it will be placed behind that change.

**Comment by 44vince44** [comment] 2021-05-19 09:08
@Dendraspis 

> Trimming is called after closing the Code Editor.
But speaking of this, this behavior should stop

I suggest not changing anything here. The behavior is perfect once you get used to it. @stax76 spent much time to find this solution THAT GUARANTEES in 99.99% of cases that everything works OK and that ALL preview windows are synchronized in terms of range selection. If anything is changed, this feature will certainly be broke... Be careful please ( = change nothing 😁 )

**Comment by Dendraspis** [comment] 2021-05-19 09:28
I understand what you mean. But there are no *99.99%*, and certainly no guarantee at all.

Example:
1. Load the source - a normal 25fps video
2. Cut/Trim the video
3. **Add** a `ChangeFPS` filter with a setting of 50 fps
4. Open/Close Code Editor to verify the filters

Everything should work including point 3. But when you open the Code Editor to check the code and maybe fine tune some parameters, the result will be *broken* - only because you wanted to check/edit something else! So in that case you have to remember where the `Cutting` filter was placed before opening the Code Editor, so you can place it there again after closing the Code Editor.
This is not how it should work!  🤔

**Comment by 44vince44** [comment] 2021-05-19 10:04
This is because in Staxrip logic, BY DESIGN, Trim has always been intended to be placed at the end.
Therefore my previous text:

> you created it (the trim) with the preview window, then you moved it in the main window's filter section, which should not be allowed!!!! and that's the bug you have found.

**Comment by Dendraspis** [comment] 2021-05-19 11:45
And it's sort of useful, **but** there should be no change of the order .... and if there should be one, than the trim have to be recalculated - which will probably never happen.  😂 

So I tend to remove the re-applying of `Cutting` when Code Editor is opened/closed.  🤔

**Comment by JJKylee** [comment] 2021-05-19 14:11
> So I tend to remove the re-applying of `Cutting` when Code Editor is opened/closed. 🤔

Sounds reasonable. I just hope another bug is not made in the course. 😝

That said, I'm also wondering: why haven't there been any users who brought this up so far? 🤔
(Maybe there used to be some in the past, but ever since I started using StaxRip, I've never seen this topic being brought up. 🙄)
Well, that may mean that I'm the _only one_ who wants to force rearrange the filter order. 😂
If users are happy with the current workings done by StaxRip on the `trim` filter (=automatically re-putting the `trim` filter at the bottom after Code Editor is opened and closed), then you don't have to mind, @Dendraspis. I won't complain either... although it means I have to re-do the trim job. 😁😁😁😁😁

**Comment by 44vince44** [comment] 2021-05-19 16:06
@Dendraspis 

> So I tend to remove the re-applying of Cutting when Code Editor is opened/closed. 🤔

If I'm not mistaken, the reapplying of cutting is exactly the logic that ensures the sync of the trim values when MULTIPLE preview windows are open... (designed by @stax76)

**Comment by Dendraspis** [comment] 2021-05-19 16:29
> Sounds reasonable. I just hope another bug is not made in the course. 😝

That's what I say to myself after **every** change.   😂 

> That said, I'm also wondering: why haven't there been any users who brought this up so far? 🤔

I guess they are trimming at the end, but to be honest I think there are very, very few users, that use trimming.

> Well, that may mean that I'm the _only one_ who wants to force rearrange the filter order. 😂

Simply **yes**.  😁 

> If users are happy with the current workings done by StaxRip on the `trim` filter (=automatically re-putting the `trim` filter at the bottom after Code Editor is opened and closed), then you don't have to mind, @Dendraspis. I won't complain either... although it means I have to re-do the trim job. 😁😁😁😁😁

Changed it already.  😁

**Comment by 44vince44** [comment] 2021-05-19 17:46
@Dendraspis I completely trust your wise qualities as coder and analyst, as ALWAYS !!!

**Comment by Dendraspis** [comment] 2021-05-20 20:31
Ok, the current state is not bulletproof and we could call it a bug, but it is less confusing and more understandable than he old one.

### Before:
Every time the Preview or CodeEditor was closed, the `Cutting` filter was removed (didn't matter where it was) and a new one was added at the end/bottom. 
**Drawback:** Above we already talked about the resulting problems. 

### Now:
Instead of renewing an existing `Cutting` filter, it will be overwritten/edited. 
**Drawback:** The Preview takes ***all*** filters into consideration when displaying the frame and cutting. So when a frame number changing filter is applied ***after*** `Cutting`, opening the Preview will obviously break the ranges.

**Comment by 44vince44** [comment] 2021-05-20 20:49
I will test this thoroughly tomorrow 🤔

**Closed** 2021-05-21 16:47 UTC
Labels: added/fixed/done, bug, feature request, not an issue

**Comment by JJKylee** [comment] 2021-05-22 22:29
> ### From now on:
> Instead of renewing an existing `Cutting` filter, it will be overwritten/edited.
> **Drawback:** The Preview takes _**all**_ filters into consideration when displaying the frame and cutting. So when a frame number changing filter is applied _**after**_ `Cutting`, opening the Preview will obviously break the ranges.

True.

I tested the same source with the same settings (with `Cutting` force put _before_ `QTGMC`) in v2.6.0.
(The average frame rate becomes 25 -> 50.)
I re-opened and closed _Preview_ before encoding, and `Cutting` is not renewed like before.

Result:
Now, the video is cut at wrong frames: _twice the length I originally expected_.

So, I could avoid the refreshing `Cutting` filter at the bottom this time, but I can't see any _improvement_ over the previous behavior. Both have incorrect results although the detail is different.

If so, isn't it better to have force-refreshed `Cutting` filter at the bottom like before? At least it gives the correct frame cut of the video stream.

Or shouldn't I have re-opened _Preview_?

 Hmm... 🤔❓

**Comment by Dendraspis** [comment] 2021-05-23 09:07
I still depends on the order. Have in mind, that Preview uses all active filters for displaying and cutting, whereas `Cutting` is always applied at the point where it is set.

So to achieve what you would like to do you can do...

1. 
    - Apply QTGMC  (which doubles the frame rate)
    - Apply Cutting
    - Leave Cutting below QTGMC, because Cutting uses the doubled frame rate
­   
2.
    - Apply Cutting
    - Apply QTGMC  (which doubles the frame rate)
    - Don't open Preview again, otherwise you have to move Cutting to the end, at least below QTGMC
­   
3.
    - Apply Cutting
    - Apply QTGMC  (which doubles the frame rate)
    - Do something else
    - Disable QTGMC
    - Open Preview, adjust the cutting and close it
    - Enable QTGMC again (which is still below Cutting

Example (3) is just to demonstrate how to handle re-cutting with frame rate changing filters after/below Cutting.


> So, I could avoid the refreshing Cutting filter at the bottom this time, but I can't see any improvement over the previous behavior.

The difference is, that you are now able to open the Code Editor without destroying the cutting. Now it's also easier to cut the video before adding a filter, for example a frame interpolation filter like `ChangeFPS(60)`.

> If so, isn't it better to have force-refreshed Cutting filter at the bottom like before? At least it gives the correct frame cut of the video stream.

That was only the case if Cutting was your last step. Look at the example I posted a few days ago.

> Or shouldn't I have re-opened Preview?

Indeed.  😁 

It's still not perfect, but at least you won't destroy the cutting by opening the CodeEditor anymore. And yes, there is still space for improvements.
