### ISSUE TITLE
Manually editing the Cutting script restores it to the settings in the preview window

### ISSUE THREAD

**Issue by HASJ** [staxrip/staxrip#511] opened 2021-02-12 19:24 UTC
**Describe the bug**
If there is a `Cutting` filter added to the script and you manually edit the code, the filter will revert to the original setting, discarding the manually set one.

**Expected behavior**
For the script to be retain my modifications and the preview to reflect that.

**How to reproduce the issue**
Since there is no way to add a `Cutting` filter manually, you have to:
Click `Preview`
Set a time window to trim the source
Double click on the `Cutting` filter, in `AVS Filters`
Change the trimming values
Click OK
Check either the `Preview` or the `Cutting` filter again and the values will be the old ones

**Provide information**
- Used StaxRip version
StaxRip 2.1.8.

**Comment by HASJ** [comment] 2021-02-12 19:29
I initially created all the trim timings, copied the code and then would add them back to extract clips from the movie. Unless there is a better way to create multiple trims from the same file and extract them as separate files without creating multiple jobs, this is what I've trying to do.

**Comment by JJKylee** [comment] 2021-02-12 19:56
I found the same phenomenon, and according to @Dendraspis, this is not a bug.
It's how _Preview_ and _Code Editor_ are designed in regards to trims: _Preview_ is the master, and _Code Editor_ follows. So when you need to do trims, use _Preview_, not _Code Editor_. 😅

**Comment by Dendraspis** [comment] 2021-02-12 20:07
That's right. At least at the moment the values are not re-imported.

If you wanna change the trims by hand, you can copy the code in ***Cutting*** and add it to another section. Then disable ***Cutting*** and delete all trims in ***Preview***.

If you don't wanna use ***Preview*** at all, you can simple add the trimming code in any section.

**Comment by HASJ** [comment] 2021-02-12 20:50
@Dendraspis 
> If you don't wanna use Preview at all, you can simple add the trimming code in any section.
Then the audio doesn't get trimmed 😥

**Comment by 44vince44** [comment] 2021-02-12 20:56
I confirm this is not a bug, this is how Staxrip is intended to work (since ever). Cutting must be set in the preview and not be typed in ! I believe allowing to edit manually the cutting filter could cause problems with the logic of many previews opened from different origins (from main window, and from edit window). @HASJ what is wrong with using the preview ?

**Comment by HASJ** [comment] 2021-02-12 21:49
@44vince44 
>what is wrong with using the preview ?

Like I said, trying to extract small clips from the same video is counterintuitive when using the preview. I had to figure out you needed to make different jobs for each clip and, for each, go to the preview window and select the trim timmings yet again.
At first I believed the `Split` function of the preview window would do this but it doesn't.
If there was a... `Create jobs with the selected trims` option in the preview, this would be a great solution but I don't know how hard it would be to implement.

Should I create a feature request issue?

**Comment by 44vince44** [comment] 2021-02-12 21:53
@HASJ I have a working solution give me 2 minutes, I'm writing it... No need for feature request. It's already there.

**Comment by 44vince44** [comment] 2021-02-12 22:01
@HASJ 
Here is the solution for your problem:

1) BEFORE you load your video file, you MUST select the option OPTIONS>Audio>"On Load use Avisynth script as audio source"
2) Chose a source filter that handles Video AND Audio, such as FFMS2 (and not FFVideoSource or Automatic)
3) Open or drag-drop your video file. Then set up the filters and encoders parameters. 
4) In the code editor, chose any slot other than crop and resize (and Cutting), delete what's inside and type your Trim (a,b) filter

Create the job(s), run. The resulting file will be cut, both video and audio streams.

> Then the audio doesn't get trimmed 😥


Not with this method!

**Comment by HASJ** [comment] 2021-02-12 23:04
@44vince44 Yeah but my feature request would be much more practical. What if you want to do a dozen clips? Quite bothersome.
Regardless, many thanks. I'll be using this for the time being.

**Comment by 44vince44** [comment] 2021-02-12 23:16
Once the file is loaded (properly, as explained above), you just type the values for Trim(a,b), set the output name, click on Next to create job, then type new values for Trim(a,b), new output name, press Next. And so on.

If you want to request a feature that automatically creates jobs for every partial range, you can do so. up to the coders to decide...

**Comment by HASJ** [comment] 2021-02-12 23:30
I know and since this hasn't been implemented, I have close to zero hopes it'd be actually done, since it's so niche. But it wouldn't hurt to at least ask.

**Comment by JJKylee** [comment] 2021-02-13 01:43
I also think @44vince44's suggestion is useful as well as practical. 👍

Maybe `Join Filters`(`Ctrl+J`) may come in handy in `Code Editor`.

![StaxRip_2 1 8 0_Code-Editor_Join-Filters_20210212](https://user-images.githubusercontent.com/3157518/107838045-d4d1c900-6d58-11eb-8f91-74f52026b402.jpg)

![StaxRip_2 1 8 0_Code-Editor_Join-Filters_merged_20210212](https://user-images.githubusercontent.com/3157518/107838046-d9967d00-6d58-11eb-9b1a-63b012573b85.jpg)

I made a separate **_template_** for processing audio via `avs`.

I guess there's one catch in encoding the `avs` audio with `ffmpeg`: you need to add a custom option `-vn`. Otherwise, you'd be encoding video as well in audio encoding.

![StaxRip_2 1 8 0_ffmpeg_avs_audio_encoding_-vn_20210212](https://user-images.githubusercontent.com/3157518/107838254-d8b21b00-6d59-11eb-8151-80683bc66f81.jpg)

**Comment by 44vince44** [comment] 2021-02-13 07:07
@JJKylee 

 you need to add a custom option -vn. Otherwise, you'd be encoding video as well in encoding audio.

That's an important catch! and a good find 👍🏼 

Thanks !

**Comment by stax76** [comment] 2021-02-13 11:07
> I know and since this hasn't been implemented, I have close to zero hopes it'd be actually done, since it's so niche. But it wouldn't hurt to at least ask.

Priority Medium as far as I'm concerned, but only if it's easy enough to build.

**Comment by 44vince44** [comment] 2021-02-14 14:49
We can close this one because the feature request https://github.com/staxrip/staxrip/issues/512 is WORKING (I've tested it)

**Closed** 2021-02-14 15:43 UTC

**Comment by BishtNeeraj22** [comment] 2025-01-05 07:37
Can anyone show the process of trimming audio along with the video.
