### ISSUE TITLE
Opening file crashes on mpeg/vob files when ffmpeg is selected

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1035] opened 2023-07-04 13:15 UTC
If you select ffmpeg > ProRes and ffmpeg > mov then import source .mpeg or VOB file, the program completely crashes then closes without any errors.

It will also crash with default settings H265 > mpv or .mp4.

Per my observation this is happening once you preselect the AVS Filters using Field > QTGMC Interlaced.

If you open the file first it will not crash, but as soon as you enable "Field" to try and enable Interlace it completely crashes. 
I hope this is helpful, i'm using StaxRip 2.21.0 but same behavior with older versions.

**Comment by Dendraspis** [comment] 2023-07-04 17:29
Sorry, I can't reproduce your scenario, either AVS nor VS, x265 or ffmpeg, QTGMC or not. Especially when the encoder should have no impact on the file opening.

Crashes due to filters are pretty rare, because mostly they throw out an error message, but in all cases it is very likely the filter parameters are set wrong and/or the filter is not meant to be used with your source file.

It would be useful to see the log file.
For further diagnoses it would be necessary to also provide a sample file as well as the code line(s) in `QTGMC Interlaced` you have used.

![image](https://github.com/staxrip/staxrip/assets/50659978/f6c65244-23ed-4d3b-83ce-ec46aab5410c)

![image](https://github.com/staxrip/staxrip/assets/50659978/cbda3c98-d752-45e5-8741-936bc309cc25)

**Comment by craposoup** [comment] 2023-07-04 20:09
I am able to create it.  
I've recorded a video for reference: https://mega.nz/file/MA8WyCBC#5G3Y10l2lMZNW0ZWNelad88QxK_d66Za6zpEacSFOao

As you will see, it just closes with no error message, where are the logs stored? it completely closes no matter what I choose.
I am not mismatching any parameters, ProRes with .mov is alligned, the default somehow dont work for me also.

**Comment by Dendraspis** [comment] 2023-07-04 20:55
Even if some interesting parts are cut off, I can see, that you can reproduce it. But the point is, that I have done another test following your video and I still can't reproduce it.
I think it should be related to your source file in some way.... a sample file would be nice.

🤔   Did you use a clean setup or do you use the settings/templates from an older StaxRip version, for example by using a user profile folder for the settings (that wasn't cleared up) or by copying them by hand to the new folder?

> Are there any special install conditions? folder location etc?

Nope, whereas I would recommend using a short path for the StaxRip folder, because some apps and filters don't like long paths.

**Comment by craposoup** [comment] 2023-07-05 01:39
I have been testing with a Clean install, no binary overlap, the latest version works fine on another system running Windows 11.

Another clean install is crashing on my Win10 Pro, 8GB RAM, Nvidia GeForce GTX 1650 graphics card, system

Here is the root cause:

Its crashing with the latest Plugins_JPSDR.dll, version: 3.3.4.0 file
![image](https://github.com/staxrip/staxrip/assets/49623148/271b76ba-5509-4d98-a3cc-33aab89b2872)

After I replaced the file with an older version which i know works, then the latest Staxrip works.
![image](https://github.com/staxrip/staxrip/assets/49623148/df33cb84-4199-4a3c-bfbb-c6087d7ba399)

I'm not sure why this is happening?  also what I'm i missing with the new version?

Here are the error logs:

Error Log 1
************************************************
Application: StaxRip.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at StaxRip.INativeFrameServer.OpenFile(System.String)
   at StaxRip.DirectFrameServer..ctor(System.String)
   at StaxRip.FrameServerFactory.Create(System.String)
   at StaxRip.VideoScript.Synchronize(Boolean, Boolean, Boolean)
   at StaxRip.VideoScript.GetInfo()
   at StaxRip.VideoScript.GetFrameCount()
   at StaxRip.Calc.GetOverheadBytes()
   at StaxRip.Calc.GetSizeInBytes()
   at StaxRip.MainForm.tbBitrate_TextChanged()
   at StaxRip.MainForm.UpdateSizeOrBitrate()
   at StaxRip.MainForm.AudioTextChanged(StaxRip.UI.TextEdit, StaxRip.AudioProfile)
   at StaxRip.MainForm.tbAudioFile0_TextChanged()
   at StaxRip.MainForm._Lambda$__R4-1(System.Object, System.EventArgs)
   at StaxRip.UI.TextEdit._Lambda$__61-4(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnTextChanged(System.EventArgs)
   at StaxRip.UI.TextBoxEx.OnTextChanged(System.EventArgs)
   at System.Windows.Forms.Control.set_Text(System.String)
   at System.Windows.Forms.TextBoxBase.set_Text(System.String)
   at System.Windows.Forms.TextBox.set_Text(System.String)
   at StaxRip.UI.TextEdit.set_Text(System.String)
   at StaxRip.MainForm.DetectAudioFiles(Int32, Boolean, Boolean, Boolean)
   at StaxRip.MainForm.OpenVideoSourceFiles(System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at StaxRip.MainForm.OpenVideoSourceFiles(System.Collections.Generic.IEnumerable`1<System.String>)
   at StaxRip.MainForm.ShowOpenSourceSingleFileDialog()
   at StaxRip.MainForm.ShowOpenSourceDialog()
   at StaxRip.UI.MenuItemEx.OnClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ToolStripDropDown.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at StaxRip.Startup.Main()

Error Log 2
************************************************
Faulting application name: StaxRip.exe, version: 2.21.0.0, time stamp: 0x64a21a67
Faulting module name: Plugins_JPSDR.dll, version: 3.3.4.0, time stamp: 0x64201879
Exception code: 0xc000001d
Fault offset: 0x00000000000a11a7
Faulting process id: 0x27d8
Faulting application start time: 0x01d9aed959fce2f6
Faulting application path: C:\StaxRip-v2.21.0-x64\StaxRip.exe
Faulting module path: C:\StaxRip-v2.21.0-x64\Apps\Plugins\AVS\JPSDR\Plugins_JPSDR.dll
Report Id: 457cf813-984d-42d8-b6cb-4605f081cebd
Faulting package full name: 
Faulting package-relative application ID: 

Please advise?

**Comment by craposoup** [comment] 2023-07-07 11:44
Any updates?

**Comment by Dendraspis** [comment] 2023-07-08 14:54
Nope because I'm currently afk.
I'll check it when I'm back, but it looks interesting.

> I'm not sure why this is happening? also what I'm i missing with the new dll version?

Either there is a bug or something has changed in that QTGMX implementation. What you're missing is a good question, I don't have the time to check each filter for detailled changes and/or extended test runs.

**Comment by craposoup** [comment] 2023-07-22 11:57
Another issue:  App crashes as soon as you select Noise>TemporalDegrain2
Win10, Nvidia GPU.

Faulting application name: StaxRip.exe, version: 2.22.0.0, time stamp: 0x64a5f186
Faulting module name: neo-dfttest.dll, version: 1.0.0.0, time stamp: 0x630d4069
Exception code: 0xc000001d
Fault offset: 0x0000000000011267
Faulting process id: 0x212c
Faulting application start time: 0x01d9bc927d2b53a6
Faulting application path: C:\StaxRip-v2.22.0-x64\StaxRip.exe
Faulting module path: C:\StaxRip-v2.22.0-x64\Apps\Plugins\Dual\DFTTest Neo\neo-dfttest.dll
Report Id: 86289792-7241-4384-a689-e4b0b4ce3f82
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Dendraspis** [comment] 2023-07-23 15:22
> Another issue: App crashes as soon as you select Noise>TemporalDegrain2
✔️ 

The other issue is still under investigation....

**Comment by craposoup** [comment] 2023-07-23 19:49
I was able to isolate ISSUE #1 related to "Plugins_JPSDR.dll"

Starip is shipped with the "AVX2" version of "Plugins_JPSDR.dll" which for me dont work on Windows 10.
I downloaded the "JPSDR.dll" pluggins pack from https://github.com/jpsdr/plugins_JPSDR/releases/tag/3.3.4

Here is the breakdown:
plugins_JPSDR_v3_3_4\x64\Release_W7_AVX2 - Does not work on Win10
plugins_JPSDR_v3_3_4\x64\Release_W7_AVX - This one works on Win10

Snapshot of the one that works, we need to solve why "**\Release_W7_AVX2\Plugins_JPSDR.dll**" is crashing on Win10.
![image](https://github.com/staxrip/staxrip/assets/49623148/6e3de184-375a-4f47-bb94-59b30116b57c)

**Comment by Dendraspis** [comment] 2023-07-23 21:43
Basically the AVX2 version works also on Win10.
What CPU do you have?

**Comment by Dendraspis** [comment] 2023-07-24 19:26
Wow, I know that XEON has this problem with some filters, but it seems your i5 is a bit too old?  i5s have AVX2 support since 4xxx. So sadly you have to replace it also with every new release.  😩   Anyway a good catch!  👍 

TemporalDegrain2  will be fixed in the next release, so I close this issue for now.

**Closed by Dendraspis** 2023-07-24 19:26 UTC
Labels: bug, added/fixed/done, not reproducible
