### ISSUE TITLE
Channel number restriction is needed for AC3/EAC3 encoding via ffmpeg

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#521] opened 2021-02-16 10:55 UTC
**Is your feature request related to a problem? Please describe.**

This was discussed in [Doom9's forum](https://forum.doom9.org/showthread.php?p=1933320#post1933320) about a month ago.

Since `ffmpeg` supports **_up to 5.1 channels_** for AC3/EAC3 encoding, we need to restrict the channel options accordingly.

If the user accidently selects a channel layout not supported by `ffmpeg`, he will run into an error as follows:

```
[ac3 @ 000002e160279200] Specified channel layout '7.1' is not supported
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Describe the solution you'd like**

![StaxRip_2 1 8 1_AC3-EAC3_channels_restriction_20210216](https://user-images.githubusercontent.com/3157518/108053249-03be9800-7002-11eb-8d3e-72205ee5935f.jpg)

**Comment by anthony75smith75** [comment] 2021-02-17 01:25
Have also noticed this issue after trying to do EAC3 7.1 channel encoding. One day ffmpeg will no doubt support greater than 5.1 channels for EAC3 but today is not that day. Have wanted this feature for some time. Does anyone know how to encode EAC3 7.1? Guess for now, as suggested we have to remove this option since it just returns an error.

**Comment by Dendraspis** [comment] 2021-02-17 01:42
> One day ffmpeg will no doubt support greater than 5.1 channels for EAC3 but today is not that day. Have wanted this feature for some time. 

I doubt that. The first ffmpeg feature request tickets regarding 7/8 channel encoding support are more than 7 years old!!

Just a side note:
You can also select *qaac* as EAC3 encoder, which makes no sense and at least the command line shows that ffmpeg is used instead.  Who wants to create that issue? 😁

**Comment by JJKylee** [comment] 2021-02-17 02:17
> Just a side note:
> You can also select _qaac_ as EAC3 encoder, which makes no sense and at least the command line shows that ffmpeg is used instead. Who wants to create that issue? 😁

As for me, I don't mind as long as they don't yield errors... 😆

**Comment by stax76** [comment] 2021-02-17 07:48
Changing this dropdown menu might be difficult.

A warning in the main dialog should be easy.

**Comment by anthony75smith75** [comment] 2021-02-17 07:53
Yeah I have wanted EAC3 7.1 for about 7 years plus. Wonder why it's so hard to implement?

**Comment by JJKylee** [comment] 2021-02-17 07:56
@stax76, don’t waste your time. A warning message will be enough, I guess.

**Comment by JJKylee** [comment] 2021-02-24 14:38
I'm afraid this issue is _not_ correctly fixed.

Although I set the output AC3 channels to the same as the source (7.1 AAC), I see no warning message in the main window.

![StaxRip_2 1 8 3_AC3-EAC3_channel_warning_failure_20210224](https://user-images.githubusercontent.com/3157518/109015839-6818d180-766a-11eb-95fd-279173452fa0.jpg)

OTOH, another user is experiencing an opposite issue: AAC 7.1 encoding encounters the _**irrelevant**_ AC3/EAC3 channel warning. See [this post on Doom9](https://forum.doom9.org/showthread.php?p=1936630#post1936630).

**Comment by stax76** [comment] 2021-02-24 15:10
In both cases it would be interesting to see a screenshot of the audio options dialog.

The code:

```VB
If (gap.AudioCodec = AudioCodec.AC3 OrElse gap.AudioCodec = AudioCodec.EAC3) AndAlso
    gap.Params.ChannelsMode = ChannelsMode._7 OrElse gap.Params.ChannelsMode = ChannelsMode._8 Then

    If ProcessTip("AC3/EAC3 6.1/7.1 is not supported by ffmpeg.") Then
        Return Block("Invalid Audio Channel Count", GetAudioTextBox(ap))
    End If
End If
```

It was missing if the encoder is ffmpeg.

There should now be a hotfix using this code:

```VB
If (gap.AudioCodec = AudioCodec.AC3 OrElse gap.AudioCodec = AudioCodec.EAC3) AndAlso
    (gap.Params.ChannelsMode = ChannelsMode._7 OrElse gap.Params.ChannelsMode = ChannelsMode._8) AndAlso
    gap.GetEncoder = GuiAudioEncoder.ffmpeg Then

    If ProcessTip("AC3/EAC3 6.1/7.1 is not supported by ffmpeg.") Then
        Return Block("Invalid Audio Channel Count", GetAudioTextBox(ap))
    End If
End If
```

**Comment by Dendraspis** [comment] 2021-02-24 15:14
I think I know why ... gimma a second

**Comment by stax76** [comment] 2021-02-24 15:17
I'm also at it.

**Comment by stax76** [comment] 2021-02-24 15:22
I think I have an improvement now:

```VB
If (gap.AudioCodec = AudioCodec.AC3 OrElse gap.AudioCodec = AudioCodec.EAC3) AndAlso
    ((gap.Params.ChannelsMode = ChannelsMode._7 OrElse gap.Params.ChannelsMode = ChannelsMode._8) OrElse
    (gap.Channels = 7 OrElse gap.Channels = 8)) AndAlso
    gap.GetEncoder = GuiAudioEncoder.ffmpeg Then

    If ProcessTip("AC3/EAC3 6.1/7.1 is not supported by ffmpeg.") Then
        Return Block("Invalid Audio Channel Count", GetAudioTextBox(ap))
    End If
End If
```

Hotfix is online.

**Comment by stax76** [comment] 2021-02-24 15:24
Still room for improvement. 🤨

**Comment by stax76** [comment] 2021-02-24 15:28
I hope the last hotfix works.

```VB
If (gap.AudioCodec = AudioCodec.AC3 OrElse gap.AudioCodec = AudioCodec.EAC3) AndAlso
    (gap.Channels = 7 OrElse gap.Channels = 8) AndAlso gap.GetEncoder = GuiAudioEncoder.ffmpeg Then
    
    If ProcessTip("AC3/EAC3 6.1/7.1 is not supported by ffmpeg.") Then
        Return Block("Invalid Audio Channel Count", GetAudioTextBox(ap))
    End If
End If
```

**Comment by Dendraspis** [comment] 2021-02-24 15:28
Is it possible `gap.Channels = TempProfile.Channels`is missing here for your solution?:

https://github.com/staxrip/staxrip/blob/ee74bea12fb60fe4a33cf2c811571c9a4a96b0e9/Forms/AudioForm.vb#L763-L776

**Comment by stax76** [comment] 2021-02-24 15:29
@Dendraspis 

The code is in the main dialog.

**Comment by JJKylee** [comment] 2021-02-24 15:29
The hotfix by @stax76 seems to be working right.

![StaxRip_2 1 8 3_hotfix1_AC3-EAC3_channel_warning_success_20210224](https://user-images.githubusercontent.com/3157518/109023832-fa70a380-7671-11eb-808c-c6adbecf2c7e.jpg)

And the warning is not issued with any kind of AAC encoders, which is as expected.

**Comment by stax76** [comment] 2021-02-24 15:34
Ok thanks for testing, sometimes I need a few tries, I commit it so.

**Comment by Dendraspis** [comment] 2021-02-24 15:36
@stax76 
Ooooookay, thought it would query/use the results made in AudioForm, because i had the same solution like you (except the ffmpeg query) and it didn't work for me.  🤔 
But as long as it works for everybody else..  😁 

I I close it now, because it seems to be fixed, tested and positively confirmed.

**Closed by Dendraspis** 2021-02-24 15:36 UTC
Labels: added/fixed/done, feature request, priority medium

**Comment by stax76** [comment] 2021-02-24 15:38
Yes, I hope it's fixed.

**Comment by Lollaskates** [comment] 2021-09-05 07:31
This new error message actually causes issues if you don't want to downmix. Ffmpeg handles forcing a 7.1+ source (dtshdma / truehd) into 5.1 ac3 no problem, I've been doing it all year.

Downmixing comes with its own problems with volume levels, phases, etc. This new implementation actually prevents my existing workflow from functioning as it was, and I can no longer add my job until I go in and add -ac 6 to downmix and satisfy this new error block.

Can this new error message be just a warning and not a blocking message? Or can it be overidden?

**Comment by Lollaskates** [comment] 2021-09-14 03:21
@stax76 could an "expert mode" or something similar be added in options that bypasses these red alerts? I don't want to be forced to downmix via -ac 6

**Comment by Dendraspis** [comment] 2021-10-05 13:12
This is a blocking message on purpose, because ffmpeg does not support 7+ channels für (E)AC3.
I don't understand the need of a bypass or similar, because even if StaxRip would allow it, the conversion will crash on execution.  🤔 

What's the problem adding the downmix to the profile or template ?
