### ISSUE TITLE
If i lock the current user/session (key: WIN+L) while encoding with Staxrip .. I get errors on the frames encoded.

### ISSUE THREAD

**Issue by chrixxxx** [staxrip/staxrip#832] opened 2022-01-29 19:11 UTC
**Describe the bug**
If i lock the current user/session (key: WIN+L) while encoding with StaxRip .. I get visual "errors" on the frame/frames encoded at the moment I'm locking (and unlocking too) the desktop.
Few times, doing the same thing, StaxRip gave me a "file input error" dialog box (without any other message).. and after I "abort" it "completes" the encode - at that point - (muxing what was encoded till there).

The source is an AVS Avisynth script.

It's many months I was trying to figure out the origin of all these errors I often found in my encodes with Staxrip.. and I'm pretty sure it's Staxrip now.

I thought it should be some filter used in the AVS script or the encoder (but I had the "glitches" whatever encoder I choosed).. but I tried using the same script without using Staxrip (encoding directly from the AVS using FFMPEG or VCEENC by the command line) and the encode is always perfect even if I lock/unlock the desktop many times in the meanwhile.

**Provide information**

Windows 10 64bit - AMD GPU Radeon RX580 - StaxRip 2.10.0 (last update) - AVISYNTH+ 3.71 64bit

**Comment by Dendraspis** [comment] 2022-03-22 22:19
Sadly (or luckily) I cannot reproduce it, especially due to lack of an AMD graphics card. 
StaxRip starts VCEEnc and ffmpeg via a system command line call, so the problem seems to be very specific, because it's almost the same as starting the command line by hand.

I'll keep it in mind, but it seems we have to close it for now. Maybe another user will have the same issues so we can re-open it again.

**Closed by Dendraspis** 2022-03-22 22:19 UTC
Labels: not reproducible

**Comment by therealt3nzin** [comment] 2022-03-24 06:21
@chrixxxx The issue is likely with fast boot, AMD ReLive, or a combination of both. Turn off fast boot by changing the registry entry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power\HiberbootEnabled` to the value `0` and disable AMD ReLive desktop recording at the following location in AMD Radeon Software:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/42627350/159853785-6b3925db-56fd-4b8d-aad0-d809bc844bf9.png">

@Dendraspis If you need an AMD GPU on the cheap for testing, the WX2100 series cards can be routinely found used for €60-80 depending on your country.
