### ISSUE TITLE
VP9 to any format = dropped frames in the encode

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#312] opened 2020-08-29 17:14 UTC
**Describe the bug**
When using YouTube 4K VP9 as a source (25fps), the encoded file *always* features dropped frames. I can load the file into avidemux and encode it that way without dropped frames. This behaviour happens in Staxrip 1.7.0.0 and all releases, including the current release (2.1.3.0).

**Expected behaviour**
All frames should be encoded and there should be no 'jerky' motion. I have analysed this on a frame-by-frame basis and the issue is the encoded file, not the player.

**How to reproduce the issue**
If you use youtube-dl, grab (https://www.youtube.com/watch?v=Jne9t8sHpUc) in 2160p and try to convert to x264 using ffmpeg, NVENC, or the included x264 build. 

As I can't post the source file for copyright and size reasons, here is the mediainfo output (muxed using mkvmerge, but also attempted the mp4 stream):

General
Format                                   : Matroska
Format version                           : Version 4
File size                                : 513 MiB
Duration                                 : 4 min 6 s
Overall bit rate                         : 17.5 Mb/s
Encoded date                             : UTC 2020-08-26 17:26:59
Writing application                      : mkvmerge v44.0.0 ('Domino') 64-bit
Writing library                          : libebml v1.3.10 + libmatroska v1.5.2

Video
ID                                       : 1
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 4 min 6 s
Bit rate                                 : 17.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Bits/(Pixel*Frame)                       : 0.084
Stream size                              : 509 MiB (99%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 4 min 6 s
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 3.76 MiB (1%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Provide information**
I have provided information above. No errors are produce and the encode completes, but this issue remains when encoding to all main resolutions (2160 VP9 -> 2160 x264, 1080 x264, etc.)

This may be an issue with an external program, but avidemux does indeed handle appear to handle the file, but this only happens on Staxrip (not Handbrake or avidemux)

**Hardware info**
Tested on Skylake-based Xeon and i7, both with Windows 10 Pro. One with 32GB RAM and one with 16GB ECC). The NVENC encode was using a GTX 1080 Ti. This is not a hardware issue as far as I can tell.

I hope I have provided enough information. Please let me know if you need any more details.

**Comment by 44vince44** [comment] 2020-08-30 09:48
Please provide the log file, so I can check the processing chain. you can stil find it in Staxrip's settings folder, in the logs subfolder!
zip it and drop it here.Thank you

**Comment by stax76** [comment] 2020-08-30 10:00
@vonH 

Maybe it's the source filter that causes the problem, the default is probably FFVideoSource, you can try LWLibavVideoSource instead, you can change the source filter before or after loading the source.

**Comment by 44vince44** [comment] 2020-08-30 10:44
I'm downloading the file to test it, I also think it's an issue with the source filter...

**Comment by 44vince44** [comment] 2020-08-30 11:04
CONFIRMED:
FFVideosource is selected automatically and drops/duplicates frames instead of processing them all.
FIX: @vonH use LWLibavVideoSource instead, as @stax76 suggests, and it will work flawlessly.

**Comment by 44vince44** [comment] 2020-08-31 06:31
UPDATE: FFMS (FFVideoSource) is being updated for all these issues, but latest update ffms2_0055b2d StvG does not address this issue.
So keep using LWLibavVideoSource.

**Comment by 44vince44** [comment] 2020-08-31 14:57
@stax76, I tried to add the source filter is the settings to automatically open vp9 with LWLibavVideoSource but it didn't work, still opens with FFVideoSource (when source = Automatic):

![SNAG-0002](https://user-images.githubusercontent.com/17828567/91734047-13146b00-ebb3-11ea-961d-458982f64dab.jpg)

Here is the [MediaInfo of the source](https://pastebin.com/cxSEBmxp).

Is there somthing I'm doing wrong? shouldn't it automatically open with source LWLibavVideoSource ?

**Comment by Patman86** [comment] 2020-08-31 18:03
84/5000
It seems to be a problem with ffms2, please report the error [here](https://github.com/FFMS/ffms2/issues) as well.

**Comment by JJKylee** [comment] 2020-08-31 21:44
> @stax76, I tried to add the source filter in the settings to automatically open vp9s with LWLibavVideoSource but it didn't work, it still opens with FFVideoSource (when source = Automatic):
> 
> ![SNAG-0002](https://user-images.githubusercontent.com/17828567/91734047-13146b00-ebb3-11ea-961d-458982f64dab.jpg)
> 
> Here is the [MediaInfo of the source](https://pastebin.com/cxSEBmxp).
> 
> Is there somthing I'm doing wrong? shouldn't it automatically open with source LWLibavVideoSource ?

AFAIK, source filters operate on **file types(extensions)**, not mediainfo values. So your setting for vp9/v_vp9 becomes useless if the app cannot find a file with vp9 or v_vp9 extension in %source_dir% or %temp_dir%.

Since (undemuxed) mkv files are dealt with **default** source filter, you need to set the default source filter to LWLibavVideoSource.

Or give mkvextract a priority over other preprocessors in dealing with mkv files, and make LWLibavVideoSource the source filter for **ivf** files (the default demuxed vp8/vp9 video stream from mkv by mkvextract). That said, I'm not sure if LWLibavVideoSource can deal with ivf files.

**Comment by 44vince44** [comment] 2020-09-01 17:15
@JJKylee Thanks for the explanation !
@Patman86 about Vp9 in ffms2 it is known that the support isn't complete. The latest release fixes problems with VC1. People on the forum are mentioning that they are waiting fixes for VP9. So everything indicates that it is a well known issue (and we have to wait!)

**Comment by vonH** [comment] 2020-09-01 20:49
Thank you @44vince44, @stax76, and @Patman86. LWLibavVideoSource does indeed process the file correctly. Perhaps an intermediate fix would be for Staxrip to automatically use LWLibavVideoSource for VP9 sources, at least until the issue is fixed within ffms2?

**Comment by JJKylee** [comment] 2020-09-06 21:43
> Perhaps an intermediate fix would be for Staxrip to automatically use LWLibavVideoSource for VP9 sources, at least until the issue is fixed within ffms2?

Well, I don't know whether it is hard or not to implement selecting source filters based on **codec**s (mediainfo vales) not on **file type**s (extensions) at the level of the app source codes, but as you know, not everything can be automated. I think this is something you need to set at the time of running like many others. You simply need to change the source filter to another one. :)

That said, I'm also wondering if there's any way to set an **event command** based on the mediainfo values of the source file. But unfortunately, I haven't been successful so far. :( I guess this is something to be tackled at the source codes level.

**Comment by 44vince44** [comment] 2020-09-07 13:35
Sooner or later, ffms2 will be fixed. in the meantime, @vonH you can set "default" to LWLibav. or simply create a template for youtube videos with VP9 using LWLibav instead of automatic.

**Comment by vonH** [comment] 2020-09-10 06:54
> Sooner or later, ffms2 will be fixed. in the meantime, @vonH you can set "default" to LWLibav. or simply create a template for youtube videos with VP9 using LWLibav instead of automatic.

Thank you. I've tested LWLibav with 8K, 4K, 1080p, 720p, and 480p. There are still some frame issues with a few 8K and 1080p videos that are not present in the source (checked frame by frame), and it's repeatable, but would need to do more testing. One such video is https://www.youtube.com/watch?v=dbB-mICjkQM (480p). The VP9 source using LWLibav seems to result in a few dropped and duplicated frames that are not in the source. The mp4 source has no issues. I've encoded the same file six times on two different systems and would appreciate knowing if you find the same issue.

**Comment by vonH** [comment] 2020-09-10 06:57
> > Perhaps an intermediate fix would be for Staxrip to automatically use LWLibavVideoSource for VP9 sources, at least until the issue is fixed within ffms2?
> 
> Well, I don't know whether it is hard or not to implement selecting source filters based on **codec**s (mediainfo vales) not on **file type**s (extensions) at the level of the app source codes, but as you know, not everything can be automated. I think this is something you need to set at the time of running like many others. You simply need to change the source filter to another one. :)
> 
> That said, I'm also wondering if there's any way to set an **event command** based on the mediainfo values of the source file. But unfortunately, I haven't been successful so far. I guess this is something to be tackled at the program source codes level.

Staxrip already appears to have source selection based on codec, unless I'm mistaken and it only selects based on container? 🤔

**Comment by JJKylee** [comment] 2020-09-10 09:07
> Staxrip already appears to have source selection based on codec, unless I'm mistaken and it only selects based on container? 🤔

Preprocessors (indexers, demuxers/remuxers) and source filters work on _**files**_, so they are triggered by **file types** identified by _extensions_. It is up to **source filters** to figure out what codec is used in the given file before they start decoding.

**Comment by stax76** [comment] 2020-09-12 16:22
@JJKylee 

What can be tried is additionally support the format with an extended syntax, like so:


mkv extension and VP9 format:

mkv:vp9


Any extension containing VP9 format:

*:vp9

**Comment by JJKylee** [comment] 2020-09-12 17:52
Sounds like a very good idea. 👍

**Comment by 44vince44** [comment] 2020-09-12 19:54
@stax76 I agree also 👍 very good idea!
(I guess we can still leave "mkv" or have to do mkv:all ?)

BTW I saw you are not including the FFMS2 build of StvG anymore in latest beta, you included the one of FFMS group. But I really think that StvG is better. [Here ](https://cloud.owncube.com/s/tcwyzNJ6LgD2iN7) is latest StvG build, based on ffmpeg n4.4@1c7e55dd50. It's given in doom9's FFMpegSource forum, where you appear from time to time.
For instance, the youtube video of @vonH doesn't even open correctly with FFMS2 2.40 of FFMS group, but it opens with StvG's build (with some frames dropped, some duplicated).

**Comment by stax76** [comment] 2020-09-13 00:14
@44vince44 

mkv is equal to mkv:*, at least if the first implementation is not buggy.

StvG built is now included.

**Closed by stax76** 2020-09-13 00:14 UTC
Labels: bug, priority medium, tool issue

**Comment by 44vince44** [comment] 2020-09-13 10:40
Thanks !!
