### ISSUE TITLE
resamplehq error

### ISSUE THREAD

**Issue by jkkma** [staxrip/staxrip#1101] opened 2023-08-26 09:37 UTC
![Screenshot 2023-08-26 053527](https://github.com/staxrip/staxrip/assets/16640398/ca0aecd0-2023-45b9-b639-a4ed3762a5b1)
Selecting any kernel for resamplehq throws this, dont understand what the issue is?

**Comment by Dendraspis** [comment] 2023-08-26 10:29
The issue is I missed a definition name change in the script. Change the code line to
`clip = resamplehq.resample_hq(clip, %target_width%, %target_height%, kernel='Spline36')`  <-- with underscope
and it should work.

Will be fixed for the next release...

**Closed by Dendraspis** 2023-08-26 10:29 UTC
