### ISSUE TITLE
SVT Encoders implementation

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#150] opened 2020-03-31 16:53 UTC
hi Stax, hi Raven,

it would be great if you have time for these #61 request.

The encoding procedure is the same for everyone, only the output format for SVT-HEVC is different.
Look here:

[SVT-AV1](https://github.com/OpenVisualCloud/SVT-AV1#windows-operating-systems-64-bit)
[SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9#windows-operating-systems-64-bit)
[SVT-HEVC](https://github.com/OpenVisualCloud/SVT-HEVC#windows-operating-systems-64-bit)

**Comment by stax76** [comment] 2020-03-31 20:08
I made a test and the output distorted with green color.

D:\Projekte\VB\StaxRip\bin\Apps\Encoders\ffmpeg\ffmpeg.exe -loglevel fatal -hide_banner -i D:\Samples\aaa_temp\aaa.avs -nostdin -f rawvideo -pix_fmt yuv420p - | C:\Users\frank\Desktop\SvtAv1EncApp.exe -i stdin -n 328 -w 1280 -h 720 -q 20 -b C:\Users\frank\Desktop\test.ivf

**Comment by stax76** [comment] 2020-03-31 20:20
The green distortion apparently was caused by using Windows Terminal and PowerShell instead of CMD, I hate CMD.

**Comment by Patman86** [comment] 2020-03-31 21:02
I want to make some tests tomorrow, maybe there is a solution.

**Comment by stax76** [comment] 2020-04-01 00:18
I think I found out everything input related, for vs -f vapoursynth has to come before -i

-pix_fmt yuv420p has to be defined before -f yuv4mpegpipe

and for 10 bit:

-pix_fmt yuv420p10 -f yuv4mpegpipe **-strict -1**

**Comment by Patman86** [comment] 2020-04-01 17:15
> 
> 
> I made a test and the output was distorted with green color.
> 
> D:\Projekte\VB\StaxRip\bin\Apps\Encoders\ffmpeg\ffmpeg.exe -loglevel fatal -hide_banner -i D:\Samples\aaa_temp\aaa.avs -nostdin -f rawvideo -pix_fmt yuv420p - | C:\Users\frank\Desktop\SvtAv1EncApp.exe -i stdin -n 328 -w 1280 -h 720 -q 20 -b C:\Users\frank\Desktop\test.ivf

with cmd /c in front of your code, you can use the commandline and your outputfile has no green color

**Comment by stax76** [comment] 2020-04-01 21:14
Good idea to use cmd in powershell.

I wrote a basic GUI today and checked in the code but it's not receiving progress due to the fact the console code and documentation is written by somebody who is fairly clueless.

https://github.com/OpenVisualCloud/SVT-AV1/issues/945

https://github.com/OpenVisualCloud/SVT-AV1/issues/779

**Comment by Patman86** [comment] 2020-04-01 21:24
I love your [commit](https://github.com/staxrip/staxrip/commit/790ee2e01468fd45d34b45773fd1674df17c78f1)... i think i will neveruse SVT-AV1 encoder... really humble command line interface... i have followed the issues which you mentioned... the devs of SVT-AV1 have a lot of work to do for a user friendly encoder

**Comment by stax76** [comment] 2020-04-01 22:44
StaxRip has problems because it's not writing line breaks, working around this might me difficult...

https://github.com/OpenVisualCloud/SVT-AV1/issues/1178

**Comment by stax76** [comment] 2020-04-02 04:02
I've examined it a bit because I'm interested in everything console related, it would probably at least take a day for me, the related code is rather complicated:

https://referencesource.microsoft.com/#system/services/monitoring/system/diagnosticts/AsyncStreamReader.cs

For now, I quit working on support for this encoder.

**Comment by Patman86** [comment] 2020-04-02 04:42
That's really interesting!!! Thanks for your effort! I will also have a look at this.

**Comment by stax76** [comment] 2020-04-02 17:00
Currently, I'm not fit enough for something difficult, I would probably do some research to see if people had this issue before. I would download the .NET Framework source code, make a test project that uses AsyncStreamReader.cs and then with debugger help try to understand how it works, how the data flows etc.

I could learn a couple of things here so it's somehow interesting, maybe in a few days or at some time if they don't fix it meanwhile.

**Comment by stax76** [comment] 2020-04-03 18:59
I think I have most of it working and hope that I can finish it tomorrow.

**Comment by stax76** [comment] 2020-04-04 00:33
It's working now with last commit.

**Comment by Patman86** [comment] 2020-04-04 07:29
Great! I test it and give you a feedback.

**Comment by Patman86** [comment] 2020-04-05 18:04
Encoder works as it should including progress feedback. Only thing that want to be opimized in the future is the encoder options window. SVT-AV1 support a lot off settings like 8 and 10 bitdeph, hdr, two pass encoding etc. If CQP enabled, the option must be --rc 0, i cant see this command in commandline. But for now good work ;)

Orientate on [this](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md#list-of-all-configuration-parameters) for encoder options or the other encoder option windows...

**Comment by stax76** [comment] 2020-04-05 19:22
It can be improved though it's not exactly very exiting work. 😀

> If CQP enabled, the option must be --rc 0

I think --rc 0 is default, a general policy in staxrip is not showing default values in command lines.

**Comment by Patman86** [comment] 2020-04-05 19:35
But it must be shown in command line during encode or not? Yeah, - - rc 0 is default

**Comment by stax76** [comment] 2020-04-06 22:19
In the docs the default for --rc is 0, the console output shows that it's working:

SVT [config]: **BRC Mode** / QP  / LookaheadDistance / SceneChange                  : **CQP** / 50 / 33 / 0

**Closed** 2020-04-20 20:59 UTC
Labels: request
