### ISSUE TITLE
Video not entirely encoded

### ISSUE THREAD

**Issue by coolpringles** [staxrip/staxrip#1081] opened 2023-08-21 16:24 UTC
**Describe the bug**
Some videos stop encoding after a while resulting in an incomplete mux

**Expected behavior**
The entire video gets encoded

**How to reproduce the issue**
Unsure- it seems to be random

**Provide information**
No error message in logs as far as I can tell
StaxRip Version 2.25.0
Log: https://pastebin.com/N9mr6PVC
Input file is 11 min 48 s, h264 output is only 5 min 50 s

Maybe a way around this could be to verify that the length of the h264 output is what it should be?

**Comment by Discograp** [comment] 2023-08-22 00:17
need info

1. container
2. audio-track

**Comment by Dendraspis** [comment] 2023-08-22 05:17
Can you post the log file of one of those incomplete encodes?

**Comment by Discograp** [comment] 2023-08-22 06:11
> Can you post the log file of one of those incomplete encodes?

O_O where are these logs? where are located?

**Comment by Dendraspis** [comment] 2023-08-24 16:09
Are you able to reproduce this scenario with the same file?
If so: Has the output video always the same length?
Do other source files have the same problem?

**Comment by coolpringles** [comment] 2023-08-24 17:04
> Are you able to reproduce this scenario with the same file? If so: Has the output video always the same length? Do other source files have the same problem? How much RAM do you have?

I've got 16GB of ram, the issue seems entirely random and usually just trying again means the video will encode properly.

**Comment by Dendraspis** [comment] 2023-08-25 20:30
From my point of view it looks like you ran out of memory while the video was encoding. That would explain why it appears randomly and on random frames.
As far as I can see you haven't applied any filters, except for loading the video file, so it should not need much memory, but depending on your system settings and parallel running tasks, it can happen.

If it would be a general issue, a lot more users would have complained about it.
Try to close as many apps as possible and give it a try and I guess it will happen not that often anymore, maybe not more.

**Comment by rkoll927** [comment] 2023-08-25 23:55
I've been experiencing the same problems with StaxRip Version 2.27 & 2.28. 

I'm using x264  and transcoding an aac from the source ac3 with ffmpeg. I like to mux the source ac3 audio into the final mkv as well.  

OS is Windows 10 Pro 22H2, HW is 8 core i7-11800H w/ 32GB Ram & Nvidia A2000 GPU

I have videos that start and stop almost immediately, but then others that decide to quit & mux at 80%.

This specific log was an instance of encoding about 63% of the total duration (TRT: 45:27 - 41171 of 65384 frames encoded) 
[2023-08-25 - 19.07.13 - Star Trek- DS9 - S03E17 - Visionary_staxrip.log](https://github.com/staxrip/staxrip/files/12444149/2023-08-25.-.19.07.13.-.Star.Trek-.DS9.-.S03E17.-.Visionary_staxrip.log)

**Comment by Dendraspis** [comment] 2023-08-26 08:55
`QTGMC` is definitely one of those filter, that are pretty memory consuming, even the video resolution is small.
In your case I can give just the same advice: close all apps and then start the encode - you should recognize a difference.

Additionally you can try one of the (older) official binaries to see if that makes a difference for you:
https://artifacts.videolan.org/x264/release-win64/

**Comment by Augur1989** [comment] 2023-08-28 08:04
i experienced the same issues, but only when the CPU is undervolted under a specific level.
So for me it seams as if the encoder doesn't get enought resources for a moment, it just ends the operation.
May it be, you undervolted your cpu as well @coolpringles?
Since i noticed that, i'm running all encodings at higher voltage levels, but of course it would be way more resource efficient if the encoder could just be paused for that short moments, when there are not enough resources.

**Comment by rkoll927** [comment] 2023-09-01 15:16
Just to circle back with an update:

I have tried some of the suggested solutions; I've dumped as many background processes as I could, curtailed startup apps, closed everything except Staxrip and explorer, and I've even SetMemoryMax. 

The result is now more hits than misses, but the misses are still just as random. And it sometimes takes a couple retries until encoding is successful.

My next step is to try one of the older x264 binaries and maybe even roll back staxrip to an earlier release. (I tend to update with each new release, and encoding has been solid, for me, up until 2.25/26 if memory serves)

**Comment by Dendraspis** [comment] 2023-09-01 17:54
@rkoll927 
You could also provide the source file so I can try to reproduce the problem - link here or on Discord.
Because of its random nature such issues are really hard to check, but it just can be CPU or RAM related. Or maybe an app intereferes, like AntiVirus.
Nevertheless please let us know the outcome of your testing.

**Comment by rkoll927** [comment] 2023-09-09 16:43
I would send you a sample file, but it is truly random.  File "X" would encode fine in one test, and not in another.  I don't definitively have any true "problem files." 

**_BUT_**

I believe I have solved the problem that _I_ was having.

I ran additional encodes with older x264 binaries, and even past versions of staxrip. The incomplete encode problems were still happening and still just as random.

I went through my script and enabled/disabled filters one-by-one and let a batch of files encode. _**For me**_, the issue appears to have been the the "DeRainbow" filter.  I ran a few more tests replacing DeRainbow with bifrost and chubbyrain2 (not at the same time) and everything is now rock solid.

I've run tests with the new 2.29 as well and my findings are holding true.

I wish I had a better more all-encompassing finding that would help others experiencing this problem.

**Comment by Dendraspis** [comment] 2024-01-05 22:57
With `v2.29` I introduced a `Frame Mismatch` check, which is written at the bottom of the log file.
When verified, that it works as intended, I will extend it to throw out an error message, so the user will notice it directly.

Example:
```
--------------------------- Frame Mismatch ---------------------------
WARNING: Target file has 1500 frames, but should have 2000 frames!
Encoding was terminated at 75%!
```

So I close this now...

**Closed by Dendraspis** 2024-01-05 22:57 UTC
Labels: bug, tool issue, added/fixed/done, not an issue, not reproducible
