### ISSUE TITLE
Green Screen in cropping dialog when using VapourSynth

### ISSUE THREAD

**Issue by Thomas-MB** [staxrip/staxrip#1455] opened 2024-08-16 12:50 UTC
Helllo,

I'm new with VapourSynth, but because of some features I need, I'm currently switching my setup from AviSynth to VapourSynth and I thought I'm done, because every filters (that I use) are working fine.

But now I'm facing a problem with the cropping dialog. It's only showing a green screen for all source I tested (they are all 2160p with HDR10 and some also with DV). Nothing changes when I move the Time-Slider.
This behaviour occurs when I have an already open project and switch from AVS Filters to VS Filters as well as wenn I have VS Filters active before importing the video. The preview is working fine, only the cropping dialog is broken. I tried to switch the source filter from ffsm2 to another, but this also doesn't work.

Stax Rip Version: 2.41.7

Best regards
Thomas

**Comment by Thomas-MB** [comment] 2024-08-16 13:10
I compared it with a source, I'm not removed the dv and the script looks identical. For info, I'm removing dv because I make some tests have to cut and cutting is still not supported for dv.


import os, sys
import vapoursynth as vs
core = vs.core

sys.path.append(r"E:\encoding\StaxRip-v2.41.0-x64\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"E:\encoding\StaxRip-v2.41.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll", altsearchpath=True)

tcFile = r"E:\encoding\_name_of_the_video_folder_\source_[No DV]_temp\source_[No DV]_timestamps.txt" # timestamps file path
clip = core.ffms2.Source(r"E:\encoding\_name_of_the_video_folder_\source_[No DV].mkv", cachefile=r"E:\encoding\_name_of_the_video_folder_\source_[No DV]_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"E:\encoding\_name_of_the_video_folder_\source_[No DV].mkv", cachefile=r"E:\encoding\_name_of_the_video_folder_\source_[No DV]_temp\temp.ffindex")

clip.set_output()

**Comment by Dendraspis** [comment] 2024-08-16 13:24
Interestingly I cannot reproduce it.
I have opened a video under AviSynth, then switched to VapourSynth and when I click on `Crop`, everything works as intended.

**Comment by Thomas-MB** [comment] 2024-08-16 13:30
Ok, then give me the weekend and I test a little bit more and also with other sources.

If you have additional ideas/hints, what could rise this behaviour, I'm happy to hear. The `_name_of_the_video_folder_` thingy is only a replacement here in the ticket for the real video folder name.

**Comment by Thomas-MB** [comment] 2024-08-16 13:41
First try and hit. It seems, that it's something in my template file. Means, with a fresh extract of StaxRip I have not the problem.

I will make a new Template and will reply, what I found out.

**Comment by Dendraspis** [comment] 2024-08-16 15:52
Did you delete your post regarding the reproducible issue with your template?  🤔 

> only a replacement here in the ticket for the real video folder name

Of course I know, but depending on the length and used characters it could be a potential culprit.

**Comment by Thomas-MB** [comment] 2024-08-16 15:59
I deleted, because it was wrong, what I wrote. Hadn't seen, that it was swiched back to AviSynth.

Currently, I can say:
- It's **not** because of my template.
- It's **not** because of the foldername
- It works with another source (some older 1080p, I think with x264).

I will create a short example file and provide it here.

**Comment by Dendraspis** [comment] 2024-08-16 16:17
Okay, so please try to create a small sample file for that issue, that you can share with me. And of course a detailed step-by-step instruction on how to reproduce it, so hopefully I can reproduce it.

Strange, that you have this pretty often, but I haven't seen it after sooooooo many tests.

**Comment by Thomas-MB** [comment] 2024-08-16 20:20
How to reproduce the bugs:
1. Take fresh StaxRip 2.41.7 (I use the 2.41.0 and the 2.41.7 Update) with first Settings Option (subfolder)
2. Use the default template "Automatic Workflow"
3. Import the cropbug.mkv via drag&drop
4. Switch from AVS Filters to VS Filters
5. Open Crop Dialog

OR Switch Step 3 and 4.

[cropbug.zip](https://github.com/user-attachments/files/16641362/cropbug.zip)

**Comment by Dendraspis** [comment] 2024-08-16 21:17
I have used a fresh `v2.41.7` and went step by step of your list an the result is:  😕 

<img width=700 src=https://github.com/user-attachments/assets/6a4df7e4-20d2-4780-b2e5-e2d7c32da0c5>

<img width=700 src=https://github.com/user-attachments/assets/a8d6b59c-0df8-43d6-9ec9-6f09e55814bd>

**Comment by Thomas-MB** [comment] 2024-08-17 11:50
Thx, that helps. Then it should be important for you, that I have no dedicated graphic card and use currently a Laptop with an Intel Core i5-1250P.

**Comment by Dendraspis** [comment] 2024-08-17 12:26
Thanks for letting me know.  👍 
There is a rough check and your GPU supports Vulkan, so this option is enabled for you. But it seems like it has some issues with the plugin or so. Not sure if I can/will do something about that....

Just keep in mind, that you have to disable this option on that Notebook.  😅 

So I close this one ... have fun.

**Closed by Dendraspis** 2024-08-17 12:26 UTC

**Comment by Andrasolin** [comment] 2024-08-18 06:45
usually Green frames appear due to compatibility errors

need information about the PC system on which this BUG
and need "media info"

OS - 
CPU - 
RAM - 
GPU -

**Comment by Dendraspis** [comment] 2024-08-18 06:51
Problem is solved, so no need to ask for the information.
