### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YOURMOMMYFACE** [staxrip/staxrip#353] opened 2020-10-04 19:50 UTC
ArgumentOutOfRangeException (2.1.3.0)

Value to add was out of range.
Parameter name: value

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 71
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 250
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 192

**Comment by stax76** [comment] 2020-10-05 08:12
Please try the latest beta version.

**Comment by stax76** [comment] 2020-10-05 10:54
Duplicate of #183

**Closed by stax76** 2020-10-05 10:54 UTC
Labels: bug, priority medium
