### ISSUE TITLE
hides while still working

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#693] opened 2021-05-08 09:59 UTC
Hi everybody

When I'm going to do a work with BD folder, it somethig funny happens:

I select a BD folder
Show me languages, subtitles, etc. and I select what i want
StaxRip use eac3to to extract all files...everything is OK

But when it finish to extract....., it hides of the screen, but it's not crack, no It still works in second plane or third plane.  If you open task manager you don't find it in main window, you must go to user window and deploy the user and finally you see it, it is working well, without any problems.

After 5-10min (BD 1080) or 15-25min (BD4k) StaxRip show in your screen doing Crop, make a index and finallly finish your work to make a encode.

Is it possible don't hide the program while it is working? If you go out of your PC or Laptop when you come back you don't find if StaxRip is working or crack o something wrong in your computer.

Best regards and apologizes for my bad english, it is not my mother tongue.

**Comment by 44vince44** [comment] 2021-05-08 12:01
Hi @papa-pitufo 
Yes we know this behaviour in Staxrip is annoying, and it should be fixed, but not soon. Unfortunately Staxrip has still things from its original architecture in the early 2000's.
So be patient, because now, there is nothing we can do.....

**Comment by papa-pitufo** [comment] 2021-05-08 12:27
> Yes we know this behaviour in Staxrip is annoying, and it should be fixed, but not soon. Unfortunately Staxrip has still things from its original architecture in the early 2000's.
> So be patient, because now, there is nothing we can do.....

Ok, but I would swear that in old versions (2.1.X) that did not happen or it was not so accused.  But I'm not sure.  Sorry

**Comment by Dendraspis** [comment] 2021-05-08 12:38
As far as I remember nothing was changed in the behavior of the forms/windows. 
Like @44vince44 already mentioned, I can't tell you when or even if there will be a fix.

**Comment by papa-pitufo** [comment] 2021-05-08 12:39
> As far as I remember nothing was changed in the behavior of the forms/windows.
> Like @44vince44 already mentioned, I can't tell you when or even if there will be a fix.

Ok, OK, sorry

**Comment by Dendraspis** [comment] 2021-05-08 12:41
No need to say *sorry*, it is a bug and it has no issue yet, so everything is fine.  👍

**Comment by 44vince44** [comment] 2021-05-21 11:14
Was anyone able to reproduce that ?
- opening a 4K BD folder
- using a desaturate filter

See what happens....

**Comment by papa-pitufo** [comment] 2021-05-21 13:01
> Was anyone able to reproduce that ?
> 
> * opening a 4K BD folder
> * using a desaturate filter
> 
> See what happens....

Yes, of course, I'll will do, but sorry, 
which desaturate filter I must to use to give you validate news?

**Comment by 44vince44** [comment] 2021-05-21 16:51
No @papa-putufo, not you, I would like someone else to try and to see if the same thing happens.

I cannot test myself because I can't download such huge amount of data or get a 4K blu ray.

**Comment by papa-pitufo** [comment] 2021-05-21 18:01
Ahh, ok, no problem.  Thanks a lot

**Comment by JJKylee** [comment] 2021-05-24 04:31
Can anyone provide a sample to test this with?
I don't have any 4K BD folder rip myself, so I'm just curious.
Or at least some pointer/URL to the sample...? 🤔❓

**Comment by papa-pitufo** [comment] 2021-05-29 12:55
If you want I can upload 4k BD folder to my NAS and give you a link to download when you can do it.

Tell me something

**Comment by JJKylee** [comment] 2021-05-29 14:34
I hope its size is not too big.

If it's a copyright sensitive material, you better NOT put a link here in GitHub.
In such case, I recommend the Discord channel instead.
https://discord.gg/rRn7vGU

My nick is _JKyle_, @44vince44's is _ZKSVince_, and @Dendraspis's is _Dendraspis_.
PM(private message) the link to anyone of us if possible.
And if the size is less than 20 GB, I'd recommend Google Drive.

**Comment by papa-pitufo** [comment] 2021-05-29 14:58
A 4k BD folder size is usually 60Gb or greater.
If you transform to BDRemux you can choose languages, eliminate extras, etc, and the size is minor but ussually close to 40-50 Gb

Do you want to try it in Discord channel????

Waiting your news

**Comment by JJKylee** [comment] 2021-05-29 15:33
> A 4k BD folder size is usually 60Gb or greater.
> If you transform to BDRemux you can choose languages, eliminate extras, etc, and the size is minor but ussually close to 40-50 Gb

Man... 😖

**Comment by JJKylee** [comment] 2021-05-30 02:41
After studying the 75.72 GiB BD folder data provided by @papa-pitufo, I've found the cause of the stuttering issue he's talking about. It's because the **_source filter_** for the extracted `h265` - `LWLibavVideoSource` by default - takes a BIG amount of time in processing/caching the HUGE video data (52.23 GiB) _without displaying the progress_. But since it succeeds in indexing the video stream anyway, StaxRip window shows up again after the indexing process is over.

This is something that can't be fixed on StaxRip's end. Use some other source filter like `DGSource` that displays the progress along the way. I tried using it and it sure displays the progress in the _Processing..._ window of StaxRip.

BTW, `Grayscale()` and `Desaturate` didn't have any issues, as expected.

### [Side Notes]

1. _eac3to_
 
_eac3to_ definitely needs to be updated. (But I know it can't. 😭) It simply can't demux some Dolby audios like TrueHD and AC3 tracks with Atmos metadata. I think it's because the `avcodec-54.dll` file it uses to demux the source is too old (more than 6 years ago!!!!!) to parse the audio streams correctly. 😓

Besides, although _eac3to_ succeeds in demuxing the video streams, it can't preserve the dynamic metadata(RPU) of the source.

2. Handling Dolby Vision Profile 7 BD data

The source is a Dolby Vision Profile 7 BD data and thus the video data is basically a dual-layer single-track HEVC data. But I couldn't find a way to extract the video data to a dual-layer single track file and thus couldn't extract the RPU data with `dovi_tool`. I'm wondering if there's any _open source_ tool that can do it. 🙄

However, the BL and EL layers are recognized as _separate_ video tracks and each can be extracted successfully by _eac3to_, although the RPU data cannot be extracted afterwards. But it's OK since we can _still_ go on with _HDR10_ even if conversion back to Dolby Vision can't be done.

3. _MakeMKV_ Issues

It turns out that _MakeMKV_ has issues in handling Dolby Vision Profile 7 BD data. It took me forever to remux this source to an `mkv` file using _MakeMKV_, so I had to force stop it. Maybe it's related to _mkvmerge_ not being able to mux Dolby Vision video data to `mkv` from other container formats than `mp4`. I hope this is fixed sooner or later. 🙄

**Comment by papa-pitufo** [comment] 2021-05-30 10:07
@JJKylee I change to DGSource, I tell you about it.

Sides notes: How about if we use the new version of TsMuxer? Could we solve anything or  no?
Because Ts recognize DSTMA, TrueHD, Dolby Vision, etc.
But I don't know if we can do it anything else than change eac3to to TsMuxer.

Sorry

If you want that I do any test, please tell me and try it.

**Comment by papa-pitufo** [comment] 2021-05-30 11:16
@JJKylee I use DGSource but show me an error in script.  With LWlib.. or FFVideoSource not happen.

Is there any wrong?  I don't see it.

Best regards.

Probably should I to move this test or problem with us to a discussions section????

**Comment by JJKylee** [comment] 2021-05-30 14:00
If run separately, _tsMuxeR_ can surely demux Dolby audios, but embedding it in StaxRip is a totally different thing. It involves overhauling the source code at a very fundamental level. That's a BIG feature request.

Besides, I'm doubtful if _tsMuxeR_ can merge `m2ts` files of a BD data into a single file based on the BD playlist, like _eac3to_ can now. (Neet to check this out though...)

According to your log, you haven't set up _DGDecNV_ correctly. Follow the instructions on [the wiki document](https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV%28DGSource-and-DGIndexNV%29-in-StaxRip) closely.

> Probably should I to move this test or problem with us to a discussions section????

I don't think it's a good idea. There's _nothing more_ we can talk about regarding this matter as of now 'cuz _all issues basically derive from the limits of tools like source filters, eac3to, etc._.

**Comment by papa-pitufo** [comment] 2021-05-30 14:35
Ok, thank you very much, I review the set up DGDecNV

Best regards

**Comment by JJKylee** [comment] 2021-05-31 13:54
Like I explained above, this is not a bug but a tool issue.
I think we can close this thread.

**Closed** 2021-06-01 09:18 UTC
Labels: added/fixed/done, bug, help wanted, not reproducible
