### ISSUE TITLE
Open Multiple Files Breaks When Source Path Contains a Comma

### ISSUE THREAD

**Issue by AYColumbia** [staxrip/staxrip#1073] opened 2023-08-12 13:36 UTC
**Describe the bug**
Exception thrown when a source folder in the path has a comma in the name, e.g., "C:\media\tv\show, the" when using the Open | Multiple Files method.  The exception is thrown during the file processing.  File batch seems to be fine.

**Expected behavior**
The files are processed properly the same as a single file or file batch and proceeds to the UI to allow me to start the encoding queue.

**How to reproduce the issue**

I reproduced this with the default "out-of-the-box" settings when you first launch the app so you should be able to reproduce as well.
1. Create a folder with a comma in the name, e.g., "C:\media\tv\show, the"
2. Copy 2 or more source files like mp4 or mkv
3. Right click Source and select Open | Multiple files
4. Select the files from step 1 location
5. Let the app proceed after which it should crash

**Provide information**
Here's the log info (note that my source path is "C:\Media\Test\Show, The"):
------------------------- System Environment -------------------------
StaxRip    : v2.25.0
Windows    : Windows 10 Pro 2009
Language   : English (United States)
CPU        : 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz
GPU        : NVIDIA GeForce RTX 3050 Ti Laptop GPU, Intel(R) UHD Graphics
Resolution : 1920 x 1080
DPI        : 96
Code Page  : 1252
------------------------------ Exception ------------------------------
System.IO.FileNotFoundException: Could not find file 'C:\Media\Test\Show'.
File name: 'C:\Media\Test\Show'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2146

Thank you and please let me know if there's anything else  you may need.

**Comment by Dendraspis** [comment] 2023-08-12 14:06
Oh, an interesting bug. I'll have a look at it and can hopefully solve the issue for the next release.

Thanks for the detailed report.

**Comment by Dendraspis** [comment] 2023-08-12 20:08
I had a closer look at it and I can't reproduce it, even then the file name includes a comma, too:

![image](https://github.com/staxrip/staxrip/assets/50659978/6994fda6-f986-410b-ad80-ef481847cb04)

Is it possible you use `StaxRip v2.25` with settings from a previous version?

**Comment by AYColumbia** [comment] 2023-08-12 20:36
What if only the folder has the comma?  Did you try that because in my situation only folder has the comma.  I just tried again AFTER I removed the Settings folder and let StaxRip recreate it.  Once the UI came up, I tried it again with the defaults and the same thing happened, i.e.,

```
FileNotFoundException (v2.25.0)

Could not find file 'C:\Media\Test\Show'.

System.IO.FileNotFoundException: Could not find file 'C:\Media\Test\Show'.
File name: 'C:\Media\Test\Show'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2146
```
This is what the UI looks like after I OK my way back through the errors and messages if that may help.
![2023-08-12 15_35_06-Automatic Workflow - StaxRip v2 25 0](https://github.com/staxrip/staxrip/assets/6758781/bb63d031-b21c-4e91-b584-2a20efe79a02)

**Comment by AYColumbia** [comment] 2023-08-12 20:46
I tried one more thing.  I renamed the folder to remove the comma but added a comma to the file names and now it's dying where the comma is on the file name.  The full file name is: **Knight Jiu-Jitsu,S01E00.mp4**

```
FileNotFoundException (v2.25.0)

Could not find file 'C:\Media\Test\Show- The\Knight Jiu-Jitsu'.

System.IO.FileNotFoundException: Could not find file 'C:\Media\Test\Show- The\Knight Jiu-Jitsu'.
File name: 'C:\Media\Test\Show- The\Knight Jiu-Jitsu'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2146
```
Don't know why it's crashing for me and not for you.  Can it be a localization or encoding issue?  When I mention encoding, am referring to text encoding, i.e., ANSI, UTF8, etc.

**Comment by Dendraspis** [comment] 2023-08-13 05:39
Yes, I've tried all combination, even with and without a space after the comma.
Here I took your path to test it:

![image](https://github.com/staxrip/staxrip/assets/50659978/e3363ef2-1fd6-4f9c-a1e9-c8aab0ec3a6d)

Doesn't matter what I try, everything works. It seems the problem is on your side. The error message confirmes this even more. The problem is not StaxRip being unable to find the file at the wrong location. At the point of the crash StaxRip has loaded the file already, read some media information and tries to gather some more information about it. So when it crashes, it tries to ask Windows for the file size.

Overall it is always a good idea to separate storage files from the system files, meaning using another Partition for e.g. media files. That could be the culprit. You can also try to disabling your AV temporarily and/or starting StaxRip *as Administrator*.

**Comment by AYColumbia** [comment] 2023-08-13 13:03
Wow, that's really strange.  Keep in mind this is happening on both my laptop and server so it's not just one PC.  Also, I only used the C: drive for test/sample purposes.  I normally use D: on my laptop and different media drives on my server.

Could I be missing dependencies for the app like some library or a version of some runtime deployment?  If I have some time this week, I may grab the code and run it from Visual Studio to debug and see what exactly is happening.  Thankfully the File Batch option works fine for the most part.  I also found if you add too many files to File Batch it chokes, especially if those files are from different folders.  But that's for another bug report if I have time to reproduce it. ;)

I appreciate you trying to repro and know it's hard to figure it out if you can't reproduce it.

**Comment by Dendraspis** [comment] 2023-08-13 13:31
Okay, I tried it on an older machine with Windows 10 v2004 and the error message appears, same as yours. I'll check that and come back when it's fixed - hopefully.  😁

**Comment by Dendraspis** [comment] 2023-08-13 14:29
Okay, I was able to find the problem.
It's fixed now and the next release should be fine. Sadly I can't provide a hotfix due to too many changes since last release, so you have to wait a bit.

**Closed by Dendraspis** 2023-08-13 14:29 UTC
Labels: bug, tool issue, added/fixed/done

**Comment by AYColumbia** [comment] 2023-08-13 16:28
Sweet! Good stuff.  I appreciate you being "dog-on-a-bone" persistent. :D I should have given you the OS info in my initial post which probably would have helped, i.e., Windows version 22H2 (10.0.19045 Build 19045.3324).  I'm guessing you're on Win11 already? ;)

**Comment by Dendraspis** [comment] 2023-08-13 18:14
Nope, I'm still on Win10 20H2. 😎 

Don't worry, it seems to be fixed now, so all good.  😁
