### ISSUE TITLE
Frame Mismatch

### ISSUE THREAD

**Issue by filyse** [staxrip/staxrip#1400] opened 2024-06-17 20:06 UTC
------------------------- System Environment -------------------------

StaxRip    : v2.41.0
Settings   : v2.41
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : Russian (Russia)
CPU        : 13th Gen Intel(R) Core(TM) i7-13700K
RAM        : 32GB
GPU        : Intel(R) UHD Graphics 770, NVIDIA GeForce RTX 3080
Resolution : 3840 x 2160
DPI        : 144
Code Page  : 1251

----------------------- Media Info Source File -----------------------

C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv

General
Complete name            : C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 2.01 GiB
Duration                 : 44 min 8 s
Overall bit rate         : 6 526 kb/s
Frame rate               : 23.976 FPS
Writing application      : mkvmerge v82.0 ('I'm The President') 64-bit
Writing library          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 44 min 8 s
Bit rate                 : 6 078 kb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.122
Stream size              : 1.87 GiB (93%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Codec ID                 : A_AAC-2
Duration                 : 44 min 8 s
Bit rate                 : 445 kb/s
Channel(s)               : 6 channels
Channel layout           : C L R Ls Rs LFE
Sampling rate            : 48.0 kHz
Frame rate               : 46.875 FPS (1024 SPF)
Compression mode         : Lossy
Stream size              : 141 MiB (7%)
Language                 : English
Default                  : Yes
Forced                   : No

Text
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 43 min 50 s
Bit rate                 : 77 b/s
Frame rate               : 0.313 FPS
Count of elements        : 823
Stream size              : 25.0 KiB (0%)
Title                    : English [SDH]
Language                 : English
Default                  : No
Forced                   : No

------------------------------ Demux MKV ------------------------------

mkvextract 84.0

C:\Users\filys\Desktop\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe --ui-language en C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv tracks 2:"C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1_[en] {English [SDH]}.srt" 1:"C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac"

Extracting track 1 with the CodecID 'A_AAC' to the file 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac'. Container format: raw AAC file with ADTS headers
Extracting track 2 with the CodecID 'S_TEXT/UTF8' to the file 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1_[en] {English [SDH]}.srt'. Container format: SRT text subtitles

Start:    2:58:16
End:      2:58:18
Duration: 00:00:01

General
Complete name         : C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 141 MiB
Overall bit rate mode : Variable

Audio
Format                : AAC LC
Format/Info           : Advanced Audio Codec Low Complexity
Format version        : Version 4
Codec ID              : 2
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel layout        : C L R Ls Rs LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 141 MiB (100%)

---------------------- Indexing using ffmsindex ----------------------

C:\Users\filys\Desktop\StaxRip\Apps\Plugins\Dual\ffms2\ffmsindex.exe C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\temp.ffindex

Writing index... done.

Start:    2:58:18
End:      2:58:19
Duration: 00:00:00

---------------------------- Configuration ----------------------------

Template                : 720p
Video Encoder           : NVEnc
Video Encoder Profile   : NVEncC (Nvidia) | H.264
Container/Muxer Profile : MKV (mkvmerge)
+++++
Process Priority        : Idle
Delete Temp Files       : Permanent

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\Users\filys\Desktop\StaxRip\Apps\FrameServer\AviSynth\plugins\")

LoadPlugin("C:\Users\filys\Desktop\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
tcFile = "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv", cachefile="C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("C:\Stax\Upload\Sullivans.Crossing.S02E01.1080p.WEB.H264-ResilientSandyChickenOfAurora[TGx]\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.mkv", cachefile="C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\temp.ffindex")
Lanczos4Resize(720, 408)

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 63496
Time      : 44:08.312
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 720
Height    : 408
Frames    : 63496
Time      : 44:08.312
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

---------------------- Media Info Audio Source 2 ----------------------

General
Complete name         : C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 141 MiB
Overall bit rate mode : Variable

Audio
Format                : AAC LC
Format/Info           : Advanced Audio Codec Low Complexity
Format version        : Version 4
Codec ID              : 2
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel layout        : C L R Ls Rs LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 141 MiB (100%)

----------------------------- Find Gain 2 -----------------------------

ffmpeg N-115847-g7c95c7de4a-x64-gcc14.1.0

C:\Users\filys\Desktop\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -i "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac" -sn -vn -hide_banner -af volumedetect -f null NUL

[aac @ 00000198bdb21580] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac':
  Duration: 00:43:36.99, bitrate: 453 kb/s
  Stream #0:0: Audio: aac (LC), 48000 Hz, 5.1, fltp, 453 kb/s
[Parsed_volumedetect_0 @ 00000198bdb24440] n_samples: 0
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf61.3.104
  Stream #0:0: Audio: pcm_s16le, 48000 Hz, 5.1, s16, 4608 kb/s
      Metadata:
        encoder         : Lavc61.8.100 pcm_s16le
[Parsed_volumedetect_0 @ 00000198bdb25080] n_samples: 762722304
[Parsed_volumedetect_0 @ 00000198bdb25080] mean_volume: -25.5 dB
[Parsed_volumedetect_0 @ 00000198bdb25080] max_volume: -0.9 dB
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_0db: 1
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_1db: 1128
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_2db: 58300
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_3db: 110704
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_4db: 194728
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_5db: 313341
[Parsed_volumedetect_0 @ 00000198bdb25080] histogram_6db: 480407
[out#0/null @ 00000198bdb2bb80] video:0KiB audio:1489692KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown

Start:    2:58:31
End:      2:58:34
Duration: 00:00:03

-------------------------- Audio Encoding 2 --------------------------

ffmpeg N-115847-g7c95c7de4a-x64-gcc14.1.0

C:\Users\filys\Desktop\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -i "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac" -c:a libmp3lame -q:a 4 -af volume=0.9dB -y -hide_banner "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en]_3996286542.mp3"

[aac @ 00000204ffbf16c0] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en].aac':
  Duration: 00:43:36.99, bitrate: 453 kb/s
  Stream #0:0: Audio: aac (LC), 48000 Hz, 5.1, fltp, 453 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en]_3996286542.mp3':
  Metadata:
    TSSE            : Lavf61.3.104
  Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp
      Metadata:
        encoder         : Lavc61.8.100 libmp3lame
[out#0/mp3 @ 00000204ffbf4100] video:0KiB audio:44093KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.000523%

Start:    2:58:34
End:      2:58:52
Duration: 00:00:18

General
Complete name         : C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en]_3996286542.mp3
Format                : MPEG Audio
File size             : 43.1 MiB
Duration              : 44 min 8 s
Overall bit rate mode : Variable
Overall bit rate      : 136 kb/s
Writing library       : Lavf61.3.104

Audio
Format                : MPEG Audio
Format version        : Version 1
Format profile        : Layer 3
Format settings       : Joint stereo / MS Stereo
Duration              : 44 min 8 s
Bit rate mode         : Variable
Bit rate              : 136 kb/s
Channel(s)            : 2 channels
Sampling rate         : 48.0 kHz
Frame rate            : 41.667 FPS (1152 SPF)
Compression mode      : Lossy
Stream size           : 43.1 MiB (100%)

-------------- Video encoding command line encoder: XviD --------------

"C:\Users\filys\Desktop\StaxRip\Apps\Encoders\x_v_i_d_encraw-1.3.7\xvid_encraw.exe" -bitrate 1500 -progress -max_key_interval 100 -kboost 100 -ostrength 10 -oimprove 10 -odegrade 10 -chigh 30 -clow 15 -turbo -vhqmode 4 -bvhq -nopacked -masking 2 -imin 1 -bmin 1 -pmin 1 -threads 20 -par %target_sar% -i "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.avs" -avi "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_out.avi"

Trying to retrieve width and height from input header
xvidcore build version: xvid-1.3.7
Bitstream version: 1.3.7
Detected CPU flags: ASM MMX MMXEXT SSE SSE2 SSE3 SSE41 TSC 
Detected 24 cpus, using 20 threads.
xvid_encraw - raw mpeg4 bitstream encoder written by Christoph Lampert
Tot: enctime(ms) =125725.00,               length(bytes) = 491309560
Avg: enctime(ms) =   1.98, fps = 505.04, length(bytes) =    7737
I frames:    982 frames, size =   36877/36213332, quants =  1 / 1.71 /  8
P frames:  21735 frames, size =   16541/359534254, quants =  1 / 1.78 / 12
B frames:  40779 frames, size =    2343/95561974, quants =  2 / 3.33 / 18

Start:    2:58:31
End:      3:01:54
Duration: 00:03:22

General
Complete name        : C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_out.avi
Format               : AVI
Format/Info          : Audio Video Interleave
Format settings      : BitmapInfoHeader
File size            : 470 MiB
Duration             : 44 min 8 s
Overall bit rate     : 1 489 kb/s
Frame rate           : 23.976 FPS
Conformance errors   : 1
RIFF                 : Yes
General compliance   : File size 492867584 is less than expected size 492868965 (offset 0x1D608FCE)

Video
ID                   : 0
Format               : MPEG-4 Visual
Format profile       : Advanced Simple@L5
Format settings      : BVOP2
Format, BVOP         : 2
Format, QPel         : No
Format, GMC          : No warppoints
Format, Matrix       : Default (H.263)
Codec ID             : XVID
Codec ID/Hint        : XviD
Duration             : 44 min 8 s
Bit rate             : 1 484 kb/s
Width                : 720 pixels
Height               : 408 pixels
Display aspect ratio : 16:9
Frame rate           : 23.976 (24000/1001) FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 8 bits
Scan type            : Progressive
Compression mode     : Lossy
Bits/(Pixel*Frame)   : 0.211
Stream size          : 469 MiB (100%)
Writing library      : XviD 69

---------------------------- Muxing to AVI ----------------------------

ffmpeg N-115847-g7c95c7de4a-x64-gcc14.1.0

C:\Users\filys\Desktop\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_out.avi -i "C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en]_3996286542.mp3" -map 0:v -map 1 -c:v copy -c:a copy -strict -2 C:\Stax\Rip\Xvid\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.avi

Input #0, avi, from 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_out.avi':
  Duration: 00:44:08.31, start: 0.000000, bitrate: 1488 kb/s
  Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x408 [SAR 1:1 DAR 30:17], 1484 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn
Input #1, mp3, from 'C:\Stax\Temp\XviD\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora_temp\ID1 English [en]_3996286542.mp3':
  Metadata:
    encoder         : Lavf61.3.104
  Duration: 00:44:08.38, start: 0.023021, bitrate: 136 kb/s
  Stream #1:0: Audio: mp3 (mp3float), 48000 Hz, stereo, fltp, 136 kb/s
      Metadata:
        encoder         : Lavc61.8.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Output #0, avi, to 'C:\Stax\Rip\Xvid\sullivans.crossing.s02e01.1080p.web.h264-resilientsandychickenofaurora.avi':
  Metadata:
    ISFT            : Lavf61.3.104
  Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x408 [SAR 1:1 DAR 30:17], q=2-31, 1484 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn
  Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 136 kb/s
      Metadata:
        encoder         : Lavc61.8.
Press [q] to stop, [?] for help
[avi @ 00000290d4b70940] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[out#0/avi @ 00000290d48be240] video:479794KiB audio:44093KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.785584%

Start:    3:01:54
End:      3:01:55
Duration: 00:00:00

---------------------------- Job Complete ----------------------------

Start:    2:58:31
End:      3:01:55
Duration: 00:03:23

--------------------------- Frame Mismatch ---------------------------

WARNING: Target file has 63497 frames, but should have 63496 frames!
Encoding was probably terminated at 100,0% with a mismatch of -1 frames!

--------------------------- Frame Mismatch ---------------------------

Target file has 63497 frames, but should have 63496 frames!

**Comment by Dendraspis** [comment] 2024-06-17 21:57
Without being able to reproduce hard to tell where the frame comes from, but most likely through muxing the AVI file together.


You can turn `Frame Mismatch` on/off in `Project » Options » Misc` and in case you do something like that more often I advise you to create a template with that feature being turned off.

**Comment by filyse** [comment] 2024-06-19 14:35
still failed.
[image: Screenshot_1.png]

ср, 19 июн. 2024 г. в 18:43, Dendraspis ***@***.***>:

**Comment by Dendraspis** [comment] 2024-06-19 15:26
Sadly there is no screenshot here, just the name of the file.  😕

**Comment by filyse** [comment] 2024-06-19 23:25
Even after I unchecked the options. The error still remains. I have the old
version 2.31 and everything works fine on it. And after the update, this
error appears. And I've already dug through everything in the settings to
no avail.[image: Screenshot_1.png]

ср, 19 июн. 2024 г. в 22:26, Dendraspis ***@***.***>:

**Comment by filyse** [comment] 2024-06-20 14:37
Last time I forgot to save the template. Now it passed without the error
window. But, after the rendering is completed, the window with staxrip is
lit as if the render wants to start again. and the files remain in the temp
folder. Although I set them in the settings to delete them after the
rendering is completed.[image: Screenshot_3.png][image:
Screenshot_2.png][image:
Screenshot_1.png]

чт, 20 июн. 2024 г. в 08:19, Dendraspis ***@***.***>:

**Comment by Dendraspis** [comment] 2024-06-20 15:11
Sadly there are no screenshots in here when you chose to answer via email.  😕

**Comment by filyse** [comment] 2024-06-20 21:22
<img width="1039" alt="Screenshot_1" src="https://github.com/staxrip/staxrip/assets/52866885/4cd4d619-521f-4a1b-9e39-07743048963a">
<img width="476" alt="Screenshot_2" src="https://github.com/staxrip/staxrip/assets/52866885/a821cee4-0f91-4e78-a27d-fbe2a385e95b">
<img width="980" alt="Screenshot_3" src="https://github.com/staxrip/staxrip/assets/52866885/38b4e4e6-6a9a-4835-8bae-50fab5e10e62">

**Comment by Dendraspis** [comment] 2024-06-21 09:03
> Last time I forgot to save the template.

You don't need to create a template, just make sure this option is disabled before you add the job.

> But, after the rendering is completed, the window with staxrip is lit as if the render wants to start again.

Sounds normal.

> and the files remain in the temp folder.

So either you have run a job, that has not the right settings or StaxRip cannot delete the folder because a file is opened somewhere else and so it blocks the deleting process.

I have tested it and cannot reproduce it at all.

**Comment by filyse** [comment] 2024-06-21 10:39
I did everything right. And this error is only for the xvid_encraw codec. There are no such problems on h264. I have many different templates and they all work. Except when the rendering takes place on xvid.

And here is a screenshot that shows an error and refers to the 461st line of code, namely staxrip. And as I said, such errors did not exist in previous versions of staxrip. And it appeared only from version 2.32 and higher. Because in 2.31 and below everything works fine. And of course, the codec itself has not been updated for 200 years and there are no errors in it. It works as before.
<img width="704" alt="Screenshot_1" src="https://github.com/staxrip/staxrip/assets/52866885/c9f6e4f4-cd30-40f3-a488-4e21d54abddd">

**Comment by Dendraspis** [comment] 2024-06-21 11:26
> And this error is only for the xvid_encraw codec. There are no such problems on h264.

Because at some point an extra frame is created as discussed earlier.

> And it appeared only from version 2.32 and higher.

`v2.32` was the first version with that feature which can be checked on the Changelog.

I suggest starting from scratch. This error message can ***only*** be thrown out when `Abort On Frame Mismatch` is enabled for that running job/project. When it's disabled, this simply cannot happen.

**Comment by filyse** [comment] 2024-06-21 13:02
When I uncheck the box. The error is simply not displayed as a notification. But it still exists and is present in the log. So all your messages are essentially useless. This doesn't solve my problem at all. If the checkbox is checked, an error message is displayed. If there is no checkmark, no error message is displayed. But in both cases the error is still present. Disabling error notification does not solve the problem.

**Comment by filyse** [comment] 2024-06-21 13:04
Actually, why argue and try to prove something to each other? You can just take it and try it. Here's the template. Try it yourself.
https://mega.nz/file/7n5ywbyI#yhpj37AV0wGrmUf77Rb08sR1mO27G-_m4yUPF5tOS4o

**Comment by Dendraspis** [comment] 2024-06-21 15:52
> If there is no checkmark, no error message is displayed. But in both cases the error is still present. Disabling error notification does not solve the problem.

Okay, now I got it!
Indeed in case of a frame mismatch the deletion of temp files is canceled to make it possible to check the output files and maybe start new muxing attempts.

I will add an option to delete temp files anyway or at least check the difference...

**Comment by filyse** [comment] 2024-06-21 16:09
In my case it makes no sense to check the difference. It will be enough to simply delete temporary files. Since the file is not broken and everything is readable.

**Comment by Dendraspis** [comment] 2024-06-21 16:14
Not by yourself, but checking the difference and ignoring the whole canceling when the difference is just 1 frame - I think that can make sense.

> Since the file is not broken and everything is readable.

In your case of course, but I have to make it working for all encodes.

**Comment by Dendraspis** [comment] 2024-06-21 18:46
I guess this will work for everyone:

![image](https://github.com/staxrip/staxrip/assets/50659978/01ffa667-af95-48fd-8b83-1459e4119d80)

**Comment by Dendraspis** [comment] 2024-06-22 06:30
If you wanna try it out:
[StaxRip v2.41.4 (EXE-only)](https://ufile.io/eirp2ma1)

**Comment by filyse** [comment] 2024-06-22 16:32
Now the window does not light up red. But folders in temp are still not deleted
![Uploading Screenshot_2.png…]()

**Comment by filyse** [comment] 2024-06-22 16:33
<img width="1185" alt="Screenshot_2" src="https://github.com/staxrip/staxrip/assets/52866885/527ea448-d637-4444-8ddf-79660c00ffd9">
Now the window does not light up red. But folders in temp are still not deleted

**Comment by filyse** [comment] 2024-06-22 16:50
But with these settings everything is fine.
<img width="513" alt="Screenshot_1" src="https://github.com/staxrip/staxrip/assets/52866885/f23a6d9c-603d-4715-aef6-5e51aa793ca0">

**Comment by Dendraspis** [comment] 2024-06-22 17:25
The error message is separated from the temp file deletion - just to keep that in mind.

Thanks for the feedback, there was indeed a stupid little bug, that I have fixed now.  I will release the official `v2.41.4` probably tomorrow where this issue will be fixed, so once out you should update unless you don't care about the thresholds, then keep it at `-1` and you're fine.

**Closed** 2024-06-23 05:20 UTC
Labels: bug  :bug:, added/fixed/done, feature request

**Comment by Andrasolin** [comment] 2024-06-24 10:24
try this
![340553965-e446d971-8700-4dce-9446-f15103a660ec](https://github.com/staxrip/staxrip/assets/150133906/8031d746-da07-4a49-85bf-b4daf41e28bd)
