### ISSUE TITLE
Japanese Audio Track Incorrectly Labeled as Spanish When Loading Blu-ray

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [staxrip/staxrip#1453] opened 2024-08-15 15:32 UTC
**Description:**

When selecting and loading a Blu-ray that contains a Japanese audio track, StaxRip incorrectly labels the Japanese audio track as Spanish in the interface, even before the encoding process begins. This issue has been persistent across multiple versions, including the latest one.

**Steps to Reproduce:**

   Open StaxRip.
   Load a Blu-ray disc that includes a Japanese audio track.
   Observe the audio track listing in the interface.

**Expected Behavior:**

The Japanese audio track should be correctly labeled as Japanese in the StaxRip interface.

**Actual Behavior:**

The Japanese audio track is mislabeled as Spanish in the StaxRip interface before any encoding has started.

**Screenshots:**

![c90e2ec5ce73863bd02efb9070c209f4](https://github.com/user-attachments/assets/e051e8a6-96c4-4c3f-a978-d3d28c892aba)

**Environment:**

    StaxRip Version: 2.41.7 (Latest Version)
    Operating System: Windows 10 Pro 64-bit
    Source: Blu-ray Disc with Japanese Audio Track

**Additional Context:**

This issue occurs consistently across multiple Blu-rays, not just a single disc. The problem has been tested with several Blu-rays containing Japanese audio tracks, and the error persists in every case. This issue has been present for a while, not just in the latest version.

**Comment by Dendraspis** [comment] 2024-08-15 16:17
Thanks for the report.

It looks like this issue is sort of already fixed in `v2.42` as the whole audio treatment was/is altered.

Just to verify that:
Is the audio file name on the screenshot given by StaxRip or did you change it or even put that file there by hand?
What was the source (Blu-Ray or single file), how did you open it (single file, File Batch, Merged, ..) and can you tell me the file name of the source file?

**Comment by Aiyomi-Irirako** [comment] 2024-08-15 16:18
didnt change anything
i opened only the file and this is what i get

**Comment by Dendraspis** [comment] 2024-08-15 16:27
Ah, thanks. Just asked, because the part before `ID2` is usually not there, but it should be caused by the Blu-Ray folder. Thanks for the information.


I had to test it with your file name to verify it really works now ... and yes, it does work:  😅 

<img width=800 src=https://github.com/user-attachments/assets/204af22b-e2fa-4c50-ad56-05ee7a398fef>

**Comment by Aiyomi-Irirako** [comment] 2024-08-15 16:33
ah ok :D

Thank you very much. So, I just need to wait for the new version, and the issue should be resolved? Also, do you know when it will be released? It seems that version 2.42 is not available yet.

**Comment by Dendraspis** [comment] 2024-08-15 17:08
You're welcome. 

Yes. The hard part is the waiting itself, because it will take a few weeks.  😅

**Closed** 2024-08-19 09:59 UTC
Labels: bug  :bug:, added/fixed/done
