### ISSUE TITLE
Downmix AAC 8 7.1 to AC3 5.1

### ISSUE THREAD

**Issue by deadlyshadow79** [staxrip/staxrip#1070] opened 2023-08-06 13:17 UTC
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).
Hello

I convert AAC 7.1 to AC3 5.1 using Staxrip 2.25
in comparison to other encoders (e.g. Handbrake or FFMPEG Audio Encoder) loudness of Left & Right Rare Surround channels is lower, Why, is it normal?

Regards

**Comment by Dendraspis** [comment] 2023-08-06 14:58
Hello,

the keyword is "or", so I've deleted the discussion.

Did you specify decoder and/or encoder or did you leave everything on Automatic?

**Comment by deadlyshadow79** [comment] 2023-08-06 15:33
No I didn't specify decoder/encoder

**Comment by Dendraspis** [comment] 2023-08-06 22:48
You could check the log file, but in that case FFMPEG should be used to decode and encode the audio file.
The only thing you can change is the Normalization. - everything else should be caused by FFMPEG, keeping in mind, that all other settings must be the same.  🤔

**Comment by deadlyshadow79** [comment] 2023-08-07 15:17
Sorry i made a mistake, source Audio is not AAC, it's 8 channels TruHD but it doesn't affect the result.
I've upload them, i appreciate you if you can compare them.

Log File:  https://drive.google.com/file/d/1Ys_UohsgPhtC1BqRXCw1EUq2UIjoUXEY/view?usp=sharing
https://drive.google.com/file/d/1gLeYCx7hz1XG4hPPAZdGk0xy2CjbofrV/view?usp=sharing
https://drive.google.com/file/d/1TvjTbCj4yt3VmrRM_6Y6pismTqrYcS9p/view?usp=sharing

Compare loudness of Rear surrounds

**Comment by Dendraspis** [comment] 2023-08-07 17:38
Yes, there is a difference., and here is the reason:

![image](https://github.com/staxrip/staxrip/assets/50659978/f349be88-8c30-4f23-a08a-754443cdb1c4)

The lower one is the one made by `FFmpeg` CLI. Left/Right/Center/LFE are absolutely the same, but it seems `FFMPEG Audio Encoder` normalizes the Surround Channels a bit (more).

Nevertheless the the Log File shows, that everything seems to be okay from the calling perspective, and also the data and file size is the same. So it is indeed normal, the question is now:  how does the source looks like?  😁

But I'll close this for now as everything works like intended, at least regarding StaxRip.

**Closed by Dendraspis** 2023-08-07 17:38 UTC
Labels: question, tool issue, added/fixed/done, not an issue

**Comment by deadlyshadow79** [comment] 2023-08-07 22:12
source
https://drive.google.com/file/d/1wy_RWjgGA-0KgHZnoOcaSIhY0ljkqtCV/view?usp=sharing

**Comment by Dendraspis** [comment] 2023-08-08 18:40
Fact is:
Both are different from the source when you expect them to be simply merged. But it's normal to make channels louder/quieter when merging, so nothing wrong with that. But in my opinion the `ffmpeg.exe` generated file is a bit more accurate, because it prevents the characteristics of both channels better - in my opinion.
But at the end you have to choose what's better for you and your ears.

**Comment by deadlyshadow79** [comment] 2023-08-08 22:02
Thank You so much.
so, in your opinion, FFMPEG Audio Encoder.mkv is more accurate. I think the same.

Regards

**Comment by Dendraspis** [comment] 2023-08-09 04:17
You're welcome.

But no, I meant `ffmpeg.exe`, the one that is used by StaxRip.

**Comment by deadlyshadow79** [comment] 2023-08-09 14:08
Ok.
Thank You

**Comment by deadlyshadow79** [comment] 2023-08-14 20:41
I have done a new Test.
I've Converted the source file to AAC 5.1 using staxrip with QAAC encoder, loudness of Left & Right Rare Surround channels is the same as left & right side surround channels.
