### ISSUE TITLE
AutoCrop ignores analyzed frames

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1324] opened 2024-04-24 16:46 UTC
Hi,

One of my biggest issues are with autocrop.exe which I believe is developed by you guys.

Around 2 years ago, I asked you to please increase the limit of the frames it checks and you kindly did it. It's 200 frames tops which is good. 

But, sometimes in the videos there - in rare cases -  there are a part that don't have black bars or in other words, it's fullscreen. But the autocrop doesn't care if the duration is too short. Like if it's 2 frames in 200 frame, it doesn't care and ruthlessly crops the whole thing.  

It would be great if you could make it more sensitive. Or at least, there would be an option for it to alert the user so he/she could check. Otherwise it would crop the fullscreen parts and make the results invalid.

**Comment by Dendraspis** [comment] 2024-04-24 18:07
If you can tell me how to do that, without scanning every 50 frames (~2s)....

A more robust detection would have to scan ~720 to ~1800 frames per hour of video and that would take a lot of time.
In most cases 10 scans are enough, as long as you don't deal with IMAX or another techniques that change the aspect ratio. If you know it in advance, you can take care, otherwise you're screwed, that's right.

The best approach is to crop manually after checking different scenes.  😕

**Comment by LazyNCoder** [comment] 2024-04-24 18:17
Sometimes when I use crop window, I can see some fullscreen images between others. But still it doesn't care.
I used to use this window to check and correct the cropping process, but now that I have the "auto crop" option, I barely check. 

There are lots of content that have weird frames in them. Some have forced subtitles on the blackbars. 

What I'm saying is, there is still some fullscreen frames visible using the tool but it's not sensitive enough to realize it. Maybe just a warning would be enough for a through check by the user. 
Also, if we can have more than 200 frames, it would be awesome. 

I don't know if what I asked is possible, but I have to go for it.

**Comment by Dendraspis** [comment] 2024-04-24 20:56
> Sometimes when I use crop window, I can see some fullscreen images between others. But still it doesn't care.
> There are lots of content that have weird frames in them. Some have forced subtitles on the blackbars.
> What I'm saying is, there is still some fullscreen frames visible using the tool but it's not sensitive enough to realize it.

In case you can reproduce it, please try to create a sample or record it so I can see what happens - that would help extremely.
Basically the procedure works good and right now I can't imagine what's going wrong.  🤔  

> Maybe just a warning would be enough for a through check by the user.

There is always a possibility to miss some frames as long as you don't check every frame. So not sure if that helps or is necessary.

> Also, if we can have more than 200 frames, it would be awesome.

That's doable, yeah.  😅

**Comment by LazyNCoder** [comment] 2024-04-24 21:29
Can I use the email in your profile to send the information about this problem?

**Comment by Dendraspis** [comment] 2024-04-25 00:08
Yes, you can, whereas the preferred way to interact/chat is Discord. But if you don't use Discord, feel free to write an email.

**Comment by Dendraspis** [comment] 2024-04-25 10:24
Okay, the sample is exactly what was needed so I can reproduce and test my modifications. There is definitely something wrong...

**Comment by LazyNCoder** [comment] 2024-04-25 10:26
Thank you. I've sent you another sample as well.

**Comment by LazyNCoder** [comment] 2024-04-25 11:46
I actually mentioned it here:
https://github.com/staxrip/staxrip/issues/559

But I guess I couldn't make clear that there are unusual frames that autocrop sees but ignores them. 

Anyway, better late than never 🙂

**Comment by Dendraspis** [comment] 2024-04-25 11:53
I had to check it:
This issue persists since `v1.7` from 2017 or even longer!  😲 

Fix will take a few days.

> But I guess I couldn't make clear that there are unusual frames that autocrop sees but ignores them.

Indeed.  😅   And without those specific samples I still would believe, that there is no issue!  🙄 
The problem is, that it works, depending on the sizes of every frame that was considered.

Additionally I don't (or didn't) know any non-IMAX-videos that use multiple aspect ratios within such a short time.
It seems I ran into this issue a few times within the last years, but I thought it was because the AutoCrop didn't catch those specific frames. 

Interesting... definitely a good catch!  👍

**Comment by Dendraspis** [comment] 2024-04-26 04:42
The new `v2.38.6` works well with your sample files. Feel free to check other videos and let me know how it works, please.

**Comment by Dendraspis** [comment] 2024-04-27 08:43
Did you have the chance to run the new `AutoCrop` (the one, that is in the `Crop` window) on other files? Can you give me any feedback?

**Comment by LazyNCoder** [comment] 2024-04-27 21:41
Thank you very much for fixing the bug. I'm really grateful for it. 
I haven't had time to check, but I'm gonna do it soon. 
I didn't want to post a spam comment, but it wasn't polite to just not say anything.

**Comment by LazyNCoder** [comment] 2024-04-29 15:35
Unfortunately, the bug is still there. I compared the hash files of AutoCrop.exe between v2.37.6 and 2.38.6 and it's the same file.

**Comment by Dendraspis** [comment] 2024-04-29 15:44
Can you first test if the integrated AutoCrop, the one you start from the Crop window, works?

**Comment by LazyNCoder** [comment] 2024-04-29 15:52
Ah YES!
it works. perfectly. 
I was trying with "auto crop" and it was returning the incorrect values as before. But when I used the crop window, everything was fine.

**Comment by LazyNCoder** [comment] 2024-04-29 16:09
OK I replaced the exes and everything works fine. Thank you very much for everything.

**Comment by Dendraspis** [comment] 2024-04-29 16:27
So the proper version will be released with `v2.39`.

I guess we can close this issue now...

PS: Would be nice if you could answer my question from the mail. 😅

**Closed** 2024-04-29 16:27 UTC
Labels: bug  :bug:, added/fixed/done, feature request
