### ISSUE TITLE
x265 direct input ram usage issue with 4 gb ram PC

### ISSUE THREAD

**Issue by tuilakhanh** [staxrip/staxrip#445] opened 2021-01-13 10:54 UTC
**Describe the bug**
x265 pipe make system with 4gb ram freeze after a few minutes running

**Expected behavior**
When i change the pipe to vspipe, it will run normally
**How to reproduce the issue**

1. Change frame server to vapoursynth
2. Set pipe to none
3. Do a encode with x265, preset slow
4. The system will freeze

**Provide information**
Staxrip version: 2.1.7.1

**Additional context**

I also upgraded my ram to 8GB and it was running normally
**Please be as clear and as detailed as possible**

**Comment by Patman86** [comment] 2021-01-13 16:30
Can you please check whether this also happens with AviSynth?

**Comment by Dendraspis** [comment] 2021-01-13 16:36
Just a side note:
I'm running currently a 1080p encode using x265 direct AVS input without pipe and it needs less than 1GB RAM.

**Comment by Patman86** [comment] 2021-01-13 16:40
> Just a side note:
> I'm running currently a 1080p encode using x265 direct AVS input without pipe and it needs less than 1GB RAM.

But how much RAM do you have installed?

**Comment by Dendraspis** [comment] 2021-01-13 16:48
28GB - just wanted to say, that it doesn't seem to be that hungry.  😉

**Comment by Patman86** [comment] 2021-01-13 16:52
I compared the two last weekend and vpy is a bit hungry than avs (~ 500 MB).

**Comment by DJATOM** [comment] 2021-01-13 17:57
I have 64 GB and didn't encountered ram issues on my side, but I tested 3.4 fix on simple scripts. Probably more debugging needed to see where possible leak occurs.

**Comment by msg7086** [comment] 2021-01-13 18:07
I have 128GB installed so it's not bothering me either. I can see in DJATOM's code there's frame pre-fetching going on, so that definitely costs memory to improve multi threading efficiency. Reducing memory usage will hurt speed for sure. My recommendation is to throw more memory sticks on it, because, vapoursynth is "designed for modern computers", so feed it properly.

**Comment by Patman86** [comment] 2021-01-13 18:23
I agree with you both!  Maybe there is still room for improvement.

**Comment by DJATOM** [comment] 2021-01-13 18:33
I found a small problem when we interrupt encoding with ctrl+c. frameDoneCallback still requesting new frames while x265 waiting reader to stop. Maybe I can somehow catch that signal in callback and stop asking for new frames, fighting with that now.

**Comment by Patman86** [comment] 2021-01-13 19:23
> I found a small problem when we interrupt encoding with ctrl+c. frameDoneCallback still requesting new frames while x265 waiting reader to stop. Maybe I can somehow catch that signal in callback and stop asking for new frames, fighting with that now.

[This](// completed frames simply correspond to how many times the completion callback is called) from vspipe helps?

**Comment by Patman86** [comment] 2021-01-13 19:32
> I found a small problem when we interrupt encoding with ctrl+c. frameDoneCallback still requesting new frames while x265 waiting reader to stop. Maybe I can somehow catch that signal in callback and stop asking for new frames, fighting with that now.

Perhaps the vspipe.cpp will help from line 173 downwards

**Comment by DJATOM** [comment] 2021-01-13 19:49
I almost fixed this by adding that to abrEncApp
![изображение](https://user-images.githubusercontent.com/4888694/104501718-c755e180-55e8-11eb-8f64-2bdd6f6cdacf.png)
and executing my "cancellation" code in the `VPYInput::release()` method. As I have said, that abr thing did mess encoder a lot. I'm missing fully working 3.3 branch.

**Comment by DJATOM** [comment] 2021-01-15 03:48
After 2 nights of debugging I finally found where deadlock occurs. 
Basically `Reader::threadMain()` should also have check for b_ctrl_c `if (m_input->readPicture(*src) && !b_ctrl_c)` otherwise deadlock occurs at `PassEncoder::destroy()` -> `m_reader->stop();`. With "light" script and y4m input `Reader` sometimes stopping gracefully, but still having deadlocks with heavy loaded machine. I'm so tired now, will commit my changes tomorrow.

**Comment by DJATOM** [comment] 2021-01-15 22:17
Mentioned changes landed into my repo.

**Comment by tuilakhanh** [comment] 2021-01-16 02:37
> Mentioned changes landed into my repo.

Let's do some test :D

**Comment by tuilakhanh** [comment] 2021-01-16 03:43
The encoder is working fine now, both avs and vpy. The ram usage and perfomance also has been improved. Thanks for the x265 mod

**Comment by tuilakhanh** [comment] 2021-01-16 07:39
Now I have a problem with x265 @DJATOM mod direct input

![alt text](https://media.discordapp.net/attachments/737981119630409820/799900778604789760/unknown.png)

![alt text](https://media.discordapp.net/attachments/737981119630409820/799904808772435968/unknown.png)

It only happen with direct input, vspipe mode is working fine

**Comment by msg7086** [comment] 2021-01-16 07:56
C0000374 is Heap Corruption.

**Comment by JJKylee** [comment] 2021-01-16 22:30
@tuilakhanh, I also had the same problem and reported an [issue](https://github.com/DJATOM/x265-aMod/issues/4). Now the issue is fixed in [@DJATOM's release today](https://github.com/DJATOM/x265-aMod/releases/tag/3.4%2B56).

Try this one. I tested it just now with a 78-minute VOB(MPEG-2, AC-3, 720x480) and have **not** observed any **memory leak** issue as well. Rather, the memory gets a little smaller near the end.

@Patman86, I think you can refer to this new fix for your release. 😃

And @stax76, I suggest this build be used for shipment with the next release of StaxRip. It seems desirable in every respect, IMHO.

**Comment by tuilakhanh** [comment] 2021-01-17 02:07
I can confirm it is fixed.

Thanks to @DJATOM

**Comment by tuilakhanh** [comment] 2021-01-17 10:45
Fixed at https://github.com/staxrip/staxrip/commit/868113570fa3c6199fec9c6a459428446db4d54e

**Closed** 2021-01-17 10:45 UTC
Labels: added/fixed/done, tool issue
