### ISSUE TITLE
Autocrop 2.4.0.0 Causing Application Crash

### ISSUE THREAD

**Issue by yammes08** [staxrip/staxrip#1424] opened 2024-07-10 21:54 UTC
**Describe the bug**
With a particular media file, Autocrop 2.4.0.0 is crashing Staxrip with the following error:
```
------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: AutoCrop 2.4

"C:\Users\Encoding\StaxRip-v2.41.6-x64\Apps\Support\AutoCrop\AutoCrop.exe" D:\Encoding\Sources\file_temp\file_source.vpy 0 15 0

System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoCrop.Module1.Main() in D:\Code\Github\staxrip\staxrip\Source\Tools\AutoCrop\Main.vb:line 47


Auto Crop returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 366
   at StaxRip.MainForm.AutoCrop() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2655
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2394
```

**Expected behavior**
Autocrop does not cause Staxrip to crash.

**How to reproduce the issue**

Use a source file with the following mediainfo:
```
General
Unique ID                                : 111147769354743132037981186590697926858 (0x539E481F24C70FBF78ABE73EC7E130CA)
Complete name                            : file.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 20.5 GiB
Duration                                 : 1 h 26 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 33.9 Mb/s
Frame rate                               : 24.000 FPS
Movie name                               : 
Encoded date                             : 2023-03-31 12:29:57 UTC
Writing application                      : mkvmerge v75.0.0 ('Goliath') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1
IMDB                                     : tt0053699
TMDB                                     : movie/21240

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Format settings, Slice count             : 4 slices per frame
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 26 min
Bit rate mode                            : Variable
Bit rate                                 : 33.0 Mb/s
Maximum bit rate                         : 35.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.663
Stream size                              : 19.9 GiB (97%)
Title                                    : MPEG-4 AVC Video / 32992 kbps / 1080p / 24 fps / 16:9 / High Profile 4.1
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 1 h 26 min
Bit rate mode                            : Variable
Bit rate                                 : 635 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 11.719 FPS (4096 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 393 MiB (2%)
Title                                    : FLAC 2.0
Writing library                          : libFLAC 1.2.1 (2007-09-17)
Language                                 : English
Default                                  : Yes
Forced                                   : No
MD5 of the unencoded content             : C4BE6A6C209773AE429985A11C5C1A7F

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 26 min
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 138 MiB (1%)
Title                                    : 
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Dialog Normalization                     : -31 dB
dialnorm_Average                         : -31 dB
dialnorm_Minimum                         : -31 dB
dialnorm_Maximum                         : -31 dB

Text
ID                                       : 4
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 24 min
Bit rate                                 : 38.8 kb/s
Frame rate                               : 0.481 FPS
Count of elements                        : 2438
Stream size                              : 23.5 MiB (0%)
Title                                    : English
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 1
00:01:33.000                             : en:Chapter 2
00:07:01.208                             : en:Chapter 3
00:14:16.333                             : en:Chapter 4
00:25:10.500                             : en:Chapter 5
00:34:39.375                             : en:Chapter 6
00:48:07.792                             : en:Chapter 7
00:52:36.208                             : en:Chapter 8
01:04:53.083                             : en:Chapter 9
01:14:13.958                             : en:Chapter 10
01:19:39.667                             : en:Chapter 11
01:26:14.333                             : en:Chapter 12
```

**Provide information**
```
------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: AutoCrop 2.4

"C:\Users\Encoding\StaxRip-v2.41.6-x64\Apps\Support\AutoCrop\AutoCrop.exe" D:\Encoding\Sources\file_temp\file_source.vpy 0 15 0

System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoCrop.Module1.Main() in D:\Code\Github\staxrip\staxrip\Source\Tools\AutoCrop\Main.vb:line 47


Auto Crop returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 366
   at StaxRip.MainForm.AutoCrop() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2655
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2394
```

**Comment by yammes08** [comment] 2024-07-11 00:25
I'll add this in case it is of relevance.

On the last working version I had, the autocross command is: `"C:\Users\Encoding\StaxRip-v2.31.0-x64\Apps\Support\AutoCrop\AutoCrop.exe" D:\Encoding\Sources\file_temp\file_source.vpy 15 0`.

On the latest version it is `"C:\Users\Encoding\StaxRip-v2.41.6-x64\Apps\Support\AutoCrop\AutoCrop.exe" D:\Encoding\Sources\file_temp\file_source.vpy 0 15 0` - there's an extra `0` before the `15`.

**Comment by Dendraspis** [comment] 2024-07-11 06:21
Looks like you are using an old version of `AutoCrop`. Make sure, that you use `AutoCrop v2.4` that comes with `v2.40` and later, by checking the file properties.

Especially when jumping over so many versions, remember to not extract and overwrite the new version over an existing one. Also use fresh/new settings to make sure there won't be any side effects.

**Comment by jessielw** [comment] 2024-07-11 06:39
> Looks like you are using an old version of `AutoCrop`. Make sure, that you use `AutoCrop v2.4` that comes with `v2.40` and later, by checking the file properties.
> 
> Especially when jumping over so many versions, remember to not extract and overwrite the new version over an existing one. Also use fresh/new settings to make sure there won't be any side effects.
> 
> > I'll add this in case it is of relevance.
> 
> That's correct as the command has changed in `v2.3` I think. That also means you can't use a new version of StaxRip with an old version of `AutoCrop` and vice versa.

That was just a test he was doing. However, the failure happens on the latest version of AutoCrop on the latest version of StaxRip. I sent you the sample file via discord to reproduce the bug. It happens right after you open the source and it's done indexing.

**Comment by Dendraspis** [comment] 2024-07-11 06:46
I will check that file and come back with an answer...

**Comment by Dendraspis** [comment] 2024-07-11 10:01
Can you extract this one to `.\Apps\Support\AutoCrop` and repeat the whole opening to verify, that the issue is gone with this fix?

[AutoCrop v2.4.1.zip](https://github.com/user-attachments/files/16174753/AutoCrop.v2.4.1.zip)

**Comment by yammes08** [comment] 2024-07-11 10:10
> Can you extract this one to `.\Apps\Support\AutoCrop` and repeat the whole opening to verify, that the issue is gone with this fix?
> 
> [AutoCrop v2.4.1.zip](https://github.com/user-attachments/files/16174753/AutoCrop.v2.4.1.zip)

It resolves the issue with my test file, I'll let @jessielw check with his file too.

**Comment by Dendraspis** [comment] 2024-07-11 16:28
Here is an even better fix:
[AutoCrop v2.4.2.zip](https://github.com/user-attachments/files/16180701/AutoCrop.v2.4.2.zip)

Both parties confirmed, that the fix works, so I close this issue now.

**Closed by Dendraspis** 2024-07-11 16:28 UTC
Labels: bug  :bug:

**Comment by jessielw** [comment] 2024-07-11 16:40
Thanks for the quick fix @Dendraspis!
