### ISSUE TITLE
Error when opening .srip project files

### ISSUE THREAD

**Issue by kuzon3** [staxrip/staxrip#1375] opened 2024-06-01 06:58 UTC
Opening a .srip save file by double clicking will give error "Error parsing argument...."save file path".....exception of type 'system.exception' was thrown.

Drag and drop of .srip works/opens just fine with no error message.
"Save file path" = I didn't want to type out my save file path 😅

Staxrip version: v2.39.3

**Comment by Dendraspis** [comment] 2024-06-01 08:23
It will be necessary to see that error message as I can't reproduce it.

You can black out sensible data or you can move your `srip` file to for example `A:\Sample.srip` which should also work.

**Comment by kuzon3** [comment] 2024-06-01 08:46
![Untitled2](https://github.com/staxrip/staxrip/assets/113875688/8f8bb064-a9a0-48e2-a6c2-55766c52b57a)

**Comment by Dendraspis** [comment] 2024-06-01 11:07
Interestingly after creating a path like yours, I can also reproduce it for other paths as well.  🥴 

Thanks for the report.  👍 

It will be fixed with the next release...

**Closed** 2024-06-01 11:28 UTC
Labels: bug  :bug:, added/fixed/done
