### ISSUE TITLE
2.1.9.0: Ugly looking drop-down menu item margins in Options > Subtitles > Subtitles

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#623] opened 2021-03-25 00:14 UTC
See this screenshot:

![StaxRip_2 1 9 0_bad-portion_in_dropdown-menu_20210324](https://user-images.githubusercontent.com/3157518/112399738-03ca4b80-8cc4-11eb-976c-fca8449d1531.gif)

This happens only at the _first_ click on the drop-down menu.

And this is also true for the `System Colors` theme.

And 2.1.20 has the same issue:

![StaxRip_2 1 20_bad-portion_in_dropdown-menu_20210324](https://user-images.githubusercontent.com/3157518/112399801-278d9180-8cc4-11eb-9601-270746787ffa.gif)

**Comment by stax76** [comment] 2021-03-25 01:53
Unfortunately it's not reproducible (with Scale Factor = 1).

Either way maybe not possible to fix since it's really Microsoft .NET Framework code.

**Comment by JJKylee** [comment] 2021-03-25 01:59
I didn't know it's related to the UI scale factor.
Anyway, sad to hear that it's more of a framework issue. 😥

**Comment by stax76** [comment] 2021-03-25 02:09
Which scale factor do you use?

**Comment by JJKylee** [comment] 2021-03-25 02:10
1.25.

**Comment by stax76** [comment] 2021-03-25 02:37
I was now able to reproduce it. Making the dialog bigger has it fixed here, tested with scale 1.25.

**Comment by Dendraspis** [comment] 2021-03-25 07:29
@JJKylee 
So you can check if this works for you:
[StaxRip v2.1.21.zip](https://github.com/staxrip/staxrip/files/6202723/StaxRip.v2.1.21.zip)

**Comment by JJKylee** [comment] 2021-03-25 07:34
`Options` > `Subtitles` drop-down menus are fixed, but now the newly widened `General` > `Startup Template` drop-down menu suffers from a similar issue. 😅

**Comment by Dendraspis** [comment] 2021-03-25 07:38
Are your template names that long?  😲

**Comment by JJKylee** [comment] 2021-03-25 07:47
![StaxRip_2 1 21_drop-down-menu_glitch_in_Startup-Template_20210324](https://user-images.githubusercontent.com/3157518/112436757-58d98200-8d03-11eb-889d-9b07cb0407d2.jpg)

Yeah, some of my template names are looong. 😅

> And why is there no facepalm reaction smiley ?!?!?!?!?!?!?!?!?!?!?!

🤔 ⇦ What for? 🙄

**Comment by Dendraspis** [comment] 2021-03-25 08:48
> Yeah, some of my template names are looong. 😅

That should be the reason ... for some reason.  🤔 
But it's fixed now:
[StaxRip v2.1.22.zip](https://github.com/staxrip/staxrip/files/6203242/StaxRip.v2.1.22.zip)

> 🤔 ⇦ What for? 🙄

Stop kidding me.  😝

**Comment by JJKylee** [comment] 2021-03-25 09:14
This is really embarrassing.

`Startup Template` drop-down menu is fixed, but now the `Subtitles` drop-down menu has a permanent white margin on the right.

![StaxRip_2 1 22_drop-down-menu_glitch_in_Subtitles-option_20210325](https://user-images.githubusercontent.com/3157518/112447998-2afa3a80-8d0f-11eb-9224-484228fdbb9a.jpg)

Looks like a never ending situation. 😥

I better shorten my template names instead of seeing this permanent white margin on the right. 😓

**Comment by Dendraspis** [comment] 2021-03-25 09:18
Come on .... all my tests were satisfying.  😢 

Okay, can see it ... trying to fix (or revert) it.

**Comment by JJKylee** [comment] 2021-03-25 09:24
Like @stax76 said above, maybe the scale factor is the culprit. Mine is 1.25.

**Comment by Dendraspis** [comment] 2021-03-25 09:39
I'm already solving ....

**Comment by stax76** [comment] 2021-03-25 09:40
@Dendraspis 

The last change made it a lot worse here, it can now be seen permanently.

**Comment by Dendraspis** [comment] 2021-03-25 09:57
@stax76 
I know. 😁

**Comment by Dendraspis** [comment] 2021-03-25 10:12
@JJKylee 
How does this work for you?
[StaxRip v2.1.23.zip](https://github.com/staxrip/staxrip/files/6203835/StaxRip.v2.1.23.zip)

There is still a tiny problem, but it should be possible to fix it, too.

**Comment by tormento** [comment] 2021-03-25 10:18
![image](https://user-images.githubusercontent.com/2351785/112457121-bbf70300-8d5b-11eb-8bc8-483de3ee9426.png)
I have this since 2.1.9.0, Tried the builds here but no fix yet.

**Comment by Dendraspis** [comment] 2021-03-25 10:24
I've updated to v2.1.24 - issue should be fixed now. I can't reproduce it anymore.  🎉 

@tormento
One issue for each problem!

**Comment by 44vince44** [comment] 2021-03-25 10:26
THANKS @Dendraspis v2.1.24 it is working fine here now !!!

**Comment by JJKylee** [comment] 2021-03-25 10:31
Me, too.

But I've learned that the template name should not exceed 44 letters, cuz otherwise a white margin starts forming on the right in the `Startup Template` drop-down menu. 😅

I've shortened the name, and it looks perfectly fine now. 👍👍👍

**Comment by stax76** [comment] 2021-03-25 10:33
@Dendraspis 

I think the issue is somewhere here:

https://github.com/staxrip/staxrip/blob/master/Source/UI/TaskDialog.vb#L107

Or here:

https://github.com/staxrip/staxrip/blob/master/Source/UI/TaskDialogBaseForm.vb#L188

**Comment by Dendraspis** [comment] 2021-03-25 10:49
@JJKylee 
But with v2.1.24 the width should not matter anymore.  🤔 

@stax76 
I wanted to change the color system for the new TaskDialog this weekend anyway. 
Nevertheless:  wrong issue  😋

**Comment by JJKylee** [comment] 2021-03-25 10:59
> @JJKylee
> But with v2.1.24 the width should not matter anymore. 🤔

Oh, I was talking about this _teeny-tiny_ white margin.

![StaxRip_2 1 23_drop-down-menu_smaill_white_margin_on_right_20210325](https://user-images.githubusercontent.com/3157518/112462454-4a4c9400-8d1e-11eb-96b4-25785b0ab2a2.jpg)

Never mind. It's nothing compared to before. 😁

**Comment by JJKylee** [comment] 2021-03-25 11:11
So it seems to be related to the scale factor... again. Hmm... 🤨

**Comment by Dendraspis** [comment] 2021-03-25 12:07
@JJKylee 
I can fix this probably, but can you tell me what happens with the white border, when your templates are even longer ?

**Comment by Dendraspis** [comment] 2021-03-25 16:14
Try this one:
[StaxRip v2.1.32.zip](https://github.com/staxrip/staxrip/files/6206147/StaxRip.v2.1.32.zip)

**Comment by JJKylee** [comment] 2021-03-25 16:47
Wow... No more tiny white margins any more. All drop-down margin related issues are gone with 2.1.32.
Good job, @Dendraspis!!! 👍👍👍👍👍

**Closed** 2021-03-25 16:55 UTC
Labels: added/fixed/done, bug, priority high

**Comment by JJKylee** [comment] 2021-03-25 16:58
@Dendraspis, I can see you also fixed the TaskDialog theme issue too in this dev version.
So I can see no more TaskDialog like this in `System Colors` theme.

![](https://user-images.githubusercontent.com/2351785/112457121-bbf70300-8d5b-11eb-8bc8-483de3ee9426.png)

But there's a very minor thing with `System Colors` theme in 2.1.32.

![StaxRip_2 1 32_Assistant-message_System-Colors-theme_20210325](https://user-images.githubusercontent.com/3157518/112512510-aa5c2e00-8d50-11eb-98f9-24bde5a9f42f.jpg)

**Comment by Dendraspis** [comment] 2021-03-25 17:22
@JJKylee 
It's not even an issue.  😂 
@stax76  updated the assistent a while ago (days after themes were implemented) and created a third step:

- No problems: Accent Color
- Warning, that doesn't block the job: Accent Color
- Warning, that blocks the job: Highlight Color

Before it was *No problem* and *Warning* only. But yes, in the future we should give that third step a color or get rid of it.

**Comment by Dendraspis** [comment] 2021-03-25 18:24
@JJKylee 
It's fixed.  😉
