### ISSUE TITLE
Can't use AVISource filter, issue on multiple systems.

### ISSUE THREAD

**Issue by nj2359** [staxrip/staxrip#1169] opened 2023-12-30 01:38 UTC
Re-opening this under a new thread because the original was closed too quickly for me to perform any followup tests.

StaxRip 2.30.0 - can't use AVISource
StaxRip works on my older system with a 4690k CPU
On my newer system, with an 8700k cpu, is where I get the error.
Both systems are running Win10 and have the prerequisites of .net and visual C++
The issue exists for both FFV1 and HuffYUV lossless encoded files. I have not tested other formats.

Note* FFVideoSource and DirectShowSource work and will load the video.
I do not want to use FFVideoSource, which is selected by default, because audio goes out of sync when deinterlacing with QTGMC. DirectShowSource works and produces a good copy of my final encoded file to FFV1 .MOV with the audio still in sync.
However, I want to figure out why I can't use AVISource which will also keep the audio in sync, as tested on the working system.

The 8700k system had AviSynth+ 3.7.3 installed. I uninstalled it in case it was somehow interfering with the embedded AviSynth in StaxRip, but that did not resolve the issue.
I've recopied the original StaxRip portable folder multiple times to ensure I'm testing with an unaltered copy.

In StaxRip, AviSynth Mode: is set to "Use Portable directly"
image

Is StaxRip fully portable and self contained? I'm not sure where else to go. See log output below.
```
------------------------- System Environment -------------------------

StaxRip : v2.30.0
Windows : Windows 10 Enterprise 22H2 2009 (19041.1.amd64fre.vb_release.191206-1406)
Language : English (United States)
CPU : Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
RAM : 64GB
GPU : NVIDIA GeForce RTX 3080
Resolution : 1920 x 1080
DPI : 96
Code Page : 1252

----------------------- Media Info Source File -----------------------

D:\TestVideo.avi

General
Complete name : D:\TestVideo.avi
Format : AVI
Format/Info : Audio Video Interleave
Format profile : OpenDML
Format settings : WaveFormatEx
File size : 5.34 GiB
Duration : 14 min 9 s
Overall bit rate : 54.0 Mb/s
Frame rate : 29.970 FPS

Video
ID : 0
Format : HuffYUV
Format version : Version 2
Codec ID : HFYU
Duration : 14 min 9 s
Bit rate : 52.5 Mb/s
Width : 720 pixels
Height : 576 pixels
Display aspect ratio : 5:4
Frame rate : 29.970 (30000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:2
Bit depth : 8 bits
Scan type : Interlaced
Bits/(Pixel*Frame) : 4.220
Stream size : 5.19 GiB (97%)

Audio
ID : 1
Format : PCM
Format settings : Little / Signed
Codec ID : 1
Duration : 14 min 9 s
Bit rate mode : Constant
Bit rate : 1 536 kb/s
Channel(s) : 2 channels
Sampling rate : 48.0 kHz
Bit depth : 16 bits
Stream size : 156 MiB (3%)
Alignment : Aligned on interleaves
Interleave, duration : 10 ms (0.29 video frame)
Interleave, preload duration : 49 ms

------------------------ Error opening source ------------------------

AVISource: couldn't locate a decompressor for fourcc HFYU
(D:\TestVideo_temp\TestVideo_source.avs, line 3)

AddAutoloadDir("C:\tools2\StaxRip-v2.30.0-x64_test\StaxRip-v2.30.0-x64\Apps\FrameServer\AviSynth\plugins")

AviSource("D:\TestVideo.avi", audio=false)
```

@[nj2359](https://github.com/nj2359) nj2359 added the [question](https://github.com/staxrip/staxrip/labels/question) label [yesterday](https://github.com/staxrip/staxrip/issues/1167#event-11354379101)
@Dendraspis
Collaborator
[Dendraspis](https://github.com/Dendraspis) commented [11 hours ago](https://github.com/staxrip/staxrip/issues/1167#issuecomment-1872107310) • 
Which version of StaxRip are you using on the "working" system?
Did you use the exact same file?

According to [VideoHelp](https://forum.videohelp.com/threads/389661-AviSynth-avisource-couldn-t-locate-a-decompressor) and [StackOverflow](https://stackoverflow.com/questions/51947622/avisynth-cant-open-my-avi-file-avisource-couldnt-locate-a-decompressor-for) using DirectShowSource() should be the solution as AviSource() seems to need external codecs to work on some sources.

Is StaxRip fully portable and self contained? I'm not sure where else to go.

Yes, no installation of AviSynth+ required.

@[Dendraspis](https://github.com/Dendraspis) Dendraspis added the [added/fixed/done](https://github.com/staxrip/staxrip/labels/added%2Ffixed%2Fdone) label [11 hours ago](https://github.com/staxrip/staxrip/issues/1167#event-11357096283)
@[Dendraspis](https://github.com/Dendraspis) Dendraspis closed this as [completed](https://github.com/staxrip/staxrip/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [11 hours ago](https://github.com/staxrip/staxrip/issues/1167#event-11357096570)

@nj2359
Author
[nj2359](https://github.com/nj2359) commented [4 hours ago](https://github.com/staxrip/staxrip/issues/1167#issuecomment-1872330815) • 
Yes, I made sure to replicate the same environment as much as possible. Same version 2.3.0, exact same source video file. If there are other logs I should be pulling, let me know. Enabling debugging does not produce any more in this particular log output, as it cannot get past loading the file.
I'd like to know where StaxRip is looking for the source filter and failing.

Tested on a 3rd system and I have the same exact issue not being able to use AviSource
AVISource: couldn't locate a decompressor for fourcc HFYU.
Things to note:
klite codec pack is installed on all systems
the 2 problematic systems have adobe creative suite, premier pro, photoshop, lightroom classic
I do not want to uninstall adobe suite
I want to know how to pinpoint the cause without just trial and error
I'm not sure if or how other software will interfere with StaxRip, as it is portable.
I will try on a clean 4th machine eventually.

AviSource filter is the only one keeping the audio in sync during deinterlacing, so I really want to get it working.
I discovered DirectShowSource does NOT keep audio sync on longer videos when deinterlacing with QTGMC, when
converting from HuffYUV to FFV1, it becomes evident in longer videos as audio is out of sync toward end.
In my previous workflow with Virtualdub2, I would capture old VHS tapes and encode in HuffYUV lossles, but then I discovered the better FFV1 lossless, so I started using that.
So I've got a mix of HuffYUV and FFV1 source files
With Virtualdub2, I would then need to re-encode to ProRes422 without doing anything like deinterlacing, otherwise I'd lose audio sync.
I would then need to deinterlace the ProRes422 file and also encode the final output to ProRes422 as well.
This was the only way I could find to keep the audio in sync.
Another reason I used ProRes, Davinci resolve did not support FFV1, but they finally do now in both MKV and MOV containers.
I want to eliminate the extra middle step of re-encoding and ideally keep the FFV1 format.
So far, StaxRip using the AviSource Filter seems to be working the way I need, however, I need it to function on my faster machine.
My final output is deinterlacing with QTGMC, directly from the source HuffYUV file and encoding to an FFV1 MKV

Comparing Virtualdub2 vs StaxRip for encoding jobs, StaxRip is nicer to work with by not having to manually edit the scripts for each file, so it's quicker and easier to queue up jobs
It is also better for anyone who is not very familiar with the scripting language, like myself, and being able to see how StaxRip builds the scripts is very helpful.

**Comment by darkcity87** [comment] 2023-12-30 04:34
Try adding `, fpsnum=30000, fpsden=1001` to FFVideoSource it maybe fix sync issue

**Comment by nj2359** [comment] 2023-12-30 06:16
I setup a windows 10 22H2 VM, with the prerequisites of .net and visual c++.  StaxRip 2.3.0 will not launch in the VM.  Should I be able to run it in a VM?
I will test with your suggestion, however, a deinterlace job takes a while.

Yet I know AviSource works and keeps the audio in sync, where it's able to run on the slower PC without the decompressor error.  Can anyone help me figure out why it will not run on 2 of my systems?

**Comment by nj2359** [comment] 2023-12-30 07:16
`, fpsnum=30000, fpsden=1001` did work to keep audio in sync, great solution!

Here is what the full code looks like, under "Source" for anyone else who runs into audio sync issues with 29.97FPS source video.
`tcFile = "%temp_file%_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("%source_file%", cachefile="%source_temp_file%.ffindex", timecodes=tcFile, fpsnum=30000, fpsden=1001) : FFVideoSource("%source_file%", cachefile="%source_temp_file%.ffindex", fpsnum=30000, fpsden=1001)
`
By adding fpsnum=30000 and fpsden=1001 within the FFVideoSource function, you are explicitly setting the frame rate to 30000/1001 (which is approximately 29.97 FPS)
This makes sense, now that it has been brought to my attention by @darkcity87 
This is a completely viable solution.  However, I'm still happy to figure out why I can't use AviSource if anyone can tell me what else I can do to troubleshoot.
@darkcity87  Thanks again!

**Comment by Dendraspis** [comment] 2023-12-30 18:21
> I setup a windows 10 22H2 VM, with the prerequisites of .net and visual c++.  StaxRip 2.3.0 will not launch in the VM.  Should I be able to run it in a VM?

I guess you meant `v2.30.0` ? 😄
If you mean, that StaxRip won't start or opens and immediately closes itself, then this is caused by a bug, that is already fixed for the next release. `v2.29` shouldn't have this issue if you wanna test it before the next release.


Depending on the source and used filters it might be necessary to set a definite frame rate as already mentioned before. 

Just to be noted: This as well as the choice or usage of filters is not StaxRip related. To get help about specific filters I recommend their docs and video editing specialized forums.

So I close this issue now (again)...

**Closed** 2023-12-30 18:22 UTC
Labels: duplicate, question

**Comment by nj2359** [comment] 2023-12-30 18:52
Please re-open this issue.

Just when I think I have a solution, I don't.  I didn't pick it up at first but using `, fpsnum=30000, fpsden=1001` keeps the audio in sync, however, using QTGMC deinterlace, there is a jitter every 6 - 8 frames where it's as if it repeats a previous frame.  It is not the same type of jitter when you have the field order incorrect.  The correct field order for my videos is AssumeTFF().
This issue does not exist if using AviSource filter.  I need to get AviSource filter working.  Again I'm not sure why it won't work on my good machine if StaxRip is pointing to itself for all plugins.

**Comment by nj2359** [comment] 2024-01-01 01:42
The audio sync without frame jitter solution is this, set the framerate in the encoder options, **not** by using `, fpsnum=30000, fpsden=1001` with the FFVideoSource filter.  This keeps the audio in sync and got rid of the jitter that would occur every 8, 15, 30 frames, when a frame was repeated.

for re-encoding from HuffYUV to FFV1, set it to 29.97FPS with this line in encoder options.  With my 8700k cpu, I use more threads for just encoding without deinterlacing, as it makes a big difference in performance.
threads=10
-r 30000/1001 -coder 1 -level 3 -context 1 -g 1 -slices 24 -slicecrc 1

For deinterlacing with QTGMC, from HuffYUV source, and encoding to FFV1, you have to set 59.94 FPS (double the 29.97 framerate) as QTGMC doubles the framerate.  I also use less threads in the encoder while deinterlacing, because the deinterlacing is taking all the CPU power and the encoder is just waiting, so more threads make no difference.
threads=2
-r 60000/1001 -coder 1 -level 3 -context 1 -g 1 -slices 24 -slicecrc 1
![image](https://github.com/staxrip/staxrip/assets/25471276/1881832f-3150-4a70-a7d5-4660446541a2)
