### ISSUE TITLE
Direct input chunk encoding error

### ISSUE THREAD

**Issue by apophis906** [staxrip/staxrip#457] opened 2021-01-17 18:37 UTC
**Describe the bug**
When pipe is set to none with new beta and chunks set to more than one, every chunk will be an exact copy of the first chunk. When the pipe is set to avs2pipemod the output will be as before with each chunk the correct part of the video.

**Expected behavior**
Output of each chunk to be separate parts of the video defined by the chunk cut points.

**How to reproduce the issue**

I tested this will different files and the same result happened with each. Just load a video file and set chunk to more than one. Once the encode is finished the first chunk will be the first part of the file and any other chunk will be a copy of the same file.

**Provide information**

This is using version 2.1.7.2 with portable avisynth and the included x265. The log shows that is thinks it is encoding the chunk correctly, however the output file is still the first part. Just changing the pipe to avs2pipemod caused it to act correctly again.

With direct input.
--------------------------- Video encoding ---------------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Encoders\x265\x265.exe --seek 0 --frames 760 --crf 20 --preset slower --output-depth 10 --aq-mode 3 --aq-strength 0.6 --ssim --psnr --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --deblock -1:-1 --output "D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc" "D:\Backup\test\iZombie test_temp\iZombie test_new direct.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [info]: 1920x1080 fps 24000/1001 i420p8 frames 0 - 759 of 1520
raw  [info]: output file: D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc
x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --psnr used with psy on: results will be invalid!
x265 [warning]: --tune psnr should be used if attempting to benchmark psnr!
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 3 inter / 3 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 4
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 40 / 8 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 5 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 3 / 0.6 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rect amp limit-modes rd=6 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 limit-tu=4 signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing deblock(tC=-1:B=-1) sao
x265 [info]: frame I:     10, Avg QP:18.52  kb/s: 26029.39  PSNR Mean: Y:52.084 U:54.142 V:56.359  SSIM Mean: 0.986997 (18.860dB)
x265 [info]: frame P:    146, Avg QP:19.90  kb/s: 10640.33  PSNR Mean: Y:48.577 U:50.757 V:53.081  SSIM Mean: 0.984943 (18.223dB)
x265 [info]: frame B:    604, Avg QP:25.71  kb/s: 1256.31   PSNR Mean: Y:47.811 U:50.450 V:53.134  SSIM Mean: 0.982041 (17.457dB)
x265 [info]: Weighted P-Frames: Y:1.4% UV:1.4%
x265 [info]: Weighted B-Frames: Y:2.5% UV:2.2%
x265 [info]: consecutive B-frames: 8.3% 2.6% 12.8% 17.9% 8.3% 39.7% 1.9% 5.1% 3.2% 
encoded 760 frames in 0:07:14.56 (1.75 fps), 3384.99 kb/s, Avg QP:24.50, Global PSNR: 48.976, SSIM Mean Y: 0.9826636 (17.610 dB)

Start:    11:25:12 AM
End:      11:32:30 AM
Duration: 00:07:17

----------------------- Video encoding chunk 2 -----------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Encoders\x265\x265.exe --seek 760 --frames 760 --crf 20 --preset slower --output-depth 10 --aq-mode 3 --aq-strength 0.6 --ssim --psnr --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --deblock -1:-1 --output "D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc" "D:\Backup\test\iZombie test_temp\iZombie test_new direct.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [info]: 1920x1080 fps 24000/1001 i420p8 frames 760 - 1519 of 1520
raw  [info]: output file: D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc
x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --psnr used with psy on: results will be invalid!
x265 [warning]: --tune psnr should be used if attempting to benchmark psnr!
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 3 inter / 3 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 4
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 40 / 8 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 5 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 3 / 0.6 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rect amp limit-modes rd=6 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 limit-tu=4 signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing deblock(tC=-1:B=-1) sao
x265 [info]: frame I:     10, Avg QP:18.52  kb/s: 26029.39  PSNR Mean: Y:52.084 U:54.142 V:56.359  SSIM Mean: 0.986997 (18.860dB)
x265 [info]: frame P:    146, Avg QP:19.90  kb/s: 10640.33  PSNR Mean: Y:48.577 U:50.757 V:53.081  SSIM Mean: 0.984943 (18.223dB)
x265 [info]: frame B:    604, Avg QP:25.71  kb/s: 1256.31   PSNR Mean: Y:47.811 U:50.450 V:53.134  SSIM Mean: 0.982041 (17.457dB)
x265 [info]: Weighted P-Frames: Y:1.4% UV:1.4%
x265 [info]: Weighted B-Frames: Y:2.5% UV:2.2%
x265 [info]: consecutive B-frames: 8.3% 2.6% 12.8% 17.9% 8.3% 39.7% 1.9% 5.1% 3.2% 
encoded 760 frames in 0:07:15.76 (1.74 fps), 3384.99 kb/s, Avg QP:24.50, Global PSNR: 48.976, SSIM Mean Y: 0.9826636 (17.610 dB)

Start:    11:25:12 AM
End:      11:32:31 AM
Duration: 00:07:18

With avs2pipemod
--------------------------- Video encoding ---------------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\FrameServer\AviSynth\AviSynth.dll -trim=0,759 -y4mp "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod.avs" | C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Encoders\x265\x265.exe --frames 760 --crf 20 --preset slower --output-depth 10 --aq-mode 3 --aq-strength 0.6 --ssim --psnr --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --deblock -1:-1 --y4m --output "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc" -

avs2pipemod[info]: invoking Trim ...
avs2pipemod[info]: writing 760 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
y4m  [info]: 1920x1080 fps 24000/1001 i420p8 unknown frame count
raw  [info]: output file: D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc
x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --psnr used with psy on: results will be invalid!
x265 [warning]: --tune psnr should be used if attempting to benchmark psnr!
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 3 inter / 3 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 4
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 40 / 8 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 5 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 3 / 0.6 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rect amp limit-modes rd=6 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 limit-tu=4 signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing deblock(tC=-1:B=-1) sao
avs2pipemod[info]: finished, wrote 760 frames [100%].
avs2pipemod[info]: total elapsed time is 410.692 sec.
x265 [info]: frame I:     10, Avg QP:18.52  kb/s: 26029.39  PSNR Mean: Y:52.084 U:54.142 V:56.359  SSIM Mean: 0.986997 (18.860dB)
x265 [info]: frame P:    146, Avg QP:19.90  kb/s: 10640.33  PSNR Mean: Y:48.577 U:50.757 V:53.081  SSIM Mean: 0.984943 (18.223dB)
x265 [info]: frame B:    604, Avg QP:25.71  kb/s: 1256.31   PSNR Mean: Y:47.811 U:50.450 V:53.134  SSIM Mean: 0.982041 (17.457dB)
x265 [info]: Weighted P-Frames: Y:1.4% UV:1.4%
x265 [info]: Weighted B-Frames: Y:2.5% UV:2.2%
x265 [info]: consecutive B-frames: 8.3% 2.6% 12.8% 17.9% 8.3% 39.7% 1.9% 5.1% 3.2% 
encoded 760 frames in 0:07:16.98 (1.74 fps), 3384.99 kb/s, Avg QP:24.50, Global PSNR: 48.976, SSIM Mean Y: 0.9826636 (17.610 dB)

Start:    11:32:33 AM
End:      11:39:51 AM
Duration: 00:07:17

----------------------- Video encoding chunk 2 -----------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\FrameServer\AviSynth\AviSynth.dll -trim=760,1519 -y4mp "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod.avs" | C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Encoders\x265\x265.exe --frames 760 --crf 20 --preset slower --output-depth 10 --aq-mode 3 --aq-strength 0.6 --ssim --psnr --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --deblock -1:-1 --y4m --output "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc" -

avs2pipemod[info]: invoking Trim ...
avs2pipemod[info]: writing 760 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
y4m  [info]: 1920x1080 fps 24000/1001 i420p8 unknown frame count
raw  [info]: output file: D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc
x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --psnr used with psy on: results will be invalid!
x265 [warning]: --tune psnr should be used if attempting to benchmark psnr!
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 3 inter / 3 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 4 / 4
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 40 / 8 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 5 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 3 / 0.6 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rect amp limit-modes rd=6 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 limit-tu=4 signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing deblock(tC=-1:B=-1) sao
avs2pipemod[info]: finished, wrote 760 frames [100%].
avs2pipemod[info]: total elapsed time is 437.614 sec.
x265 [info]: frame I:     14, Avg QP:18.70  kb/s: 26337.28  PSNR Mean: Y:47.523 U:46.828 V:50.546  SSIM Mean: 0.984612 (18.128dB)
x265 [info]: frame P:    137, Avg QP:20.19  kb/s: 12008.50  PSNR Mean: Y:46.159 U:46.907 V:50.563  SSIM Mean: 0.980379 (17.073dB)
x265 [info]: frame B:    609, Avg QP:25.30  kb/s: 1476.14   PSNR Mean: Y:45.160 U:46.577 V:50.275  SSIM Mean: 0.977648 (16.507dB)
x265 [info]: Weighted P-Frames: Y:0.0% UV:0.0%
x265 [info]: Weighted B-Frames: Y:0.0% UV:0.0%
x265 [info]: consecutive B-frames: 9.9% 1.3% 11.3% 11.3% 9.3% 44.4% 4.6% 4.6% 3.3% 
encoded 760 frames in 0:07:35.62 (1.67 fps), 3832.71 kb/s, Avg QP:24.26, Global PSNR: 46.160, SSIM Mean Y: 0.9782688 (16.629 dB)

Start:    11:32:33 AM
End:      11:40:09 AM
Duration: 00:07:36

**Comment by Dendraspis** [comment] 2021-01-17 19:30
Both log parts look good. What about the parts ***after*** the *Video encoding chunk 2* section ?

**Comment by apophis906** [comment] 2021-01-17 20:17
> Both log parts look good. What about the parts _**after**_ the _Video encoding chunk 2_ section ?

That is what got me. They both look fine on input into x265. Just that if you look at the direct input one you can see that the I,P,&B frames and bitrate are identical with both chunks. Compared to the avs3pipemod one that they differ like they should.

Rest of the log for direct input
---------------------------- Muxing to MKV ----------------------------

mkvmerge 52

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Support\MKVToolNix\mkvmerge.exe -o "D:\Backup\test\iZombie test_new direct.mkv" "D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc" + "D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc" --ui-language en

mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
'D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
'D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
No append mapping was given for the file no. 1 ('D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc'). A default mapping of 1:0:0:0 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
The file 'D:\Backup\test\iZombie test_new direct.mkv' has been opened for writing.
Appending track 0 from file no. 1 ('D:\Backup\test\iZombie test_temp\iZombie test_new direct_out_chunk2.hevc') to track 0 from file no. 0 ('D:\Backup\test\iZombie test_temp\iZombie test_new direct_out.hevc').
The cue entries (the index) are being written...
Multiplexing took 0 seconds.

Start:    11:32:31 AM
End:      11:32:31 AM
Duration: 00:00:00

General
Complete name            : D:\Backup\test\iZombie test_new direct.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 25.6 MiB
Duration                 : 1 min 3 s
Overall bit rate         : 3 389 kb/s
Encoded date             : UTC 2021-01-17 16:32:31
Writing application      : mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
Writing library          : libebml v1.4.1 + libmatroska v1.6.2

Video
ID                       : 1
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main 10@L4@Main
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 1 min 3 s
Bit rate                 : 3 386 kb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 10 bits
Bits/(Pixel*Frame)       : 0.068
Stream size              : 25.6 MiB (100%)
Writing library          : x265 3.4+55+1-2e0a870f0:[DJATOM's Mod][Windows][GCC 10.2.1][64 bit] 10bit
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

---------------------------- Job Complete ----------------------------

Start:    11:25:11 AM
End:      11:32:31 AM
Duration: 00:07:20

Rest of log for avs2pipemod
---------------------------- Muxing to MKV ----------------------------

mkvmerge 52

C:\Users\William\Downloads\StaxRip-x64-2.1.7.2\Apps\Support\MKVToolNix\mkvmerge.exe -o "D:\Backup\test\iZombie test_new avs2pipemod.mkv" "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc" + "D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc" --ui-language en

mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
'D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
'D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
'D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
No append mapping was given for the file no. 1 ('D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc'). A default mapping of 1:0:0:0 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
The file 'D:\Backup\test\iZombie test_new avs2pipemod.mkv' has been opened for writing.
Appending track 0 from file no. 1 ('D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out_chunk2.hevc') to track 0 from file no. 0 ('D:\Backup\test\iZombie test_temp\iZombie test_new avs2pipemod_out.hevc').
The cue entries (the index) are being written...
Multiplexing took 0 seconds.

Start:    11:40:10 AM
End:      11:40:10 AM
Duration: 00:00:00

General
Complete name            : D:\Backup\test\iZombie test_new avs2pipemod.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 27.3 MiB
Duration                 : 1 min 3 s
Overall bit rate         : 3 613 kb/s
Encoded date             : UTC 2021-01-17 16:40:10
Writing application      : mkvmerge v52.0.0 ('Secret For The Mad') 64-bit
Writing library          : libebml v1.4.1 + libmatroska v1.6.2

Video
ID                       : 1
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main 10@L4@Main
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 1 min 3 s
Bit rate                 : 3 610 kb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 10 bits
Bits/(Pixel*Frame)       : 0.073
Stream size              : 27.3 MiB (100%)
Writing library          : x265 3.4+55+1-2e0a870f0:[DJATOM's Mod][Windows][GCC 10.2.1][64 bit] 10bit
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

---------------------------- Job Complete ----------------------------

Start:    11:32:32 AM
End:      11:40:10 AM
Duration: 00:07:37

**Comment by Dendraspis** [comment] 2021-01-17 20:30
Both look the same and it should produce the same result - if ``seek`` works inside x265.

Is  it possible to upload the source file? We did some testings a few days ago and it worked for us, so maybe your source is causing it accidentally.

@44vince44 , @JJKylee 
Are you with me?
I'm curious if this because of the new x265 version !?!

**Comment by 44vince44** [comment] 2021-01-17 20:36
@Dendraspis maybe latest x265 build does not seek inside avs/vpy ?

**Comment by Patman86** [comment] 2021-01-17 20:38
I've tested it on my latest build (including a Memory Leak Fix from @DJATOM) and it works with no issues.

**Comment by 44vince44** [comment] 2021-01-17 20:44
@Patman86 

> I've tested it on my latest build (including a Memory Leak Fix from @DJATOM) and it works with no issues.

I only wish you shared your build with use 😢 It's not in your repository...

**Comment by Patman86** [comment] 2021-01-17 20:49
> @Patman86
> 
> > I've tested it on my latest build (including a Memory Leak Fix from @DJATOM) and it works with no issues.
> 
> I only wish you shared your build with use 😢 It's not in your repository...

Online 😁

**Comment by 44vince44** [comment] 2021-01-17 20:51
My tests confirm the following:

@Dendraspis please can you flag this as a TOOL issue
@DJATOM it appears the avs seeking feature is not yet committed in your project

While waiting the so much awaited build of @Patman86, I tested beta v2.1.7.2 with a x265 build made by @Patman86 and it did work correctly (confirming what @Patman86 said)

**Comment by Dendraspis** [comment] 2021-01-17 21:04
@Patman86
> Online 😁

Too late!  😋 

I was wondering why there was no "Patman" listed in the x265 header... 🤔

**Comment by Patman86** [comment] 2021-01-17 21:07
> @Patman86
> 
> > Online 😁
> 
> Too late! 😋
> 
> I was wondering why there was no "Patman" listed in the x265 header... 🤔

For the next stable 😜

**Comment by DJATOM** [comment] 2021-01-17 21:12
Sure, will add avs seeking into next build.
I did some development today. My local copy now can load vapoursynth from external location, pick certain output from script and and manually override parallel requests (with constraint on maximum allowed threads from vapoursyth - should be useful for debugging, but might come in handy with "easy" scripts). 
The syntax is `--reader-options output=1;library=C:\vs-r52.1-portable\VSScript.dll;requests=24`. 
Now I'm going to watch some ongoing animes and sleep, planning to make new release tomorrow.

**Comment by 44vince44** [comment] 2021-01-17 21:14
@DJATOM enjoy your animes and your night !

**Comment by apophis906** [comment] 2021-01-17 21:27
> @apophis906 : get x265M-3.4+36-5239276dd-x64-gcc10.2.0 from Patman86's repository (https://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip_Tools) then replace x265.exe of Staxrip, edit version when asked to.

I just finished a test with it and it came out correct with different parts for each chunk like expected.

**Comment by Dendraspis** [comment] 2021-01-17 22:11
@apophis906 
Thanks for your feedback.  So you can use it like @44vince44 already mentioned and I think the next beta has a proper running x265 build with all features .... again. ☺️ 

@Patman86 
Would be really appreciated.  😉  Thanks for that!

@44vince44 
Thanks for your help!  👍 

@DJATOM 
Thanks for your fast response and support.

**Comment by JJKylee** [comment] 2021-01-17 23:49
Guys, all this was happening while I was outside. Good to hear that the issue is finally taken care of. 😄

**Comment by 44vince44** [comment] 2021-01-18 08:04
@DJATOM would you be so kind as to look at this as well, maybe before building, because it is also related to avs input:
https://github.com/staxrip/staxrip/issues/456

**Comment by DJATOM** [comment] 2021-01-18 17:39
New release is out.

**Comment by 44vince44** [comment] 2021-01-18 18:13
And is working perfectly ;-)  Many, many thanks !

**Closed** 2021-01-18 22:13 UTC
Labels: added/fixed/done, bug, priority high, tool issue
