### ISSUE TITLE
VapourSynth SAR bug with Batch Encodes

### ISSUE THREAD

**Issue by pianistrevor** [staxrip/staxrip#428] opened 2021-01-09 08:12 UTC
Tried with custom template and default "Manual Workflow" template (using VapourSynth instead of AviSynth)

I haven't tested AviSynth yet, but when I crop a video in VapourSynth workflow and add files by batch, it creates a very obviously incorrect SAR (I tested an episode of the Flintstones, in BluRay 1920x1080 progressive video, and when I cropped it became SAR 3:4. Chilling Adventures of Sabrina had the same problem - became 135:109)

Both these progressive inputs should be 1:1, I've checked the MediaInfo flags. And when I load the project file (after the encode begins) and analyze the values, the DAR, PAR, and SAR are all correct. Hitting "Next" and starting the encode again fixes the problem, so it seems to be a problem with adding files via batch.

Tested in 2.1.7.0 Stable. Did not notice this in 2.1.6.0 stable.

**Comment by Patman86** [comment] 2021-01-09 08:43
Did you check the box below?

![image](https://user-images.githubusercontent.com/54327252/104087287-ec4ffa80-525e-11eb-9bd7-be5338056faf.png)

If not, do this and test again.

**Comment by pianistrevor** [comment] 2021-01-09 17:12
I tried this, which didn't fix it. This isn't a cropping issue - it's a Storage Aspect Ratio issue. Cropping was correct, but the program is adjusting _width_ when cropping, creating a weird SAR.

**Comment by 44vince44** [comment] 2021-01-09 21:20
can you please post a log file.
storage aspect ratio is actually W divided by H. it has absolutely no meaning. so i don't know why it's a problem...
the meaningful values that can affect image are PAR or DAR.

**Comment by pianistrevor** [comment] 2021-01-10 04:36
![Screenshot (65)](https://user-images.githubusercontent.com/31118933/104114490-e0455680-52b9-11eb-9285-1955bfafe6eb.png)
![Screenshot (66)](https://user-images.githubusercontent.com/31118933/104114491-e0dded00-52b9-11eb-9cbf-e2f90f8fd731.png)

[S02E11. Chapter Thirty-One꞉ The Weird_new.txt](https://github.com/staxrip/staxrip/files/5792230/S02E11.Chapter.Thirty-One.The.Weird_new.txt)
[S02E11. Chapter Thirty-One꞉ The Weird_new_staxrip.log](https://github.com/staxrip/staxrip/files/5792231/S02E11.Chapter.Thirty-One.The.Weird_new_staxrip.log)
![Screenshot (67)](https://user-images.githubusercontent.com/31118933/104114523-3d410c80-52ba-11eb-8ef7-7349f91a8a4a.png)
![Screenshot (68)](https://user-images.githubusercontent.com/31118933/104114524-3e723980-52ba-11eb-860a-6cd3e06060be.png)
![Screenshot (69)](https://user-images.githubusercontent.com/31118933/104114525-3e723980-52ba-11eb-9e44-07b22dda2aaf.png)

Should be everything you need. Notice that the project file, after loading the .srip file AFTER THE BATCH ENCODE started, it correctly calculates the SAR and DAR.

**Comment by 44vince44** [comment] 2021-01-10 07:52
Ok, first, about your sar and SAR:
"SAR" in the UI means STORAGE aspect ratio
"sar"  in x265 command line means sample aspect ratio, it means pixel aspect ratio "PAR" of the UI.
That's right: x265's "sar" = Staxrip's "PAR" 

This is the x265 command line detail of your encode:
`D:\StaxRip\Apps\Encoders\x265\x265.exe --crf 21 --profile main10 --output-depth 10 --rd 4 --rskip 0 --limit-refs 0 --rdoq-level 1 --psy-rdoq 1 --refine-mv 1 --rect --b-intra --aq-mode 3 --aq-motion --subme 5 --me star --max-merge 5 --bframes 8 --rc-lookahead 80 --lookahead-slices 4 --scenecut-bias 0.05 --ref 4 --max-luma 1023 --sar 135:109 --selective-sao 0 --no-sao --output "D:\Blu-Ray Remuxes\Chilling\S02E11. Chapter Thirty-One꞉ The Weird_temp\S02E11. Chapter Thirty-One꞉ The Weird_new_out.hevc" "D:\Blu-Ray Remuxes\Chilling\S02E11. Chapter Thirty-One꞉ The Weird_temp\S02E11. Chapter Thirty-One꞉ The Weird_new.vpy"`

The issue here is why is --sar 135:109 appearing in the command line code?

As a general rule, when doing batch operations with automated modifiers, you need to lock some things.
Here is what I suggest:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/104117365-75336880-5329-11eb-9c84-b640c9f397c9.jpg)

Use this setting in your template when doing batch encodes, Always.

**Comment by pianistrevor** [comment] 2021-01-10 09:40
Thank you for the help!

Yes, I was aware that x265 was inserting an ungodly PAR and thus creating an ungodly SAR.

Second, while I agree that locking things for batch encodes makes sense, it would make sense that not entering values for Target PAR would default to 1:1. It's a thought.

Third, I disabled the second of the two earlier and that didn't fix it. Unchecking the first one, however, did fix it. I don't remember checking that box manually, but it makes sense that I wouldn't want to use ITU for non-DVD material.

**Comment by 44vince44** [comment] 2021-01-10 09:51
@pianistrevor 
You're welcome! I was glad to help.

This is not a bug: see, when you crop your video, Staxrip doesn't know what to do with the metadata because it doesn't know why you are cropping.
So it is a requirement to lock at least one of those inter-dependant parameters. The logical one to lock is target PAR = 1.
Of course, if you don't crop, there is no reason for any thing to go wrong.

I suggest you close this thread now!

**Comment by stax76** [comment] 2021-01-10 22:18
I'm not sure if I understand it correctly, pianistrevor has cropped by manually writing vapoursynth crop code with known crop values?

The most common way is enabling the crop filter and enter the known crop values under:

Options > Image > Crop

**Comment by pianistrevor** [comment] 2021-01-10 22:26
No - I used AutoCrop 2.1.0.0, and it puts the values into the .vpy script.

**Comment by stax76** [comment] 2021-01-10 22:42
But then I don't understand why the AR must be defined/locked manually.

**Comment by stax76** [comment] 2021-01-10 22:54
I've tried it now and can reproduce it.

**Comment by stax76** [comment] 2021-01-11 02:59
It was a regression that happened 3 days ago:

https://forum.doom9.org/showthread.php?p=1932823#post1932823

**Closed** 2021-01-11 07:23 UTC
Labels: added/fixed/done, bug, priority low
