### ISSUE TITLE
MCTemporalDenoise (There is no function named 'addgrainC') on Low and Very Low settings

### ISSUE THREAD

**Issue by fa1rid** [staxrip/staxrip#1401] opened 2024-06-19 01:45 UTC
When using the Denoise Filter "MCTemporalDenoise" and setting it to "Low" or "VERY LOW" the below error appear. "Medium" and above are not affected by the problem.

MCTemporalDenoise(settings="low")

```
Script error: There is no function named 'addgrainC'.
(J:\Apps\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\GradFun2DB\GradFun2DBmod.avsi, line 300)
(J:\Apps\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\MCTemporalDenoise\MCTemporalDenoise.avsi, line 1103)
(J:\Apps\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\MCTemporalDenoise\MCTemporalDenoise.avsi, line 1121)
(G:\The Message\The.Message_temp\The.Message_c2.avs, line 40)
```

![image](https://github.com/staxrip/staxrip/assets/6115961/475eb9bd-7eb9-4db4-8583-d31a477df9e0)

**Comment by Dendraspis** [comment] 2024-06-19 05:36
Please check out `v2.41` and tell me the exact filter call as I can't reproduce it here.

`MCTemporalDenoise(settings="very low")` works without issues.

**Comment by fa1rid** [comment] 2024-06-19 09:41
I tried v2.39.3 and it doesn't have any issue.
v2.41 shows the same error as v2.40.

I tried to use different video file with different resolution and framerate I get the below error instead:

![image](https://github.com/staxrip/staxrip/assets/6115961/7c8e4cb7-e143-468c-8ec5-863a0a1832af)

I'm getting mixed results based on the input video resolution/format and when adding copping/cutting filters.


### Test
Below is a 60 seconds sample video that was generated using ffmpeg. The same video is used in different staxrip versions:

![image](https://github.com/staxrip/staxrip/assets/6115961/46df8840-2a65-4f49-99bf-cd97fd64bb92)

![image](https://github.com/staxrip/staxrip/assets/6115961/5ee405ed-74f5-4979-95f9-8df482e7a06a)

Here's the video file:
https://github.com/staxrip/staxrip/assets/6115961/87947e6a-3f93-42dc-b645-851706ee6ebb

Command used to generate the video:
```
ffmpeg -f lavfi -i color=c=white:s=1920x1080:r=30:d=60 -vf "drawtext=fontfile=./fonts/consola.ttf:text='%{n}':fontcolor=black:fontsize=150:x=(w-text_w)/2:y=h/2-80,drawtext=fontfile=./fonts/consola.ttf:text='%{pts\:hms}':fontcolor=black:fontsize=120:x=(w-text_w)/2:y=h/2+80,drawbox=y=0:color=black@1:width=iw:height=140:t=fill,drawbox=y=ih-140:color=black@1:width=iw:height=140:t=fill" -c:v libx264 -t 60 -pix_fmt yuv420p -preset slower -profile:v high -level:v 4.0 -crf 20 Frames-letterbox-60s.mp4
```

**Comment by Dendraspis** [comment] 2024-06-19 11:41
Okay, I was able to reproduce it and it will be fixed with the next release....

**Comment by fa1rid** [comment] 2024-06-19 16:06
so what is the cause of these issues? why only Low and very low?

How about MOD4 clip issue?

**Comment by Dendraspis** [comment] 2024-06-19 17:04
Different settings require different requirements.

> How about MOD4 clip issue?

The filter requires the video to be MOD4, so you have to crop 2px less or more to get that.

**Closed** 2024-06-23 06:38 UTC
Labels: bug  :bug:, added/fixed/done
