### ISSUE TITLE
Problem with umlauts

### ISSUE THREAD

**Issue by Mister-XY** [staxrip/staxrip#456] opened 2021-01-17 17:13 UTC
Hello, I found an error, namely, if I have not installed Avisynth and there are umlauts in the name, then the video is not encoded and breaks off with an error message.
But if I make an ae oe ue out of an ä ö ü, then he encodes the videos.

```
Error Video encoding (2.1.7.2)

Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 19.9 --profile main10 --output-depth 10 --hist-threshold 0.01 --sar 12:11 --output "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc" "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [error]: Error loading file: Import: couldn't open "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"
x265 [error]: unable to open input file <E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs>

StaxRip.ErrorAbortException: Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 x265 3.4+56 aMod gcc10.2.1 msg7086/DJATOM

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 19.9 --profile main10 --output-depth 10 --hist-threshold 0.01 --sar 12:11 --output "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc" "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [error]: Error loading file: Import: couldn't open "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"
x265 [error]: unable to open input file <E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs>


   bei StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:Zeile 374.
   bei StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 79.
   bei StaxRip.x265Enc.Encode() in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 43.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 317.
```

**Comment by 44vince44** [comment] 2021-01-17 21:49
I confirm this in the same context (but now I'm using Patman86 latest x265M gcc build):

-uninstalled Avisynth from my system
-tried to process a file with umlauts, OR accented characters, AVS,  NO PIPE

    ===> Result: **failed** with same error mentioned in post above

- If I remove the umlauts/accented characters, the encode **works**

- If I keep the umlauts/accented characters, no Avisynth on the computer, use AVS2PIPEMOD, the encode **works**
- If I keep the umlauts/accented characters, use VPY , NO-PIPE the encode **works**

Cannot test yet if installing Avisynth on the system will work (the file Devil.dll of System32 is locked by a currently running long encode)

(Of course, my settings are set to use internal Avisynth all the time)

**Comment by stax76** [comment] 2021-01-17 22:03
It looks like a text encoding bug in builds by @DJATOM and @Patman86, at the moment the error happened I checked the script encoding with VS Code, and it was CP1252 like on your and my system and like what x265 should use, so the script was correct.

To workaround this you can do:

x265 Options > Input/Ouput > avs2pipemod

I tested it, and it worked, please confirm that it works.

@DJATOM
@Patman86
@msg7086

I tried both UTF-8 and CP 1252 encoding and neither was working, according to my test there is a bug.

The best possible solution should be enforcing UTF-8 by adding a UTF-8 manifest like x264 did recently:

https://code.videolan.org/videolan/x264/-/blob/master/x264res.manifest

This gives AviSynth full Unicode support.

In Visual Studio:

Visual Studio C++ -> Project -> Properties -> Linker -> Manifest File

mingw:

https://github.com/gpac/gpac/commit/af9bc874c710d3fa1e36c66ce006574d1cd0ac5f
https://github.com/gpac/gpac/commit/39a078f7ff8e27b3dfec86b78f139258251c519b

I made a test, DJATOMs build does not have a manifest according to Resource Hacker, this should mean that it's possible to add an external manifest x265.exe.manifest, so I tried that with a UTF-8 manifest and a UTF-8 script, but it wasn't working, that should mean just adding a manifest is not sufficient, but there is a bug.

**Comment by stax76** [comment] 2021-01-17 22:24
> Cannot test yet if installing Avisynth on the system will work (the file Devil.dll of System32 is locked by a currently running long encode. Maybe DevIL.dll should also have a symlink ? I thought this dll was not used, except for video to image processing)

There should not be a difference, since the last beta release you can install the portable avisynth of staxrip in the system, next to avisynth.dll there is an install.ps1 and uninstall.ps1 script, it does exactly the same what the official installer does.

**Comment by 44vince44** [comment] 2021-01-17 22:29
@stax76 indeed, I've just installed it and the problem is the same.

It seems that the AVS-reader of x265 has problems with the non-ASCII characters... While VPY-reader works perfectly.
@Patman86  any thoughts?

**Comment by Patman86** [comment] 2021-01-17 22:37
> It seems that the **AVS-reader of x265 has problems with the non-ASCII characters**... While VPY-reader works perfectly.
> @Patman86 any thoughts?

I'm looking

**Comment by 44vince44** [comment] 2021-01-17 22:44
@stax76 

> x265 Options > Input/Ouput > avs2pipemod
> I tested it, and it worked, please confirm that it works.

Confirmed (already in my first test)

**Comment by Mister-XY** [comment] 2021-01-18 04:35
`x265 Options > Input/Ouput > avs2pipemod` works, i have tested it.

**Comment by stax76** [comment] 2021-01-18 10:17
Code working in all language configuration can be found here:

https://github.com/staxrip/staxrip/blob/master/FrameServer/AviSynthServer.cpp

and here:

https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/avisynth.c

These were tested by me because they are used in staxrip and mpv.net which both have a UTF-8 manifest since a few weeks. That means on Windows 10 1903 or later UTF-8 is used, on earlier systems the system code page is used because Windows does not know about UTF-8 manifest.

**Comment by 44vince44** [comment] 2021-01-18 17:13
Is this the solution to our problem:
https://github.com/msg7086/x265-Yuuki-Asuna/issues/14

**Comment by JJKylee** [comment] 2021-01-18 18:21
> @stax76 DJATOM has released build x265-x64-v3.4+62-aMod-gcc10.2.1+opt
> This is working with umlauts, and seeking inside AVS is implemented.

Yes. I tested it with a _Korean_ named avs file encoded in UTF-8 on a UTF-8 Korean Windows 10 (codepage 65001), and I see no errors.
Good job, @DJATOM! A million thanks!! 😄

**Comment by Mister-XY** [comment] 2021-01-18 19:05
didn't work for me
```
Error Video encoding (2.1.7.2)

Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 x265-x64-v3.4+62-aMod-gcc10.2.1

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 19.9 --profile main10 --output-depth 10 --hist-threshold 0.01 --sar 12:11 --output "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc" "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [error]: Error loading file: FFVideoSource: Can't open 'E:\BluRay\RIP\Der arme M�llerbursch und das K�tzchen_t03.mkv'
(E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs, line 4)
x265 [error]: unable to open input file <E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs>

StaxRip.ErrorAbortException: Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 x265-x64-v3.4+62-aMod-gcc10.2.1

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 19.9 --profile main10 --output-depth 10 --hist-threshold 0.01 --sar 12:11 --output "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc" "E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [error]: Error loading file: FFVideoSource: Can't open 'E:\BluRay\RIP\Der arme M�llerbursch und das K�tzchen_t03.mkv'
(E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs, line 4)
x265 [error]: unable to open input file <E:\BluRay\Temp\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs>


   bei StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:Zeile 374.
   bei StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 79.
   bei StaxRip.x265Enc.Encode() in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 43.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 317.
```

**Comment by stax76** [comment] 2021-01-18 19:17
I've uploaded a staxrip hotfix.

For the first time we are achieving real long path supported by all important tools, pretty amazing, a few months ago I thought it will never happen.

But the build has to be tested if Umlaute or other ANSI is working on systems prior Windows 10 1903.

**Comment by 44vince44** [comment] 2021-01-18 19:26
I have such a machine (1809) but no access to it right now and for the following 2-3 days due to lock-down. But I will certainly make the test when possible!

**Comment by 44vince44** [comment] 2021-01-18 19:37
@Mister-XY get the hotfix:


See:

```
--------------------------- Video encoding ---------------------------

x265 3.4+62-aMod-gcc10.2.1 DJATOM

"C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 24 --preset slow --output-depth 10 --colorprim bt709 --colormatrix bt709 --transfer bt709 --output "C:\Temp\_StaxRip\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc" "C:\Temp\_StaxRip\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03.avs"

avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [info]: 856x480 fps 1000000/41731 i420p8 frames 0 - 3599 of 3600
raw  [info]: output file: C:\Temp\_StaxRip\Der arme Müllerbursch und das Kätzchen_t03_temp\Der arme Müllerbursch und das Kätzchen_t03_out.hevc
x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-3 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(8 rows)
x265 [warning]: Source height < 720p; disabling lookahead-slices
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 3 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 25 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 4 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-24.0 / 0.60
x265 [info]: tools: rect limit-modes rd=4 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 signhide tmvp strong-intra-smoothing deblock
x265 [info]: tools: sao

```

**Comment by DJATOM** [comment] 2021-01-18 19:43
Probably will not work with older if it silently ignores manifest's directives.
But yeah, test if possible.

**Comment by stax76** [comment] 2021-01-18 20:09
Ideally it would fall back to the CP of the system in that case, I think this works in staxrip, mpv.net and x264.

If it's not supported then Win 7 staxrip users still can pipe with avs2pipemod or ffmpeg.

**Comment by Mister-XY** [comment] 2021-01-19 05:34
Thx, i have download the new Beta and it's look like fine.

**Comment by JJKylee** [comment] 2021-01-19 05:59
Then you may close this issue thread. 😃

**Closed** 2021-01-19 06:59 UTC
Labels: bug, priority high, tool issue

**Comment by Patman86** [comment] 2021-01-21 22:20
So, I managed the manifesto so that it works when compiling with GCC. Unfortunately I am having some compilation problems with MSVC. Here I either get an error message or the manifest is not integrated. The same problem exists with @DJATOM's build.

**Comment by 44vince44** [comment] 2021-01-23 17:06
I confirm that the manifest method fails on Windows 10 previous to 1903:
I have just tested it on a 1809 machine.
So it's as expected...

**Comment by 44vince44** [comment] 2021-01-23 18:35
@Patman86 your latest build works OK with avs direct mode + non ASCII characters in filename 👍 
But there are new additions that DJATOM made and that you haven't synced in your build, like --reader-options library that latest Staxrip uses when encoding in vpy mode.
So it makes your build unusable with Staxrip >= 2.1.7.4 in vpy mode !

**Comment by Patman86** [comment] 2021-01-23 18:42
> @Patman86 your latest build works OK with avs direct mode + non ASCII characters in filename 👍 
> But there are new additions that DJATOM made in his build and that you haven't synced in your build, like --reader-options library that latest Staxrip uses when encoding in vpy mode.
> So it makes your build unusable with Staxrip >= 2.1.7.4 in vpy mode !
> 
> That was just for your information ;-)

I used that part from msg7086 but there is not a extra option for that feature.

**Comment by 44vince44** [comment] 2021-01-23 19:41
@Patman86 you have a point there, and it has surprised me as well.
But then it can be considered as part of the mods that are now a requirement in Staxrip.

Note that this was added very recently in DJATOM build, it may not yet appear in msg7086 commits...

>  Then I use vspipe again ... 😒😒

I hope that's temporary ....

**Comment by msg7086** [comment] 2021-01-23 19:48
I can only port patches when I have some spare time. On the other hand, if any of you did the work, a PR is welcome. Sadly, my new job cost a lot more time than my previous one, so.

**Comment by Patman86** [comment] 2021-01-23 19:51
msg7086 added the feature at 12/31/2020 but without creating an extra option for that.

**Comment by 44vince44** [comment] 2021-01-25 05:00
@Patman86 I saw you remove x265 and x264 builds from your repository.... I'll miss those 😢

**Comment by therealt3nzin** [comment] 2021-01-25 05:26
@44vince44 URL's just changed [x264 - 265](https://www.mediafire.com/folder/arv5xmdqyiczc/x264_-_x265_by_Patman) & [Tools](https://www.mediafire.com/folder/vkt2ckzjvt0qf/Tools_for_StaxRip_by_Patman)

**Comment by Dendraspis** [comment] 2021-01-25 11:17
@44vince44 
Yes and no. My graphics card is definitely broken - tried a lot of cleaning and reassembling, but it's dead. Fortunately I remembered that I own an old Intel with IGP.  😁   So I can use my computer partially, but ***without fun***! Even my cursor is slightly lagging while moving. 😭 
But thanks for asking. 😊

**Comment by 44vince44** [comment] 2021-01-25 13:42
> Even my cursor is slightly lagging while moving

OMG !!!
