### ISSUE TITLE
Seemingly random I/O Exception when deleting files

### ISSUE THREAD

**Issue by HASJ** [staxrip/staxrip#728] opened 2021-06-07 02:22 UTC
**Describe the bug**
Error just pops up when reading or writing files. It might have something to do with `Create job for each selection`.
Right after closing the warning, StaxRip goes to the next file and freezes at 100%.

**Expected behavior**
For there to be no error.

**How to reproduce the issue**
1. Start jobs
2. ???
3. Not sure. Happens at random.

**Provide information**
![image](https://user-images.githubusercontent.com/9345660/120950284-dc104e80-c71c-11eb-8467-48981de02066.png)

- Used StaxRip version
2.6.0

**Comment by HASJ** [comment] 2021-06-07 02:28
Seems to be related to this option:
![image](https://user-images.githubusercontent.com/9345660/120951298-e3d0f280-c71e-11eb-8e65-31cbdbf7fa5c.png)

**Comment by JJKylee** [comment] 2021-06-07 03:54
My experience is a little different. I tried five times with different sources and had a consistent result.

I set `Delete temp files` to `Recycle Bin`. In Preview, I create different jobs based on the selections.

When I start the jobs, I immediately see the same error as #727.

But _encoding jobs start anyway_ and the popup error window becomes inactive and inaccessible once the encoding jobs start.

After the jobs are over, the temp folder _indeed_ moves to the Recycle Bin _unlike @HASJ's case_. And if I click `OK` on the popup error window, I go through the same error reporting process as #727.

But the real problem in this case is that _the cuts are not done the proper way_.

I guess what I experience basically derives from the same bug as #727 that's related to `Preview` and `Trim` code change.

And since I can't observe the same error as @HASJ's, maybe his error is not coming from the `Recycle Bin` setting. My guess is that maybe he clicked the `OK` button of the popup window too quickly...? 🙄❓😅

**Comment by 44vince44** [comment] 2021-06-07 04:49
Yes I'll help for sure, but later if this is not fixed (have work now 😁 )

**Comment by Dendraspis** [comment] 2021-06-07 15:35
I can't reproduce it ... maybe one of you is able to do it?!
It is related to the temp folder deletion. Something prevents the OS from deleting the files, probably an open file. 

@HASJ 
Is it somehow reproducible for you?
If you: create all your jobs, then close all StaxRip instances, open one instance only without start parameters and start the queue. Does it still happen?

**Comment by JJKylee** [comment] 2021-06-07 17:14
First, I need to clarify this:

> But the real problem in this case is that _the cuts are not done the proper way_.
> I guess what I experience basically derives from the same bug as #727 that's related to `Preview` and `Trim` code change.

⇨ My guess was _wrong_. This was because **`mkvmerge` cannot split `flac` files**.

> Splitting tracks of this type (flac) is not supported. (mkvmerge)

My sample file was [this](https://drive.google.com/file/d/1vTzpVTEojE0R0FeUOxK6iBYx7japf-7B/view?usp=sharing). It has `flac` in its audio.

Now I tested with [v2.6.9](https://github.com/staxrip/staxrip/files/6607246/StaxRip_v2.6.9.zip).

Same settings as above: `Recycle Bin` and multi-cut-multi-jobs. But now I re-encode the `flac` audio track to `aac` in order to avoid the issue mentioned right above.

Result: _Everything is OK_. The `temp` folder is removed, no more popup errors, and outputs are in sync.


Now I think this is the situation @HASJ was in. In my first reply, I thought he was talking about some situation _different_ than mine (= a multi-job situation with _multiple source files_) 'cuz this didn't occur to me when the multi-cut-multi-job error window popped up.

> Right after closing the warning, StaxRip goes to the next file and freezes at 100%.

I wasn't able to access the warning window _at all_ in the same situation.

So I think what @Dendraspis said is right.

> Something prevents the OS from deleting the files, probably an open file.

@HASJ, plz confirm if this is the situation you're in. If so, then maybe it's a problem not originating from StaxRip since v2.6.9 seems to have fixed the multi-cut-multi-job issue.

**Comment by HASJ** [comment] 2021-06-08 15:14
Sorry for the delayed response.
I'm on 2.6.9 now.

@Dendraspis @JJKylee Without failure, this error always occurs when the last job in a temp folder is concluded and `Delete temp files` is set to anything but `Disabled`.
Maybe StaxRip is somehow still accessing the temp folder and thus Windows stops it's deletion? Because I can't think of nothing else.
![image](https://user-images.githubusercontent.com/9345660/121206361-c733d800-c84e-11eb-93f4-e2df341e725c.png)
Processing reaches 100% and attempts to delete the files but StaxRip wasn't able to close the processing dialog, resulting in the error? That's what I think is happening.

**Comment by Dendraspis** [comment] 2021-06-08 15:23
> If you: create all your jobs, then close all StaxRip instances, open one instance only without start parameters and start the queue. Does it still happen?

Did you try this?

It also would be nice to have the log file of the last encode.

**Comment by JJKylee** [comment] 2021-06-08 16:09
@HASJ, see if your anti-virus software is stopping StaxRip from deleting the `temp` folder.

**Comment by Dendraspis** [comment] 2021-06-08 16:12
If it's always the last encode while the order doesn't matter, it should be OS related.  Especially because no one here can reproduce it.

But it would be nice to see the log file to see which tools StaxRip started.

**Comment by JJKylee** [comment] 2021-06-08 16:40
@HASJ, I can't understand what the error message in the screenshot means.
Plz use `Copy Message` so that we can _translate_ and understand it.

**Comment by HASJ** [comment] 2021-06-08 22:41
> 
> 
> @HASJ, see if your anti-virus software is stopping StaxRip from deleting the `temp` folder.
> Or make sure you have the _write permission_ on the `target` and `temp` folders.
This started with 2.6.0. Didn't happen before. I don't have an AV.


> In the same vein, I can't understand what the error message in the screenshot means.
> Plz use `Copy Message` or the log itself so that we can _translate_ and understand it.

> O nível de chamada do sistema está incorreto
Translates roughly to...
> The system's call level is incorrect.

@Dendraspis I can't reproduce it reliably. Tenth try, no errors.

**Comment by JJKylee** [comment] 2021-06-09 00:00
> This started with 2.6.0. Didn't happen before. I don't have an AV.

Even if you don't have anti-virus software, Windows still runs internal policies that control IO access of software.
I highly suspect that something other than StaxRip, like some other software or system policy settings change by Windows update, etc., is causing this error, 'cuz no one else here can reproduce the same issue. Hmm... 🤔

If I were you, I'd launch _Windows Event Viewer_ (`eventvwr.msc` on `Win`+`R`) and look into the error events in the past 24 hours. It would help me figure out what went wrong system-wise. Try that too when the error occurs again.

> I can't reproduce it reliably. Tenth try, no errors.

It's a very peculiar and rare case. 😲
As you may know, there's no way we can help without the log, like @Dendraspis pointed out.
Report back **_with the log file_** when the error occurs.

**Comment by 44vince44** [comment] 2021-06-09 07:19
This happened to me in two cases:

- the project is open in another staxrip instance (not encoding)
- mpv.net crashed when doing a preview, but mpvnet.exe process was not killed.

So it is external to Staxrip, and user has to be careful!

**Comment by Dendraspis** [comment] 2021-06-09 07:55
The error message doesn't appear anymore, instructions were not carried out or kept unanswered and we don't get enough information to try to reproduce it with mostly identical settings.

I close it for now.....

**Closed by Dendraspis** 2021-06-09 07:55 UTC
Labels: bug, not reproducible
