### ISSUE TITLE
Cannot do chunked encoding with SVT-AV1

### ISSUE THREAD

**Issue by McMasterGold** [staxrip/staxrip#1136] opened 2023-10-02 15:18 UTC
When trying to encode with more than one chunk using SVT-AV1, I get the following error message:

Error Video encoding chunk 2 (v2.29.0)

Video encoding chunk 2 returned exit code: 1 (0x1)

----------------------- Video encoding chunk 2 -----------------------

SvtAv1EncApp 1.7.0-0+13-b922871f-[Mod-by-Patman]-x64-msvc1937

C:\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -trim=750,1499 -y4mp "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2.avs" | C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf" --frames 750 --rc 0 --crf 38 --progress 2 --preset 4 --irefresh-type 2 --tile-rows 0 --tile-columns 0 --enable-qm 1 --qm-max 9 --qm-min 0 --tune 2

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.7.0-0+13-b922871f [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Aug 29 2023 11:12:17
Svt[info]: -------------------------------------------
avs2pipemod[info]: invoking Trim ...
avs2pipemod[info]: writing 750 frames of 60/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-10bit progressive video.
Error: Invalid parameter '--output' with value 'E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf'
Error in configuration, could not begin encoding! ... 
Run C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --help for a list of options
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 0.012 sec.
avs2pipemod[error]: only wrote 0 of 750 frames.

StaxRip.ErrorAbortException: Video encoding chunk 2 returned exit code: 1 (0x1)

----------------------- Video encoding chunk 2 -----------------------

SvtAv1EncApp 1.7.0-0+13-b922871f-[Mod-by-Patman]-x64-msvc1937

C:\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -trim=750,1499 -y4mp "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2.avs" | C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf" --frames 750 --rc 0 --crf 38 --progress 2 --preset 4 --irefresh-type 2 --tile-rows 0 --tile-columns 0 --enable-qm 1 --qm-max 9 --qm-min 0 --tune 2

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.7.0-0+13-b922871f [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Aug 29 2023 11:12:17
Svt[info]: -------------------------------------------
avs2pipemod[info]: invoking Trim ...
avs2pipemod[info]: writing 750 frames of 60/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-10bit progressive video.
Error: Invalid parameter '--output' with value 'E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf'
Error in configuration, could not begin encoding! ... 
Run C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --help for a list of options
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 0.012 sec.
avs2pipemod[error]: only wrote 0 of 750 frames.

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.SvtAv1Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 74
   at StaxRip.SvtAv1Enc._Closure$__18-0._Lambda$__1() in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 127
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 373

----------

The issue occurs with several video files, amount of chunks (unless set to 1) does not make a difference, and neither does a different container for the output video. I have also tried without any sort of filter.

The log file is here: https://pastebin.com/LwMcwG5b

**Comment by Dendraspis** [comment] 2023-12-11 09:09
Thank you for the report, the log file helped a lot. 👍 

The problem is fixed and will be included in the next release...

**Closed by Dendraspis** 2023-12-11 09:09 UTC
Labels: bug
