### ISSUE TITLE
Subtitle Muxing Breaks MKV Jobs

### ISSUE THREAD

**Issue by NMX12** [staxrip/staxrip#174] opened 2020-04-27 13:14 UTC
When I add subtitles to an MKV-container job the encoding gets all the way to the finish line then comes time to mux everything together I receive this error that fails the whole job which results in no output.

```
**Error (2.0.6.0)

Output file missing

StaxRip.ErrorAbortException: Output file missing
   at StaxRip.Subtitle.Cut(List`1 subtitles) in D:\Projekte\VB\staxrip\General\Misc.vb:line 2002
   at StaxRip.GlobalClass._Closure$__._Lambda$__31-3() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 132
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 138**
```

It's trying to find a system path from someone else's computer.
It's also present in v2.0.8.0.

**Comment by Patman86** [comment] 2020-05-06 11:41
You use the subtitle cut method and added subtitle(s)? Can you share your log file?

**Comment by stax76** [comment] 2020-05-06 12:47
Please fill out this template:

**Describe the bug**
A clear and concise description of what the bug is.


**Expected behavior**
A clear and concise description of what you expected to happen.


**How to reproduce the issue**

Test if the bug happens only with a particular source file or source file type, if so then upload a sample file. If you cannot upload the file then please install the application https://github.com/stax76/MediaInfo.NET and post media info about the source file.

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

1. Go to '...'
2. Click on '...'
3. Using '...' encoder.
4. 'AviSynth or VapourSynth' being used.
5. Filter(s) x is being used.
6. If it's tied to a hardware encoder then post your hardware specs.


**Provide information**

If there is a error message than copy the message if possible, if not then make a screenshot. Ater that search for the log file because it should not only contain the error message but also additional useful debug information. The log file is located in the temp folder and the temp folder is located in the same directory as the source file. The log file ends with _staxrip.log. Visit the wesite pastebin.com and paste the log file content there, use the auto expire feature and set it to one year.


**Notes before posting**
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- If you require help with one of the frame servers, tools or scripting then post in the forums rather then opening a ticket here:
  https://forum.videohelp.com
  https://forum.doom9.org
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is espeically true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.


**Additional context**
Add any other information or additional context that can be helpful.


**Please be as clear and as detailed as possible**

**Comment by NMX12** [comment] 2020-05-07 05:21
@Patman86 @stax76 

https://drive.google.com/open?id=1smjRIAtbCSqrU3QAf-UguYnL1c0KNjMX

Everything you need is in there.

**Comment by Dendraspis** [comment] 2020-05-07 07:10
What happens if you disable *Convert SUP to IDX* ?  🤔

**Comment by NMX12** [comment] 2020-05-07 07:15
@Dendraspis 

Got the same error.

**Comment by Patman86** [comment] 2020-05-07 12:03
THX for the link. I have a look at it and give you a feedback.

**Comment by stax76** [comment] 2020-05-07 15:07
Looks clearly like a broken MKV file.

------------------ Demux MKV using mkvextract 44.0.0 ------------------

C:\Users\NMX7\Downloads\2.0.8.0\Apps\Support\MKVToolNix\mkvextract.exe "C:\Users\NMX7\ToRunThrough\**Heaven Sent.mkv**" tracks 0:"C:\Users\NMX7\ToRunThrough\Heaven Sent_temp\Heaven Sent ID1 English" 1:"C:\Users\NMX7\ToRunThrough\Heaven Sent_temp\Heaven Sent ID1 -1396ms English.mp2" --ui-language en

Error: (mkvextract) The file 'C:\Users\NMX7\ToRunThrough\**Heaven Sent.mkv**' could not be opened for reading: **Not a valid Matroska file (no EBML head found)**.

**Closed** 2020-05-07 15:10 UTC
Labels: not an issue
