### ISSUE TITLE
Incorrect playback of frames in some players

### ISSUE THREAD

**Issue by bron101** [staxrip/staxrip#1177] opened 2024-01-05 14:34 UTC
**Describe the bug**
When I encode any video in h264(CPU) it provides some glitches in VirtualDub playback and it freezes in Telegram (Android), Instagram etc. Built in Win11 video player,MPC-BE, Telegram desktop  plays it perfectly.
It starts with version higher than 2.13.0

**How to reproduce the issue**
1.StaxRip higher than  v2.13.0 (2.31.0 too)
2.Any format video
3. Encode to h264
4. Play it in VirtualDub
or
5. Save this glitches video in VirtualDub to h264
7.Play it with ANY player and it glitches 

**Provide information**
I have recorded a video of glitch with frames.  https://youtu.be/ZmQXmHK1_PA 
After editing the video in VirtualDub it starts playing with such glitches in all players. Any videos encoded in version 2.13.0 work everywhere perfectly without frame glitches

**Comment by Dendraspis** [comment] 2024-01-05 16:59
If it's just that short clip, it would be better to share it with me and also the encoder settings. And which encoder did you use? And which filters? Can you share the log file? Does it also occurs to other video files with another media type and/or resolution?

Latest release of VirtualDub was in 2014, right?

Sadly I can't reproduce it due to lack of information.  😕

**Comment by bron101** [comment] 2024-01-05 17:52
I'm sorry it's VirtualDub2 https://sourceforge.net/projects/vdfiltermod/ 2020 latest version
I used same QTGMC profiles

AssumeTFF()
QTGMC(preset="Slow", InputType=0, sourceMatch=3, sharpness=0.2, tr2=2, Lossless=2, ediThreads=8)

I couldn't attach the files here. Here's the link to all the files. https://we.tl/t-meV0zR3zI0 Just 70mb. Original file, QTGMC profile, logs

![Снимок экрана 2024-01-05 205023](https://github.com/staxrip/staxrip/assets/23642084/3d95417f-0ba2-4b1b-9ae1-dade0010b88b)

**Comment by Dendraspis** [comment] 2024-01-05 19:09
Okay, I made a quick test and opened your video file, used  your filters and `x264` with your settings - audio was removed.
None of my players has an issue with the outcome, including `VirtualDub2`.

***But:***
Recently I've implemented a small feature to check if the encode was done completely and it has written to your log file:
```
--------------------------- Frame Mismatch ---------------------------
WARNING: Target file has 532 frames, but should have 536 frames!
Encoding was terminated at 99,3%!
```

So there is definitely an issue at least with that encode, but it must be on your side.
Please try another version of `x264` or another encoder. Maybe re-doing the encode after a system restart will help...

But there seems to be nothing I can do.  😕 

https://github.com/staxrip/staxrip/assets/50659978/15577dce-7f82-4d40-89f3-24d1c9fe3981

**Comment by bron101** [comment] 2024-01-05 19:22
Thanks for the answer. I just learned how to use Stax for my needs and download new versions. Why there is no the warning in 2.13 and older version? Another version of x264 encoder?  Restart PC and re-encode doesn't work. How to change x264 in 2.31 to 2.13 version?

**Comment by Dendraspis** [comment] 2024-01-05 19:33
> Why there is no the warning in 2.13 and older version?

Which warning do you expect? The encoder signaled that it worked successfully.

> Another version of x264 encoder? 
> How to change x264 in 2.31 to 2.13 version?

Just copy `Apps\Encoders\x264\x264.exe` over or replace it with another build you find on the internet.

**Comment by bron101** [comment] 2024-01-05 19:51
> Which warning do you expect?

```
--------------------------- Frame Mismatch ---------------------------
WARNING: Target file has 532 frames, but should have 536 frames!
Encoding was terminated at 99,3%!
```
There is no same warning in Stax 2.13 log. And Stax just says nothing wrong at the end😁 I don't know if it should or should not show such errors after coding is finished?

> Just copy Apps\Encoders\x264\x264.exe over or replace it with another build you find on the internet.

Thanks! I'll try.

**Comment by Dendraspis** [comment] 2024-01-05 20:01
The **Frame Mismatch** was introduced in `v2.29`.

> And Stax just says nothing wrong at the end.

As already mentioned, the encoder responded with `All good, I finished successfully`.
Nevertheless there will be a **Frame Mismatch** warning in the future, but at first I have to verify the implementation. So for now it's just a note in the log file.

Maybe you could also try to re-download StaxRip in case something went wrong with the download or extraction.

**Comment by bron101** [comment] 2024-01-05 20:40
I just tried another versions of x264, same Frame Mismatch. I re-downloaded StaxRip and nothing. Also with x265 same thing! 

`WARNING: Target file has 532 frames, but should have 536 frames!
Encoding was terminated at 99,3%!
`
But with VCEEnC 264/264 it's all good!

 I can't understand why this problem doesn't appear on  2.13 version

**Comment by Dendraspis** [comment] 2024-01-05 21:04
Very interesting, especially always the same frames.  🥴 
`VCEEncC` uses your GPU for encoding, so there could be an issue with the tools and/or your CPU.

But sadly, as I can't reproduce it and it is definitely no StaxRip issue by itself, I can't do anything more.

**Comment by Dendraspis** [comment] 2024-01-05 22:50
Ok, I might get the reason for your issue:

`RAM        : 7GB`

`QTGMC` can be very RAM hungry, depending on source and settings. So if you run out of RAM, this behavior might happen.

**Comment by bron101** [comment] 2024-01-06 08:24
I don't think memory is the problem. I closed all programs and RAM consumption was up to 70% peak.

**Comment by Dendraspis** [comment] 2024-01-06 11:56
I had several cases where 32GB were not enough to handle 2 filter calls, so it's pretty difficult to say how much is needed to prevent issues. 

But since I used the same source with the same settings, I guess that should be the problem.
I also assume, that it will work for you when you disable/remove the `QTGMC` filter call or choose another filter, that might be less demanding, even the outcome might be different in terms of specifications.

If possible, try to run your encode on another PC with more RAM (16+ GB). If it works, then you have your answer. 

Up to this point I can't help any more, because for me it works fine and StaxRip itself is definitely not the problem.
So I'm closing this issue...

**Closed** 2024-01-06 11:56 UTC
Labels: bug, tool issue, added/fixed/done, not reproducible
