### ISSUE TITLE
Frame Mismatch with wrong assumption

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1315] opened 2024-04-17 10:00 UTC
I have got this in DV profile 5 encode

![image](https://github.com/staxrip/staxrip/assets/34553588/283f62bb-6823-4fb7-859d-76633bc0ac60).

I have created newproject and all StaxRip settings are set to default..

DoVi metadata has been cropped by DoVi_Scripts.bat from here https://github.com/R3S3t9999/DoVi_Scripts/releases

**Comment by madey83** [comment] 2024-04-17 10:07
[_new_staxrip.log](https://github.com/staxrip/staxrip/files/15009335/_new_staxrip.log)

**Comment by madey83** [comment] 2024-04-17 12:23
DoVi metadata has been cropped by DoVi_Scripts.bat from here

Is there a reason why you do that, when StaxRip makes everything for you already?


i get used to do that....

**Comment by madey83** [comment] 2024-04-17 12:51
so far one time issue

**Comment by Dendraspis** [comment] 2024-04-17 14:31
> i get used to do that....

No problem with that in general, but be aware that you might potentially create broken results in case of specific conditions like on your sample above.

**Comment by madey83** [comment] 2024-04-17 15:54
this is first time when i had this issue... My workflow for dovi encode worked even before you where added dovi extract ability...

**Comment by Dendraspis** [comment] 2024-04-17 16:56
That's what I mean. 
But I had enough discussions about the right handling, for example #1280 and #1304, and created a guide with all the necessary information. If you don't care, it's okay for me.

Nevertheless I try to reproduce this issue, but was not able so far. 😕

**Comment by madey83** [comment] 2024-04-17 19:49
so pospond this.. if it will happen again i will try do everything by staxrip

**Comment by Dendraspis** [comment] 2024-04-21 14:44
I still can't reproduce it, but I have added a bit of code to make the check a bit more robust. 

I will close this issue for now, feel free to reopen it when you encounter this issue again - again with a log file, please.

**Closed by Dendraspis** 2024-04-21 14:44 UTC
Labels: bug  :bug:, not reproducible
