### ISSUE TITLE
Demux Audio returned exit code: 1 (0x1)

### ISSUE THREAD

**Issue by kamalhwk** [staxrip/staxrip#810] opened 2021-12-08 17:46 UTC
Error Demux Audio (v2.10.0)

Demux Audio returned exit code: 1 (0x1)

----------------------------- Demux Audio -----------------------------

ffmpeg N-103081-gf7958d0883-x64-gcc10.3.0 Patman

C:\Users\olivetti\Desktop\StaxRip-v2.10.0-x64\StaxRip-v2.10.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i "C:\Users\olivetti\Desktop\MISTER CARATé.ts" -vn -sn -c:a copy "C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1."

[mpeg2video @ 0000000000523c80] Invalid frame dimensions 0x0.
    Last message repeated 17 times
Input #0, mpegts, from 'C:\Users\olivetti\Desktop\MISTER CARATé.ts':
  Duration: 01:51:11.74, start: 18555.767689, bitrate: 4238 kb/s
  Program 700 
    Metadata:
      service_name    : Iqraa
      service_provider: ART
  Program 701 
    Metadata:
      service_name    : Cima
      service_provider: 
  Program 703 
    Metadata:
      service_name    : Hekayat 
      service_provider: JMC
  Program 705 
    Metadata:
      service_name    : Hekayat2
      service_provider: JMC
  Program 706 
    Metadata:
      service_name    : Aflam 1
      service_provider: JMC
  Stream #0:0[0x203]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 704x576 [SAR 12:11 DAR 4:3], 25 fps, 25 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 15000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:1[0x2a8]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2[0x83]: Audio: mp2, 48000 Hz, mono, fltp, 32 kb/s
  Program 708 
    Metadata:
      service_name    : Aflam 2
      service_provider: JMC
  Program 709 
    Metadata:
      service_name    : Cinema
      service_provider: JMC
  Program 713 
    Metadata:
      service_name    : Jordan
      service_provider: ART
  Program 721 
    Metadata:
      service_name    : ARZKR!
      service_provider: JMC
  Program 728 
    Metadata:
      service_name    : Iraq medical
      service_provider: JMC
  Program 730 
    Metadata:
      service_name    : Al-Khabar TV
      service_provider: JMC
  Program 734 
    Metadata:
      service_name    : Almasalah
      service_provider: JMC
  Program 737 
    Metadata:
      service_name    : JORDAN DERETNA
      service_provider: JMC
  Program 738 
    Metadata:
      service_name    : Iraq Now
      service_provider: JMC
  Program 742 
    Metadata:
      service_name    : El FADJR 2
      service_provider: JMC
  Program 766 
    Metadata:
      service_name    : Dijlah Tarab
      service_provider: ART
  Program 790 
    Metadata:
      service_name    : Jordan Radio 
      service_provider: ART
  Program 796 
    Metadata:
      service_name    : Hawa Dijlah Radio
      service_provider: JMC
  Program 798 
    Metadata:
      service_name    : Almamlaka TV
      service_provider: 
  Program 803 
    Metadata:
      service_name    : Zaytouna Radio & TV
      service_provider: JMC
  Program 805 
    Metadata:
      service_name    : a Konoz Alhayat
      service_provider: JMC
  Program 806 
    Metadata:
      service_name    : EL HIKMA TV DZ
      service_provider: JMC
  Program 809 
    Metadata:
      service_name    : kirkuk alan
      service_provider: JMC
  Program 1113 
    Metadata:
      service_name    : Karawan tv
      service_provider: JMC
[NULL @ 00000000005518c0] Unable to find a suitable output format for 'C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1.'
C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1.: Invalid argument

StaxRip.ErrorAbortException: Demux Audio returned exit code: 1 (0x1)

----------------------------- Demux Audio -----------------------------

ffmpeg N-103081-gf7958d0883-x64-gcc10.3.0 Patman

C:\Users\olivetti\Desktop\StaxRip-v2.10.0-x64\StaxRip-v2.10.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i "C:\Users\olivetti\Desktop\MISTER CARATé.ts" -vn -sn -c:a copy "C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1."

[mpeg2video @ 0000000000523c80] Invalid frame dimensions 0x0.
    Last message repeated 17 times
Input #0, mpegts, from 'C:\Users\olivetti\Desktop\MISTER CARATé.ts':
  Duration: 01:51:11.74, start: 18555.767689, bitrate: 4238 kb/s
  Program 700 
    Metadata:
      service_name    : Iqraa
      service_provider: ART
  Program 701 
    Metadata:
      service_name    : Cima
      service_provider: 
  Program 703 
    Metadata:
      service_name    : Hekayat 
      service_provider: JMC
  Program 705 
    Metadata:
      service_name    : Hekayat2
      service_provider: JMC
  Program 706 
    Metadata:
      service_name    : Aflam 1
      service_provider: JMC
  Stream #0:0[0x203]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 704x576 [SAR 12:11 DAR 4:3], 25 fps, 25 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 15000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:1[0x2a8]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2[0x83]: Audio: mp2, 48000 Hz, mono, fltp, 32 kb/s
  Program 708 
    Metadata:
      service_name    : Aflam 2
      service_provider: JMC
  Program 709 
    Metadata:
      service_name    : Cinema
      service_provider: JMC
  Program 713 
    Metadata:
      service_name    : Jordan
      service_provider: ART
  Program 721 
    Metadata:
      service_name    : ARZKR!
      service_provider: JMC
  Program 728 
    Metadata:
      service_name    : Iraq medical
      service_provider: JMC
  Program 730 
    Metadata:
      service_name    : Al-Khabar TV
      service_provider: JMC
  Program 734 
    Metadata:
      service_name    : Almasalah
      service_provider: JMC
  Program 737 
    Metadata:
      service_name    : JORDAN DERETNA
      service_provider: JMC
  Program 738 
    Metadata:
      service_name    : Iraq Now
      service_provider: JMC
  Program 742 
    Metadata:
      service_name    : El FADJR 2
      service_provider: JMC
  Program 766 
    Metadata:
      service_name    : Dijlah Tarab
      service_provider: ART
  Program 790 
    Metadata:
      service_name    : Jordan Radio 
      service_provider: ART
  Program 796 
    Metadata:
      service_name    : Hawa Dijlah Radio
      service_provider: JMC
  Program 798 
    Metadata:
      service_name    : Almamlaka TV
      service_provider: 
  Program 803 
    Metadata:
      service_name    : Zaytouna Radio & TV
      service_provider: JMC
  Program 805 
    Metadata:
      service_name    : a Konoz Alhayat
      service_provider: JMC
  Program 806 
    Metadata:
      service_name    : EL HIKMA TV DZ
      service_provider: JMC
  Program 809 
    Metadata:
      service_name    : kirkuk alan
      service_provider: JMC
  Program 1113 
    Metadata:
      service_name    : Karawan tv
      service_provider: JMC
[NULL @ 00000000005518c0] Unable to find a suitable output format for 'C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1.'
C:\Users\olivetti\Desktop\MISTER CARATé_temp\ID1.: Invalid argument

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.ffmpegDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj, Boolean overrideExisting) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 386
   at StaxRip.ffmpegDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 301
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3411
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2214

**Comment by Dendraspis** [comment] 2022-03-22 09:14
Sadly (or luckily) I cannot reproduce this issue with my TS files.
Du to missing information about the source and the given settings, I cannot help at that point. And because this issue is that old, I'll close it for now. Feel free to re-open it when you can provide further information, for example the whole log file. A short sample could also be very helpful.

**Closed by Dendraspis** 2022-03-22 09:14 UTC
Labels: bug, not reproducible
