### ISSUE TITLE
Synthesis of issues discovered while investigating the Turkish locale issue

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#543] opened 2021-02-25 07:28 UTC
**Intro**
This thread is to follow up all matters that have been exposed when using a turkish locale. please follow up here instead of discussions.

For reference, the discussion is https://github.com/staxrip/staxrip/discussions/487

**Context**
While using a Turkish locale computer, @darkcity87 reported a bug with AviSynth. Then @stax76 and @JJKylee intervened.

## Actions (taken and STILL TO TAKE)

1) @stax76 corrected caps problem with Turkish locale with this commit https://github.com/staxrip/staxrip/commit/c79cef12e35ad3bb83bc6328be8fe8b74ebefd5c

2) After that commit, @darkcity87 still got a problem with  QTGMC with Repair that would NOT work, because the required plugin plugins_JPSDR.dll doesn't load. But when he edited inside  QTGMC.avsi the word ''NNEDI3" and changed it to "nnedi3" then plugin_JPSDR.dll loaded and QTGMC worked OK. So that means that there is still something to investigate. Read more here:
https://github.com/staxrip/staxrip/discussions/487#discussioncomment-403649

- **Action Required => please investigate more, the caps problem is still here, or decide to "hack" QTGMC.avsi with the change NNEDI3 -> nnedi3  and consider this closed.**

In the mean time I wrote something on the Doom9 forum for QTGMC https://forum.doom9.org/showthread.php?p=1936696#post1936696

3) At the same time, when investigating SMDegrain, @JJKylee and DavidRyan of Doom9 forum found that MedianBlur2 required UPDATE. here is the link  http://avisynth.nl/index.php/MedianBlur2 EDIT: please find update link at pinterf's page. Click https://github.com/staxrip/staxrip/issues/543#issuecomment-785725119

- **Action Required => please update MedianBlur2**

**Comment by Dendraspis** [comment] 2021-02-25 07:34
> please investigate more, the caps problem is still here.

This might be the point where it starts to be a tool issue.  🤔

**Comment by 44vince44** [comment] 2021-02-25 07:37
Since it's only with QTGMC, we could ask them to fix it ! and the whole issue is closed after we update if they accept to fix)

**Comment by JJKylee** [comment] 2021-02-25 08:45
I think we better download pinterf's mod of MedianBlur2 from [here](https://github.com/pinterf/MedianBlur2/releases).
AviSynth wiki is not yet updated about the most recent version.

**Comment by 44vince44** [comment] 2021-02-25 09:38
Thanks for the link @JJKylee

**Comment by stax76** [comment] 2021-02-25 09:39
I've updated MedianBlur2 locally.

**Comment by 44vince44** [comment] 2021-02-25 09:40
@stax76 What do you suggest for QTGMC ?

**Comment by stax76** [comment] 2021-02-25 12:23
The problem is I cannot reproduce it and also not explain it, but I will definitively further investigate it, and I think it's great that nobody had given up, especially not @darkcity87, and we are making progress.

What I already tried is:

![lang-settings](https://user-images.githubusercontent.com/11410540/109152146-6256e500-776b-11eb-885b-c5f10a6b0de6.png)

That is the dialog where the system code page can be changed, but this did not help to reproduce the problem.

I can also try changing my UI language to Turkish, it's possible in Windows 10 from the settings dialog, did this before with Korean or Russian, but I don't see why that would make a difference. And there are maybe more Turkish settings I can try.

We could also create a doom9 thread, maybe the avisynth devs or power users have an idea.

**Comment by stax76** [comment] 2021-02-25 12:33
What StaxRip version was used by darkcity87? Did he try the last Beta?

**Comment by darkcity87** [comment] 2021-02-25 12:52
@stax76  i use v2183 i updated QTGMC.avci and Zs_RF_Shared.avci

Before update .avci files only repair profiles didnt work after update .avci files all QTGMC profiles didnt work till i change ''NNEDI3" to "nnedi3"

**Comment by stax76** [comment] 2021-02-25 14:34
I've uploaded 2.1.8.4 Beta, please try.

ToLower/ToUpper is replaced with ToLowerInvariant/ToUpperInvariant in the entire application.

https://stackoverflow.com/questions/6225808/string-tolower-and-string-tolowerinvariant

**Comment by darkcity87** [comment] 2021-02-25 15:29
I tested all field and noise filters everything work except SMDegrain its work if i remove ''contrasharp=true''


```
  Script error: There is no function named 'medianblur'.
  (C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 618)
  (C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 545)
  (C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\SMDegrain\SMDegrain.avsi, line 546)
  (D:\v\video_temp\video.avs, line 14)
```

```
AddAutoloadDir("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\FrameServer\AviSynth\plugins")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\DFTTest\dfttest.dll")
Import("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\Dither\dither.avsi")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\Dither\dither.dll")
Import("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\NNEDI3\edi_rpow2.avsi")
Import("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\LSFmod\LSFmod.avsi")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\masktools2\masktools2.dll")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\mvtools2\mvtools2.dll")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\RgTools\RgTools.dll")
Import("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi")
LoadPlugin("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll")
Import("C:\Portable\StaxRip-x64-2.1.8.4-Beta\Apps\Plugins\AVS\SMDegrain\SMDegrain.avsi")
LSMASHVideoSource("D:\v\video.mp4")
SMDegrain(tr=6, thSAD=600, contrasharp=true, refinemotion=true)
```

**Comment by 44vince44** [comment] 2021-02-25 15:54
I'm downlading latest beta.
I have to check the mediablur2, at least if it works on a non localized setup...

**Comment by 44vince44** [comment] 2021-02-25 16:10
@stax76 maybe to reproduce that, you need to enable case sensitivity on the staxrip test folder. this is a feature that is set only on a specific folder, it doesn't affect all the system or disk (fortunately)
Here is a tutorial: https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10

I'm sorry today I barely have time, maybe later I'll help testing that...

**Comment by 44vince44** [comment] 2021-02-25 16:50
@JJKylee apparently the fox for SMDegrain contrasharp = true doesn't work (it's not specific to Turkish) I'm investigating...

**Comment by darkcity87** [comment] 2021-02-25 16:57
@44vince44 @JJKylee 

i notice ''MedianBlur2.dll'' missing in my code if i add ''MedianBlur2.dll'' in manually its working with ''contrasharp=true''

**Comment by JJKylee** [comment] 2021-02-25 17:02
Maybe @stax76 forgot to include the `dll` before _SMDegrain_. 🤔

**Comment by 44vince44** [comment] 2021-02-25 17:07
What dll ? Is there a dll that has to be included. Well, when I load Plugins_JPSDR it works without updating anything, so if the whole thing was JPSDR inclusion ... 🤣

**Comment by JJKylee** [comment] 2021-02-25 17:11
`MedianBlur2.dll` before calling _SMDegrain_. It's a must for `contrasharp=true`.

**Comment by stax76** [comment] 2021-02-25 17:16
staxrip defines MedianBlur and MedianBlurTemporal as filters contained in MedianBlur2.dll, but SMDegrain.avsi does not contain MedianBlur or MedianBlurTemporal

**Comment by 44vince44** [comment] 2021-02-25 17:17
LOL I think i missed that. I'll see if I can pull it myself...

**Comment by 44vince44** [comment] 2021-02-25 17:22
@stax76 it's in the header of the SMDegrain.avsi 😠 

> and medianblur2 now will be used in Minblur instead of Quantile RemoveGrainHD in avs 2.6

**Comment by 44vince44** [comment] 2021-02-25 17:25
![SNAG-0005](https://user-images.githubusercontent.com/17828567/109191821-335a6680-779f-11eb-8dfe-07a0f22bfc96.jpg)

**Comment by stax76** [comment] 2021-02-25 17:29
The script must contain MedianBlur and not MedianBlur2, a MedianBlur2 filter is not known to staxrip.

**Comment by 44vince44** [comment] 2021-02-25 17:31
The dll is called medianblur2.dll

**Comment by darkcity87** [comment] 2021-02-25 17:35
[I see this](https://forum.doom9.org/showthread.php?p=1936668#post1936668)
and add ''MedianBlur2.dll'' in code then it works

**Comment by stax76** [comment] 2021-02-25 17:38
staxrip detect things automatically, nothing is done manually.

How can SMDegrain.avsi use a MedianBlur filter without the string MedianBlur being found in SMDegrain.avsi file?

I don't get it. 😊

**Comment by Dendraspis** [comment] 2021-02-25 17:41
Maybe because it calls another filter, that calls MedianBlur  🤤

**Comment by stax76** [comment] 2021-02-25 17:46
OK, I will fix it.

**Comment by 44vince44** [comment] 2021-02-25 18:01
Since it is EXPLICITLY mentionned in the information header of SMDegrain.avsi, it seems logical that it has to be included 🤣

**Comment by stax76** [comment] 2021-02-25 18:08
I think same problem here:

https://forum.doom9.org/showthread.php?p=1915089&highlight=depends#post1915089

Working currently on a solution for both.

**Comment by stax76** [comment] 2021-02-25 19:13
Hotfix is online.

**Comment by 44vince44** [comment] 2021-02-25 19:16
Thanks @stax76 !!!

**Comment by Dendraspis** [comment] 2021-02-25 19:21
I hope the neverending story ends here.  😔

**Comment by 44vince44** [comment] 2021-02-25 19:30
I have tested SMDegrain and now it WORKS 🚀 

So, if we consider the problem with QTGCM a pure tool issue, maybe we could close this. @stax76 you decide 😄

**Comment by darkcity87** [comment] 2021-02-25 19:44
QTGCM and Turkish Locale issue already fixed with v2.1.8.4. I tested almost every filter all working except SMDegrain.
If SMDegrain also fixed nothing left.

Thanks @stax76 and everyone.

@stax76 can you add code comments for Turkish relevant code like last time if not added yet.

**Comment by stax76** [comment] 2021-02-25 19:45
darkcity87 wrote everythings works except SMDegrain with contrasharp=true, which also works now, so can finally be closed.

**Closed by stax76** 2021-02-25 19:45 UTC
Labels: bug, feature request, information/overview/summary

**Comment by stax76** [comment] 2021-02-25 19:49
@darkcity87 

SMDegrain is fixed in the last hotfix.

> can you add code comments for Turkish relevant code like last time if not added yet

It should not happen again because ToLowerInvariant and ToUpperInvariant is now used everywhere and normal ToLower and ToUpper will not be used again anywhere in the future.

**Comment by JJKylee** [comment] 2021-02-25 21:18
So QTGMC issue can be ignored then. Right? Then can I close the issue I reported on realfinder's GitHub repo now?

**Comment by 44vince44** [comment] 2021-02-25 22:00
I believe you can... for all we know that issue could never be addressed in their repository.  Before closing you could link to the post where Stax76 explains what he did. But I'm sure you've already done it 😁
