### ISSUE TITLE
Duplicate temp folders/file (duplicate source names) causes Source file not to be loaded - no error message or indication of problem

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1514] opened 2024-10-20 14:47 UTC
Reference new issue or related comment in #1512

NVEnc h265 v.2.42.1

NVEncC (x64) 7.66 (r2994) by rigaya, Sep  2 2024 12:52:18 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            AMD Ryzen 9 3950X 16-Core Processor [4.40GHz] (16C/32T)
GPU            #0: NVIDIA GeForce RTX 4060 (3072 cores, 2460 MHz)[PCIe4x8][565.90]
NVENC / CUDA   NVENC API 12.2, CUDA 12.7, schedule mode: auto

Source files that attempt to create a temp folder with the same name as an existing temp file name will prevent StaxRip from loading the new source file.

No warning or explanation is given - StaxRip simply does not load the new file. A Dolby Vision file extracts the RPU/Json file then does not complete the source load. 

The old temp folder must be manually deleted before attempting to load the new source video with a duplicate name. 

Loading "Episode 1.mkv" and re-encoding then attempting to load another source file named "Episode 1.mkv" results in StaxRip not loading the new source file and giving no indication that a problem has occurred - The Main StaxRip dialog reappears blank - nothing loaded.

### Some sort of error message, dialog asking permission to delete the existing temp folder, or automatically delete of the previous duplicate name temp folder needs to be implemented to avoid this problem or inform the user.

Best solution would be to show a dialog asking permission to delete the existing temp folder,

**Comment by Dendraspis** [comment] 2024-10-21 04:31
Does the log file mention an error as there has to be one.

**Comment by noblemd00** [comment] 2024-10-21 18:20
The issue is not that an error occurred - the issue is...

... that NO error is indicated, so, WAS THERE AN ERROR? 
The user is left guessing! 
Guessing that something out of the ordinary happened. 
Guessing what to do to fix the issue!???

The problem occurs so few and far between that the error or even the fact that there was an error is not immediately apparent. 
StaxRip simply shows a blank main screen with nothing filled in (no error indicated - no indication anything wrong happened).

StaxRip needs to, at least, make the user aware that an error occurred and what it was. 
Previously, when duplicate named temp folder paths were used for different source files, StaxRip showed a  "... does not match the source file..." message. NOTE: It did not say what to do to fix the issue - only educated guessing helped fix the problem.

It would be prudent to indicate a possible solution to fix the problem, ("A duplicate named temp file exists...") so the user is not left guessing how to fix.

**_The perfect solution would be for StaxRip to test that the temp folder path already exists and rename (preferably or if absolutely necessary delete) the old temp folder before creating the new temp folder._**

------------------------ Error opening source ------------------------

FFVideoSource: The index does not match the source file
(S:\VidTemp\0201.test.The.Gone.1_temp\0201.test.The.Gone.1_source.avs, line 5)

AddAutoloadDir("U:\StaxRip-x64\Apps\FrameServer\AviSynth\plugins\")

LoadPlugin("U:\StaxRip-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
tcFile = "S:\VidTemp\0201.test.The.Gone.1_temp\0201.test.The.Gone.1_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("S:\Movie.Temp\0201.test.The.Gone.1.mkv", cachefile="S:\VidTemp\0201.test.The.Gone.1_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("S:\Movie.Temp\0201.test.The.Gone.1.mkv", cachefile="S:\VidTemp\0201.test.The.Gone.1_temp\temp.ffindex")

Also, to duplicate the error, the first source file needs to be loaded using a different template from the second source file. 
(at least my tests indicated this is the case)

1. Create 2 source files with the same name.
2. Create 2 templates with the same (Options) temp folder path.
3. Use the first template to encode the first file. 
4. Use the second template and attempt to encode the second file.
5. StaxRip will start to process the second source file then return to a blank Main StaxRip screen as if StaxRip was restarted.

This is StaxRip after the second source file has supposedly loaded...

<img width="619" alt="241021 140327" src="https://github.com/user-attachments/assets/abfd4ea7-5a31-467c-a9a4-e274ebcac725">

**Comment by Dendraspis** [comment] 2024-10-22 12:58
> StaxRip needs to, at least, make the user aware that an error occurred and what it was.

I will have a look...

> Previously, when duplicate named temp folder paths were used for different source files, StaxRip showed a "... does not match the source file..." message.

That also depends on the used source filter.

> The perfect solution would be for StaxRip to test that the temp folder path already exists (dialog asking the user - rename or delete - continue - and) rename/delete the old temp folder before creating the new temp folder.

Definitely not as that could prohibit the chance to prepare data/files for StaxRip. If you want to use the same temp folder you may want to delete the temp files after encoding, otherwise choose individual temp folders or deal with the consequences.


I will see if I can improve the handling...
I have tried multiple times to reproduce this issue under "normal" conditions without success, but I will try to follow your steps.

**Comment by noblemd00** [comment] 2024-10-22 14:06
There has to be a point in the programing that initially creates the _temp folder - a "folder exists test" could be inserted at that point to delete or rename the existing temp folder ((delete/rename existing temp folders option could be a setting - see below).  

Also, there used to be a "delete temp folders after processing" setting (not sure of exact name - see #872) - not there anymore. I searched settings  - don't think I missed it, but possible(?) Adding a RENAME option to the temp folder (DELETE after) setting would be useful. That would retain the folder but not create duplicate folder name interreference.

**Comment by Dendraspis** [comment] 2024-10-22 14:46
> There has to be a point in the programing that initially creates the _temp folder - a "folder exists test" could be inserted at that point to delete or rename the existing temp folder 

No, StaxRip creates the folder if it doesn't exist and then it uses the files in that folder if present - for example Dolby Vision and HDR10+ metadata. If found, they are used and extraction is skipped. Under normal conditions you never run into a situation where a temp folder is used by two (or more) different source files. When you have to specify another location:  Use (dynamic) subfolders!

> Also, there used to be a "delete temp folders after processing" setting [..] - not there anymore.

Seems you have missed it. It was overhauled in `v2.38.0 (2024-04-16)` and moved to Project Options:

<img width=660 src=https://github.com/user-attachments/assets/14dc59de-a20b-4782-8f8f-a749fea6b751>

**Comment by noblemd00** [comment] 2024-10-22 17:23
So, I didn't miss the Temp Files option in Settings because it is now in Project Options! Finally found it - would never have looked there without help!

Request you add an option to keep/rename the temp folder - RENAME (add a number to the name or other simple rename) in the current location - that would allow rapid re-access (rather than having to undelete and all the hassle that entails with finding the proper deleted files in the maze of the recycle bin, plus, eliminating the possibility of accidental erasure by emptying the recycle bin).

----------------------------------------

Under normal circumstances when re-encoding multiple TV episodes there is aways the chance that two TV episodes would be named (for instance) S02E01 Episode 1. 

Happens all the time - I can give you numerous examples of many current and past TV shows that do not have specific episode names and the episode is named for the season/episode number. The format "S##E## Episode ##" is a standard for entertainment databases (TMDB, IMDB, TVMAZE, EIR, TMS, and etc.) to name unnamed TV episodes. These databases are used in almost every downloader program such as SONARR, SABnzbd, and etc.

As an example, one of the most prevalent duplicate episode names are PILOT episodes - named "S01E01 Pilot.mkv" (variable extensions). 

The chances of re-encoding a file when there is an existing temp folder with the same name will happen often enough to require it to be handled.

**Comment by Ding-adong** [comment] 2024-10-22 20:25
Previously, before option moved to project overhaul, if I did a job and then again later with same filename in the same temp folder, staxrip would recognise the temp.ffindex is not compatible and rebuild a new one.

Now with latest version staxrip refuse to load new source file. I have to go into temp folder and delete temp.ffindex file and then staxrip will build new temp.ffindex. The older version does it right and the latest version doesn't. Something changed somewhere.

There is no need to delete temp folder especially if you have new sound file that you want to keep and use for the latest new source file.

**Comment by Dendraspis** [comment] 2024-10-25 16:26
> So, I didn't miss the Temp Files option in Settings because it is now in Project Options! Finally found it - would never have looked there without help!

So you never check the Changelog and/or the Settings and Project Options? 😅  

> Request you add an option to keep/rename the temp folder

Nope, you can define an unique temp folder paths via Project Options.

> Under normal circumstances when re-encoding multiple TV episodes there is aways the chance that two TV episodes would be named (for instance) S02E01 Episode 1.

So in that case the file name is the same, but they have different extensions?
Or do you specify an special temp folder on a specific location?

> As an example, one of the most prevalent duplicate episode names are PILOT episodes - named "S01E01 Pilot.mkv" (variable extensions).

***The future versions will use default temp folders that include the extension of the source file as well. This should also solve your issue then.***

> The chances of re-encoding a file when there is an existing temp folder with the same name will happen often enough to require it to be handled.

All or at least most of the file can be re-used when you open a source file again instead of opening the project file.

> Previously, before option moved to project overhaul, if I did a job and then again later with same filename in the same temp folder, staxrip would recognise the temp.ffindex is not compatible and rebuild a new one.

This has nothing to do with StaxRip - the behaviour hasn't changed. If an index file already exists, it will be used. Of course that may cause issues if the source file, that belongs to that file, has changed meanwhile. Depending on what happens StaxRip can report the issue or the source filter crashes StaxRip.
In such cases you have to delete the index file first or set an dynamic temp folder, so a new temp folder is used every time you open the source file. But for such cases also pay attention to my bold/italic answer above.

**Comment by noblemd00** [comment] 2024-10-26 01:27
> The future versions will use default temp folders that include the extension of the source file as well. This should also solve your issue then.

Not sure what you mean by the above. If this will result in duplicate named temp folders NOT being attempted, then that will fix the problem of two different source files (with the same name) attempting to create a folder with the same temp folder name. 

As attempt to clarify the description of the issue (not sure if my previous description of the issue was clear - hopefully this description is more understandable) ...

Currently, if episode 1 from the show "Paris Has Fallen" (source file named "S01E01 Episode 1.mkv") is encoded and then later an attempt is made to load a source file of episode 1 from the TV show "Last King of the Cross" (also named "S01E01 Episode 1.mkv"), it results in StaxRip attempting to create a duplicate named temp folder. StaxRip proceeds through the initial source loading, but does not complete the source load. StaxRip does not inform the user of a problem. Instead, StaxRip reverts back to the last StaxRip main screen that was in use before the attempt to load the second source file was initiated. 

NOTE this will occur if the previous source temp folder "S01E01 Episode 1_temp" was not deleted or renamed - hence, my reason for requesting an option to auto-rename temp folders. A simple solution to the problem - better than deleting! 

I do not delete the temp folders in case a re-encode problem occurs and delete them later en-mass when certain I'm done with the re-encoding.
***********************************************

When the duplicate temp folder issue occurs, the user is left wondering what happened! 

When the issue occurred 2 weeks ago, In my case, I eventually figured out what happened. Now 2 weeks later the problem occurs again - 2 weeks have passed and I have re-encoded possibly dozens of files without the issue happening. Now, again the StaxRip screen returns and once again I am left wondering for a few moments what has happened. A little faster this time, I eventually realize it is that pesky duplicate name temp folder problem.

Sometimes after this issue occurs, I continue with the re-encode process (not realizing StaxRip reverted to the previous source I re-encoded).

**Comment by Dendraspis** [comment] 2024-10-26 11:00
> Not sure what you mean by the above.

What I meant was:
```
Filename:  \.Source.mkv
Temp Folder NOW:  .\Source_temp\.
Temp Folder NEW:  .\Source.mkv_temp\.
```

> Currently, if episode 1 from the show "Paris Has Fallen" (source file named "S01E01 Episode 1.mkv") is encoded and then later an attempt is made to load a source file of episode 1 from the TV show "Last King of the Cross" (also named "S01E01 Episode 1.mkv"), it results in StaxRip attempting to create a duplicate named temp folder (and using files from the current temp folder).

First StaxRip creates subfolders for the source files, this means the described scenario cannot occur by default because there cannot be 2 `S01E01 Episode 1.mkv` in one folder. So to make this an issue, you have to set a specific Temp Folder Path in Project Options. In that case you have to add an unique identifier to the path to avoid multiple usage of an existing temp folder.

> StaxRip proceeds through the initial source loading, but does not complete the source load. StaxRip does not inform the user of a problem. Instead, StaxRip reverts back to the last StaxRip main screen that was in use before the attempt to load the second source file was initiated.

I still have a look on that....

**Comment by Dendraspis** [comment] 2024-10-26 16:58
- Adding source file extension to temp folder name will be added in `v2.42.2`  ✔️ 
- Fixing not appearing error message when indexing will be added in `v2.42.2` ✔️ 

To avoid the mentioned issues you will still have to use an unique temp folder path like mentioned above.

**Comment by noblemd00** [comment] 2024-10-26 18:45
> First StaxRip creates subfolders for the source files, this means the described scenario cannot occur by default because there cannot be 2 S01E01 Episode 1.mkv in one folder. So to make this an issue, you have to set a specific Temp Folder Path in Project Options. In that case you have to add an unique identifier to the path to avoid multiple usage of an existing temp folder.
<img width="347" alt="241026 132934" src="https://github.com/user-attachments/assets/d3123dac-de28-4589-bf87-147f0104ff1e">

I download (simulated-actually an existing video file) and loaded the first source video (automatically named "S01E01 Episode 1.mkv" - 38.7MB) I drag-n-dropped then encoded the first source file. Note added "First" to the target name - to differentiate the source loaded screens - see after second source initial load). 

<img width="230" alt="241026 134255" src="https://github.com/user-attachments/assets/94703055-93d0-4703-b304-6f626e596b16">

![FirstLoad](https://github.com/user-attachments/assets/64842436-c619-4c02-ba77-1cdf93a3ae6c)

After checking the re-encoded file I delete the FIRST (38.7Mb) "S01E01 Episode 1.mkv" source file.

Later in the day, I download (simulated) another file that is also auto-named "S01E01 Episode 1.mkv" (106 MB) and drag-n-dropped - loaded the SECOND source file "S01E01 Episode 1.mkv" into StaxRip.
 
<img width="216" alt="241026 135421" src="https://github.com/user-attachments/assets/cd051b06-8b43-4da9-b31b-945180b45637">

Note the different MB size - a different video file named "S01E01 Episode 1.mkv"

After the SECOND source file initial load (Processing - Indexing, etc.) - this is the reverted (FIRST) StaxRip Main screen (partial)
<img width="578" alt="241026 135942" src="https://github.com/user-attachments/assets/e6b2fca0-a0f1-4d71-b5bb-88efde0ef5b5">

Note the screen returned to the previous (First source) Main screen after the SECOND source attempted initial processing.

Your adding of the extension to temp folders will only prevent the issue if the two source files have different extensions.

Only manually renaming or (auto/manual) deleting the FIRST source temp folder (or manually/auto deleting some of the temp files) will prevent the issue of same named source files. 
Note: delete = no ability to easily reload - re-encode if needed.

**Comment by Dendraspis** [comment] 2024-10-26 21:21
> After checking the re-encoded file I delete the FIRST (38.7Mb) "S01E01 Episode 1.mkv" source file.

Okay, but in that case this is obviously a handling issue. You delete the source file, but not the belonging temp folder. So in that scenario the mentioned change with the temp folder name won't help you. You have to choose between deleting the temp folder after the encode is finished and/or setting up a unique temp folder name - or you delete the temp folder by hand when you're deleting the source file.

> Note: delete = no ability to easily reload - re-encode if needed.

In order to do that you would also have to demux the video stream - and I would recommend keeping the source file instead. But when you delete the source file, what's the point of keeping some temp files? Re-encoding would not be possible, because the referenced source file doesn't exist anymore.

> For the purpose of easy reloading and re-encoding a RENAMING option (not deleting) the Temp file folder is the best solution.

You can specify a unique temp folder instead. Renaming would not solve your issues as the full paths are used everywhere, means renaming the temp folder will break every reference to a file inside that folder.

> Edit:
Adding an abbreviated date-time code to the _temp folder name could be a solution (???) i.e. 10261521_temp (Oct 26 15:21) - not sure if that would work - the .srip file keeps all the other info - why not the temp folder name (or does it already)?

That's what I was talking about the whole time.  😅   You can also add a random number, for example:
`%source_dir%\%current_date%_%random:4%_%source_name%_temp`

**Comment by noblemd00** [comment] 2024-10-27 12:34
> After checking the re-encoded file I delete the FIRST (38.7Mb) "S01E01 Episode 1.mkv" source file.

> Okay,` but in that case this is obviously a handling issue. You delete the source file, but not the belonging temp folder. So in that scenario the mentioned change with the temp folder name won't help you. You have to choose between deleting the temp folder after the encode is finished and/or setting up a unique temp folder name - or you delete the temp folder by hand when you're deleting the source file.

The issue is not how I handle File names - I know if I restart a .srip file from a temp folder that the original source needs to be in the same location with the same name to reprocess the file. StaxRip will show a missing source message if the original source is not present or misnamed. YES, everything needs to be the same to make changes then re-encode.  

1. I do not delete until I check the re-encode. 
2. If a situation exists where I might need to re-encode the source I either temporarily rename the file or move it to a temp folder for later retrieval/rename to original.
3. When deleting a file on my NAS (my usual download location) a file remains in the recycle bin until a scheduled empty at 5AM. 

The issue is not how the files are temporarily save for later use if needed - the issue is that StaxRip does not work properly if you attempt to re-encode files with the same name without user taking manual steps to prevent (delete or rename) the duplicate folder problem (or settings - delete temp folders). 

A null issue if the below works...

> That's what I was talking about the whole time. 😅 You can also add a random number, for example:
%source_dir%\%current_date%_%random:4%_%source_name%_temp

A slight change to move the temp folder to my high speed NVME drive
S:\vidtemp\%current_date%_%random:4%_%source_name%_temp

Thank you for this info.

Wouldn't it be prudent for StaxRip to do this automatically and therefore avoid duplicate named temp folders?

**Comment by Dendraspis** [comment] 2024-10-27 13:02
> The issue is not how the files are temporarily save for later use if needed - the issue is that StaxRip does not work properly if you attempt to re-encode files with the same name without user taking manual steps to prevent (delete or rename) the duplicate folder problem (or settings - delete temp folders).

But it's part of the intended workflow and offered possibilities. The problem is, that you remove a file from a folder without removing/deleting its belonging temp folder.

> Wouldn't it be prudent for StaxRip to do this automatically and therefore avoid duplicate named temp folders?

No, it would just shift the problems. StaxRip is meant to handle the temp folder that way whereas it offers you the possibility to adjust it for your needs. If you for example don't use separate folders per series, this is the way you have to go.

> A slight change to move the temp folder to my high speed NVME drive
`S:\vidtemp\%current_date%%random:4%%source_name%_temp`

In case you want it a bit shorter you can remove the date and eventually extend the random number to 8 digits:
`S:\vidtemp\%random:8%_%source_name%_temp`

**Comment by noblemd00** [comment] 2024-10-27 14:53
> But it's part of the intended workflow and offered possibilities. The problem is, that you remove a file from a folder without removing/deleting its belonging temp folder.

I am NOT removing files from any folder if it is needed for further use and nothing is being removed from the _temp folder. I am NOT permanently deleting the source file until I know it will not be needed to make changes and re-encode. (see repeated info below). 

TO REPEAT...
The issue is not how I handle File names - I know if I restart a .srip file from a temp folder that the original source needs to be in the same location with the same name to reprocess the file. StaxRip will show a missing source message if the original source is not present or misnamed. YES, everything needs to be the same to make changes then re-encode.

The issue is DUPLICATE TEMP FOLDER NAMES causing an unhandled problem - not anything else. 
I know all about file handling procedures. (see repeated info above.)

That being said... The random number solution seems to work well.

**Comment by Dendraspis** [comment] 2024-11-09 00:42
With `v2.42.2` the temp folder name also includes the source file extension, which solves the issues with 2 source files with identical names, but different file extension. So this part is done.

When it comes to re-using an existing temp folder this won't be altered as it is wanted that the temp folder is predictable so data can be prepared for StaxRip. In that case I offered a way to solve the issue with unique temp folder names.

So I close this issue now...

**Closed by Dendraspis** 2024-11-09 00:42 UTC
Labels: bug  :bug:, added/fixed/done, feature request, handling issue, implemented in RC
