### ISSUE TITLE
staxrip 2.30.0 dont launching in win11(21h2)

### ISSUE THREAD

**Issue by amirhamdidz** [staxrip/staxrip#1159] opened 2023-12-20 20:07 UTC
staxrip 2.29.0 launching normal
but staxrip 2.30.0 dont launching in win11 21h2

when i try to open StaxRip.exe nothing happen

i already installed
Microsoft Visual C++ Redistributable Runtimes All-in-One
.NET Framework 4.8.1

**Comment by nero-0** [comment] 2023-12-20 21:37
Probably duplicate of: #1158

You can try this:
> Please replace the `StaxRip.exe` file with this one and check again, if the issue is gone:
> [StaxRip v2.30.1.zip](https://github.com/staxrip/staxrip/files/13709377/StaxRip.v2.30.1.zip)

https://github.com/staxrip/staxrip/issues/1158#issuecomment-1861851011

**Comment by amirhamdidz** [comment] 2023-12-20 21:39
it work thank bro

**Closed** 2023-12-20 21:41 UTC
