### ISSUE TITLE
Cannot rewind or fast forward x265 movies encoded with StaxRip

### ISSUE THREAD

**Issue by spopic** [staxrip/staxrip#317] opened 2020-09-02 09:16 UTC
This template is meant for usage questions of StaxRip.

Hi!

Some strange things happens when I use CPU encoding options (x265) in StaxRip 2.0.8.0.  (CPU is Ryzen 9/3900X) .The output file is OK, but I cannot rewind or fast forward x265 movies encoded with StaxRip neither on TV nor on PC (I have tried with MPC-HC and VLC players).

When I encode movies with NVENC (VGA - NVidia GTX 1660 Ti), I am able to fast forward or rewind encoded movies!

Please, what could be the problem?

Best regards,
SP

**Comment by Dendraspis** [comment] 2020-09-03 01:15
It seems to be necessary to check your settings, so attach a log file of such an encode, please.

Have you already tested the latest beta version?

**Comment by 44vince44** [comment] 2020-09-03 04:00
@Dendraspis  nice to see you're back!

@spopic The problem is the encoding profile of x265. For some time now, Staxrip sets default to the 10 bits profile "Main10". For best compatibility, you need to set it back to
**Depth = 8 bits
Profile = Main.**
and save it as your main template.

For your information: most hardware players won't play Main10 which is the current default settings of Staxrip (especially if not updated), and MPC-HC for sure doesn't work with Main10.

**Comment by spopic** [comment] 2020-09-03 05:45
Dendraspis & 44vince44,

Thanks for your reply. I have tried to encode with beta version (StaxRip.exe - 2.1.3.9-beta) also, but the result is the same...

In the meantime, I bought x265 HEVC Upgrade software (x265 Encoder) which is working fine (rewinding and fast forward is OK) with Slow preset...

I will use StaxRip for NVENC encoding only (my VGA card supports B-frames in HEVC encoding). 

In the meantime I will try the 8bit/Main profile  as suggested by 44vince44....

Thank you very much for your support.

Best regards!

**Comment by Dendraspis** [comment] 2020-09-03 06:37
@44vince44 Not really yet, but I'll try to be more present. 😬 

He mentioned using MPC-HC and VLC. I can confirm that both work great with 10bit x265 encodes. 
Hardware players and TVs are a different story, but if they can play 4K movies (which are 10bit h265), they should also accept smaller resolutions.

A log file would be great so check. 🤔

**Comment by spopic** [comment] 2020-09-03 12:57
[2020-09-02 - 15.14.10 - SRB-X265-Cronos.1993.SPANISH.1080p.BluRay.H264.AAC_staxrip.log](https://github.com/staxrip/staxrip/files/5168596/2020-09-02.-.15.14.10.-.SRB-X265-Cronos.1993.SPANISH.1080p.BluRay.H264.AAC_staxrip.log)

Hi!

Log file attached.

Best regards,
spopic

**Comment by Dendraspis** [comment] 2020-09-03 14:59
Difficult. You could try switching MP4BOX to another MP4-Muxer and see if it works.
I think somebody with more MP4 experience should check it - I only use MKV.

You could also try changing LSmashVideoSource for FFVideoSource which works better/more accurate. 

Just another side note:
Interesting encoder settings. Hope you fine tune your settings - your result is 20% bigger than the source. 🤔

**Comment by spopic** [comment] 2020-09-03 16:53
Thanks for your reply. Encoder settings are just for the testing purposes (bitrate is even higher than the original, etc.)

I will try your suggested settings and I will switch to mkv container/muxer and LSmashVideoSource but at the moment I am satisfied with x265 HEVC Upgrade software (x265 Encoder) and I need some time for testing and hopefully I will come to a conclusion...

In the meantime, thank you very much for your help!

Best regards!

**Comment by 44vince44** [comment] 2020-09-03 17:46
> He mentioned using MPC-HC and VLC. I can confirm that both work great with 10bit x265 encodes.

@Dendraspis you're right, my problems playing standard x265 Main10 encodes were due to my settings in MPC-HC, now they play all right.
I didn't try VLC because I don't have it and i don't want to install it. (how would i care about vlc when i use mpv.net ;-))))

@spopic try the following in MPC-HC: set in options > internal filters > button "Video decoder" > Hardware decoder = "None"
Note that this only disables hardware decoder, it doesn't disable hardware acceleration in video rendering.
Your log shows also that you use advanced customization in the x265 parameters, I have no experience with that, I only use presets!

**Comment by Dendraspis** [comment] 2020-09-03 20:39
> I will try your suggested settings

Very good.  😃 

> and I will switch to mkv container/muxer and LSmashVideoSource

No no, try using FFVideoSource.  😉 


@44vince44 
Very nice. And yes, I should remove VLC and replace it with something else. 😄 

> I only use presets

😕 😨

**Comment by spopic** [comment] 2020-09-04 04:43
Hi guys,

I used LSmashVideoSource, Profile Main, 8 bit, mkv container and I found and copied in StaxRip folder x265 build I have found in **another x265 encoding program** -  **x265 3.4+6-g73f96ff39:[Windows][GCC 11.0.0][64 bit] 8bit+10bit+12bit** and voila! Everything is working fine! I am able now to rewind and fast forward all encoded movies on TV and with MPC-HC and VLC players!

Thanks for your support.

Yours sincerely,
spopic

**Comment by Dendraspis** [comment] 2020-09-04 11:52
🤔   I think the key was/is using MKV instead of MP4. The used x265 version should be negligible.

You're welcome.

-----------

The question is:  why is MP4 not working as intended?!
Despite the other issues I'll close this for now....

**Closed by Dendraspis** 2020-09-04 11:52 UTC

**Comment by Patman86** [comment] 2020-09-04 12:55
Only mp4box cause this error/issue. Use ffmpeg to generate the mp4 file and the error/issue don't exist. Have a look here #158

**Comment by spopic** [comment] 2020-09-04 13:11
Thanks to everyone!

Best regards!
