### ISSUE TITLE
SMDegrain - there is no function named 'color_propGet'

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1009] opened 2023-05-17 09:47 UTC
**Describe the bug**
When trying to apply following degrain filter 
```
pre=SMDegrain(tr=1,mode="TemporalSoften",blksize=32,prefilter=8  ,thSAD=700,LFR=400,DCTFlicker=false,contrasharp=false,refinemotion=true)
    SMDegrain(tr=2,mode="MDegrain"      ,blksize=32,prefilter=pre,thSAD=400,LFR=200,DCTFlicker=true ,contrasharp=true ,refinemotion=true)
```
getting 
Script Error

Script error: There is no function named 'color_propGet'.
(D:\Temp\StaxRip-v2.15.0-x64\Apps\Plugins\AVS\SMDegrain\SMDegrain.avsi, line 1116)
(K:\Ghost.1990.1080p.BluRay.Remux.AVC.TrueHD.5.1-PmP_temp\Ghost (1990) BDRip 1080p H.265 [UKR_ENG] [Hurtom]_view.avs, line 52)

StaxRip v2.15.0

**Comment by Dendraspis** [comment] 2023-05-17 10:47
Should be already fixed in v2.16.0  😀

**Comment by IevgenSobko** [comment] 2023-05-17 11:04
With 2.16 you can't even add SMDegrain filter because of UI crash :)

**Comment by IevgenSobko** [comment] 2023-05-17 11:20
Here what I get when try to add SMDegrain in 2.16.0
```
InvalidOperationException (v2.16.0)

Sequence contains no elements

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at StaxRip.VideoScript.GetAvsLoadCode(String script, String scriptAlready) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 530
   at StaxRip.VideoScript.GetAVSLoadCodeFromImports(String code) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 602
   at StaxRip.VideoScript.ModifyAVSScript(String script) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 614
   at StaxRip.VideoScript.ModifyScript(String script, ScriptEngine engine) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 331
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath, Boolean flipVertical) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 296
   at StaxRip.VideoScript.GetInfo() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 649
   at StaxRip.VideoScript.GetFrameCount() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 663
   at StaxRip.VideoScript.GetSeconds() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 659
   at StaxRip.MainForm.AviSynthListView_ScriptChanged() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 6193
   at StaxRip.FiltersListView.OnChanged() in D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:line 275
   at StaxRip.FiltersListView._Lambda$__14-0(VideoScript script) in D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:line 32
   at StaxRip.VideoScript.RaiseChanged() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 26
   at StaxRip.VideoScript.AddFilter(VideoFilter filter) in D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:line 103
   at StaxRip.FiltersListView.AddClick(VideoFilter filter) in D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:line 265
   at StaxRip.UI.MenuItemEx._Closure$__31-0`1._Lambda$__0() in D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:line 452
   at StaxRip.UI.MenuItemEx.OnClick(EventArgs e) in D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:line 672
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Dendraspis** [comment] 2023-05-17 18:17
Interesting, I'll check it when I'm back.

**Comment by Discograp** [comment] 2023-05-18 01:22
> I just open source and add SMDegrain filter. That is it. And it crashes for me.

Does the software immediately turn off when a new script is read?

Please describe your PC system:
OS
CPU
RAM
GPU

**Comment by IevgenSobko** [comment] 2023-05-18 07:29
It is showing error window with possibility to copy text and open bug report.
After closing, it dissapears.
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
AMD RYZEN 5900X
32 GB RAM
NVIDIA GTX 1080

**Comment by Discograp** [comment] 2023-05-18 10:55
1) современный процессор АМД оптимизирован-совместим с этим скриптом?

2) 32 бита или 64 бита который из них использует SMDegrain?

3) другие софты-лаунчеры с этим SMDegrain работают без ошибок?

=========================================

1) Is a modern AMD processor optimized-compatible with this script?

2) 32 bits or 64 bits, which one does SMDegrain use?

3) other software with this SMDegrain work without errors?

**Comment by IevgenSobko** [comment] 2023-05-18 12:01
First of all lets clarify whether we are talking about UI crash in 2.16 or 'color_propGet' missing function.

If it is about UI crash. I don't think it depends on processor.
It is not custom SMDegrain. It is one that you provide with StaxRip.
With 2.15 there is no this issue when you add build in into StaxRip SMDegrain, and I was able to encode multiple files with this filter enabled with default parameters provided by UI interaction like in screenshot below
<img width="733" alt="Screenshot 2023-05-18 at 14 00 00" src="https://github.com/staxrip/staxrip/assets/14232100/d8bc1c72-ae18-4e8b-ab73-a9aaab3decac">

**Comment by Discograp** [comment] 2023-05-18 13:03
then the problem is that your CPU is old - 6-7 years old?

stay in version 2.15

**Comment by IevgenSobko** [comment] 2023-05-18 13:12
I would't consider CPU Launched in **the end of 2020** to be an old one.

**Comment by Dendraspis** [comment] 2023-05-18 18:14
I don't think it is related to the hardware. 🤔

Thanks for providing the screenshots. I'll have a look at this issue when I'm back, then I can tell your more ... hopefully. 😅

**Comment by IevgenSobko** [comment] 2023-05-18 18:43
I see you have updated TransformsPack v1.6 in 2.16.0.
SMDegrain depends on it. For me it looks like they made some change not compatible with older SMDegrain script used in StaxRip.
I've tried to put latest SMDegrain(with fixed AviSynth version check :) ) and ExTools into AutoloadScripts folder and it didn't crash.

**Comment by Discograp** [comment] 2023-05-19 05:42
>     1. Is a modern AMD processor optimized-compatible with this script?

=============================================

> I see you have updated TransformsPack v1.6 in 2.16.0. SMDegrain depends on it. For me it looks like they made some change not compatible with older SMDegrain script used in StaxRip. I've tried to put latest SMDegrain(with fixed AviSynth version check :) ) and ExTools into AutoloadScripts folder and it didn't crash.

**Comment by Discograp** [comment] 2023-05-19 09:32
> I see you have updated TransformsPack v1.6 in 2.16.0. SMDegrain depends on it. For me it looks like they made some change not compatible with older SMDegrain script used in StaxRip. I've tried to put latest SMDegrain(with fixed AviSynth version check :) ) and ExTools into AutoloadScripts folder and it didn't crash.

ok - script developers are bad, they didn’t think that users of ryzens would experience problems

**Comment by Dendraspis** [comment] 2023-05-19 12:24
Yeah, it should be related to the file and function parameters you used, seems I missed a dependency.

Will be fixed in the next release, which will be published next week (probably).

**Closed by Dendraspis** 2023-05-19 12:24 UTC
Labels: bug, added/fixed/done
