### ISSUE TITLE
New VCEEnc v6.13 and nightly versions of StaxRip

### ISSUE THREAD

**Issue by NikosDi** [staxrip/staxrip#759] opened 2021-07-29 16:06 UTC
Hello again.

A new VCEEnc v6.13 has been released using latest AMF v1.4.21 and adding a new encoding mode (--qvbr).

Are there any nightly builds of StaxRip ?

I mean do we have to wait a few months for a new full version of StaxRip v2.80 just for a few new parameters added to StaxRip (e.g for VCEEnc)?

I think for small additions like a new version of a tool (e.g VCEEnc) and a few parameters added, it would be very useful if there were nightly versions (sort of)

BR,
Nikos

**Comment by Dendraspis** [comment] 2021-07-29 17:38
v2.8.0 should be released within the next days.
Untill then you can update VCEEnc by yourself and use the Custom field to add the param.

The problem is, that there are always other things already implemented, that are not ready yet. So you have to handle it a bit with care. 

Nevertheless:
[StaxRip v2.7.4.zip](https://github.com/staxrip/staxrip/files/6902417/StaxRip.v2.7.4.zip)

**Closed by Dendraspis** 2021-07-29 17:38 UTC
Labels: added/fixed/done, question
