### ISSUE TITLE
Audio missing when doing (HE) AAC 7.1 encodes

### ISSUE THREAD

**Issue by snozinho** [staxrip/staxrip#1027] opened 2023-06-24 21:43 UTC
**Describe the bug**
When converting media with StaxRip, HE-AAC 7.1 tracks are absent from output file

**Expected behavior**
HE-AAC 7.1 tracks should be muxed in output file

**Additional context**
Same issue than this topic : https://github.com/staxrip/staxrip/issues/796 except the issue is now present again in StaxRip 2.20.0 and the solution on said topic doesn't work anymore.

**Comment by Discograp** [comment] 2023-06-25 08:29
And what codec did you use?

NVEnc 7.28
- Fix AAC bitstream not in ADTS format and extradata missing error caused using --audio-copy when input is ts files.

QSVEnc 7.44
- Fix AAC bitstream not in ADTS format and extradata missing error caused using --audio-copy when input is ts files.

**Comment by snozinho** [comment] 2023-06-25 12:24
Hello @Discograp,

I didn't use any codec in this particular instance as video is on "Copy Mux"

**Comment by Dendraspis** [comment] 2023-06-25 12:26
AviSynth or VapourSynth? MKV or MP4? qaac or ffmpeg?  😅

**Comment by snozinho** [comment] 2023-06-25 12:47
@Dendraspis sorry 😁
I'd say AviSynth on your first question, but the two others are MKV and qaac for sure 👍

**Comment by Dendraspis** [comment] 2023-06-27 09:13
Please stop cross-posting issues, discussions and messages on Discord ehile providing cutted information - this makes it a lot more difficult.

From discussions:
> my issue is that I used to use "Decoding method: Pipe" to workaround this issue but now even that option leaves the output file without the encoded he-aac 7.1 track

**Comment by Dendraspis** [comment] 2023-07-01 01:46
This took a while, because this issue is caused by 3 bugs at 3 different places:
1. MediaInfo v23.03 did not work as intended
2. There was a bug in StaxRip executing the wrong ffmpeg command line
3. A bug in qaac64 still persists using 7.1 AAC HE encodes

StaxRip v2.21 will be able to work properly, but qaac64 creates faulty encodes using the HE option. This might be related to an issue I opened about 3 years ago: https://github.com/nu774/qaac/issues/62
So at this point there seems to be no way it will be fixed. Nevertheless I opened a new issue for that particular issue: https://github.com/nu774/qaac/issues/92

At least AAC LC will work with the next release coming out the next days.

**Closed** 2023-07-01 01:51 UTC
Labels: bug, tool issue, added/fixed/done

**Comment by Dendraspis** [comment] 2023-07-05 14:43
Good news:  [qaac v2.80](https://github.com/nu774/qaac/releases/tag/v2.80) was released to fix this issue (and more). 
Couldn't test it, but it will be available in the next release of StaxRip. Feel free to update manually and test it ... and to give feedback.  😁

**Comment by snozinho** [comment] 2023-07-05 18:56
> Good news: [qaac v2.80](https://github.com/nu774/qaac/releases/tag/v2.80) was released to fix this issue (and more). Couldn't test it, but it will be available in the next release of StaxRip. Feel free to update manually and test it ... and to give feedback. 😁

Updated, tested, fixed and approved ! 😃
