### ISSUE TITLE
More missing options for AV1 Aomenc

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#375] opened 2020-10-16 13:21 UTC
**Is your feature request related to a problem? Please describe.**
Some missing parameter options.

**Missing Option:**
- CPU Used: ``Speed 9 - Fastest``

**Suggestion:**
- Rename CPU Used: ``8 - Fastest`` to ``8 - Ultra Fast`` or something like that.
- Add CPU Used ``9 - Fastest`` since 9 is actually technically the fastest speed.

---

**Missing Option:**
- ``--enable-fwd-kf`` (Enable forward reference keyframes)

**Suggestion:**
- Add checkbox for this in the "Slice Decision" section called ``Enable Forward Reference Frames``

---

**Missing Option:**
- ``--enable-keyframe-filtering`` (Apply temporal filtering on key frame(0: no filter, 1: filter without overlay (default),2: filter with overlay))

**Suggestion:**
- Add an input box somewhere called ``Enable Keyframe Filtering`` and allow the user to specify values (0,1,2)

---

**Missing Option:**
- ``--enable-chroma-deltaq`` (Enable chroma delta quant (0: false (default), 1: true))

**Suggestion:**
- Add checkbox somewhere called ``Enable Chroma Delta Quant`` with a default value of 0 (False)

---

**Missing Option:**
- ``--mv-cost-upd-freq`` (Update freq for mv costs0: SB, 1: SB Row per Tile, 2: Tile, 3: Off)

**Suggestion:**
- Add an input box somewhere called `Update Freq for MV Costs`` and allow the user to specify values (0, 1, 2, 3)

**Comment by stax76** [comment] 2020-12-15 23:56
We need contributors interested in this encoder.

**Comment by Dendraspis** [comment] 2020-12-17 01:00
There were a lot of other parameters missing and on the other hand others had old options selectable.

Should be fixed now so they can be set/used, but someone should look at the settings and their options if everything is okay - it was a really f*(x!*§ huge task❕ 
Especially if default values are set, dependencies are okay and so on. Any volunteers? @44vince44 ??  😉  But first lets wait for the next beta.  😁 

For new bugs/misses I would suggest create new issues... I close this now!

@stax76 
I've re-positioned every single option and took the same tab names as they are at the CLI-help in order to be able to compare them to find missing parameters - makes our life a lot easier. Should be the best practice as long as there is no contributor who takes care of each change and applies them.

**Comment by 44vince44** [comment] 2020-12-17 16:10
@Dendraspis WOW good work! 
For testing, I'll do my best of course!
Unfortunately I don't have knowledge in this codec, but I promise I'll spend some time on it when the beta is available!

**Comment by Dendraspis** [comment] 2020-12-17 16:42
@44vince44 
Thanks ... and don't forget #361 and #365. 😁 
That's what I thought yesterday. But I guess it will take few years till AV1 will be a real alternative for me, especially regarding compatibility and speed.

At least now we can run test with an up to date GUI and encoder, since @stax76 has imported aomenc v2.0.0 in the last beta build. 😎 

So have fun.... 🥳

**Comment by 44vince44** [comment] 2020-12-20 09:25
@Dendraspis 
There is no official doc for the command line option (except the help file) !! 😮 
There are some things I noticed:

1. --enable-keyframe-filtering = 1 is default. Shouldn't it be removed from the command line when selected value 1 ?
2. these parameters have possible values 0,1,2,3. But help file does NOT say which one is default! 
--coeff-cost-upd-freq=0
--mode-cost-upd-freq=0
--mv-cost-upd-freq=0

(0 is for SB, which I don't understand meaning of SB, and 3 is for Off). None of the values are default in the help file. Is 0 (SB) considered to be implicit default ? in this case the current implementation is OK. If not, then we should change it.

Otherwuse I found nothing else "strange" on this page...

**Comment by Dendraspis** [comment] 2020-12-20 22:48
> --enable-keyframe-filtering = 1 is default. Shouldn't it be removed from the command line when selected value 1 ?

> these parameters have possible values 0,1,2,3. But help file does NOT say which one is default!
> None of the values are default in the help file. Is 0 (SB) considered to be implicit default ? in this case the current implementation is OK. If not, then we should change it. 🚀 

Indeed, they have no default set, but the default of a existing number is 0. The only solution would be adding an *unset* option for all default-less parameters in order to force these settings, but I doubt this would be useful. So let's keep it simple and less frustrating for first-time-users. 😁 

> Can we please move Input-Bit-depth from tab "AV1 Specific 7" to Encoder Global, and place it under Bit-depth ? Because they come in that order in the help file, and we could really need to change that (BTW, this should be automatically detected, maybe it is, but undocumented.)

This is a fun fact - the help has **two** entries for `--bit-depth`. I decided to keep the second one under ***AV1 Specific (7)*** because it is AV1 specific and right above `--input-bit-depth`, which kind of belongs together, especially to prevent irritations.

> cq-level = 24 is set as default in staxrip. When value is 24, the switch disappears from command line. Is is from trusted source that 24 = default ? 

No, there is no official default. That's why I/we want it to set to a value, that can be used as default value without producing files bigger than source or with terrible quality (see #361). If your test showed there might be a better default/average/starting point, please let me know!  🙏 

> auto-alt-ref =1 default, is it really (help says nothing) ? or shouldl it always appears for values 0 and 1.

This was wished/voted by users in #361 ...
> Reason(s):
﻿ 1. ﻿﻿﻿﻿It is better to have "auto alt ref" Enabled because according to some AV1 users in discord, having it disabled will result in a "completely shit encode"
﻿ 2. If you're doing a single pass encode, auto-alt-ref is actually disabled by default, but you can force it to be enabled by forcibly specifying it.
﻿ 3. alt-ref frames are used when using a 2-pass encode by default if it is not specified. Based on my limited understanding, you are generally better off just forcibly enabling this setting for most case scenarios.

> sb-size= dynamic, need to check default.

Same as above with the default 0.

**Comment by Dendraspis** [comment] 2020-12-20 23:36
> @Dendraspis
There is no official doc for the command line option (except the help file) !! 😮

Isn't it common for high-end codecs and applications?!? 😮 
Yeah, a good reason to stick to x265 and wait 2 years.  🙄

**Comment by 44vince44** [comment] 2020-12-21 06:55
> @44vince44
> Isn't it common for high-end codecs and applications?!? 😮 I thought this is the way it should be in 2020?! 😬
> Yeah, a good reason to stick to x265 and wait another 2 years. 🙄

Haha ;-) you may be very, very right. I'm on it now, checking the stuff I wanted to check yesterday evening....

I mean: a codec that reached version 2, that chose to use new wording (CPU-used naturally refers to multi-threading, here refers to speed) and **still has no explanatory documentation**... So the actual meaning of options is being guessed/discussed by users instead of being given by the devs.
Pity....

**Comment by 44vince44** [comment] 2020-12-21 07:20
Something is VERY WRONG with the speed and usage of CPU... I can't get it encode at more than 26% cpu.. what's wrong??

**Comment by 44vince44** [comment] 2020-12-21 07:31
Results, confirmed problems:

1. Threads = 0 must not be set. 0 won't work as "automatic" it works as 1 or as no switch in the command line
With threads = 0, the observed max cpu usage is 13% on a 8 logical cpu machine.
With no threads switch at all, same observation as Threads=0
With Threads=8 I have between 26% and 50% cpu usage.
With threads more than 8 I have same as 8

**Suggestion: use Threads = 8**

**Comment by Dendraspis** [comment] 2020-12-21 10:40
> Something is VERY WRONG with the speed and usage of CPU... I can't get it encode at more than 26% cpu.. what's wrong??

I think that could be normal for AV1, depending on which CPU and settings were used. Therefore chunk encoding is requested in #368.

**Comment by Dendraspis** [comment] 2020-12-21 13:37
> I. Threads = 0 must not be set in the initial settings. 0 won't work as "automatic" it works as 1 or as no switch in the command line

🤦‍♂️  WOW. Okay, so I set it to 128 to nobody would be limited. 🤔   *I'm still shocked*

> II. Tiles vs SB  ✔️ 

> III. Rate mode Q (BUG)  ✔️ 

> IV- CQ-Level 24 (BUG)  ✔️ 

> V- BUG: Rate modes Q and CQ must remove the target bitrate and grey out the Size and target bitrate in the interface

Will be fixed next ....

> VI- Custom switches appear in the command line between "" (BUG)  ✔️

**Comment by 44vince44** [comment] 2020-12-21 14:14
Thanks @Dendraspis !

> 🤦‍♂️ WOW. Okay, so I set it to 128 to nobody would be limited. 🤔 I'm still shocked

I was shocked all along the tests I did, too 🤣 
But however I thing 128 is too irrealistic. Something like 8 or 12 is more appropriate for an initial setting... most common video encoding machines are 8. Ryzens 12+...

**Comment by Dendraspis** [comment] 2020-12-21 17:57
Thanks, @44vince44  !  😉 

🤔  Are the other AV1 encoders also that "simple* ?  But the docs from x265 are really a big PLUS, even when there are some bugs/disagreements. 

You're right, but on the other side it also doesn't matter if 1024, 128 or 64 for us. On the other hand you can buy an *AMD Ryzen Threadripper 3990X* with ***64C/128T***, so this limit should be okay, at least for the super rich.  🙄 
I tend to keep it at 128, because it is better to not accidently slow the encode down.

**Comment by 44vince44** [comment] 2020-12-21 18:50
> On the other hand you can buy an AMD Ryzen Threadripper 3990X with 64C/128T, so this limit should be okay, at least for the super rich. 🙄

Ok so I just need to wait till I'm rich :rofl

The other encoders seem less complex indeed, but it's really strange how they lack documentation !
However when I was reading some articles, it appeared to me that SVT-AV1 will be the encoder that will have encoding profiles,  allowing to use very simple command lines... But it's to soon to know which will be the most interesting.

**Comment by Dendraspis** [comment] 2020-12-21 21:16
Ok, point ***V*** is also done.  👍  So I can close it one more time.  😁 

> The other encoders seem less complex indeed, but it's really strange how they lack documentation !

Real man don't seem to need documentations.  😁 
But thanks for the infos.  👍  😊  I think it confirms why there are not so many interested people in that encoders. I'll try to give it a short try next year.

**Closed by Dendraspis** 2020-12-21 21:16 UTC
Labels: added/fixed/done, bug, feature request, priority low

**Comment by Dendraspis** [comment] 2020-12-22 22:04
@Dendraspis Warning my friend, setting threads of aomenc to 128 gives an out of range error. I tried value 32 it passed ok. Please change the initial setting !!!! (to 32 seems good)

@44vince44 
I start to hate this encoder ... and me for spending so much time into it. 😡  😡 
But:  Default is set to 32.  Thanks for your testing and helping! 👍 

***Took this quote from another thread, but it belongs here.***

**Comment by 44vince44** [comment] 2020-12-23 04:43
@Dendraspis we share the exact same feeling about this encoder 🤣 
Let's hope we're DONE with it this time!

**Comment by 44vince44** [comment] 2020-12-29 13:21
This copies a post I made in another thread, but ir belongs here
@Dendraspis I have something very unfortunate for you :-( -sorry 😢

This has not been adressed in aomenc:

    V- BUG: Rate modes Q and CQ must remove the target bitrate and grey out the Size and target bitrate in the interface
    ===> When Rate modes Q and CQ are selected, The --target-bitrate=xxx switch MUST BE removed, and the interface items "Size" and "Video Bitrate" must disappear from the interface (as they do in other encoders when selecting qualiby based modes)

Well at least remove the --target-bitrate=xxx switch when q and cq modes selected, please ? 😃

Well the good news is that x265 3-pass tested in 2-chunk mode works well ;-) I'll do a single chunk test later ;-)

**Comment by Dendraspis** [comment] 2020-12-29 15:49
@44vince44 
Stop pushing - I saw it already.  😝   So stay tuned...
But it's strange because I could bet it worked when I worked on it.  🤔

**Comment by Dendraspis** [comment] 2020-12-29 16:23
@44vince44 
Okay, found it ... and yes, it worked perfectly - till stax76 destroyed it before he made the beta.  
The next beta should work as intended.  😄

**Comment by 44vince44** [comment] 2020-12-29 19:05
@Dendraspis I didn't mean to push! I know how annoying this has become for you 🤣 🤣
I'm happy you could find it so soon ! thanks!

**Comment by Dendraspis** [comment] 2020-12-29 19:56
@44vince44 
I was just kidding.  :smile:
Yeah, happy it's over now - again. :grin:

**Comment by 44vince44** [comment] 2020-12-30 05:02
@Dendraspis sorry to bring that back again, but can you please check also that --cq-level=xx disappears when Rate Mode = CBR or VBR ? I'm not sure your last commit adress that as well...

Synthesis of tho modes:
Rate Mode = q  => --end-usage=q ;  --cq-level=xx  **AND NO --target-bitrate**
Rate Mode= cq => --end-usage=cq;  --cq-level=xx  **AND NO --target-bitrate**

Rate Mode = VBR => --end-usage=vbr;  --target-bitrate=xxxx  **AND NO --cq-level**
RateMode = CBR => --end-usage=cbr;  --target-bitrate=xxxx **AND NO --cq-level**

**Comment by Dendraspis** [comment] 2020-12-30 08:10
Is or should be done/fixed now - but sadly a bit too slow, because the new beta is out.  😞 

@44vince44 
Is it over now?  I mean really over? Done? Fixed?  😇 
Have fun testing it next time.  😁

**Comment by 44vince44** [comment] 2020-12-30 09:40
@Dendraspis I have tested with the latest beta AND the latest exe that has been given by @stax76, and which INCLUDES your latest commit.
**Good news:** everything is OK, the initial settings and command line are self-consistent, we finally have something that works on-the-fly.

Small problem: there is a "Target Bitrate" field under "Rate Mode" in "Rate Control 1" tab. It should be removed (when set to 0 it causes no problem, but when set to <>0, it adds a second switch --target-bitrate. So simply remove it please !

**Comment by Dendraspis** [comment] 2020-12-30 10:06
@44vince44 
Why do your tests always result in different results than mine?
I'm sure I tested every combination and it worked. I'll check it later - seems to be the wrong time to fix bugs also - have not enough of it. :disappointed: 
Thanks for testing!  :smile:

**Comment by 44vince44** [comment] 2020-12-30 13:05
@Dendraspis thanks to you my friend you are the one doing the hard work! And please don't take any pressure !

Please don't misunderstand my report, it is something very simple, and that cause no problem if you ignore it. But maybe fixing it is very easy because you'll maybe ONLY NEED TO REMOVE code.

Here is the problem, illustrated:

I) In Rate-Mode = Q or CQ: EVERYTHING OK, NO PROBLEM

![SNAG-0000](https://user-images.githubusercontent.com/17828567/103352761-cdf43d00-4aaf-11eb-9b45-a796ca4dd95b.jpg)

IIa)  In Rate-Mode = CBR or VBR, If you TOUCH NOTHING, everything is OK

![SNAG-0001](https://user-images.githubusercontent.com/17828567/103352802-e8c6b180-4aaf-11eb-9295-685386b046c0.jpg)

Note that the value of --target-bitrate is calculated correctly (I tested, and it aims the correct size of final file, which is the expected behavior)

![SNAG-0002](https://user-images.githubusercontent.com/17828567/103352952-422ee080-4ab0-11eb-840e-102a0373f05d.jpg)

Again, until now everything OK
![SNAG-0003](https://user-images.githubusercontent.com/17828567/103352973-4d820c00-4ab0-11eb-8c65-3994e5001a58.jpg)


IIb) In Rate-Mode =CBR or VBR if you touch this setting, here is the problem:

![SNAG-0003](https://user-images.githubusercontent.com/17828567/103352988-55da4700-4ab0-11eb-8e9c-ced0f6e9296c.jpg)


So the FIX is : simply don't make this new " Target bitrate" appear below Rate Mode CBR or VBR.

**Comment by Dendraspis** [comment] 2020-12-30 20:27
@44vince44 
You missed something:  😬 

![SR](https://user-images.githubusercontent.com/50659978/103378970-60aecf00-4ae4-11eb-82c7-6fda4ed95316.JPG)

> you are the one doing the hard work!

No, I'm not - at the moment I'm doing the boring work, that's also necessary, or fixing bugs implemented by myself.  🙄 

> Please don't misunderstand my report, it is something very simple, and that cause no problem if you ignore it.

A bug is a bug and should be fixed - and of course I would not misunderstand your report!!  🤝  Thanks for that.  ☺️ 
Btw: Your illustrations are ..... very detailled.  😄  My English is not that good, but I'm sure I would understand it with less informations.  😁   But thanks, it was very clear!  👍 

> So the FIX is : simply don't make this new " Target bitrate" appear below Rate Mode CBR or VBR.

I've fixed it now. Let's see if the next beta works for you, too. 🤔

**Comment by stax76** [comment] 2020-12-30 21:10
> you are the one doing the hard work!

It wasn't visible in the changelog, the UTF-8 support of x264 resulted in a huge modernization and refactoring effort:

https://github.com/staxrip/staxrip/commit/bcdbcc59318d088f8a42dddecf1ee36a9b715249

There is some complexity and therefore possible bugs. I would like to warn power users that the generated avs scripts are not always guarantied to have the same text encoding any longer, sometimes they are UTF-8 encoded without BOM and other times using the default code page. People that want to use the scripts externally sometimes must change the encoding. StaxRip and mpv.net use now a UTF-8 manifest like x264.

**Comment by 44vince44** [comment] 2020-12-31 07:42
> @44vince44
You missed something: 😬

Oh My !!!!! I did.... let's not allow something like that happen again 🤣

**Comment by stax76** [comment] 2020-12-31 08:46
I've uploaded it, have now a hotfix upload script. 😉

**Comment by 44vince44** [comment] 2020-12-31 15:14
Thanks @stax76 , thanks @Dendraspis 
This is working as expected. We can consider this OK for a long while because:
- the initial settings allow on-the-fly encoding, even if user has no knowledge
- now we can easily find the cq-level value, and the switch for the encoding mode
- many (maybe all) other switches are available, so user can find everything he want
- "custom" is available: this is very satisfactory (one day you'll have some user nag you about custom pass1 and custom pass2 affecting all passes, but **it won't be me**!)

Congrats and thanks for having this work, despite the complication of it !

**Comment by Dendraspis** [comment] 2020-12-31 21:50
@44vince44 
> * "custom" is available: this is very satisfactory (one day you'll have some user nag you about custom pass1 and custom pass2 affecting all passes, but **it won't be me**!)

 😠  Why not?!  I'm glad you did ... or not. 🤔  😁   But it's fixed in the next beta.  😃

**Comment by 44vince44** [comment] 2020-12-31 22:59
Well done!!
It means i'll have to test that again 😢

**Comment by Dendraspis** [comment] 2020-12-31 23:14
> It means i'll have to test that again 😢

No, you didn't report the bug, so you don't need to check if the fix works.  😁   Simple as that.

**Comment by stax76** [comment] 2021-01-01 17:26
Thanks, @Dendraspis and @44vince44 for working on it, I hope AV1 encoding will make good progress.
