### ISSUE TITLE
If a job fails/produces an error, move to the next job

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#354] opened 2020-10-04 22:29 UTC
**Is your feature request related to a problem? Please describe.**
From time to time, I find Staxrip spits out an error when encoding EAC3. I can restart the job and it works (no obvious cause). The problem is that the queue of jobs doesn't continue, meaning lost time. I encode remotely 24/7 so it can mean 12+ hours of lost encoding time due to an error.

**Describe the solution you'd like**
If an error is produced for any encode, and there is a queue of jobs, I would like the error to keep its current behaviour, but for Staxrip to move on to the next job. Or perhaps at least have an option to do so upon error 'move to next job upon error'.

**Describe alternatives you've considered**
No alternatives.

**Explain why the feature matters to you**
Loss of time is annoying and this feature would be a very useful.

**Additional context**
No screenshots I can provide.

**Comment by stax76** [comment] 2020-10-05 08:11
It's already supposed to work like this, but maybe the feature is broken.

When ErrorAbortException happens then an error message box is shown with a timeout of 50 seconds.

Please post the log file message.

**Comment by vonH** [comment] 2020-10-05 13:49
It seems like the feature is broken. In fact, I've never seen it skip on to the next job in the queue (since at least 1.7.x inclusive). I can't post the log as I can't seem to find it (not in the Staxrip directory - using portable). I should have taken a screenshot but didn't.

**Comment by stax76** [comment] 2020-10-05 13:57
The staxrip log file is in the temp folder, by default the temp folder is located next to the source file.

If you re-open the project from the recent menu, then you can open the log file from the main menu.

Main Menu > File > Recent Projects

Main Menu > Tools > Log File (F7 key)

Or you go in the log file history, if no project is open then you get the history with:

Main Menu > Tools > Log File (F7 key)

Or you find the history at:

Main Menu > Tools > Folders > Log Files

**Comment by vonH** [comment] 2020-10-05 17:02
I restarted the job and the logfile was overwritten. The job then completed successfully.

**Comment by vonH** [comment] 2020-10-06 19:28
@stax76 Here's another error. This is using the same template for the same season of a TV series, but for some reason there is an occasional error. The EAC3 output seems fine, however.

![image](https://user-images.githubusercontent.com/10042301/95250517-1fbf5b00-0812-11eb-97c3-83f0d9167428.png)

Here is the part of the log showing the error:    
---------------- Error Audio Encoding: E-AC3 640 kbps ----------------

Audio Encoding: E-AC3 640 kbps returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function


------------------- Audio Encoding: E-AC3 640 kbps -------------------

"C:\Users\Server\Desktop\StaxRip2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1.eac3" -c:a eac3 -b:a 640k -y -hide_banner "Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1_a2.eac3"

[eac3 @ 000001bc470a2e40] Format eac3 detected only with low score of 1, misdetection possible!
[eac3 @ 000001bc470a2e40] Could not find codec parameters for stream 0 (Audio: eac3, 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, eac3, from 'Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1.eac3':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: eac3, 0 channels, fltp
Output #0, eac3, to 'Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1_a2.eac3':
Output file #0 does not contain any stream

------------------ Audio Encoding: E-AC3 640kbps 5.1 ------------------

"C:\Users\Server\Desktop\StaxRip2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}.dtshd" -c:a eac3 -b:a 640k -y -hide_banner "Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1.eac3"

Input #0, dts, from 'Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}.dtshd':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s16p
Stream mapping:
  Stream #0:0 -> #0:0 (dts (dca) -> eac3 (native))
Press [q] to stop, [?] for help
Output #0, eac3, to 'Q:\Fringe\Season 03\Fringe.S03E02_temp\Fringe.S03E02 ID1 English {DTS HD-MA}_a1.eac3':
  Metadata:
    encoder         : Lavf58.43.100
    Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp (16 bit), 640 kb/s
    Metadata:
      encoder         : Lavc58.86.101 eac3
video:0kB audio:206188kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by stax76** [comment] 2020-10-07 15:40
The timeout was still working in my test, so I cannot reproduce it.

New in next built:

- GUI options for ffmpeg -probesize -analyzeduration

**Comment by vonH** [comment] 2020-10-07 21:04
> The timeout was still working in my test, so I cannot reproduce it.
> 
> New in next built:
> 
> * GUI options for ffmpeg -probesize -analyzeduration

I can't always reproduce the error as it seems sporadic. I encoded the same file straight after and it worked. I should probably add: I've only experienced this with DTS HD MA sources, so possibly a tool issue?

**Comment by stax76** [comment] 2021-01-01 17:23
I close it now because it's not reproducible.

**Closed by stax76** 2021-01-01 17:23 UTC
Labels: bug, not reproducible, priority medium
