### ISSUE TITLE
x265 CHUNK Staxrip other issue (file access)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#431] opened 2021-01-09 14:43 UTC
### Describe the bug
This is randomly reproducible, unfortunately (found by user apophis906 on doom9).

**When doing a chunk encode with staxrip, one of the chunks process will not be started due to the following error message:**

IOException (2.1.7.0)

The process cannot access the file 'D:\Downloads\_IDM Downloads\Samsung Toner Cartridge MLTD103L chip replace_temp\Samsung Toner Cartridge MLTD103L chip replace.avs' because it is being used by another process.

System.IO.IOException: The process cannot access the file 'D:\Downloads\_IDM Downloads\Samsung Toner Cartridge MLTD103L chip replace_temp\Samsung Toner Cartridge MLTD103L chip replace.avs' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at StaxRip.StringExtensions.WriteFile(String instance, String path, Encoding encoding)

**When validating the message, the process continues correctly.**

### How to reproduce:

Create a x265 FAST encode job, AVS, no filtering, NO audio. In the settings, ask that staxrip NOT send the temp folder to trash and NOT delete it. Select number of chunks = 3.
Run job.  (Note that the avs2pipemod will be used even if no pipe is selected. this is a bug adressed in another bug report https://github.com/staxrip/staxrip/issues/430)
If you don't have any message, wait till process finishes. When finished, press Next in the man window to re-create job, and re-run job. Eventually, you'll get the error message.

### Suggestion
When you validate the message, the process continues.
So perhaps, if the process can't access the file, it should retry automatically before throwing the message.

**Comment by JJKylee** [comment] 2021-01-09 16:47
My guess: isn't this related to this new feature introduced and existent since 2.1.4.9 Beta?

> - Set the current directory of the StaxRip process to the working directory of the current project.

The _working directory of the current project_ is usually the temp folder.

So I've found that due to this feature, I cannot delete the temp folder of the current project in Explorer while StaxRip is open with it. Windows complains that it cannot delete the folder because it's open by another program, which is obviously StaxRip. (I used to be able to do it in previous versions.)

I'm wondering if the same logic applies here: multiple sessions trying to access the **same** temp folder tend to exclude each other.

Correct me if I'm wrong.

**Comment by stax76** [comment] 2021-01-09 17:00
I also noticed the temp folder is locked but didn't really think it's because of that, so great find JJKylee!

This change can be reverted without a problem because no feature depends on it, originally it was changed because of a ffmpeg issue, but it was fixed meanwhile by explicitly defining a path for the 2pass log file.

**Comment by 44vince44** [comment] 2021-01-09 17:02
@JJKylee 

> I'm wondering if the same logic applies here: multiple sessions trying to access the same temp folder tend to exclude each other.

Accessing same folder is not an issue, and should not create problems. You can access folders simultaneously by different processes. I don't think it's related!

> I cannot delete the temp folder of the current project in Explorer while StaxRip is open with it

If you don't set Staxrip to trash or delete the temp folder after process is successful, then the whole project is still open in Staxrip, and cannot be deleted. this is actually GOOD (it's the way it should have been always ;-))))!

Then you don't need to quit staxrip, simply drop another video file, and you'll be able to delete the former temp.
Also in a batch job, when job is finished and staxrip processes next job, previous job temp can be deleted.
Only minor issue is for LAST job of the batch, although the interface is cleared, there is still a lock on LAST working folder.

i don't know if it's an important point.

**Comment by 44vince44** [comment] 2021-01-09 17:09
@stax76 you decide ;-) but let's get back to the matter at hand 😄

**Comment by JJKylee** [comment] 2021-01-09 17:19
> Accessing same folder is not an issue, and should not create problems. You can access folders simultaneously by different processes. I don't think it's related!

Of course 'only reading' simultaneously doesn't matter. But the problem with chunk encoding is that multiple sessions try to 'read and **write**' to the same temp folder. The error message seems a little misleading, but I think it happens in the course of the whole read and write process.

> If you don't set Staxrip to trash or delete the temp folder after process is successful, then the whole project is still open in Staxrip, and cannot be deleted. this is actually GOOD (it's the way it should have been always ;-))))!

I agree. I just wanted to point out that the temp folder is locked unlike before.
 
> imho, the only thing that appears here is that Working folder must be cleared when interface is cleared at the end of batch processing. (that's another matter, maybe I'll create a ticket for that one 🤣 )

Sounds reasonable.

**Comment by 44vince44** [comment] 2021-01-09 17:47
> Of course 'only reading' simultaneously doesn't matter. But the problem with chunk encoding is that multiple sessions try to 'read and write' to the same temp folder. The error message seems a little misleading, but I think it happens in the course of the whole read and write process.

yes, but not folder related. Only file related (and this is where databases have special access methods to files)

**Comment by 44vince44** [comment] 2021-01-09 17:48
@stax76 any idea on what causes the error message (initial matter in this thread) ?

**Comment by JJKylee** [comment] 2021-01-09 18:05
@44vince44 Sorry but I modified my guess after you quoted. Plz, have a look. 😢

Personally, I hope this issue is resolved if @stax76 reverts the locked temp folder feature. Let's see.

**Comment by 44vince44** [comment] 2021-01-09 18:23
Oh I just read it.
Well I guess if the feature has no more use and causes problems, even unimportant ones, it should be important...
I understand what you have explained. Indeed, there can be some protections in the file system I'm not aware of, at a folder level.
If @stax76 removes the folder lock and releases a fixed exe, I'll test it right ahead.

**Comment by 44vince44** [comment] 2021-01-09 18:38
@JJKylee @stax76 I forgot however to mention something:

-the Work Folder definition was introduced in 2.1.4.9.  right?
-at the same time, there has been some mess up with the three pass mode of x265. This had taken place in 2.1.4.9 and been fixed in 2.1.5.1 to 2.1.5.3.

So i did intensive x265 multipass testing in all versions after 2.1.5.1, including x265 multipass/**multichunk**. Did many encodes, every new beta to check the regression is gone.
At no time did I get this access error !

I'm confused...

**Comment by Dendraspis** [comment] 2021-01-09 18:51
@44vince44 
How big/long is your source? and how long does it take to finish (if no error occurs)?

**Comment by 44vince44** [comment] 2021-01-09 19:40
@Dendraspis 

> You are the craziest nerd on earth! 😂

I did that because "someone" messed up the code and then restored it... 🤣 

> How big/long is your source? and how long does it take to finish (if no error occurs)?

Small source (1 minute long), and setting encoding parameters so that the encoding process lasts a bit more than 1 minute.

> (if no error occurs)?

Remember, if an error occurs, simply by validating the message, the encoding continues and finished successfully.

**Comment by Dendraspis** [comment] 2021-01-10 13:15
I think I'll give it a try. 🤔 

> Remember, if an error occurs, simply by validating the message, the encoding continues and finishes successfully.

Ah, seems I misunderstood that, thanks.

> Besides, if I don't do three of four 3-pass/n-chunks encoding every day, I feel depressed. 🤣

***"Besides"***  🤣

**Comment by Dendraspis** [comment] 2021-01-10 16:03
Ok, I can reproduce it and located the code that's causing the problem - but I think that might take a while.  🤔

**Comment by Dendraspis** [comment] 2021-01-10 18:01
Okay, I found a good solution, so this issue should be fixed. 
Would be great if you could test it with the next beta ... ***besides***.  🤣  😉

**Comment by 44vince44** [comment] 2021-01-10 18:36
Oh yes I'm very depressed currently. I really need to test chunk encoding 🤣 
Thanks for bringing the cure ...

**Comment by stax76** [comment] 2021-01-11 01:10
@Dendraspis 

Maybe there could be a race condition if the thread of the first chunk writes the script not before another thread reads it.

**Comment by Dendraspis** [comment] 2021-01-11 02:32
@stax76 
It's already fixed and commited.  😁

**Comment by stax76** [comment] 2021-01-11 02:42
Yes, I wrote it after seeing the code of your commit, I think at least theoretically there could still be a race condition. I'll take another look after investigating a batch aspect ratio issue.

**Comment by Dendraspis** [comment] 2021-01-11 03:02
There shouldn't be one, because the writing is (sequencially) done before the first process starts. 😊

**Comment by stax76** [comment] 2021-01-11 03:21
Here is the script written:

https://github.com/staxrip/staxrip/blob/master/Encoding/x265Enc.vb#L62

This code runs when the action/thread starts, there is no guaranty however the action/thread of the first chunk runs first.

**Comment by Dendraspis** [comment] 2021-01-11 03:50
It is called by a sequential for loop and after it is sequentially executed, the thread is created (also sequentially) and started. When the first thread is started, then it goes critical. So the first call is absolutely save.  🤔

**Comment by Dendraspis** [comment] 2021-01-12 13:10
Ok, sadly this problem is not solved yet.  😞 

There must be made some bigger changes in the layout to prevent issues.  🙄

**Comment by JJKylee** [comment] 2021-01-13 03:26
Wondering this issue still persists, but I have this wild idea:
If reading the same `avs`/`vpy` by different processes causes the problem, why don't we **duplicate** and make (# of chunks) copies of the original file?

For example, if 4 chunks are to be encoded and the source avs script is `source.avs`, StaxRip makes 4 copies of `source.avs` and rename them like `source_chunk1.avs`, `source_chunk2.avs`, ..., `source_chunk4.avs` _before_ starting the job. Then let different `x265` processes read respective files.

Don't despise me if it sounds childish. 👶😭 Please tell me what you guys think.

**Comment by Dendraspis** [comment] 2021-01-13 10:28
@JJKylee 
This is already fixed by @stax76 .

> [..] why don't we duplicate and make (# of chunks) copies of the original file?

Don't misunderstand me, but this would be the solution we would think about after running out of ideas.  😁

**Closed by Dendraspis** 2021-01-13 10:28 UTC
Labels: added/fixed/done, bug, priority medium

**Comment by 44vince44** [comment] 2021-01-13 14:52
This seems fixed. With all the tests I did today using chunks and not a single time did I get an error...
