### ISSUE TITLE
My files sizes are +-10MB with the newest beta using x265 and 3 pass encoding

### ISSUE THREAD

**Issue by VEGAX265** [staxrip/staxrip#580] opened 2021-03-11 19:29 UTC
In Staxrip 2.1.8.5 beta
I created a new profile using the x265 encoder.
I set my x265 to run three passes.  I don't change any of the other settings for the encoder.
Selective SAO: used to be set to 4 now I just leave it at default.
I set my file size to 372 for the size the calculated Video Bitrate: says 551.
The file processes and outputs a file 361MB in size.

**Why are my files off by up to 10MB different than the 372 input for the size in this new beta?**

Staxrip 2.1.8.4 beta had the following 372 for the size the calculated Video Bitrate: says 578.
None of the output files ever matched this calculated Video Bitrate box but the files were always 372MB +-1MB.

Right clicking on Video Bitrate: gives me "Target Video Bitrate in Kbps (Up/Down key)"
**So what is this box really showing me compared to the final output file?**
2.1.8.5 output video bit rate is 983kb/s with overall is 1195kb/s
2.1.8.4  output video bit rate is1014kb/s with overall is 1227kb/s

**Also is there any way to use Staxrip to do multi pass using the x265 quality setting?**

[test_X265_VEGA_staxrip 2.1.8.5 beta.log](https://github.com/staxrip/staxrip/files/6125418/test_X265_VEGA_staxrip.2.1.8.5.beta.log)

[srip profiles.zip](https://github.com/staxrip/staxrip/files/6125431/srip.profiles.zip)

[mediainfo.txt](https://github.com/staxrip/staxrip/files/6125448/mediainfo.txt)

**Comment by stax76** [comment] 2021-03-11 19:41
There might be an issue with a recent change, will be investigated.

**Comment by Dendraspis** [comment] 2021-03-11 20:51
> I set my file size to 372 for the size the calculated Video Bitrate: says 551.
> The file processes and outputs a file 361MB in size.
> 
> **Why are my files off by up to 10MB different than the 372 input for the size in this new beta?**
> 
> Staxrip 2.1.8.4 beta had the following 372 for the size the calculated Video Bitrate: says 578.
> None of the output files ever matched this calculated Video Bitrate box but the files were always 372MB +-1MB.

Can you give us the correct size in **BYTES** instead of MB?

Starting with v2.1.8.5 StaxRip uses the SI prefix according to IEC (see Changelog). So **MB** instead of **MiB**, which was used but with the wrong prefix. 
`1 MB = 1,000,000 Bytes` 
`1 MiB = 1,048,576 Bytes`
`100 MiB = 104,86 MB`

Windows is still using the wrong prefix. 👎

Btw: Same with x265 by Patman, which also uses **MB** instead of **MiB** for the file sizes since `v3.5RC1+29`.

**Comment by VEGAX265** [comment] 2021-03-11 21:40
This is the file size I got according to media info File size: 362 MiB total file and Stream size: 297 MiB (82%).
According to windows its Size is 361 MB (379,113,184 bytes) and its Size on disc is: 361 MB (379,113,472 bytes)

I wanted File size media info File size    : 372 MiB this is from an older encode using old profile
Approximately Windows its Size is 371 MB (389,583,591 bytes) and its Size on disc is: 371 MB (389,586,944 bytes)

I entered 372 in Staxrip ,  What should be entering? 
Using the math above I should be seeing a file closer to 379MiB not smaller
also is 100 MiB = 104,86 MB 100 MiB = 104.86 MB comma vs period?

Please let me know  Thanks

**Comment by Dendraspis** [comment] 2021-03-11 23:42
Ok, I had to checkit (again), but everything works as intended.

`Filesize: 200 (entered)` 
`Bitrate: 6986 (calculated)`
`Audio: 500 (total of 2x 250kbps audio tracks`

The source file has 5342 frames @ 25 fps, so we estimate:
`6986 kbps + 500 kbps = 7486 kbps in total`
`7486 kbps / 8 / 25 fps = 37.43 KB per frame`
`37.43 KB * 5342 = 199,951.06 KB = 199.95106 MB = 190,68819 MiB`

The resulting file is about **2MB** smaller:
<img src="https://user-images.githubusercontent.com/50659978/110869043-efe91780-82c9-11eb-9624-866c312e2758.png">


So there are your **10MB**:   
`372 MiB = 390,070,272 B = 390 MB`
`372 MB = 372,000,000 B = 354,77 MiB`

So in order to achieve 372 MiB, you must enter 390 MB.

The difficulty is, that Windows and some old apps still use **MiB**, but show **MB** as unit, which is wrong.
I think I'm going to implement a switch to let the user decide which prefix should used.  🤔  When you only work with Windows tools and binary prefix, it might be a bit annoying.

**Comment by 44vince44** [comment] 2021-03-12 07:22
The MiB vs MB has been introduced for maybe 20 years (or more) now, and still there is always a confusion about it... I don't know how this has to be adressed...

**Comment by Dendraspis** [comment] 2021-03-12 08:41
It is because Windows displays **MB** and nobody pays attention when there is an **i** in between, because it's too small/thin.

**Comment by VEGAX265** [comment] 2021-03-12 14:12
Just a thought.
The simple way to do this is to include defaults under the Size: menu options to put "X" number of files per DVD-R or BD-R minus about 5MiB for extras like covers pics.

Would it be possible to get the units on the screen next to the boxes?

**Comment by Dendraspis** [comment] 2021-03-12 15:11
@VEGAX265 
Have you ever clicked on the colored "Size:" label?  😉 

Here is the last build with optional prefix, can be set via *Settings*:
[StaxRip v2.1.8.5D_Prefix.zip](https://github.com/staxrip/staxrip/files/6130883/StaxRip.v2.1.8.5D_Prefix.zip)

**Comment by VEGAX265** [comment] 2021-03-12 15:52
Thank you for the math help today.  Im fighting a sinus infection and my head was really hurting from this.
I use the Size: label all the time, love it too.  I just have to re enter my files sizes every time there is a new build with drastic changes.  not a big deal as I only really use 5 different file sizes.  5,10,20,22,24 per DVD-R
When i right click the box there is no info box like there is for the Video Bitrate:

Very nice StaxRip v2.1.8.5D_Prefix.zip  Can you put the selected prefix on the user interface next to the box?

I do most of my files in batch mode.  Is there any way to make Staxrip do x265 constant quality with a multi pass?

**Comment by 44vince44** [comment] 2021-03-12 16:00
>  Is there any way to make Staxrip do x265 constant quality with a multi pass?

No there is no such option, because multi-pass modes are already constant quality modes.
Think of it like that (although this is not totally accurate, but t helps understand): the analysis passes allow to analyze the full video and establish a complexity chart of the frames, then with the specified global bit rate, a global constant quality factor is calculated. When the last pass runs, it encodes with this global constant quality factor.
REMEMBER this is not totally accurate, but helps understand 😁

**Comment by VEGAX265** [comment] 2021-03-12 16:13
Thanks for quick explanation 44vince44.
If you do get the prefix on the main interface screen a right click info for "Total Output File Size" would be nice to explain the difference in bytes as Dendraspis stated.
1 MB = 1,000,000 Bytes
1 MiB = 1,048,576 Bytes

Thanks for clearing my head up today.  This is closed with me
Keep up the great work.

**Comment by Dendraspis** [comment] 2021-03-12 16:19
> a right click info for "Total Output File Size" would be nice to explain the difference in bytes as Dendraspis stated.

Is already explained via HelpText of the setting.  😁 

> Can you put the selected prefix on the user interface next to the box?

I think so.   😁 
Here is the latest build:
[StaxRip v2.1.8.5D_Prefix2.zip](https://github.com/staxrip/staxrip/files/6131340/StaxRip.v2.1.8.5D_Prefix2.zip)

**Comment by VEGAX265** [comment] 2021-03-12 16:28
awesome sauce you rock!

**Comment by VEGAX265** [comment] 2021-03-19 16:52
I tested the exe files that were sent over to me and they changes were great showing us what units are used. 
Im still having issues with the file sizes not being right in the end.  I went back to 2.1.8.4 beta and the problem is there as well.
I think it has to do with the audio file changing size and the bitrate not compensating like it used to.  All 3 passes are using the same original bitrates.  After it finishes converting the audio file there is a line in all of my logs that shows Video Bitrate: 702 -> 691 with similar numbers depending on the length of the video.  

It looks like 2.1.8.5 is always taking the number on the left of that Video bitrate line.
For this one my audio file was smaller after conversion and it said this Video Bitrate: 910 -> 937 but all three passes used the 910 bit rate.

Also at that point I dont know if the number generated after audio conversion is in KiB or KB per seconds
I can post logs if you like.

**Comment by 44vince44** [comment] 2021-03-19 17:03
post the log please i'll take a look...

**Comment by Dendraspis** [comment] 2021-03-19 17:32
Maybe this has something to do with the latest issue regarding the prefix and overhead calculation in #597.

Please take the zip file from my latest posts, should be *Prefix6*.

**Comment by VEGAX265** [comment] 2021-03-19 18:06
will do as soon as I can

**Comment by VEGAX265** [comment] 2021-03-19 20:29
i was running on StaxRip v2.1.8.5D_Prefix2.zip from the link above.

Where \ how do I get Prefix6?

StaxRip v2.1.8.5D_Prefix2 in MiB mode
[2021-03-14 - 15.48.35 - file01_358MiB_staxrip.log](https://github.com/staxrip/staxrip/files/6173847/2021-03-14.-.15.48.35.-.file01_358MiB_staxrip.log)


StaxRip v2.1.8.4 Beta
[2021-03-19 - 14.34.10 - file02_372MiB_staxrip.log](https://github.com/staxrip/staxrip/files/6173852/2021-03-19.-.14.34.10.-.file02_372MiB_staxrip.log)


Im betting that #597 has this fixxed.

After reading #597 the Video Bitrate Box in Staxrip v2.1.8.5 is always kbps no mater what mode Mib or MB?

**Comment by 44vince44** [comment] 2021-03-19 20:48
Yes we worked on it yesterday and fixed it,
The kbps is always kbps because this is how all encoders work. They expect kbps.
Get Prefix6 hotfix here: https://github.com/staxrip/staxrip/issues/597#issuecomment-801985852

I think that you have to set your preferences MiB, and remember that Windows OS displays as "MB" are in reality MiB.

**Comment by VEGAX265** [comment] 2021-03-21 17:56
Tested last night using the exe from StaxRip.v2.1.8.5D_Prefix6.zip in both modes MiB and MB.  Both are not moving the second calculated video bitrate from qaac audio encoder over to the 3rd and second passes.
this is found under audio
-------------------------- Audio Encoding 1 --------------------------
qaac 2.71 
Video Bitrate: 473 -> 457 and Video Bitrate: 927 -> 959 respectively

I went back and checked my logs it was working properly in StaxRip.v2.1.8.2  and failed in StaxRip.v2.1.8.3

**Comment by VEGAX265** [comment] 2021-03-21 18:00
[537MiB actual output 523MiB.log](https://github.com/staxrip/staxrip/files/6178028/537MiB.actual.output.523MiB.log)

[213MB actual output (218,479,405 bytes) 208MiB.log](https://github.com/staxrip/staxrip/files/6178030/213MB.actual.output.218.479.405.bytes.208MiB.log)

**Comment by 44vince44** [comment] 2021-03-21 18:01
please send me this log! the one of prefix6

**Comment by 44vince44** [comment] 2021-03-21 18:07
@VEGAX265 in order to understand what is happening, I need a screenshot of the main window to see what values are displayed before processing. If you still have the temp files, you can still open the .srip file in staxrip and drop a screenshot here...

**Comment by 44vince44** [comment] 2021-03-21 18:20
You are expecting that the video bitrate gets adjusted when the audio has been encoded and its bitrate is accurately known ?

Please try to explain clearly before I answer you...

**Comment by VEGAX265** [comment] 2021-03-21 18:40
Sorry for the delay the computer that encodes is at work and I have to remote into it to get my screen shots.

I just saw that StaxRip-v2.1.9.0-Beta-x64.7z was released and I am reading thru the change log.
This may have been fixed in this release.

> You are expecting that the video bitrate gets adjusted when the audio has been encoded and its bitrate is accurately known ?
> 
> Please try to explain clearly before I answer you...

Yes exactly 
It is showing the adjustment in the audio section but it never gets applied in any of the video passes.

![213MB actual output (218,479,405 bytes) 208MiB](https://user-images.githubusercontent.com/44779244/111916756-de82d680-8a52-11eb-877e-ba1c4c6b195b.png)

![537MiB actual output 523MiB](https://user-images.githubusercontent.com/44779244/111916769-f0647980-8a52-11eb-902b-aad108a77bfa.png)

**Comment by 44vince44** [comment] 2021-03-21 18:46
@VEGAX265 now we understand what you mean! We're investigating...

**Comment by Dendraspis** [comment] 2021-03-21 19:04
@VEGAX265 
You've chosen a 5.1 audio profile with a relative high bitrate setting for a stereo file. Of course qaac will not reach it. Set it to 64kbps or 80kbps and you're problem is gone.
And StaxRip has ***never*** taken the audio bitrate *after encoding* to re-calculate the video bitrate.

**Comment by 44vince44** [comment] 2021-03-21 19:13
This seems like something that has been dropped long ago, Dendraspis is still investigating...

**Comment by VEGAX265** [comment] 2021-03-21 19:33
Hope you find it I have around 80 videos 50+ hours I have to redo.  lol
It seemed to be working in StaxRip.v2.1.8.2 beta
Thank you guys

**Comment by 44vince44** [comment] 2021-03-21 19:37
We finally understood, you know, neither of Dendraspis and I use multi-pass encode, so we didn't really see this feature/issue...

**Comment by Dendraspis** [comment] 2021-03-21 19:44
It seems my recent fix fixed an old bug, but created a new one. I will fix it for sure, but it might take a bit.

> neither of Dendraspis and I use multi-pass encode, so we didn't really see this feature/issue...

Multi-pass **with audio**, that's the point.  😁

**Comment by Dendraspis** [comment] 2021-03-22 08:31
Okay, I've fixed it and in my tests it works, but you should double-check it:
[StaxRip v2.1.10D.zip](https://github.com/staxrip/staxrip/files/6180573/StaxRip.v2.1.10D.zip)

**Comment by Dendraspis** [comment] 2021-03-22 10:40
Little update:
Fortunately I did **not** create a new bug. 😁  This bug was "introduced" in v2.1.8.2, so the latest working version with this feature is v2.1.8.1.

Will take a bit to find a solution...

**Comment by Dendraspis** [comment] 2021-03-22 11:36
More than complex, took me more time than I thought.  But it should be fixed now:
[StaxRip v2.1.11D.zip](https://github.com/staxrip/staxrip/files/6181789/StaxRip.v2.1.11D.zip)

**Comment by JJKylee** [comment] 2021-03-22 12:29
Off topic:
So the next beta version is 2.1.11? You decided not to attach the last `dev` build number? 🙄

**Comment by Dendraspis** [comment] 2021-03-22 13:01
@JJKylee 
Saw your post on Doom9 and wanted to write you when I stop wrestling with myself. 😉 
But have a look at this: https://github.com/staxrip/staxrip/discussions/579#discussioncomment-513065

**Comment by JJKylee** [comment] 2021-03-22 13:08
I already did and left a reply.
I like the new naming scheme better. At least users won't get confused. 😃

**Comment by 44vince44** [comment] 2021-03-22 16:30
please begin new naming from v2.2
if you bedin now people are gonna get confused !!

**Comment by Dendraspis** [comment] 2021-03-22 16:48
Stop being off-topic and tell me if the fix works for you, too.  😄  😜

**Comment by JJKylee** [comment] 2021-03-22 17:20
To be frank, I dare not do a 3-pass encoding with `x265`. 😝
I'll pass the honor over to @44vince44, or @VEGAX265. 😁

**Comment by 44vince44** [comment] 2021-03-22 20:10
OK I'll check now with latest exe I have.. just give me the time to do the encode... (using 4K upscaling and setting x265 on placebo, and using a sample file of 4 hours)

**Comment by 44vince44** [comment] 2021-03-22 21:29
Last hotfix has successfully fixed the problem! well done @Dendraspis !! 🎉 🚀

**Closed** 2021-03-22 23:11 UTC
Labels: added/fixed/done, bug, feature request, priority high, question
