### ISSUE TITLE
x265 option tskip doesn't change state when enabled/disabled from UI config

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1344] opened 2024-05-05 20:19 UTC
**Describe the bug**
x265 option `tskip` doesn't change state when enabled/disabled from UI config

**Comment by Dendraspis** [comment] 2024-05-05 23:19
Which `--preset` do you use?

**Comment by IevgenSobko** [comment] 2024-05-06 04:33
`placebo` for best quality

**Comment by Dendraspis** [comment] 2024-05-06 07:02
I knew it, because that's the only preset where you can encounter this problem. 😅

The default is *true* for placebo, so in case you want to disable it, you have to add `--no-tskip` to the `Custom` section untill the next release where it will be fixed.

**Comment by IevgenSobko** [comment] 2024-05-06 08:36
Yep, I use `Custom` for disabling it since I started to use StaxRip.
But recently helped my friend to also start using StaxRip, and he pointed me out to this problem again.
So I opened this issue whiile still remembering... 🤣

**Comment by Dendraspis** [comment] 2024-05-06 11:07
The biggest issue is:
Why didn't you mention it months/years/decades ago?  😕  Are there any other issues you deal with and haven't mentioned before?  😅 

I have never used `Placebo` because it takes ages and the improvement over the slower presets was negligible.

**Comment by IevgenSobko** [comment] 2024-05-06 13:00
I started to use StaxRip about just a year ago, so don't worry it was decades 🤣(when the project didn't exist).
And we use `Placebo` but with specific parameters adjustments to decrease encode time. But using placebo allows us to use bigger CRF(like 20) to decrease file size and get the same results when use for instance `Slower` but with lower CRF(18)

**Comment by Dendraspis** [comment] 2024-05-06 14:20
> when the project didn't exist

StaxRip exists for decades, so... 😅

But okay, so in other words: you basically use a slower preset with additional quality improving settings. I thought you leave it almost untouched...

Not really, you can share the whole settings and/or templates.
So in case you don't need the general settings, you can try to share a template.
Oh yeah, it is. This is why I try to separate them into main and minor versions, that are (almost) compatible. When it comes to updating I recommend the local Settings folder and running both (old and new) versions parallel and transfer everything by hand. Depending on your setup, this can be a pain in the ass, but it's save. Otherweise use the old settings and verify on the first runs, that everything works as intended.

> And if you have multiple encoding machines it becomes real pain...

As long as you have the same version everywhere, you can set one instance up and then copy the settings and templates to the other instances, so that should not be a big issue.

**Closed** 2024-05-07 08:52 UTC
Labels: bug  :bug:, added/fixed/done
