### ISSUE TITLE
"Create job for each selection" is broken again

### ISSUE THREAD

**Issue by HASJ** [staxrip/staxrip#727] opened 2021-06-07 02:10 UTC
**Describe the bug**
Whenever you use the function, StaxRip just throws an error about enumeration. You can keep using the program but the error warning never goes away.

**Expected behavior**
To work without an error.

**How to reproduce the issue**

1. Go to the `Preview` window of any video and choose `Create job for each selection` 
2. Close the `Jobs` window that pops up
3. Error warning shows up

**Provide information**
![image](https://user-images.githubusercontent.com/9345660/120950068-55f40800-c71c-11eb-92e0-c1dabf2469fa.png)

- Used StaxRip version
2.6.0

**Comment by JJKylee** [comment] 2021-06-07 03:16
Confirmed.

The error log is as follows:

```
InvalidOperationException (v2.6.0)

Collection was modified; enumeration operation may not execute.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at StaxRip.PreviewForm.GenericMenu_Command(CustomMenuItemEventArgs e) in D:\Code\Github\staxrip\staxrip\Source\Forms\PreviewForm.vb:line 982
   at StaxRip.UI.CustomMenu.OnCommand(CustomMenuItem item) in D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:line 274
   at StaxRip.UI.CustomMenu.MenuClick(Object sender, EventArgs e) in D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:line 267
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at StaxRip.UI.MenuItemEx.OnClick(EventArgs e) in D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:line 675
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by 44vince44** [comment] 2021-06-07 04:47
@JJKylee @Dendraspis 
If I understand correctly, the modification made to allow floating Trim() filter would have broken the `Create Job for each selection` ?

**Comment by JJKylee** [comment] 2021-06-07 05:27
@44vince44, that's my guess, but I'm not sure though.
We need @Dendraspis's confirmation.

**Comment by Dendraspis** [comment] 2021-06-07 07:16
Seems like I made a very stupid mistake.  :unamused:
I'll check (and fix) it later ....

**Comment by Dendraspis** [comment] 2021-06-07 08:52
Okay, I could reproduce it and it's fixed.
The problem was introduced when #676 was solved and an unfortunate interaction appeared.

Current hotfix:
[StaxRip_v2.6.9.zip](https://github.com/staxrip/staxrip/files/6607246/StaxRip_v2.6.9.zip)

**Comment by Dendraspis** [comment] 2021-06-07 15:02
Which version did you use ?

**Comment by JJKylee** [comment] 2021-06-07 15:15
2.6.9.

**Comment by 44vince44** [comment] 2021-06-08 06:31
This is an issue that will happen whenever ranges are selected, or fps are changed: the timestamps file must not be used.

Now since Staxrip is for aware users, they should know 😁 

But i agree with @JJKylee that we should change the way Staxrip handles it:

CURRENTLY:

If option to extract timestamps is ON, then Staxrip extracts timestamps and MUXES them in the output

BETTER WAY:

There should be no option to extract the timestamps, the timestamps should be ALWAYS extracted. But there should be an option to use them in the output.
So Staxrip ALWAYS will extract the timestamp file, and IF option "Use Extracted Timestamps" is ON, then mux the file.

**Comment by 44vince44** [comment] 2021-06-08 09:10
I wanted to add that i unfortunately mislead @Dendraspis a few weeks ago with the current way Staxrip handles that. Sorry 😁

**Comment by Dendraspis** [comment] 2021-06-08 09:32
@JJKylee 
I wished you would have created a new issue for that.  😉

**Comment by Dendraspis** [comment] 2021-06-09 07:57
Since a new issue is created and the original issue is done, I close this...

**Closed by Dendraspis** 2021-06-09 07:57 UTC
Labels: added/fixed/done, bug
